### ISSUE TITLE
disclaimer on title page

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#101]
Can we put this on the title page somewhere? It is required by NOAA. A small font, italics, are fine.

Disclaimer: This information is distributed solely for the purpose of pre-dissemination peer review under applicable information quality guidelines. It does not represent and should not be construed to represent any agency determination or policy

**Comment by andrew-edwards** [comment]
On it.

**Comment by andrew-edwards** [comment]
Done.

**Comment by taylori** [comment]
I think we should add this disclaimer back for the pre-SRG review.

**Comment by andrew-edwards** [comment]
Done. Uncommented it from before (should really have a switch for draft/not draft - but not tonight).
