### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#102]
Remove the double star line.
Make sure that the Canadian people are still associated and helping with hake.
And, make sure you are OK with what I wrote about Ian.

**Comment by minnowslayer** [comment]
I'm ok with what's written here

**Comment by aaronmberger** [comment]
sounds good to me

On Mon, Feb 8, 2016 at 4:28 PM, minnowslayer <notifications@github.com>
wrote:

> I'm ok with what's written here
>
> On Mon, Feb 8, 2016 at 4:19 PM, allanhicks <notifications@github.com>
> wrote:
>
> > Remove the double star line.
> > Make sure that the Canadian people are still associated and helping with
> > hake.
> > And, make sure you are OK with what I wrote about Ian.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cgrandin/hake-assessment/issues/102>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/102#issuecomment-181639327>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment]
Just edited...
