### ISSUE TITLE
line numbers still messed in my build

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#106]
See numbered page 11 in a build a couple of merges ago. I don't mid submitting a version with these weird line numbers though.

**Comment by allanhicks** [comment]
Fixed by latexing 3 times after bibtexing

**Comment by andrew-edwards** [comment]
Yes, because bibtex and then the first latex is inserting the names into the document It's why you shouldn't really delete .bbl each time ;)
