### ISSUE TITLE
New forecast catches

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#107]
@allanhicks can figure out the new forecast catches to input into all.r

**Comment by cgrandin** [comment]
I think at least one of us should know how this is done exactly so we can do it next year, (Aaron?). Does Ian Taylor know what you do here? Thanks

**Comment by aaronmberger** [comment]
Are you following [explicitly] your notes on this that you shared the other
day?  But agree with Chris that someone needs to know EVERYTHING Allan does
:)

On Thu, Feb 11, 2016 at 12:14 PM, cgrandin <notifications@github.com> wrote:

> I think at least one of us should know how this is done exactly so we can
> do it next year, (Aaron?). Does Ian Taylor know what you do here? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/107#issuecomment-183045644>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by aaronmberger** [comment]
sorry, above comment directed to Allan

On Thu, Feb 11, 2016 at 12:18 PM, Aaron Berger - NOAA Federal <
aaron.berger@noaa.gov> wrote:

> Are you following [explicitly] your notes on this that you shared the
> other day?  But agree with Chris that someone needs to know EVERYTHING
> Allan does :)
>
> On Thu, Feb 11, 2016 at 12:14 PM, cgrandin <notifications@github.com>
> wrote:
>
>> I think at least one of us should know how this is done exactly so we can
>> do it next year, (Aaron?). Does Ian Taylor know what you do here? Thanks
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cgrandin/hake-assessment/issues/107#issuecomment-183045644>
>> .
>>
>
>
>
> --
>
> *Aaron M. Berger, Ph.D. Research Mathematical Statistician*
> *Fishery Resource Analysis and Monitoring Division*
> *Northwest Fisheries Science Center*
> *2032 SE OSU Dr. Bldg. 955*
> *Newport, OR 97365-5275*
>
>
>
> *aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562 <541.867.0562>*
>
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
Yes, I followed my notes. It is intuitive when you think about it.  For the
decision table you fix catch in each year.  For the metrics you only fix
the catch in the year of interest so that you compare to the predicted
catch next year.  Otherwise, the probabilities are comparing against fixed
values, which is why we got 0 and 100%, as Chris pointed out and I ignored.

The nice thing about this collaborative process using Git is that
everything is there (except the bits of confidential data parts).  And, I
have to relearn everything every year anyways, as you can tell with the
forecasting.

**Comment by allanhicks** [comment]
done
