### ISSUE TITLE
Checking what's not automated in write-up -- suggestion

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#109]
I went through the One-page Summary and there are three sentences that may need editing, depending on results. I've put

% Manual to do.  

(and maybe a description) at the end of each. I suggest once we have checked it and updated based on the new results, we change it to

% Manual 2016 done.  

to show that someone has then checked it and updated the text if necessary.

If we do this for all instances then we can easily: 
a) Search the final .tex file for 
% Manual to do.  
and make sure that none exist.

b) Search next year for '2016 done' and change to 2017 when we've updated that (thinking ahead here - I figured this would be the first job next year!).

Any thoughts? I can't quite push right now, and won't do anything tonight except download model results.

I think we can do this pretty efficiently tomorrow. Good job with getting all the runs redone.

**Comment by aaronmberger** [comment]
Sounds like a good idea to me.  So, follow the same protocol for each major section break then...

**Comment by allan-hicks** [comment]
Good idea. We can at least flag things if we aren't sure how to correct
them.

**Comment by minnowslayer** [comment]
that seems like an OK idea to me.

**Comment by andrew-edwards** [comment]
We mostly kept to this. Just have to check manually again next time....
