### ISSUE TITLE
Page viii, stock biomass section.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#113]
Second sentence says:
"The model estimates that it was below the unfished equilibrium in the 1960s and 1970s due to lower than average recruitment." 
Shouldn't we add
"... and the onset of fishing." to that? 
But does the model really give a 'reason' for the decline? Are we better to say:
"... 1970s, presumably due to lower than average recruitment and the onset of fishing."

**Comment by cgrandin** [comment]
I agree with these changes

**Comment by aaronmberger** [comment]
as do I

On Thu, Feb 11, 2016 at 11:15 AM, cgrandin <notifications@github.com> wrote:

> I agree with these changes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/113#issuecomment-183016162>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
I think the point is that the start of the model is below equilibrium
before fishing started. Thus, the onset of fishing doesn't make sense to
me.  Maybe if we removed 1970's or made it clear "the start of the model
(1966)"?

**Comment by allanhicks** [comment]
I modified to capture that the model is starting below equilibrium.  See if you agree (commit "exec summary edit (biomass at start of model)")

**Comment by andrew-edwards** [comment]
Yes, that's better. And makes sense. Nice.
