### ISSUE TITLE
Page xix, line 6. Make more sense to refer to Table i not Table g, yes?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#114]
Although may be clearer to rewrite sentence as:
The population is predicted to decrease from 2016 to 2017 with a less than 50% probability for all catch levels investigated up to 440,000 t (Table i and Figure i).

i.e.  talk about prob of decrease, which is what is shown in Table i. Save the reader having to switch the numbers around in their head.

**Comment by andrew-edwards** [comment]
And it should be Figure j.  So Table i and Figure j, like it already is at the end of the paragraph.

**Comment by cgrandin** [comment]
Agree Table i, column 1, Figure i would be simpler to understand.
Also I think it might be better written like this:
"From 2016 to 2017, the population is predicted to decrease..."
