### ISSUE TITLE
recheck .tex files with new models...

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#115]
Guys, 

Should we do another check of our .tex file to make sure we are all on the same page given the new list of models....?  I'm just rebuilding the document now and believe I'm only a few relatively minor commits behind

**Comment by cgrandin** [comment]
Yes, we should. Maybe around 1 - 1:30 ? It would be ideal if we all built off the same commit and then compared.

**Comment by allan-hicks** [comment]
Sounds good to me. Let me know when the merge is made and I'll build the
doc.

**Comment by cgrandin** [comment]
I just merged Andy's latest changes. Let's do the check with commit # 2146409...
One more command to add to your knowledge, which commit are you currently on? Type:
git rev-parse HEAD
Which means revision-parse - it will show you the whole hash of the commit you are on. You only need to worry about the first few characters.
If you have made changes but need to merge to get up to date, do:
git stash
then it stashes all your changes away, and you can merge and build on the commit 2146409. Once done, do:
git stash apply
and all your changes will be applied to your newly-merged version. Then you continue as usual.

**Comment by cgrandin** [comment]
I tried zipping, dragging and dropping the tex file here. Let's see if it works. It doesn't support the .tex extension so I zipped it.
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/127110/hake-assessment.zip)

**Comment by allan-hicks** [comment]
You may want to also update r4ss, just to be sure:

devtools::install_github("r4ss/r4ss")

**Comment by andrew-edwards** [comment]
Chris and I would rather not update r4ss - it's a bit late for that isn't it? What if it breaks everything.....
We updated last week when you added something.

**Comment by allan-hicks** [comment]
I made a fix yesterday, but it shouldn't affect the document. It will if we
are comparing MCMC's, but we are only doing MLE's. So, it should be fine.

**Comment by aaronmberger** [comment]
Okay, building mine now and will send shortly...

**Comment by allan-hicks** [comment]
I'm building mine, but starting fresh. So, it may be a little bit.

**Comment by aaronmberger** [comment]
same here, started fresh... so ~20min

**Comment by andrew-edwards** [comment]
Okay. We'd rather not update anything.

**Comment by andrew-edwards** [comment]
Here's mine. Have to make it a zip file...

[hake-assessment-andy.zip](https://github.com/cgrandin/hake-assessment/files/127135/hake-assessment-andy.zip)

**Comment by allan-hicks** [comment]
Good point about not updating r4ss. We should make a note somewhere of the
version of r4ss we used to create this document. Here is how to install
that version:

devtools::install_github("r4ss/r4ss",ref="cf35516")

where ref is the commit number.

**Comment by andrew-edwards** [comment]
Mine and Chris's .tex files are identical.

**Comment by allanhicks** [comment]
Here is my tex file:
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/127162/hake-assessment.zip)

**Comment by aaronmberger** [comment]
and mine...



On Thu, Feb 11, 2016 at 1:47 PM, allanhicks <notifications@github.com>
wrote:

> Here is my tex file:
> hake-assessment.zip
> <https://github.com/cgrandin/hake-assessment/files/127162/hake-assessment.zip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/115#issuecomment-183071300>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment]
Mine and Allan's are identical (as with Chris's, only differences are automatic time-stamp and version number from xtable commands, that are commented out)

**Comment by cgrandin** [comment]
Yours is identical to mine Allan. Yay!

**Comment by cgrandin** [comment]
Aaron yours is not attached

**Comment by aaronmberger** [comment]
how about now....
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/127214/hake-assessment.zip)

**Comment by aaronmberger** [comment]
drag and drop doesn't work with firefox, only Chrome - so had to change browsers

**Comment by cgrandin** [comment]
It looks like yours is slightly different Aaron.. But I think you are just a couple of merges behind. Your risk tables have different values and you have NA's in the survey history table (I fixed that today in an earlier commit). Allan did some work on the risk table code (metrics) in a commit from the other day. Are you merging? Looking at the network graph?

**Comment by aaronmberger** [comment]
Yes I merged but must have been a couple behind - my bad, working between two computers today...?!?!  I just merged and built again so I'll double check those few differences are good now

**Comment by allan-hicks** [comment]
Yeah, I've been working on three different computers.  Have to make sure to
merge and sync all three, and start fresh on the build of the document,
including deleting knitr-cache.  I've been using the freshtex.bat file,
which is the same as cleantex.bat with the addition of deleting the
knitr-cache folder.

**Comment by cgrandin** [comment]
Ok, I think we are good. I'll close this.

**Comment by andrew-edwards** [comment]
Aaron - save your .tex and I can do a quick check again to be sure.
I'm on just the one computer ;)

**Comment by aaronmberger** [comment]
Ok, here is the one I build after last time
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/127271/hake-assessment.zip)

**Comment by aaronmberger** [comment]
Let me know if you want me to rebuild 'now' and then resend

**Comment by andrew-edwards** [comment]
I just checked that one. Still a few numerical differences, e.g. final column in Table i. Have you rebuilt the figures and tables lately? Or you may have to do source("all.r") and say yes to the forecast and partest questions.

**Comment by aaronmberger** [comment]
Right, I''ll have to do that tonight.  thanks andy

On Thu, Feb 11, 2016 at 3:51 PM, andrew-edwards <notifications@github.com>
wrote:

> I just checked that one. Still a few numerical differences, e.g. final
> column in Table i. Have you rebuilt the figures and tables lately? Or you
> may have to do source("all.r") and say yes to the forecast and partest
> questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/115#issuecomment-183114843>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by aaronmberger** [comment]
Okay, does this one match (or closely match)?
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/127576/hake-assessment.zip)
