### ISSUE TITLE
Table 7, extrap:no extrap column names reversed...?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#118]
I think these column names got reversed.

**Comment by cgrandin** [comment]
Fixed!

**Comment by cgrandin** [comment]
Thanks for spotting this

**Comment by allan-hicks** [comment]
Good catch, I just fixed and committed.

**Comment by aaronmberger** [comment]
Okay just comitted same fix so ignore

On Thu, Feb 11, 2016 at 3:03 PM, cgrandin <notifications@github.com> wrote:

> Thanks for spotting this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/118#issuecomment-183093801>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
Chris, can you delete my commit?

**Comment by aaronmberger** [comment]
ha ha - trifecta

On Thu, Feb 11, 2016 at 3:03 PM, Aaron Berger - NOAA Federal <
aaron.berger@noaa.gov> wrote:

> Okay just comitted same fix so ignore
>
> On Thu, Feb 11, 2016 at 3:03 PM, cgrandin <notifications@github.com>
> wrote:
>
>> Thanks for spotting this
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cgrandin/hake-assessment/issues/118#issuecomment-183093801>
>> .
>>
>
>
>
> --
>
> *Aaron M. Berger, Ph.D. Research Mathematical Statistician*
> *Fishery Resource Analysis and Monitoring Division*
> *Northwest Fisheries Science Center*
> *2032 SE OSU Dr. Bldg. 955*
> *Newport, OR 97365-5275*
>
>
>
> *aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562 <541.867.0562>*
>
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
This is why Chris handles the merging!
