### ISSUE TITLE
Cutoff at 11:30?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#125]
I think that we are getting to a good place when we are having merge conflicts over backslashes.  Do you think that a cutoff at 11:30 so that we can build the document and distribute it by noon is a good idea?

**Comment by cgrandin** [comment]
I think so. At this point I am just looking for things to do, I believe we are in a good place as well.

**Comment by andrew-edwards** [comment]
All these changes to automate the fish name are doing my head in!! 
Why bother doing them now - they could have waited until after we submit! Anyway, see my comment on Chris's commit - you've left Whiting out of the Agreement's name I think, which is presumably incorrect.

**Comment by aaronmberger** [comment]
11:30 good for me, just committed some table caption changes

**Comment by andrew-edwards** [comment]
Yes, agree to cut-off at 11:30 to stop people making minor un-needed edits ;)

**Comment by cgrandin** [comment]
I'm done committing, I'll just merge any new changes in and build the document.

**Comment by allan-hicks** [comment]
i have one more important commit to the one-pager, so please hold on.

**Comment by allan-hicks** [comment]
Thanks. I'm done with commits unless something is glaringly obvious. I
would say let's merge, quick check, then submit.

**Comment by allan-hicks** [comment]
Do we want to reflect that this is an updated draft? Or is the date on the
title page sufficient?

**Comment by aaronmberger** [comment]
I'm done.

On Fri, Feb 12, 2016 at 11:17 AM, Allan C Hicks <notifications@github.com>
wrote:

> Do we want to reflect that this is an updated draft? Or is the date on the
> title page sufficient?
>
> On Fri, Feb 12, 2016 at 11:16 AM, Allan Hicks - NOAA Federal <
>
> allan.hicks@noaa.gov> wrote:
>
> > Thanks. I'm done with commits unless something is glaringly obvious. I
> > would say let's merge, quick check, then submit.
> >
> > On Fri, Feb 12, 2016 at 11:11 AM, Allan Hicks - NOAA Federal <
> > allan.hicks@noaa.gov> wrote:
> >
> >> i have one more important commit to the one-pager, so please hold on.
> >>
> >> On Fri, Feb 12, 2016 at 11:09 AM, cgrandin <notifications@github.com>
> >> wrote:
> >>
> >>> I'm done committing, I'll just merge any new changes in and build the
> >>> document.
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <
> https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183453394
> >
> >>> .
> >>>
> >>
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183455391>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
Shoudl the date be in the footer? Sorry to be worried about this, but I am
concerned that with multiple drafts floating around, some people may be
looking at the incorrect version.

**Comment by cgrandin** [comment]
I think so. I will attempt it now

**Comment by cgrandin** [comment]
I have the date in footer  working, just need to get a short form so it doesn't overlap page numbers. Stand by

**Comment by andrew-edwards** [comment]
I wouldn't mind spending 20 minutes or so checking it. Feels like we've wasted some time with all the \fishname stuff, which may have messed things up a little (I never got to finish reading the Exec Summary) - I'm guessing people weren't really re-latex'ing and checking it was all okay ;) 
But looks like we've all caught up almost - so let's merge when Chris does the commit. Redo source("all.r"), delete knitr-cache and redo, and then take a look through. I may print the whole thing out. Expect we can submit by, say, 12:15?

**Comment by allan-hicks** [comment]
What about "Pacific Hake stock assessment 2/12/2016" in the footer?

**Comment by allan-hicks** [comment]
I'll check with Miako to see if she is going to lunch before then. I would
like the JMC to have at least 2 hours to look at this.

**Comment by aaronmberger** [comment]
ok by me.  I'll source all.r, but no need to enter any 'y', correct?

On Fri, Feb 12, 2016 at 11:33 AM, andrew-edwards <notifications@github.com>
wrote:

> I wouldn't mind spending 20 minutes or so checking it. Feels like we've
> wasted some time with all the \fishname stuff, which may have messed things
> up a little (I never got to finish reading the Exec Summary) - I'm guessing
> people weren't really re-latex'ing and checking it was all okay ;)
> But looks like we've all caught up almost - so let's merge when Chris does
> the commit. Redo source("all.r"), delete knitr-cache and redo, and then
> take a look through. I may print the whole thing out. Expect we can submit
> by, say, 12:15?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183459541>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by cgrandin** [comment]
I'd need to figure that out. Right now its "Pacific Hake February 12, 2016". Is there time?

**Comment by allan-hicks** [comment]
Woudl something like this work?

\usepackage{datetime}\newdateformat{specialdate}{\THEYEAR-\twodigit{\THEMONTH}-\twodigit{\THEDAY}}\date{\specialdate\today}

**Comment by allan-hicks** [comment]
Miako will be able to distribute it at 12:15. So let's make 12pm time to
build.

**Comment by cgrandin** [comment]
Maybe, it's not the figuring it out that takes the time, its the building. I'm on it.. look for a commit in awhile for this

**Comment by cgrandin** [comment]
Ok, should be good. I am going to build from scratch now.

**Comment by allan-hicks** [comment]
Do we want to resolve our issue regarding the one-page summary and rounding
percentages?

**Comment by cgrandin** [comment]
It's easy to do. What do you want to change?

**Comment by allan-hicks** [comment]
Any thoughts Andy?

**Comment by cgrandin** [comment]
The ones in the last bullet are rounded to zero digits where the others are all 1 digit. Is that the issue? If so, I can change that

**Comment by allan-hicks** [comment]
Can you have a look at my commit to see if you like this?

show the estimated median relative spawning biomass increasing from 76\%
    in \Sexpr{end.yr} to 80\% in \Sexpr{end.yr+1} and beginning to
stabilize in \Sexpr{end.yr+2}.

**Comment by andrew-edwards** [comment]
Or just:

to 80\% in \Sexpr{end.yr+1} and \Sexpr{end.yr+2}.

Loses the word stabilise though. Kind of obvious though?

**Comment by andrew-edwards** [comment]
Footer - you could take out 'stock' just to shorten it and keep it away from page numbers.

**Comment by cgrandin** [comment]
I managed to get everything in the footer now. I think we should do final merges, build, and submit..

**Comment by allan-hicks** [comment]
Given my experience with this crowd, I think that it is useful to keep the
word stabilize. We have been talking a lot about when the stock will
stabilize and begin to decline.  I like to let them know what I want them
to know rather than have them infer it. Does that make sense?

**Comment by andrew-edwards** [comment]
Allan - 'beginning to stabilize' isn't quite right. Implies it's going to stay constant, but it could decline the year after (as you said earlier). 
Okay - how about just 'stabilize':

...and stabilizing in \Sexpr{end.yr+2}.

**Comment by allan-hicks** [comment]
I am building. Here is my tex file (trying attach from the email, not sure
if it will work).

**Comment by aaronmberger** [comment]
Chris, let me know when to do final merge

**Comment by allan-hicks** [comment]
or "remaining stable in 2018" which removes any context of what may happen
after 2018?

**Comment by cgrandin** [comment]
Go ahead Aaron, I think we're done
And Allan I didn't get a tex file. Just send to our emails

**Comment by allan-hicks** [comment]
I think the "stable" is unstable. Can we resolve this issue. I think that
it is very important and is something that we will focus on a lot in the
JMC meeting.

**Comment by allan-hicks** [comment]
I just committed to "staying stable in 2018" What do you think?

**Comment by andrew-edwards** [comment]
Okay - I'm good with "remaining stable in 2018" as it doesn't imply what happens after.

**Comment by andrew-edwards** [comment]
Good. I'm going to shorten the footer also and commit. Less clutter at the bottom.

**Comment by aaronmberger** [comment]
Fine by me.

On Fri, Feb 12, 2016 at 12:16 PM, andrew-edwards <notifications@github.com>
wrote:

> Good. I'm going to shorten the footer also and commit. Less clutter at the
> bottom.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183473230>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment]
Okay. I'm done committing!
Will email Chris a .tex so he can compare. I'll build a .pdf and print it, and take a very quick look through.

**Comment by allan-hicks** [comment]
OK. Let's merge, build, and Chris mark this as the point of the updated
draft document

**Comment by cgrandin** [comment]
Ok, I am building now using commit 7fe34c

**Comment by andrew-edwards** [comment]
I can build the submittable .pdf again. Filename?
hake-assessment-preSRG-revised.pdf  
or 
hake-assessment-preSRG-2016-02-12.pdf

**Comment by allan-hicks** [comment]
I prefer the date in there

**Comment by allan-hicks** [comment]
Can you send it to all of us, then I'll send it to Miako?

**Comment by allan-hicks** [comment]
Did we ever update Figure 2?

**Comment by cgrandin** [comment]
Not that I'm aware of Allan.

**Comment by aaronmberger** [comment]
Right, i bet not

On Fri, Feb 12, 2016 at 12:26 PM, cgrandin <notifications@github.com> wrote:

> Not that I'm aware of Allan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183476170>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by cgrandin** [comment]
But the figure is just backscatter, not biomass - it should be the same no matter what estimation technique is used. It's raw data

**Comment by cgrandin** [comment]
Except for one region (one circle) I guess

**Comment by andrew-edwards** [comment]
Figure 2 is the same as it was last week.

**Comment by allan-hicks** [comment]
A region was removed, thus the big backscatter circle is not there
anymore.  I think we should include it.

**Comment by allan-hicks** [comment]
Each circle is a half nautical mile, so it may be a few circles

**Comment by allan-hicks** [comment]
Did you receive a pdf from me?

**Comment by cgrandin** [comment]
Yes, we should insert it. Do you have a quick way of doing it?

**Comment by cgrandin** [comment]
I will try photoshop now.

**Comment by andrew-edwards** [comment]
Can you see if Rowan is there - he did the conversion to .eps last time. We know that works.

**Comment by andrew-edwards** [comment]
Rowan is on it.

Though we started with an .eps last time I think. It was big so we made it smaller.

The one figure we don't automate.....

**Comment by cgrandin** [comment]
I'm building the doc with one I made. Reduced the size by 70%

**Comment by cgrandin** [comment]
Mine is way to big on the page

**Comment by allan-hicks** [comment]
you can use scale=0.5 or whatever to reduce it furhter.

**Comment by allan-hicks** [comment]
But, lets try to keep the .eps file size less than 3mb to keep the doc size
somewhat reasonable.

**Comment by cgrandin** [comment]
We are working on it - stand by

**Comment by allan-hicks** [comment]
Thank you very much and I apologize for forgetting about this. i owe
everyone lunch!

**Comment by cgrandin** [comment]
Nah, it's not too bad. It isn't easy doing an assessment from scratch in 3 days

**Comment by cgrandin** [comment]
Ok, please merge to get the new figure. I also added Rowan in acknowledgements since he did this for us twice and last-minute.

**Comment by allan-hicks** [comment]
Thanks for doing that. And thank Rowan for me!

**Comment by andrew-edwards** [comment]
I moved Rowan's name in acknowledgments, since it made an extra page...
You do have to delete knitr-cache. 
Will email out the .pdf shortly....

**Comment by cgrandin** [comment]
Thanks Andy

**Comment by allan-hicks** [comment]
Looks good to me. Looking forward to the pdf!

**Comment by andrew-edwards** [comment]
Sent by email and uploaded to Google Drive. Latter worked and is probably quicker.

**Comment by allanhicks** [comment]
Done!

**Comment by aaronmberger** [comment]
Great! Talk soon...

On Friday, February 12, 2016, Allan C Hicks <notifications@github.com>
wrote:

> Looks good to me. Looking forward to the pdf!
>
> On Fri, Feb 12, 2016 at 1:00 PM, andrew-edwards <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I moved Rowan's name in acknowledgments, since it made an extra page...
> > You do have to delete knitr-cache.
> > Will email out the .pdf shortly....
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183486723
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/125#issuecomment-183486943>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*
