### ISSUE TITLE
Page 4 has a big conflict bunch of text that never got resolved....

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#126]

**Comment by allan-hicks** [comment]
I'll fix it

**Comment by andrew-edwards** [comment]
Line 24 page 4 has 200,000x t for some reason - I presume the x got put in by accident.

**Comment by aaronmberger** [comment]
my build from ~9:46 this morning doesn't have that x

**Comment by allan-hicks** [comment]
Yes, a dollar sign was in there in one of my versions, causing an error.
Not ure why. But, just fixed it.

I'll search the rebuilt doc for HEAD. I already searched for fishname and
found no instance.

**Comment by allan-hicks** [comment]
Yeah, i think I accidentally inserted it.  Not sure how.

**Comment by andrew-edwards** [comment]
Allan has resolved. Think you just hit x by accident. To keep us on our toes. I hadn't merged yet but looks like it's fixed.....
