### ISSUE TITLE
Erroneous file names in appendices for SS input files

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#127]
I guess we missed one before the cutoff... I will fix this

**Comment by allan-hicks** [comment]
Ah, who ever looks at those anyways?

**Comment by cgrandin** [comment]
Ya, I know - the OCD is kicking in haha

**Comment by andrew-edwards** [comment]
It isn't all automated. Looks like it is in the .rnw file. And the .pdf. 
base.model.name <- "39_preSRGbase_updated"    in all.r
