### ISSUE TITLE
When to present our justification for extrapolated survey biomass

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#133]
Should we present our arguments for the extrapolated biomass in the data presentation or the assessment presentation?  If in the assessment presentation, then the data presentation should present both and remain neutral.  I see it fitting in either.

**Comment by cgrandin** [comment]
I would think the arguments should be in the assessment section as it was a key choice in the assessment. If that's the case I'll put a comparison of the two in the data section as you suggest. Do you have the file with the unextrapolated numbers? Like the survey-history.csv file in the data folder. If so I can get this done pretty quickly.

**Comment by cgrandin** [comment]
Oops - Nevermind!! We already have a figure in the doc comparing the two so I'll grab that code. Both are in survey-comparison.csv.

**Comment by allanhicks** [comment]
I'll put the arguments in my responses to SRG requests. It will flow quite well.

**Comment by minnowslayer** [comment]
I vote for the end of the data presentation.

**Comment by allanhicks** [comment]
How about the beginning of the assessment prez. It fits nicely when I
review last year's SRG requests.

**Comment by minnowslayer** [comment]
fine with me! And perhaps you're right about its fit in another sense: the
decision about the extrapolation has a data analysis component that segues
nicely to the assessment presentation.
