### ISSUE TITLE
Out of order model indices for bridging

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#134]
The bridging for the tuning parameters was out of order, thus the legend colors do not match correctly. I have modified all.r to properly index the models. It seems to work fine for the plot in my presentation. This error can be seen when comparing Figure 14 to Figure 15. The green symbols in Fig 14 should match the blue symbols in Figure 15.

I'm not sure if this error occurs in sensitivities or retros, but it happens when the model names are not in the order listed in `models.list`.  It should be checked or just changed to the new method throughout.

**Comment by allanhicks** [comment]
Helps if I actually make the commit. Committed now to my account (change bridge model indices in all.r)

**Comment by aaronmberger** [comment]
Nice catch, Allan!

On Saturday, February 20, 2016, allanhicks <notifications@github.com> wrote:

> Helps if I actually make the commit. Committed now to my account (change
> bridge model indices in all.r)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/134#issuecomment-186725613>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by cgrandin** [comment]
Great thanks, I thought that grep code was pretty foolproof but alas no.
