### ISSUE TITLE
all.r fails with no "models" object

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#136]
I thought we had this bug fixed (see issue #52 ). If you start with a blank R workspace, all.r will fail because it looks for a models object.  To reproduce this error, do the following

1. Open R with nothing in the workspace
2. change the doc/r working directory
3. source all.r
4. answer: y, n, n, n

And, I get this error:

`Loading all data tables (csv files) from  ../../data`
`Error in file.path(model$path, wt.at.age.fn) : object 'models' not found`

**Comment by cgrandin** [comment]
Fixed. I added code to load the weight-at-age file from the base model so I could make the cohort weight-at-age plot for the prez.

**Comment by allanhicks** [comment]
Thanks! That was fast!

**Comment by cgrandin** [comment]
No worries, I'm on and off with the kids here so I happened to be on. I'll close it up!
