### ISSUE TITLE
report catchability (q), at least the MLE estimate

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#138]
MLE value in base model seems to be 1.13689, which is available in base.model$cpue
Previous assessment reported MLE value only in Table 12. Some additional code would need to be written to get SS to produce the MCMC samples for this quantity (which is calculated as an analytical solution, not a parameter).

**Comment by allanhicks** [comment]
Done, but I'm not sharing...

**Comment by allan-hicks** [comment]
One thing we (I mean you) can do in the future is set up q as an estimated
parameter. It will then be reported as a parameter in the mcmc. But, it may
be worth seeing if it affects convergence.

**Comment by taylori** [comment]
I know I've looked at analytical solution vs. parameter this in previous
hake assessments and it didn't seem to make a difference. Nevertheless, for
computational efficiency, it might be better to stick with the analytical
solution and just get Rick to report the analytical value of q
in derived_posteriors.sso.

For this year, I think reporting the MLE (as we did last year) is perfectly
adequate. I suspect that the increase in MLE estimates from 1.012 to 1.137
is likely due to the change in the scale of the acoustic survey due to the
removal of zeros, rather than an increase in scale of the selected
population or a change in selectivity.

**Comment by allan-hicks** [comment]
Good points Ian,
I have the version of SS that we used for the MSE that reports all sorts of
additional stuff. So, I will report the posterior for q this year. But,
working with Rick to provide a solution would be a good idea.

**Comment by allanhicks** [comment]
We should insert a new row into the parameter estimates table for catchability:

MLE  |  Median 2016  |  Median 2015
1.14       1.04                    0.92

**Comment by allanhicks** [comment]
Since this was assigned to me, I'm closing it!  See #162 to prove how quickly I forget things, even when assigned to me.
