### ISSUE TITLE
*SRG additional request*

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#145]
Right after you guys left the SRG asked us to investigate the issue with the B0/R0 in the sigma R sensitivity. i.e. why is this happening. We said we would do what we can tonight, but if the issue is too deep, they said fix it for next year. Something to show we looked at it would be sufficient.

**Comment by aaronmberger** [comment]
I'll work on this as discussed - look at alternative sigma r runs when M
fixed.  Also some tuned runs for varying levels of sigma R.

aaron

On Wed, Feb 24, 2016 at 5:30 PM, cgrandin <notifications@github.com> wrote:

> Right after you guys left the SRG asked us to investigate the issue with
> the B0/R0 in the sigma R sensitivity. i.e. why is this happening. We said
> we would do what we can tonight, but if the issue is too deep, they said
> fix it for next year. Something to show we looked at it would be sufficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/145>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
Thanks Aaron. The reason is that the R0 in the table is ln(R0). If you take
exp(ln(R0)), the ratio is fine.
