### ISSUE TITLE
Email attachment wouldn't work  - so committed kriging text as two-page .pdf.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#147]
Also uploaded the two-page .pdf to the Google Drive to everyone can review it.

**Comment by cgrandin** [comment]
Looks good. Thanks

**Comment by andrew-edwards** [comment]
Awaiting length-scale range from RT, then I'll move the table to the right spot and finish this off.

**Comment by andrew-edwards** [comment]
Done and committed.
