### ISSUE TITLE
AP reports as an appendix?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#149]
Should we include the AP fishery reports as an appendix? I feel that it would be good practice and hopefully encourage them to write these reports.  Do we italicize the text to make it clear that it is a quote, and not the writing of the JTC?

**Comment by cgrandin** [comment]
Yes, I agree with this.

**Comment by andrew-edwards** [comment]
I agree, but have a feeling the SRG was going to ask for this for next year. Do we have the report? I can start it now.

**Comment by andrew-edwards** [comment]
Can see how the italics look - whole Appendix may be overkill. So just have an explanation at the start of it.....

**Comment by allanhicks** [comment]
The Canadian AP is updating the report, so let's make sure we update it when they provide a new version.

**Comment by cgrandin** [comment]
Do we have the US report to include yet?

**Comment by allanhicks** [comment]
Not yet. I sent them an idea for a start, but if they don't get us one by
tomorrow morning, then it won't be included.

**Comment by andrew-edwards** [comment]
I'd rather go with a cut-off time of, say, 3pm today? We can't be expected to include (and format) stuff at the last minute.
I have an all-day meeting tomorrow starting at 9:30 - it's downtown and I'll have wireless, so can easily check in. Would rather get it submitted by then though (or even today?).

**Comment by cgrandin** [comment]
I will offer to do it if they get it to us by noon

**Comment by andrew-edwards** [comment]
Okay. I can check in at lunch. Make a note on this issue if you get something.

**Comment by andrew-edwards** [comment]
Think I'm done for now. I'm only on my small laptop screen so not ideal for looking through the document, so someone should look through with an eye to formatting.......

**Comment by andrew-edwards** [comment]
I did just have a skim through and formatting looks good. I'll check in again later, as it looks like you're still doing some minor tweaks....

**Comment by allanhicks** [comment]
The US AP will not be submitting a report this year.
