### ISSUE TITLE
What are base.model$natage and base.model$catage?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#15]
Last year's assessment said "The current assessment estimates a strong 2010 year class comprising 70% of the coast-wide commercial catch in 2013...".  I'm trying to find values in the model output so I can calculate the 70% value.

Presumably it's in base.model (see README.md notes), but it's not clear exactly where. In R:
> dim(base.model$natage)
[1] 110  32
> dim(base.model$catage)
[1] 51 31

Both look to have 21 columns that are age classes.  natage has 2 rows per year (I think one referring to beginning of year and one to mid), while catage has 1 row per year.

Does this mean that catage is input data and natage is model output?

And is this documented anywhere (I tried ?SS_readdat ). Thanks.

**Comment by cgrandin** [comment]
Fyi, the function that reads in the MLE output is called SS_output. Anything that comes from that function can be found in base.model$xxxx
The input age comps don't start until 1975 so I am not sure which is which. I'll leave it to Allan to answer this

**Comment by allanhicks** [comment]
This value was simply the proportion from the observed age comp. It isn't a model output. So, it should be available in the data, but I'm not familiar how you are reading it in the data or compositions right now and won't be able to have a look until later tonight.

**Comment by cgrandin** [comment]
I used natage in the construction of the estimated numbers-at-age table. We may need to check this..

**Comment by cgrandin** [comment]
I double-checked my table code and indeed 'natage' is what is shown in the estimated numbers-at-age table last year (I reproduced it with my code). The following will give you a data frame of what is shown in the table and you can then extract output from it by year and age:
base.model$natage[base.model$natage$"Beg/Mid" == "B", -c(1:6,8:11)]

**Comment by andrew-edwards** [comment]
Allan - the text refers to the assessment's (not the data's) estimated proportion of the fishery catch that is the 2010 year class. Chris - natage is the estimated numbers at age (of the population). However, your answers set me on the right track (eventually!).Turns out I needed

base.model$agedbase[base.model$agedbase$Fleet==1,]

which I figured out because the function make.age.comp.fit.plot() [which gives Figure 20, the cool one with the fit to the fishery age data colour-coded by cohort] which in turn calls age.fits(). I've added the calculation for year.class.2010.in.2013  and more to the end of all.r.  The numbers get put into the Exec Summary, with the 2010 year class estimated by the current assessment to have contributed 69% of the 2013 coastwide catch, 64% of the 2014 catch  [last year's assessment estimated 70% and 64%, so presumably all good], and 69% of the 2015 catch. 
Phew. Shows the advantage of having all the figure-generating code accessible to everyone though!

**Comment by andrew-edwards** [comment]
After all that, I'd used the Observed not Estimated values anyway (by mistake). Just committing (1 Feb 10:30pm).
Now updated code, Percentages (for 2013, 2014 and 2015) are now 69%, 66% and 65%, last year's assessment was 70% and 64%.  So Obs and Estimated are close enough anyway.

**Comment by cgrandin** [comment]
I feel like you have nailed this down and we can close it... You?

**Comment by andrew-edwards** [comment]
Allan - okay to close this? I think I figured it out, and useful to have all this as a reference.
