### ISSUE TITLE
Updated 2015 CV on survey

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#151]
The updated CV for 2015 survey point is 0.0828. Should we also update this while we are at it?

**Comment by cgrandin** [comment]
Andy and I think so, we are just across the border.

**Comment by aaronmberger** [comment]
I'm not sure it is necessary given that the extra SD will overwhelm this.

**Comment by andrew-edwards** [comment]
Was it updated in the end? (I could always check the input file I guess).
I'm off today, just downloading the new runs - good job doing them so quick. I'll rebuild on Monday.

**Comment by aaronmberger** [comment]
No, not updated by me.  I had them all done before realizing to include
this change.  Did mcmc include the updated 2015 CV?

On Friday, February 26, 2016, andrew-edwards <notifications@github.com>
wrote:

> Was it updated in the end? (I could always check the input file I guess).
> I'm off today, just downloading the new runs - good job doing them so
> quick. I'll rebuild on Monday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/151#issuecomment-189514801>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by aaronmberger** [comment]
And I see mcmc run also used previous (0.092) value.  Again, I'm not worried as the extra SD will overwhelm this small change.  I say leave it as is and make a note for next year.

**Comment by allanhicks** [comment]
As Aaron noted, it uses the larger cv. I did an mcmc with the new cv, but
have not compared the results.

**Comment by cgrandin** [comment]
We ended up using the previous CV, which was slightly larger than the new one. I think we have agreement at this stage to use what we have, so closing.
