### ISSUE TITLE
Note that all sensitivity runs are now loaded on google site (models 55-70)

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#152]

**Comment by allanhicks** [comment]
mcmc folder for 55_2016base is uploaded. The comparison for 2016 forecasted catch is a little more different than the MLE, but still not much different. See attached pdf for mcmc comparisons.

[compare_39.55_mcmc.pdf](https://github.com/cgrandin/hake-assessment/files/148675/compare_39.55_mcmc.pdf)
