### ISSUE TITLE
I managed to build the new doc.

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#153]
Wow. It took 4.5 hours for the code to load, forecast, run retros, and run partest. I tried to put only the models included in the new all.r in the models directory but it broke the code. So you must have all the models 00-70 in there. I figured at this point we could just live with this but I will need to do a major overhaul to the loading code once we are done this year's cycle. I also think it's time for me to get a new computer with a solid state drive. 
I found an error in one of the bridge model names, but it is fixed in commit 85d9f.
So it's good to go at this point, happy compiling!

**Comment by taylori** [comment]
Nice work, Chris.

I just finished looking over a printed copy of the previous version of
the document.

Nice work everybody on putting this together. There are a few minor
changes in phrasing that I would suggest but overall it looks great.
I'll get my suggestions posted as issues over the weekend and you all
can comment on whether they make sense or not.
