### ISSUE TITLE
clear out unnecessary files from "models" folders

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#159]
Next year we might consider using a batch script or R code to clear out junk files that we'll never use like ss3.p0\* and ss3.r0\* before the upload to Google Drive. This won't reduce the total disk space much (since the covar.sso file is much bigger than the junk files), but might make things quicker to transfer. Or maybe this would just be an unnecessary tedious step.

I'm creating a new "2017 assessment" Milestone with which to associate stuff like this.

**Comment by cgrandin** [comment]
Excellent... We should also check what is being stored by SSgetMCMC and SS_output, and have them only store what we are using in the assessment if possible. This would keep the rdata files smaller, reducing the time it takes to load during the doc build.

**Comment by taylori** [comment]
Good idea. We could definitely create a hake-specific modification to these
functions, either a separate function (which might be harder to keep
updated in parallel) or a wrapper that would strip away list elements that
take up unnecessary space.

**Comment by cgrandin** [comment]
A wrapper might be easier, but more difficult to maintain - if the function changes in the package it could break the code. Perhaps we need a hake branch of r4ss?

**Comment by taylori** [comment]
Pushed back to milestone for 2018

**Comment by taylori** [comment]
clean.bat file uploaded to Google Drive contains the following commands to clear out extra ADMB files that aren't required for reading the model results. We could run this script to clear out the directory where any new model is run before uploading the remaining files to Google Drive.

The files include things like those with extension *.p01, *.p02, etc., all deleted by the first line, which are apparently copies of the .par file associated with the parameters estimation at each phase, but are definitely not needed once estimation is complete.

I think some of the deleted files are necessary for running MCMC, meaning that you would need to do the model estimation again prior to running the MCMC rather than starting the MCMC without estimation the results of a previous model if these files have been cleared out.

Feel free to edit the script as you wish. @cgrandin also had some ideas for how to run this recursively on past folders.

```
REM batch file to clean out extra ADMB-produced files
del *.p0*
del *.b0*
del *.r0*
del *.std
del *.htp
del *.eva
del *.tds
del *.bar
del *.cov
del *.dep
del *.hes
del *.rpt
del *.cpp
del *.log
del *.obj
del *.tmp
del *.ecm
del *.mc2
del *.mcm
del *.hst
del *.psv
del gradient.1
del gradient.2
del gradient.3
del gradient.4
del gradient.5
del tmp_admb
del variance




```

**Comment by taylori** [comment]
`del *.psv` is problematic for mcmc, removing from future version, re-running extra-short mcmc and uploading to 2018.18 directory.

**Comment by taylori** [comment]
Not very big benefit of using the clean.bat to cleanout files. There may be different versions floating around in the directories, one that deletes the .mcm and other mcmc files when it shouldn't. Probably safer to just not bother.
