### ISSUE TITLE
Maps in Figures 1 and 2 as postscript

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#16]
Just a reminder for whoever is making the maps in Figures 1 (overview map) and 2 (acoustic backscatter map) to save them as *.eps (encapsulated postscript). Someone just checked for that ArcGIS (which I think is what the backscatter map is done in) can save as *.eps, and it can.

**Comment by allanhicks** [comment]
Just sent Figure 1 to Chris and uploaded R code to doc/r folder.  I sent the eps to Chris and asked Julia for an eps of the backscatter figure.

**Comment by allanhicks** [comment]
I added the data needed to create the overview map into a mapData directory in the r directory. I am not sure if this is the best way to do this, so feel free to make changes as needed. The figures-overviewMap.r will need to be further updated to work with the knitr code.

**Comment by andrew-edwards** [comment]
Great. The overview map doesn't depend on the model run, so presumably is best just made outside of knitr (as you've done) and then just imported in the normal latex way. Useful to have the code though. Chris - I can do that if you like, unless you can do it quickly.

**Comment by allanhicks** [comment]
Thanks. I am liking the idea of creating figures externally and using knitr
to simply bring them in. The reason I like this method is that everyone may
create a figure to include and they could simply create the figure and
include it, they wouldn't have to figure out where in the code to insert
htis figure and the details of knitr, and it would be easy to add a figure
at the last minute. For example, my investigations on the CV of the age-1
index, or maturity data.  I also see the benefit of the generalized code
for certain figures related to the base model, and I think any figures
created with r4ss could be in the generalized section.

**Comment by andrew-edwards** [comment]
Done. Overview map is done in knitr (easy to adapt). Backscatter map done externally, and we got it shrunk down in size. I was just about to close this - Chris beat me to it!
