### ISSUE TITLE
Updating SRG draft report

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#160]
I was able to build a clean document with the new forecast levels. I'm updating the SRG report and providing a few other comments right now. Feel free to provide comments to the SRG report, or let me know what you think and I'll incorporate them into a JTC response.  Just wanted to make sure nobody else was updating SRG report numbers.

**Comment by cgrandin** [comment]
Thanks Allan. I was also able to make the document with the updated catch numbers and it is looking good. It seems like we are nearly done, with the lack of emergency dialog on here today. Should we compare our tex files one last time?

**Comment by aaronmberger** [comment]
I'm getting an error when building:
Error in base.model$wtatage$fleet : 
  $ operator is invalid for atomic vectors

So will be looking into this now.

**Comment by allan-hicks** [comment]
I would make sure to reload all models, and not use smart load.  That has
helped me with errors.  I also have only the specific models needed in my
models folder (21 folders I think), so loading doesn't take too long.

**Comment by aaronmberger** [comment]
built now, all fine

**Comment by allanhicks** [comment]
I emailed some comments and updates. Feel free to supply your own comments to the SRG.
