### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#161]
I just remembered that in past assessments we did the footers as:

left: species name  (so as we have)
right: section or appendix name

For example: 
<http://www.dfo-mpo.gc.ca/Csas-sccs/publications/resdocs-docrech/2013/2013_092-eng.pdf>

I can do that fairly quickly - it does look good and is very useful when flicking through the document (either printed or the .pdf). Having just one footer looks a bit unbalanced (unless printed), which we now currently had (becuase the right footer said something like "DRAFT - do not cite".

Any thoughts? It won't take me long. Document seems to build fine.

**Comment by cgrandin** [comment]
That does sound useful, but I don't mind either way. If you think you can do it fairly quickly..

**Comment by andrew-edwards** [comment]
Done.

**Comment by taylori** [comment]
Sorry I'm not keeping up on building the document so maybe this is obvious.
I like the footer idea--thanks for doing that.

The draft document (unlike the PoP doc you linked) also has a horizontal
line at the top of each page--is this still there and what purpose does it
serve?

**Comment by allan-hicks** [comment]
Ian, that is the latest trend.  Chris and Andy are our document stylists,
and have been doing a great job bringing us into the future.

OK, I definitely watched too much of the Academy Awards with my wife.

Allan

**Comment by taylori** [comment]
I certainly believe that Andy and Chris deserve a gold statue for their
work making this document look good.
I'm OK with the top line to keep up with the times.

**Comment by andrew-edwards** [comment]
Ian - I hadn't really noticed the top line! Since we have no header text (maybe there was for another assessment) I'll try taking it out and commit. Aha - our Canadian assessments now require it (yes, really, someone cares!). For this assessment we could undo most of the flaky formatting (e.g. Arial font) that we're normally forced to use.

**Comment by andrew-edwards** [comment]
Actually, it's not quite what I thought. So will just leave for now....

**Comment by taylori** [comment]
I'm perfectly OK with Arial, horizontal lines, and anything else that's
already in place and doesn't require change, regardless of whether it makes
anyone at FOC happy or not.

**Comment by andrew-edwards** [comment]
Arial just make me want to start every sentence with Illuminating Illinois.

**Comment by allan-hicks** [comment]
Seems to me that Arial makes you Ill.

**Comment by taylori** [comment]
You all sounds like you need a vacation.
