### ISSUE TITLE
Section 3.3: 2016 SRG

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#163]
Anyone volunteer to tackle this section? Just a short description of the SRG meeting and what happened there.

**Comment by andrew-edwards** [comment]
I already took it out - I asked at the meeting and people (including SRG I think) agreed it wasn't needed this year, only really if there was some major thing that they asked us to do.

**Comment by allanhicks** [comment]
Sounds good. It is not specifically in our terms of reference. I think that it would be useful to include if there are any important changes or disagreements at the SRG meeting, but this one was quite smooth.
