### ISSUE TITLE
Compare .tex files

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#164]
What say we all do a build of commit number 5b36f  ('Corrected the citation....' - my latest one since I'm winning the Network Graph race!). And then compare .tex files to check we're all good. 
I guess we have to email then to each other, which is fine. I have to leave soon. Chris can probably easily compare them in the morning.

**Comment by taylori** [comment]
I'm a bit behind on model loading and document compiling so I'll skip this
comparison, but go ahead without me.

**Comment by andrew-edwards** [comment]
Ian - no worries. Last time all four of us had identical .tex files (except comments regarding R versions and xtables), which was very gratifying. Presumably the .pdf files would all be the same as well.

**Comment by cgrandin** [comment]
All our TEX files are identical for commit 5b36f.

**Comment by andrew-edwards** [comment]
Great. I'm source-all.r-ing again after merging (not sure what changed with thelatest commits) and deleting knitr-cache to rebuild...
