### ISSUE TITLE
Last call for edits..

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#166]
I have gone over the doc fairly extensively, and made a few fixes to hard-wired values and cosmetic changes to the parameter tables. I think we are good to submit unless anyone would like to go through it once more.

**Comment by aaronmberger** [comment]
I've been through it as well and had no more edits.  So good to go from my
end.

On Tue, Mar 1, 2016 at 12:59 PM, cgrandin <notifications@github.com> wrote:

> I have gone over the doc fairly extensively, and made a few fixes to
> hard-wired values and cosmetic changes to the parameter tables. I think we
> are good to submit unless anyone would like to go through it once more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/166>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by taylori** [comment]
As noted on issue #158, I'm good but give Allan time to return from lunch.

**Comment by andrew-edwards** [comment]
I'm good. I just merged Chris's and built the latest - I uploaded the .pdf to Googe Drive - hake-assessment-cece0987.pdf, to identify the commit number.

**Comment by cgrandin** [comment]
Ok, I'll be offline for about an hour.. I'll check back then and see if we are good to go. Cheers and nice work everyone!

**Comment by andrew-edwards** [comment]
If Allan's good he could probably submit that .pdf. Though someone should have a final quick skim through (I'm in a workshop).

**Comment by taylori** [comment]
I'll do a quick skim right now.

**Comment by allanhicks** [comment]
Ian and I are flipping through the doc for one last check.  I am resourcing all.r and will rebuild the document one last time. Would you all like me to submit this final version to Miako, or would someone else prefer to build the document and send it out?

**Comment by cgrandin** [comment]
If it's all good, I would say go ahead and submit! Just let me know which commit number it was so I can make a tag as final 2016 version

**Comment by aaronmberger** [comment]
Agree, send out after final glance through.

On Tuesday, March 1, 2016, cgrandin <notifications@github.com> wrote:

> If it's all good, I would say go ahead and submit! Just let me know which
> commit number it was so I can make a tag as final 2016 version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/166#issuecomment-190950795>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment]
So merge mine and then we're good. I'll upload a .pdf also to the Google Drive if you want to quickly compare yours. If you're using Adobe Acrobat Pro chose Advanced - Compare Documents. It just ran really quick for me, and correctly showed that only the date had been added.

**Comment by andrew-edwards** [comment]
Just uploaded hake-assessment-4ce1b5a.pdf to Google Drive WriteUp folder. I can do a compare if someone else has a .pdf but doesn't have a version of Adobe that has the Compare thing.

**Comment by andrew-edwards** [comment]
Allan - are you sure you're caught up. Not according to your Network Graph: 
<https://github.com/allanhicks/hake-assessment/network>
Or maybe you just haven't pushed.....

**Comment by andrew-edwards** [comment]
i.e. Chris and I always fetch, merge, push.

**Comment by andrew-edwards** [comment]
Can see you've pushed now! Github means we can all keep an eye on each other ;)
Chris is fixing one more thing though....

**Comment by allanhicks** [comment]
I was on the merge step when you sent this! I should be caught up now and made a couple of edits on the one-pager.

**Comment by cgrandin** [comment]
I'm waiting to merge now to see if Allan finds anything else. Just to note, Allan increased the q values' precision in a previous commit, ec55dc, so make sure you've re-sourced since then!

**Comment by andrew-edwards** [comment]
Pretty sure I re-sourced. Kind of why I'd like to compare a couple of .pdfs.

**Comment by allan-hicks** [comment]
Is there an easy way to tell when the last change to a file other than .rnw
was changed? Probably a good idea to resource anyways.

**Comment by cgrandin** [comment]
I have everything built. I'll upload it to the google drive so Andy can compare..

**Comment by allan-hicks** [comment]
My last commit is bfecc6, and I'm building off of this.

**Comment by cgrandin** [comment]
Grandin-8cd00-hake-assessment.pdf on google drive

**Comment by cgrandin** [comment]
We are all working off merge commits which are all going to be the same... i do it sometimes to make my network graph look nice even though nothing has changed

**Comment by cgrandin** [comment]
No easy way to check only non-rnw files without writing a script. Something cool to check is the Blame on a particular code file. It's amusing

**Comment by andrew-edwards** [comment]
Table i has moved - is that okay? It should be automated but by manually fixing things it overrides latex a bit... I've seen an introduced break later on that I'll fix (I had some \newpage 's in the main text).

**Comment by allan-hicks** [comment]
i sort of like where it is. (notice the i)

**Comment by allan-hicks** [comment]
Although, it may be nice to have with Figure j, since the table and figure
are the same.

**Comment by cgrandin** [comment]
I think it's fine for now. I like the use of \enlargethispage{\baselineskip}. Didn't know that one.

**Comment by allan-hicks** [comment]
Chris, your pdf is a commit behind.  My last commit was to fix the research
and data needs section to have 1-4 on a page then 5-13 on the other.

**Comment by allan-hicks** [comment]
It is a command that should be deleted before beginning next years
document. I only use it for final tweaking, but as we saw, it can affect
other things as well.

**Comment by taylori** [comment]
I think you all need to step away from your computers and go outside and be
reminded that there's a big world out there which doesn't care about
hanging phrases and which page Table i is on.
Nothing against trying to get it right but in the interest of getting it
done, we have to stop somewhere, or at least not have you all trying to fix
the spacing and breaks simultaneously at risk of introducing further issues.

**Comment by cgrandin** [comment]
Yep, I'm not fast enough! How about we agree when to cut it off and do the comparison and I'll re-build. Yes Ian, I agree..

**Comment by allan-hicks** [comment]
Andy, are you going to re-jigger Figure i?  I'll wait for a commit before
building the final doc.

**Comment by allan-hicks** [comment]
I agree too. If Andy wants to commit one last change, go ahead. Or, if he
wants to get back to the conference we keep pulling him away from, then we
can go from here.

**Comment by andrew-edwards** [comment]
Is Figure i okay? It's mostly automated, but I had done a few hardwired things a while back as I hadn't expected the text to start changing so much......
I'm fixing something else right now.
Agree with Ian - please stop doing minor tweaks that can introduce issues. And there's a 'mixer' going on here that I want to go to ;)

**Comment by taylori** [comment]
Andy, you definitely got to get to that mixer because you've got some
scintillating stories to tell about commit bfecc6.

**Comment by andrew-edwards** [comment]
Okay. I'm done. Have just committed. Will leave Figure i where it is, though havne't looked at it,

**Comment by cgrandin** [comment]
Are we all done?

**Comment by allan-hicks** [comment]
Yes, I uploaded a tex file if you want to compare. I'm happy to use my pdf
or Chris we can use yours. And, you should send an email to Miako with the
final document, since you are the lead author.  Please cc the JTC members
(or let me know if you would like me to send the doc).

Thanks everyone! Sorry for the last minute flurry! I must have been
affected by the windstorm that blew through this afternoon.
Allan

**Comment by cgrandin** [comment]
Allan, would you mind sending it? Our webmail system is really crappy and I would have to write in all emails by hand and try to find Miako's info - there is no search function...

**Comment by cgrandin** [comment]
Grandin-0445699-hake-assessment.pdf

**Comment by taylori** [comment]
Thanks Chris. Allan is chatting with somebody but knows that he will submit
this.

**Comment by cgrandin** [comment]
Ok, thanks guys. I just saw the SRG report come in from her as well. I'll keep checking until I know it's been sent. Cheers
