### ISSUE TITLE
date on title page

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#167]
I feel that we should have a date on the title page so that it is clear what document this is, and it can be verified when referring to a document.  I realize that draft is removed, but I think it would be nice to have a date. Any objection? I know where to make this edit in the rnw files.

**Comment by cgrandin** [comment]
No objection, just commenting the date call out I think would do it

**Comment by andrew-edwards** [comment]
Can we write it as 1st March 2016   or March 1st 2016. I think uncommenting \date{}  will give something semi-ambiguous like 2016-03-01.  I can automate it for next year (there are options for \date{} I think). But, yes, a date on the front is fine.

**Comment by cgrandin** [comment]
Nice idea Andy, if nobody has started this, I will do it now..

**Comment by andrew-edwards** [comment]
Done it.

**Comment by andrew-edwards** [comment]
Is good to have, since there is no actual date of publication (like our stock assessments or a journal article).
