### ISSUE TITLE
Error in values in Executive summary

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#168]
This is the same text I fixed in the model projection section. I have it done but just hold off for new commit...

**Comment by andrew-edwards** [comment]
I think Allan has fixed it - check his commit.

**Comment by andrew-edwards** [comment]
Oh, it was different. Is the rest correct then? I haven't been checking.

**Comment by allan-hicks** [comment]
I have not changed the Exec Summary.

**Comment by andrew-edwards** [comment]
Sorry - think you were doing one-page summary.

**Comment by cgrandin** [comment]
It's done
