### ISSUE TITLE
check page numbering?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#169]
I just made an edit for arabic page numbering throughout. Do you think there may be hidden issues?

**Comment by andrew-edwards** [comment]
Did you edit the citation bit also? Take out the xxi part, and check that the LastPage comes out correct when you latex it (twice, maybe three times are needed).

**Comment by andrew-edwards** [comment]
Or we could go Roman numerals throughout ;)

**Comment by allanhicks** [comment]
Yes, and the citation seems to work correctly with two "tex's".  Roman
numerals throughout with Arial font. I'm on it!

**Comment by andrew-edwards** [comment]
Your edits look fine. I'll merge and take a look.

**Comment by cgrandin** [comment]
Building now..

**Comment by andrew-edwards** [comment]
I'm just rebuilding, but guessing that may have to fix it to start on page 2 on second page. Then the pdf pages will correspond to the actual page numbers. I'll check and fix if necessary...

**Comment by cgrandin** [comment]
It looks good to me. I thought it would be harder to do than that!

**Comment by cgrandin** [comment]
Andy, it works as-is when you search for a page in the pdf it goes to the right one.

**Comment by allan-hicks** [comment]
Yes, it is off by 1. I'll make the change. This will help when printing
specific pages

**Comment by cgrandin** [comment]
Weird, mine is not off by one. But I have 2011 adobe.

**Comment by andrew-edwards** [comment]
But in ghostview it's off by one. I think Allan and I are making the same change - just uncommenting a line and making it:
\setcounter{page}{2}

**Comment by allanhicks** [comment]
If you try printing pages 2-3, it will start at the TOC.  What the heck are
you guys doing back in 2011?  Isn't Adobe Reader free?

**Comment by andrew-edwards** [comment]
Committed. Seems to work. Maybe not for Chris.

**Comment by cgrandin** [comment]
I bought it back then, and never wanted to pay again since it seemed to work fine!

**Comment by taylori** [comment]
As long as we're digressing about PDF software, do you guys ever use
Sumatra PDF Reader?
It's nice because it automatically refreshes when you rewrite a file rather
than giving you an error.

**Comment by cgrandin** [comment]
I just compiled from scratch and it still works fine, so I think the page numbering is good. I didn't know about that Ian, it sure would help when doing this sort of thing. It's annoying when it fails because you've left it open.

**Comment by taylori** [comment]
Supposedly you can also add something to your R script or batch file that
will close the file but I don't know how to do that.

**Comment by andrew-edwards** [comment]
Looks good. I've uploaded hake-assessment-andy-5ad46.pdf corresponding to our latest commit. I deleted my earlier ones from Google Drive.

**Comment by cgrandin** [comment]
I think we are on fe55 now

**Comment by cgrandin** [comment]
fast and furious

**Comment by andrew-edwards** [comment]
Yes. Allan keeps leaping ahead.....

**Comment by allan-hicks** [comment]
Stop me!!!!!

**Comment by allan-hicks** [comment]
Hah, even closing this issue can't stop me! I think I made my last commit.
I'm building now. Send me a pdf if you want and I'll compare them.
