### ISSUE TITLE
Submit?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#171]
Alright, I'm starting to edit page breaks. I think that we are done. Any objections to me building it and submitting it?

**Comment by cgrandin** [comment]
No objections! Let's do this

**Comment by aaronmberger** [comment]
No objections, just trying to keep up with posts...;)

On Tuesday, March 1, 2016, cgrandin <notifications@github.com> wrote:

> No objections! Let's do this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/171#issuecomment-190983830>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*
