### ISSUE TITLE
Are you getting undefined refs?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#172]
Page 33

**Comment by cgrandin** [comment]
Nope, mine's good

**Comment by allanhicks** [comment]
Yeah, I see that Chris' is good. So, Chris or Andy, can build the final version when you have finished all commits?

**Comment by cgrandin** [comment]
I will -  Andy you should head out to the mixer

**Comment by andrew-edwards** [comment]
Keep latex-ing and undefined should go away.

**Comment by allanhicks** [comment]
I wasn't latexing enough. I'm good now and uploaded my tex file for comparison.
[hake-assessment.zip](https://github.com/cgrandin/hake-assessment/files/153882/hake-assessment.zip)

**Comment by andrew-edwards** [comment]
Trying a compare .pdf on the version that Allan submitted, but it's taking a while. Which is a little worrying, since the compare I did earlier was really quick...
Aha - Allan, your bcfecc.. one has no references blah blah - aha - I'll try your new one.

**Comment by cgrandin** [comment]
I'll compare Allan's tex with mine once it's finished building

**Comment by cgrandin** [comment]
Our tex files are identical Allan

**Comment by andrew-edwards** [comment]
Okay. I can easily compare .pdf's. As long as they're similar enough (else it takes a while). 

But I'm off  - have to get my son. Chris can submit.
