### ISSUE TITLE
include estimates of total biomass or summary biomass in document

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#173]
Table 11 in the 2016 assessment document could easily have a column added showing the estimates of age 3+ biomass and/or total biomass (all ages). Those might be a better measure of biomass available to the fishery than female-only spawning biomass (although doubling spawning biomass gets you a good approximation)

**Comment by cgrandin** [comment]
I agree - Just a reminder in case someone else gets to the before I do, all mcmc calculations are done once during the loading phase. See calc.mcmc function, and the mcmccalcs item of the base.model object.

**Comment by taylori** [comment]
We can add total biomass to make.median.posterior.table using base.model$timeseries$Bio_all (related to years in base.model$timeseries$Yr)

Also, if time allows, we could calculate available biomass (which is not a direct output from SS) by multiplying selectivity * numbers * weight for each age in each year. This calculation is done in the code that I've been working on related to issue #174.

**Comment by taylori** [comment]
I've started some work on this so will self-assign, but nothing is complete so I will see if I can do it over the weekend. The document will be fine without it if I don't get it done.

**Comment by taylori** [comment]
I still think that this is important but it's more complex than I realized because the $timeseries$Bio_all column should really be read from all 999 mcmc outputs. Thus both "total biomass" and "available biomass" would require addition to the mcmc-extra calculations. That's feasible but not a high priority for the pre-SRG version of the document.

**Comment by taylori** [comment]
This change and the change required for issue #174 can be completed together sometime after the pre-SRG document is finalized (either before the meeting for the final version, or for 2018).

**Comment by taylori** [comment]
Changing this to 2018 milestone to match related issue #244. If we get it done this year between pre-SRG document and final version, so much the better.

**Comment by taylori** [comment]
Posterior median and 95% intervals for total biomass (females and males of all ages) are now included in model$extra.mcmc$timeseries in the columns "Bio_all", "Bio_all.0.025", and "Bio_all.0.975". If we have time and interest, these could be added to Tables 16 and 17.

**Comment by cgrandin** [comment]
Nice work on all of this Ian, you fixed a bunch of issues in one go! I will assign myself to add the new columns to the tables.

**Comment by cgrandin** [comment]
I've added the values to the tables (commit 5cb673eba8a390a9e337a104419a5f314c055001), but can you please check them? I removed the first two elements of the vector - if memory serves they are B0 and Binit. Also removed the last two as they are projections. Am I correct? Thanks

**Comment by taylori** [comment]
Thanks for doing this. What you did worked exactly correctly, but I revised the filter in commit 3d9c885 to use a column of year values which should make it more robust if we ever change the length of the forecast.

**Comment by cgrandin** [comment]
That's a way better way of doing it - Thanks! Let's call this done.
