### ISSUE TITLE
report predicted catch at age for forecast years

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#174]
Predictions of catch at age (in both numbers and biomass) have been frequently requested in AP and JMC meetings. We should probably routinely report these values in tables and figures in future assessments.

**Comment by taylori** [comment]
Note: there is also interest in both past and forecast catch at age by country but without separate sector- or country-specific selectivities, getting reasonable estimates would be difficult.

**Comment by taylori** [comment]
I just wrote some code to produce a figure that includes MCMC uncertainty. This function needs to be generalized and have numerical output into table format as well as the included figure.
https://github.com/taylori/hake-assessment/commit/bdb7092252b514054633f4fd5fef7f2171484285

**Comment by taylori** [comment]
Code in /doc/r/r-functions/figures-age-comp-forecast.r produces the plot below but requires reading additional info from 999 report files in extra-mcmc, creating a new (small) RData file to store that info. I haven't integrated it into the document because I don't want to break anybody's document compiling at this late stage. If we want the fig in the document, we could do any of the following (from easy to harder)

- wait until the post-SRG version of the document to add this fig
- put an .eps file for this figure in doc\main-figures rather than make it dynamic
- add in the code as-is and trust that it will work
- integrate the read of the required info into the existing extra-mcmc calculations

![image](https://cloud.githubusercontent.com/assets/4992918/22428020/47f93578-e6ba-11e6-93b9-154b72716d10.png)
EXAMPLE CAPTION: Forecast age compositions in numbers and in weight for the 2017 fishery catch (combined across all sectors). Gray bars show median estimates. Thick black lines show 50% credibility intervals and thin black lines show 95% credibility intervals).

**Comment by cgrandin** [comment]
The best way I think would be to modify fetch.extra.mcmc() in doc/r/r-functions/load-models.r so it gets the additional info, and then re-run build(). That just runs the fetching code, and not the re-running code, so it's fast. That way we just add one line to the plotting function to access the sub-list extra-mcmc. I would do it but I'm not sure where to find the info in the Report files. If you could point it out, I can do it

**Comment by andrew-edwards** [comment]
Why not just throw the .eps figure for now and then automate after we submit? We're not going to change the model runs before submitting...
Figure's good, especially since people always ask for it.

**Comment by taylori** [comment]
Will add .eps figure for this year, will then change milestone to 2018.

**Comment by taylori** [comment]
Figure added so will close issue but open a new one to remind us about additions to fetch.extra.mcmc under 2018 milestone.
