### ISSUE TITLE
include maturity ogive in document

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#175]
easy to do and will save effort looking it up from the wtatage file and dividing out the fecundity=weight

**Comment by andrew-edwards** [comment]
Glad this is here - Chris and I spent a while this morning trying to find the maturity ogive (we couldn't!) to help understand the large increase in estimated spawning biomass (we wanted to check the maturity of the age-2's).

**Comment by taylori** [comment]
The maturity x fecundity used in the model is represented in the first numerical row of the wtatage.ss file. The values haven't changed since the first empirical weight-at-age model for hake was developed in SS in 2011, and they are based on taking the Dorn (1997) estimates of maturity at length and converting these to age using estimates of length at age from some other model that included length data and estimated a parametric growth curve and a weight-length relationship. The result has age-2s with about 10% of the spawning output as the largest, fully mature individuals:
```
a0 a1     a2     a3     a4    a5     a6     a7     a8     a9    a10    a11    a12    a13    a14    a15    a16    a17    a18    a19   a20
 0  0 0.1003 0.2535 0.3992 0.518 0.6131 0.6895 0.7511 0.8007 0.8406 0.8724 0.8979 0.9181 0.9342 0.9469 0.9569 0.9649 0.9711 0.9761 0.983

```
The same approach used previously could be updated with new estimates of maturity at length (which seems to be very similar based on maturityNS.eps), and new estimates of growth and the length-weight relationship.

An alternative approach would be to directly estimate maturity at age since many (if not all) of ovaries are collected from fish that also have otoliths collected.

For inclusion in SS, the maturity would need to be multiplied by fecundity at age, which raises the question of whether fecundity is directly proportional to body weight or not.

For now, we can at least report the two ogives of maturity at length as shown in the maturityNS.eps figure. I can attempt to collect that information.

**Comment by taylori** [comment]
I forgot to note that the 2017 spawning biomass includes the contributions of the 2014 cohort at age-3, when their contributions are up to 0.25 from 0.10 based on the vector from wtatage.ss in my previous comment. The very large estimated size of this cohort seems to be based on the U.S. fishery catching LOTS of age-2s in 2016. We should add a sensitivity including more flexible time-varying selectivity to see what impact that has on the estimated size of the 2014 cohort.

**Comment by taylori** [comment]
I was able to find code from Allan that made the maturity figure in our document. Tomorrow I should be able to easily modify things to output numbers into a CSV for inclusion in a new table for the document.

**Comment by taylori** [comment]
Maturity at length table added to the document in recent commit. Maturity-at-age equivalents are added to text  for informational purposes, but both things are not used directly by the model, which depends on a combination of maturity * weight as noted in text.
