### ISSUE TITLE
produce something similar to spreadsheet created by Shannon

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#176]
In recent years, Shannon Mann has used assessment model output to develop a spreadsheet looking at estimated catch at age by country and various other quantities of interest. If we can automate the process of developing this spreadsheet, or at least speed up it's development by providing the necessary information in a format closer to the quantities the AP is interested in, that would save Shannon time and give opportunity for the JTC to make sure the calculations were being done in the way we feel is most logical. This is related to issue #174.

**Comment by taylori** [comment]
Agreed to wait until higher-priority tasks are complete then will revisit this issue.

**Comment by andrew-edwards** [comment]
Will ask at SRG what they explicitly want, if they want us to produce something.

**Comment by taylori** [comment]
I will try to get familiar with the Excel file prior to the SRG, but have assigned 2018 milestone just to clean up the issues list. I think now all issues are assigned 2018.

**Comment by andrew-edwards** [comment]
I don't understand Excel and so can't help :) Be good in the SRG to maybe start from scratch and ask what they really want (and if they do want it, not everyone might). It'd be easier for us to start with an explanation and then work out the calculations and then write the code. Chris spent a lot of time trying to reverse-engineer the spreadsheet, but starting from scratch may be more efficient. But if you can figure it out then by all means ...

**Comment by andrew-edwards** [comment]
SRG meeting. Shannon: useful to know if lots of age-2's had been caught in the past.  
Trevor: Really want: 2010 cohort - age-1 %age weight that survive, natural mortality, caught.
See what SRG recommends....

**Comment by taylori** [comment]
Double-checked SRG report on 12/13/17.
