### ISSUE TITLE
test SS version 3.30 to make sure model matches and document can be built

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#177]
Ian to run MCMC first then upload files to Google Drive to share with others for testing

**Comment by taylori** [comment]
Files uploaded. Chris rewrote r4ss function SS_readdat_3.30 which was required for the new software. Probably don't need to focus too much on this until after the JTC meeting.

**Comment by cgrandin** [comment]
I think we agreed to use SS 3.24 this year?
If so we can close this.

**Comment by taylori** [comment]
Yes, looking at where we are in the schedule and accounting for time-off
during the holidays, I'm all the more convinced that this is the way to go.
We may still want to do a sensitivity analysis comparing the 3.24 base
model to 3.30 if we have time or interest in exploring features of the new
SS, but that's not necessary and it's safer to not depend on the new SS
version.

**Comment by cgrandin** [comment]
Thanks Ian, sounds like a plan. I'll close this and we can move on to other issues.
