### ISSUE TITLE
update files related to survey for adding 1995 point

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#178]
This includes data/kriging-parameters-1995-2015.csv

**Comment by taylori** [comment]
I think we just need to remove this table (created by make.kriging.parameters.table) and move kriging parameters to the text.

**Comment by andrew-edwards** [comment]
Does Figure 2 (backscatter map) consequently need to be updated? The acoustic team gave it to us last year - if needed again then ask for .eps. Our colleague Rowan converted to .eps last year, and it's a bit fiddly.

**Comment by taylori** [comment]
Good question. I will ask.
I would also like to update Figure 9 so that it shows
* time-series from 2016 assessment
* updated time-series used in this assessment
* updated time-series if extrapolation were not included

I will re-assign this issue to myself.

**Comment by taylori** [comment]
Julia who produced the map of acoustic backscatter reports that it will not require any update based on the data processing they did in 2016. Maps of estimated biomass output from the kriging process will be updated for presentation to the SRG but don't impact our document.

**Comment by taylori** [comment]
Noted Jan 27 that this is a lower priority.

**Comment by taylori** [comment]
Map updated, table of kriging parameters has been removed (subsumed into text) and text describing survey has been updated. I cut out a paragraph that justified use of the extrapolation since I think it's adequate to say that the SRG supported it in the 2016 assessment. There is a separate issue associated with using landscape mode for the map, so I will close this issue.

**Comment by cgrandin** [comment]
I just put that issue in case I had time, it's all good!
