### ISSUE TITLE
My code currently breaks when I do have the knitr-cache still in there

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#18]
Not sure if it was anything I added in my last two commits, or what Chris did in my latest merge. It breaks around   main.tv.selex.uncertainty    in main-figures.rnw. Chris does have a warning in the comments there, so maybe something needs tweaking.      I have to leave now so flagging it to look at later/tomrrow.

**Comment by cgrandin** [comment]
Just make sure no source("all.r"), answering no to all the questions, then save.image(). I do this every time I fetch/merge, as the R code is always changing. I have just fetched/merged everyone and the document builds properly.

**Comment by andrew-edwards** [comment]
Now works. Merged Chris's latest (which didn't fix it), and restarted both my R windows (one where I do source("all.r") and one where I run knit(..)  ) and that worked. Not quite sure why, I may have redefined something somewhere, and maybe shouldn't keep R windows open for days on end without closing them!
