### ISSUE TITLE
explore sigma-R "more fully" as per SRG recommendations

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#180]
could include profiles with more values or iteratively tune following options in Methot & Taylor (2011).

**Comment by cgrandin** [comment]
Ian, could you send me a copy of the paper? I'd like to see how that works. Thanks

**Comment by taylori** [comment]
The SS_output function produces a table called $sigma_R_info which includes an "alternative_sigma_R" in the final column, which is an estimate based on the Methot & Taylor paper. The value depends on the period of recruitment deviations you look at, but I would suggest that we focus on the "Main" period only, which for us is 1970-2013. For model 19, this suggests an alternative sigmaR value of 1.457. I think once we choose a base model, we should look at that table again and add whatever value recommended as an additional sensitivity value (along with 1.0 and 2.0). I think it's likely that this value will result in almost no difference from the 1.4 default we've been using.

```
           period N_devs SD_of_devs Var_of_devs mean_SE mean_SEsquared sqrt_sum_of_components SD_of_devs_over_sigma_R sqrt_sum_over_sigma_R alternative_sigma_R
1            Main     44      1.353       1.831  0.4644         0.2902                  1.457                  0.9666                1.0404               1.457
2      Early+Main     68      1.115       1.244  0.6961         0.6382                  1.372                  0.7966                0.9799               1.372
3 Early+Main+Late     71      1.163       1.353  0.7118         0.6672                  1.421                  0.8309                1.0153               1.421
```

**Comment by cgrandin** [comment]
For the new base model 45, the value of alternative_sigma_R = 1.512 which is now included in the sensitivities. I think we've agreed to use this as method of exploring sigma R more fully. I think we can close this issue, but I'll wait until we talk about it.
