### ISSUE TITLE
Include reports from industry in assessment document

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#182]
Agreed to at JTC Dec 2016 meeting. Was Appendix B for Canadian for 2016 assessment. 
Two countries to assimilate separately.

**Comment by cgrandin** [comment]
I updated the Canadian one for this year in commit be4bef7d4139a4be511816f54421aa8b25989a99. I'll leave this open so we remember to check if the US AP is going to submit one.

**Comment by taylori** [comment]
Aaron to email US AP members.

**Comment by andrew-edwards** [comment]
Any chance we'll get this? It will make it easier to update Section 1.4.1 overview of the fisheries.

**Comment by taylori** [comment]
Response from AP member was that they will do their best but we shouldn't count on getting it in time to include in the pre-SRG document. I have a few notes from the Dec. 6 JTC meeting that I can hunt down to use in revising this section. At minimum, we can simply say that a report from the fishing industry was not available in time for this document so detailed information on the 2016 US fishery is not available at this time.

**Comment by aaronmberger** [comment]
Let's create a placeholder appendix and say that this is forthcoming, in case it doesn't arrive before mid-day tomorrow (just so SRG knows that US is submitting something and that there is 'balance' with stakeholder input into assessment (via those appendices)....

**Comment by aaronmberger** [comment]
placeholder created, but will leave this open until we get the report and insert it into the document - may be pre- or post-SRG meeting...

**Comment by cgrandin** [comment]
Thanks, it's a good idea to spur then to provide one.

**Comment by aaronmberger** [comment]
we can close this now that the placeholder is in the document and it will be clear to insert it once it arrives... closing
