### ISSUE TITLE
automate combine national comp data

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#185]
We may wish to automate the combination of US and CAN fishery comp data, currently done in a spreadsheet

**Comment by aaronmberger** [comment]
Automation stalled due to haphazard nature of required input data (new and historical Canadian and US catch and composition data by fleet, weight-at-age ss file).  Tagging this for revisiting after this year's assessment, but 2017 comps have been properly combined and double checked for this year.

**Comment by andrew-edwards** [comment]
I'll make a note to re-open this is March, just to close and hide it for now ;)

**Comment by aaronmberger** [comment]
Kelli has done this and will be part of moving data aggregation code in general to assessment repo
