### ISSUE TITLE
Canadian landings clarification

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#186]
total annual catch for Canadian SS and FT in 'landings-tac-history.csv' does not match the '....-by-month.csv' files.  Chris can you clarify which is correct.

**Comment by cgrandin** [comment]
Sorry for the delay.. they do match for 2016, but not before because last year I figured out how to include discards properly (after extensive discussions with Barry A.). The catch-by-month is correct, and I will update the landings-tac-history for those years.

**Comment by aaronmberger** [comment]
Sounds good, I'm running some models to see how things go.  I figured there would be some final tweaks in the input data.

**Comment by cgrandin** [comment]
Fixed in commit 9008d3661276ba. I hadn't updated 2007-2015 data in the landings-tac-history file after adding discards to the extraction method so 2016 matched but pre-2016 didn't. They should all match now.
