### ISSUE TITLE
Need the number of ovary samples for 2016

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#188]
data table ovary-samples.csv

**Comment by taylori** [comment]
Melissa Head has verbally agreed to provide values. I will email her to make a specific request.
Have there been ovaries collected from Canada that should also be included in this table?

**Comment by cgrandin** [comment]
No ovaries have been collected in Canada so far. I need to make this happen on this year's survey.

**Comment by taylori** [comment]
Table is now larger to reflect more detail on time of sampling thanks to Melissa Head. Also, a "Total" row has been added that may need to be set apart with a horizontal line or something like that. I'll leave issue open until any needed formatting is sorted out.

**Comment by cgrandin** [comment]
Finished and closinng. See commit cc4969bb96103be7d0a3acf42b654b49cdf5ec87
