### ISSUE TITLE
Survey MCMC estimates plot doesn't look right.

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#189]
You'll be able to see it once I commit the changes needed to get the document building properly. Should be later today. I will take a closer look at why once that commit is done. I'm just getting it up and running at this point.

**Comment by cgrandin** [comment]
I noticed that while running the 'partest' part the return value for the calls to mceval was 127 which means the program wasn't found.

**Comment by taylori** [comment]
Looking in the partest directory on my computer, it looks like the .par files are good and when I try running the executable with the .par (associated with MCMC sample 999), the Report.sso seems to match it. However, the report files in /reports/ are all identical and don't match. I will try to debug this evening or tomorrow morning.

**Comment by taylori** [comment]
I thought that using shell instead of system made it work, but it seems not. I modified load-models.r to delete the old Report.sso which will avoid reading in the same file 999 times when it fails to run.

**Comment by cgrandin** [comment]
Thanks Ian, I got it to work by running:
run.partest.model(base.model, "model-partest.RData")
in the doc/r directory after everything else was done and it worked, but I'll merge your changes and try that as well.

**Comment by taylori** [comment]
For some reason it seemed to take multiple tries, but after deleting partest folder and starting everything over, I was able to build the document and the plots looks right now.

**Comment by cgrandin** [comment]
Once I used your changes ('shell') it worked. I have had issues with 'system' working on some machines and 'shell' working on others. As long as we are all set up I think it's ok with your changes.
