### ISSUE TITLE
New figures needed

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#191]
The figures EWAforDoc.eps, fishCatchRatesUS.eps, fishDepthsUS.eps, and maybe maturityNS.eps need updating (directory doc/main-figures)

**Comment by taylori** [comment]
fishDepthUS.eps updated.

I can produce a new fishCatchRatesUS.eps but need to sort out what the confidentiality rules are for summer months when few vessels were participating.

EWAforDoc.eps need modification to add 2016 which I'm working on now.

I think we should leave maturityNS.eps or remove from document noting that we're planning on updating maturity information for next year's assessment but didn't get to it this time.

**Comment by taylori** [comment]
Ian to produce final missing figure: fishCatchRatesUS.eps.

**Comment by taylori** [comment]
Just updated fishCatchRatesUS.eps and on the phone we decided to keep the maturity figure (which will be good to reference in the text I'll add along with table of maturity ogive (issue #175). So I believe that all figures are now updated and I will close this issue.
