### ISSUE TITLE
Minor fixes "Summary of estimated model parameters and priors"

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#193]
"Number estimated" column in table created by tables-parameters.r has some errors.
Natural mortality and "Additional value for survey log(SE)" are estimated parameters, so should each have a value of 1, not "–".  Conversely, the catchability value is an analytic solution (as noted in the prior column) so should probably be "–", not 1.

Finally, the range of years for Log Rec. deviations should either be set to 
end.rec.dev.yr = end.yr - 1 instead of end.yr since 2017 recruitment isn't included in the estimates of current year stock status (start of 2017). Alternatively, we could note that the rec devs for the years end.yr to end.yr+2 are estimated quantities for purposes of forecasting.

**Comment by andrew-edwards** [comment]
Agree with the second part, as I think it would then (automatically?) not show a 2017 point in Figure e, the recruitment estimates. This would be make sense.

**Comment by cgrandin** [comment]
I'm fixing this now

**Comment by cgrandin** [comment]
Done, and the plots of recruitment and recruitment devs have also been changed.
