### ISSUE TITLE
revise text/code related to years with median fishing intensity above one 

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#196]
Model 41 has slightly revised equilibrium resulting in no longer estimating any years with median fishing intensity above 1, which causes error in executive-summary.rnw:

```
Error in median.intensity.above.one.years[1:(length(median.intensity.above.one.years) -  : 
  only 0's may be mixed with negative subscripts
```
Commenting out for now but once final base is settled, we should revise text to reflect updated results and/or modify code to not crash when `length(median.intensity.above.one.years) = 0`.

**Comment by taylori** [comment]
Looks like it might just be 1999 which is above target in the current base model, rather than 3 different years.

**Comment by andrew-edwards** [comment]
Fixed this yesterday, leaving some commented text so we can easily switch.
