### ISSUE TITLE
fix bug in pairs plot of recdevs

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#197]
Turns out that the problem is with r4ss which accidentally was no longer returning the recruitpars element in the list created by SS_output. Adding fix now, but will require update of r4ss to get this plot to work.

**Comment by taylori** [comment]
Should be sorted out in recent commit. 
Update to r4ss is associated with `packageVersion('r4ss')` 1.25.1.

**Comment by cgrandin** [comment]
Weird.. I didn't get that bug - it works for me. I'll update anyway. Thanks

**Comment by taylori** [comment]
This is the plot that wasn't working for me before. Perhaps it's because I was was using a too-new version of r4ss that broke it and now you're just leapfrogging over that bad version.
![image](https://cloud.githubusercontent.com/assets/4992918/22178019/8a47d212-dfe0-11e6-8202-7b6fd7ba69c9.png)

**Comment by cgrandin** [comment]
Ha ha, yes that might be what happened. I just re-installed r4ss to 1.25.1 and it's all good.

**Comment by aaronmberger** [comment]
This was the same crash I had when I was having trouble building (without errors) the document.  I'll try again but I suspect it will be good once I devtools r4ss and source new version.

**Comment by cgrandin** [comment]
Aaron if it works for you, can you close this issue? Thanks - I'm just trying to whiddle down the open issues.

**Comment by andrew-edwards** [comment]
I've updated to 1.25.1 but still have the issue. I think I've re-run everything from scratch, but can do so again (on Monday), and can then close if Aaron has it working.

**Comment by cgrandin** [comment]
Ok, we can figure it out on Monday Andy. I am probably heading offline soon and not coming on tomorrow. We have a full week ahead of working on this and I think we are all doing a good job of keeping on top of it. No worries!

**Comment by andrew-edwards** [comment]
I'll try deleting the new .RData file in the base MCMC directory, since that was created before I updated r4ss.

**Comment by andrew-edwards** [comment]
Hmm... still don't get the pairs plot. Will figure out on Monday.

**Comment by cgrandin** [comment]
I would try this, it removes all model rdata files:
delete.rdata.files("c:/github/hake-assessment/models")
then source(:all.r") again and try to rebuild.
This is the "turn-it-off" and "turn-it-on-again" approach.

**Comment by andrew-edwards** [comment]
Okay, pairs plot had built. I had a latex error (that I thought was still due to the pairs plot), but turns out it was for some other plots (which I think might be just because we haven't redone the calculations yet).
Aaron can close this when he's good.

**Comment by taylori** [comment]
Hopefully everybody is sorted out, but the key is that for some versions of r4ss, the base.model object was missing the $recruitpars element. This was used to get the names of all recdev parameters for subsetting the things to show in the pairs plot.

As long as base.model$recruitpars isn't NULL, then it should be OK. Deleting \models\41_BasePreSRG_v3\41_BasePreSRG_v3.RData and then re-running all.r should be enough.

This is what the head of that object is supposed to look like
```
head(base.model$recruitpars)
                     Value Parm_StDev          type   Yr
Early_InitAge_20 -0.373814    1.20514 Early_InitAge 1946
Early_InitAge_19 -0.116222    1.32603 Early_InitAge 1947
Early_InitAge_18 -0.140671    1.31201 Early_InitAge 1948
Early_InitAge_17 -0.169516    1.29605 Early_InitAge 1949
Early_InitAge_16 -0.203272    1.27811 Early_InitAge 1950
Early_InitAge_15 -0.242445    1.25819 Early_InitAge 1951

```

**Comment by aaronmberger** [comment]
Worked for me so closing...
