### ISSUE TITLE
US tribal carry over

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#2]
For 2015 we need the upper limit of US tribal catch (last year the document said that < 1000 t was caught), the amount of tribal quota reallocated, and the date(s) that happened. Please put in the file  hake-assessment/data/Further_TAC_details.csv   .

**Comment by allanhicks** [comment]
I think this is completed. Zero tribal catch in 2015 and 30000 reallocated on sept 21, I think.
