### ISSUE TITLE
add text explaining change to time-varying selectivity

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#200]
Add bullet one-page summary and update any text related to time-varying selectivity

**Comment by andrew-edwards** [comment]
See new text in Section 2.4.3. You need to add a bit more as indicated. Commit 091ef815.

**Comment by taylori** [comment]
I working on this the morning of Jan 30.

**Comment by taylori** [comment]
See also issue #239.

**Comment by taylori** [comment]
Text added to section 2.4.3 with commit 9091d3d. I'll leave issue open to remind at least one other person to read this and see if it makes sense before closing. I will try to quickly add something in the sensitivity section to address issue #239, but that may have to wait until tomorrow.

**Comment by aaronmberger** [comment]
Section 2.4.3 looks good, nice job.

**Comment by andrew-edwards** [comment]
See Chris's commit 848a236 . I think we should stick with some version of the earlier version.

**Comment by andrew-edwards** [comment]
The Exec Summary mentions the large 2014 recruitment using the earlier phi. So we at least need to ensure consistency.

**Comment by andrew-edwards** [comment]
Have done some edits in commit c8755da (and maybe one earlier).

**Comment by taylori** [comment]
It failed to automatically merge. I'm not great and manually merging because I can never remember which thing like 
>>>>>>> aedwards/master 
indicates the beginning or the end of what, so if you're willing to take a stab at it, please do. Otherwise, I'm happy to try, but no sense making conflicting merges of our conflict.

**Comment by andrew-edwards** [comment]
Done. It was just formatting as I think you didn't edit the new first paragraph and I didn't touch the second new one.
