### ISSUE TITLE
Need to undo commit  1cd96cbf9

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#205]
Looks like Aaron accidentally committed a whole new directory (Test_Models) and bunch of large files (including .exe files) in commit  1cd96cbf9 . Oopsy ;)

So we won't merge that yet (I've texted and emailed Ian, so hopefully he won't!). We (i.e. Chris) will figure out how Aaron can un-commit or un-push that. I've looked into that before and it's not totally intuitive.

Meanwhile, I can take Aaron's new catch levels and put them into forecast-catch-levels.r . Plus I'll take the text from the later commits (so Aaron can just revert back). Chris is saving the Test_Models directory just to ensure that it doesn't get lost.

**Comment by cgrandin** [comment]
See #206 for details
