### ISSUE TITLE
A bunch of files were added accidentally

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#206]
Hi Aaron - I see that you committed the new forecast numbers which is great but at the same time you accidentally added a huge folder with models, etc. in it called Test_Models. I would normally just say you should remove them and commit again, but these are probably gigabytes of data and we need to remove them from the repository or it will be massive. Andy is saving the new forecast numbers which he will commit later, but I was hoping you could undo your commit like this:

**git reset --hard 1efab16675b4ea427d194140bf389106d751822a**

which will send you back to before you committed the forecast numbers. Andy is copying them and the accompanying text and will push those again so you don't have to worry about losing them.
Once you've done that, push the changes to GitHub like this:

**git push --force**
 Take a look at your network graph to see where you're at afterwards. You'll need to merge again as you will be behind.
Thanks!

**Comment by andrew-edwards** [comment]
Everything from Aaron's except what's in Test_Models/ is now committed in commits a5bff21 and db57e6709 .

Re-running forecasts is taking a while - I'll comment shortly to confirm it all builds okay (and I'll check the figures have changed).

**Comment by cgrandin** [comment]
Aaron - you should backup your Test_Models directory outside of the git/hake-assessment directory before doing this just in case. Once done, you can move it back but make sure to put it in your .gitignore file.

Cheers

**Comment by aaronmberger** [comment]
ok, all done.  I will be offline for a bit while I travel up to Seattle, but will be back on later this afternoon.

Closing...

**Comment by andrew-edwards** [comment]
Just confirming that all forecasts run okay, and resulting tables and figures get properly updated (as one would expect!).
