### ISSUE TITLE
mcmc's on model 59, 60, 61?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#207]
I have an mcmc running on model 59 (will be done today) and will start one for model 60 later this afternoon.
I thought we talked about potentially looking at some mcmc results across time-varying selectivity SD.  Did I remember this correctly.

**Comment by taylori** [comment]
It certainly can't hurt to have them in our pocket and if we have time to produce selectivity uncertainty plots to compare among these models (Figs 26 or 27), that could be a valuable addition. Depending on how much time Chris has for restructuring the code to allow loading of the "partest" outputs for multiple models, a backup would be to produce the EPS figure externally and not dynamically within the document building.

**Comment by cgrandin** [comment]
'Partest' is no more. I am still working on it, but from now on models will have mcmc output loaded and extra-mcmc output (formerly partest) run and loaded as well. My next commit will have all of this, just working out some bugs.

**Comment by taylori** [comment]
Awesome. I'm sure it's taken some work to do this, but I think this will be really helpful in the future and give us more flexibility in comparing quantities among models.

**Comment by aaronmberger** [comment]
mcmc for model 59 uploaded to google drive; model 60 running overnight

**Comment by aaronmberger** [comment]
mcmc for model 60 uploaded to google drive, model 61 running (should be done later today).  We can look at these during the weeks leading up to the SRG.

**Comment by taylori** [comment]
Aaron how now uploaded model 61 to google drive, so I'm closing the issue. If we decide that additional plots are needed to compare among these MCMC results, we can open a separate issue that's specific to what we want to add.

**Comment by andrew-edwards** [comment]
I re-opened this just to remind myself (though I added a message, but can't see it!). 
Now download 61 (and removed .Rdata file from Google Drive in that and 62). 
Chris - you are prob up to date also - if so then just close this issue.
I'm going to remove all .RData and re-run tonight. Prob won't do any more editing; lots of great progress made today (Saturday) by you guys. ....
