### ISSUE TITLE
Manually update the RESEARCH AND DATA NEEDS

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#210]
This should probably come at the end after we've sorted everything else out, just reminding ourselves to remember to do it. I think there's no way this section can every be automated because it reflects the current thinking of the humans involved, not model results.

**Comment by aaronmberger** [comment]
I made an initial stab, but didn't end up changing much as most of all the good stuff there still stands.  Anything else to add?

**Comment by andrew-edwards** [comment]
I prob won't think of anything...

**Comment by taylori** [comment]
Haven't read Aaron's text yet, but I'm sure I'm fine with it. However, let's check in about it on the phone Monday (tomorrow) if y'all are up for a 10am call.

**Comment by aaronmberger** [comment]
Yep, talk then

**Comment by andrew-edwards** [comment]
Chris and I are good for 10am call.
