### ISSUE TITLE
fix bug in plot of time-varying selectivity (Figure 26)

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#211]
calc.tv.selex function was hard-wired to show average selectivity for non-deviation years in the first panel, causing the top right panel for 2002 to match 1990, not the true results for that year

![image](https://cloud.githubusercontent.com/assets/4992918/22298373/24490c2c-e2d5-11e6-9cf0-24e48f2460f4.png)

I've fixed the associated functions and will upload in commit momentarily, just posting issue to track the change.

**Comment by taylori** [comment]
Fixed plot using recent commit f732fac should look like this:
![image](https://cloud.githubusercontent.com/assets/4992918/22298519/9d945a78-e2d5-11e6-8216-b3e8cb787532.png)

**Comment by aaronmberger** [comment]
Nice 'catch' Ian!

**Comment by cgrandin** [comment]
Yes, good one. I suspect we will need to weed out a few more like this.
