### ISSUE TITLE
commit/push frequency and work-flow

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#214]
I'm using an issue here instead of email to make sure we all get it in a timely manner.

Andy was worried about pushing too often. You all have more experience with this than I do, but it seems to me that the only danger of pushing often is if it would leave something in a broken state. If it's just changes to the text, I'm happy to have them pushed as often as they get committed. But I'm open to whatever you all wish.

**Comment by aaronmberger** [comment]
I don't remember the internet-git network being an issue last year.  I'm guessing it was just a weird case with Andy hibernating or closing down computer before it finishing.  I'm open to whatever the individual feels comfortable with, but do like the idea that if its text changes that it be done fairly often so as to not duplicate any text changes (though can always resolve these conflicts).  I'm not worried...

**Comment by andrew-edwards** [comment]
Yes, after my email I then thought pushing often isn't so bad. It's easy for others to check the commit descriptions on the Network Graph. So really there's just no need to fetch and merge so often - the graph let's us keep an eye on each other's stuff, and know whether it's likely to conflict with what we're currently working on. It's nice to get all caught up with each other, but no need if we're working on different things.

**Comment by cgrandin** [comment]
Hi guys, I've been busy with the model structure stuff but -  I think pushing more often is better, so we can retract without losing very much if need be. It's good to build the doc from scratch as often as possible. As Andy said, watching the graph and fetch/merging whenever you're too far out of sync is good, I personally like to be all the way synced with everyone as often as possible.

**Comment by andrew-edwards** [comment]
Was wondering if we want to create an issue "I'm working on ...." that just tracks who's working on what? So we can easily keep track and not duplicate work. I'm done for today, so not worth me opening it ;)

I can see that Aaron and I are in sync with each other, but haven't merged Chris's big commit yet (too scared!). Ian has, so hopefully it's all working well......

**Comment by taylori** [comment]
I think that merging won't be as hard as it looks. Chris's stuff is all behind the scenes and doesn't impact the text. I'll try merging the things and if that fails nothing is sacrificed. If it succeeds, then maybe that will help you take the plunge tomorrow morning if you wish.

**Comment by taylori** [comment]
No issue on merge. Forging ahead. 

When we add a figure showing differences in time-varying selectivity among MCMC outputs that will likely depend on switching to Chris's new format, but for now, it looks like the document text can be edited with or without switching over and things work fine.

**Comment by andrew-edwards** [comment]
I'll merge now. I just didn't want to yesterday as wanted to get finished with the text.

**Comment by aaronmberger** [comment]
Ian and I did my merge last night and now up to date and doc builds (like the new setup Chris!)

**Comment by cgrandin** [comment]
Thanks! The fact that you can't accidentally leave a run flag on TRUE anymore is a bonus.

**Comment by andrew-edwards** [comment]
Agree with everyone. Let's keep on pushing...
Can close this now I think. We're almost all up-to-date (I think you can only tell by checking each other's network graphs, yes? I do that occasionally but mainly just keep an eye on my graph).
