### ISSUE TITLE
The extra-mcmc commit

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#215]
Just comments on this work - It takes a long time to run and as it stands now all models with mcmc directories will have the extra-mcmc part re-run when you call build(FALSE,FALSE,TRUE). I think it would be best to wait until the rest of the mcmc folders are uploaded, then do this once you have them. It took mine about 30 minutes or so to get through the 4 models that I have with mcmc folders currently (00, 41, 45, 59).
The document built at my commit but I have yet to make sure it builds with the merged work you all have done since. Thanks for you patience, this was a bugger - R likes to try to access files that the operating system has not yet released so I had lots of debugging to do to get it to work.

**Comment by cgrandin** [comment]
Plots for other mcmc models can be made like these examples:
  **make.age.comp.pearson.plot(sens.models.6[1][[1]])**
  **make.mcmc.diag.plot(sens.models.6[1][[1]], subplot = 1)**
It's just a matter of substituting in whatever model where base.model was in the calls.
I haven't included any new plots yet so I don't break the document building.

**Comment by taylori** [comment]
Looks great. I'm starting fresh now to try it out.

**Comment by cgrandin** [comment]
I get 15 warnings about covar.sso not being deleted in the retrospectives but this is nothing serious. Outputs are fine.

**Comment by taylori** [comment]
It took a while (maybe 30 minutes?) but I was able to build the doc on the first try with the new approach following steps in the README. I like the new setup. It's nice to have the options for what to re-run as function inputs instead of changing TRUE to FALSE or back in all.r.

**Comment by cgrandin** [comment]
Great news! It can't do retrospectives or forecasting on non-base models but it's set up properly now so it won't be that much work if we need to. I just wanted to get it out since we are running out of time.

**Comment by taylori** [comment]
We may not ever need retro or forecasts for non-base models so that doesn't seem a high priority right now. Thanks for your work.

**Comment by cgrandin** [comment]
Thanks Ian, I'll be able to get to the other outstanding issues tomorrow.

**Comment by cgrandin** [comment]
It seems that everyone has this working so I'm closing it.
