### ISSUE TITLE
Verify final two sentences of Forecast Decision Tables

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#216]
Last two sentences of Forecast Decision Tables in Exec Summary (currently page 17).
I think they're okay, just adapted from last year. See commit 71d7310 ; there are notes in the .rnw file.

**Comment by aaronmberger** [comment]
adjusted slightly (removed 2012 as it is slightly above average in terms of median and mean.  this is hard to tell with executive summary figures (which is fine) but is clear in the main figures (30 and 31).

Closing
