### ISSUE TITLE
Change 'SPR 100' to 'SPR=100%' in legend of Figure i to be consistent with Tables g and h

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#217]

**Comment by andrew-edwards** [comment]
And edit last sentence of caption.

**Comment by andrew-edwards** [comment]
Commented out previous final sentence of caption since it didn't make sense (was actually wrong) - see new comments executive-summary.rnw in commit 1a74f59e . 
If someone agrees then they can close this off.

**Comment by taylori** [comment]
Looks good to me.

Andy, will you be able to merge with Chris's edits today? I have some edits to tables-maturity.r, data-tables.r, main-tables.rnw, and data.rnw that are all relative to Chris's last commit that I can commit soon, but can also wait until you've merged if that will happen soon?
