### ISSUE TITLE
problem with sampling history table

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#218]
Table tab:main-sampling-history (supposed to be Table 5) created by make.sampling.history.table function. I don't see anything which has changed that would cause this to fail, but since I just edited a table, it's entirely possible that this is my fault. I can try to debug tomorrow, but for now, the only consequence seems to be a broken reference to the table and this error on page 64:
![image](https://cloud.githubusercontent.com/assets/4992918/22317362/1a008d96-e328-11e6-9549-54c87a2dd874.png)

**Comment by cgrandin** [comment]
I can check this out in the morning, I've had things like this happen before with the xtable code

**Comment by cgrandin** [comment]
Fixed in commit 8b7894c91dd1d21b58c4029cc1c0fc18c005da47. Looks like the csv file was saved with a couple of extra columns.
