### ISSUE TITLE
NAs in age data files for US fleets

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#219]
Are they supposed to be zeros?

**Comment by aaronmberger** [comment]
Yes, the NAs should be zeros in age composition files.  I double checked that the rows summed to one.

**Comment by cgrandin** [comment]
Ok, I will change them all and commit with the age data table code later. Should we add earlier years the US tables?

**Comment by cgrandin** [comment]
Done, see commit 3a6497f2dce46db7f1e99a2272fb077e0ce715e7
