### ISSUE TITLE
Thursday - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#220]
I think we did this type of issue to make sure that we're not duplicating work.
Andy - will go through text for Section 1 - Introduction 
Chris - trying to landscape an age-data table since it's now got big

**Comment by taylori** [comment]
Ian - I got a late start this morning and will be involved in a meeting for the next hour or two, so probably just trying to keep up with what's been done without changing anything.

**Comment by andrew-edwards** [comment]
I'm done with Section 1 (introduction). Did create an issue about some text to be checked. 
I'm pretty much done for the day, as heading down to Victoria for the evening.
Everything seems to build okay. I think we're done with major structural changes to the document, and it's mainly the text and a few more figures to be done. 
Chat tomorrow at 10.

**Comment by taylori** [comment]
Thanks Andy, safe travels.
Aaron and I haven't been pulling our weight the last couple days due to this assessment methods review meeting that Aaron needed to attend (and I ended up sitting in longer than expected). We both hope to contribute more tomorrow and beyond.

**Comment by cgrandin** [comment]
Let's shut this one down.
