### ISSUE TITLE
Hake still most abundant?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#222]
This sentence still okay in Section 1.1.?

"The coastal stock of \fishname\ is currently the most abundant groundfish population in the California Current system."

Just say here and I can edit if necessary.

**Comment by taylori** [comment]
I haven't heard anything otherwise, and with the stock trending upwards, some other species would have had to be estimated higher than before for things to change. I will close the issue, recognizing that if a reviewer or someone else questions this statement, we can revisit the question.

**Comment by aaronmberger** [comment]
I believe this is still a true statement (i.e., hake stock has gone up and I don't know of any in the CCLME that would have increased substantially to compete)...
