### ISSUE TITLE
Please confirm that sections 1.3.1 and 1.3.2 are still fine. And see ** in rest of section 

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#224]
Text on 1.3.1 (Management of Pacific Hake in the United States) and 1.3.1  (... Canada) - I presume none of the dates and rules have changed. Numbers in Canadian section are automated and so are good (no values in US section).

If Ian/Aaron (for US) and Chris (for Canada) could read text (unchanged from last year) and make sure still okay that would be great. I expect it's fine. 

Also, see rest of section 1 (Introduction) for US stuff that needs manually updating that I don't think I can do. I've flagged the respective paragraphs by ** to highlight them. Canadian is all good.

**Comment by andrew-edwards** [comment]
Think I've done what I can with section 1 - see commit dd91e92 .

**Comment by taylori** [comment]
Thanks Andy.
Aaron and I can take it from here. Aaron is driving home from his meeting so will probably be offline until tomorrow, but I think he's planning on going over this section tomorrow, so I will defer to him on whether to automate or not. One idea for future years would be to have automatically created text that is produced in early draft assessments which we then comment out in the final draft if we choose to replace it with a differently worded sentence.

**Comment by cgrandin** [comment]
The Canadian section (1.3.2) is fine. I also feel like I haven't done much - spending all day today figuring out how to properly make a landscape page with age proportion data tables... Looking forward to getting on with finishing up the text.
