### ISSUE TITLE
B_0 definition

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#231]
Glossary is much clearer - thanks Ian for tidying up.
One thing, B_0 is defined as
 "The estimated average unfished equilibrium ..."

I think it should just be
 "The unfished equilibrium ..."

Everything is 'estimated' so not really need here, but, less pedantically (!), it's not the 'average' since we talk about the median of B_0 and intervals (e.g. Figure c). 
Just checking that's okay with you - I'll fix that elsewhere as I'm going through Glossary. (Just double checking before I do the edits).

**Comment by taylori** [comment]
I agree. I think that the use of "average" was probably trying to get at the idea that this is a concept that doesn't apply to a specific year, but some kind of average across year. However, that same point is better made by the use of "equilibrium", so I support the change.

**Comment by andrew-edwards** [comment]
Great. Yes, it's an equilibrium because it's assuming constant recruitment (I presume), selectivity, etc. The average part comes later because we calculate a distribution for it. 
[Not edited yet but will close issue]
