### ISSUE TITLE
I'll be working on 3.5, 3.6, and 3.7 for the next few hours

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#237]
This is the model uncertainty, reference points, and model projections sections

**Comment by andrew-edwards** [comment]
Sounds good. I was going to mention that some of the updated Exec Summary text may be useful, but it looks like the sections you're working on are much more detailed, so maybe not!
I'm at work until just before 3pm. Going to get caught up again then first finish up the glossary stuff.

**Comment by cgrandin** [comment]
I'm heading out to my nephew's birthday party for awhile but will check back in a couple hours.

**Comment by aaronmberger** [comment]
moving on to 3.9 and 4.1

**Comment by aaronmberger** [comment]
closing
