### ISSUE TITLE
Longtable causing problems on page 14.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#238]
Table e is now a longtable, don't think it was last year. I think this is why it has two lines at the end of it (didn't last year), and why page 14 text goes off the page. 
Thinking it's to do with commit 7c2504a which was probably done to fix the main tables (but the same command is used to make the exec-summary table). Remember thinking that the fix in 7c2504a may have been a bit overkill, but it seemed to work. Assigning to Chris since he set up the longtable stuff ;) Expect you just need an option to have longtable or just usual table.

**Comment by andrew-edwards** [comment]
I tried moving the text around and adding blank lines in (partly to see if my extra commented out \Sexpr stuff was the cause), but that didn't fix it (so I won't commit that). Text and sections are pretty much the same as last year, so longtable is likely the issue.

**Comment by cgrandin** [comment]
The only reason for changing that one was to look the same as the ones before it in the main section. I'll do a few quick things to check what can be done but if it's going to be tedious I'll just change it back.

**Comment by andrew-edwards** [comment]
Thanks. Figured it was easier for you to do some quick checks...

**Comment by andrew-edwards** [comment]
Just noticed a warning:
'8: In print.xtable(xtable(tab, caption = xcaption, label = xlabel,  ... :
  Attempt to use "longtable" with floating = TRUE. Changing to FALSE.'
Not sure if it's actually that issue, but guessing that it might be. I think longtable is probably for standalone full page (or multipage?) tables?

**Comment by cgrandin** [comment]
Yeah that was the problem. I just put a switch so we can make two different kinds.
