### ISSUE TITLE
Add paragraph on selectivity phi comparisons in sensitivity section

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#239]

**Comment by cgrandin** [comment]
I'm working on including the density plot for 2014 recruitment for this

**Comment by taylori** [comment]
Text added about time-varying selectivity in the sensitivity section, but could use a quick read-through by someone else before closing issue. 

I have to quit for the day but will pick things up for a little while around 7am tomorrow and then need to pause again until later in the morning.

**Comment by taylori** [comment]
Text has been added and is being actively edited and discussed in other issues, so I will close this one.

**Comment by andrew-edwards** [comment]
There was a conflict but I think only formatting (we both split up that paragraph, then I edited the first new paragraph and you edited the second new one). Have committed.

**Comment by taylori** [comment]
Awesome. Thank you. I'm pausing briefly to eat some lunch but will read over the final text one more time afterwards.
