### ISSUE TITLE
I'll be working on a bit more text tonight

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#240]
I'll send off a draft version later tonight to Owen for NWFSC internal review and to Sean for review if he has time....

**Comment by taylori** [comment]
Thanks for getting this done. The draft to Owen looked good from what I've read so far and the edits I made this morning are really minor. Closing issue to clean it up.

**Comment by cgrandin** [comment]
Thanks guys, you put a lot of work in this weekend.
