### ISSUE TITLE
Tribal fishery not land hake in 2016?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#242]
This is primarily for Ian and Aaron as in 1.4.1 under US there is a statement from last year that says this: 
"Tribal fisheries did not land any hake in 2016" - where the 2016 is autogenerated.  Is this still true?  Ian and Aaron should discuss much of 1.41. U.S section and 1.3.1 to decide if anything has changed or needs updating (here's were, for me at least, Allan's institutional memory is a big loss)...

**Comment by aaronmberger** [comment]
Sorry... and for my knowledge - how do we define tribal landed hake?  I presume it is only actual landings put forth by the tribe and not tribal allocations being  reallocated to other sectors who then catch it.

**Comment by taylori** [comment]
Note for future years: in the code for processing PacFIN catch,  the FLEET=="TI" apparently designates tribal catch and shows 0 values for 2016. Tribal catch that is processed by a Mothership would not appear in this database, however, so finding a robust method to calculate tribal catch would be useful for the future.
