### ISSUE TITLE
Compare .tex and .pdf files.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#243]
I can compare them. Ian - can you fetch and merge and re-build from commit 6f22ae8, currently the latest commit. Chris thought your .tex and .pdf were from an earlier build. Thanks...

**Comment by taylori** [comment]
Sorry, I should have thought of that earlier. Rebuilding now.

**Comment by taylori** [comment]
Files uploaded with appended name "_Ian_6f22ae8". Taking down old files. Thank you!

**Comment by andrew-edwards** [comment]
.tex files - all identical (I fixed a degree symbol), except timestamps on tables (as expected) and Aaron and Ian's R version is 3.3.1 compared to our 3.3.2 (doesn't matter), and Ian's table 16 (Time-series of median posterior estimates ...) didn't build. Thus, all numbers in text and tables are identical (i.e. we're all using the same output data, implying the figures should match also).

.pdf files - ['compare documents' in Adobe Acrobat Pro 8]
 Andy v Chris's - (slight irrelevant font differences), Section 4.1 on Chris's TOC says page 53, but it should be page 54 (and you're always latex-ing twice aren't you. Strange... but don't worry about).

Andy v Aaron's - same TOC minor issue, plus Aaron's shows up more font differences and minor things on figures. Just to be sure I went through page by page (manually flicking between .pdf's) and all figures are identical (fonts occasionally are slightly different, no worries).

Andy v Ian's -  TOC is correct, Table 16 missing (as mentioned above), and also '1999' on Figure 36 (that you helpfully added yesterday!). Just delete knitr-caches I suspect.

Conclusion  all builds are essentially identical (once Ian's fixed his), and so provided we don't do major changes we don't really need to check this again tomorrow.

**Comment by cgrandin** [comment]
Excellent! So whose looks 'nicest' as a PDF for submission?

**Comment by taylori** [comment]
Great! Thanks for doing this check, Andy.
The failed table 16 was because I had an uncommitted, incomplete edit to add a column for total biomass that I've since deleted. Yet, freshtex or deleting knitr-cache should get you the 1999 label in figure h.
I'm OK with anyone's PDF being the official copy for submission, especially if somebody's fonts are prettier.

**Comment by andrew-edwards** [comment]
They look the same - the fonts for the .ss code appendices are very slightly different, and occasionally different in figure legends. So we're in our Happy Place that if three of us get sick the fourth can still submit! Aaron said he can submit it...

Ian - just to clarify, yours has the '1999' missing in Figure h. Amusing since you put it in!

**Comment by taylori** [comment]
:+1:
