### ISSUE TITLE
what style of English spelling should we use?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#245]
I see both "modeled" and "modelled" in our document. The former is more common in the U.S. but maybe the latter is more common in Canada. We seem to use "color" in a few places but never "colour". I'm happy with any consistent style, even potentially switching back and forth in alternate years.

**Comment by andrew-edwards** [comment]
We should use English ;)

**Comment by andrew-edwards** [comment]
Your switching suggestion will prompt Chris to create a \spell switch that changes things dependent on the first author, ha ha. 
Think I was trying to stick with US spelling for consistency, but no doubt will have written modelled a few times. If you see any just make them US for consistency.

**Comment by cgrandin** [comment]
I like the switching each year idea - we could bet on who notices it first. But, I think this year we could stick to US as Andy mentioned. The document was adapted from the STAR process document, so many things are probably still spelled the US way.
