### ISSUE TITLE
Table c caption not quite correct?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#247]
Table c caption, instead of:

"recruitment deviations (deviations below zero indicate less than median recruitment and deviations above zero indicate above-median recruitment)."

actually say:

"recruitment deviations (deviations below zero indicate recruitment below that estimated from the stock-recruit relationship, and those above zero indicate recruitment above the estimated value)"

or more concisely just:

"recruitment deviations, where deviations below (above) zero indicate recruitment below (above) that estimated from the stock-recruit relationship."

**Comment by taylori** [comment]
Yes, "above median" is misleading because the table shows the median of the deviations, not the deviations relative to the median. Plus the lack of stock-recruit mention is a problem. I like the "more concisely" version best, but either are fine.

**Comment by aaronmberger** [comment]
changed in document and went with Andy's third (more concisely) option
