### ISSUE TITLE
Check that all main figures and tables are referenced.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#249]
I remember some weren't the other day, so should check this. Exec summary ones are all good, just the main ones. 
In main text some might get referenced out of order (e.g. Figure 10 then Figure 9), but discussed with Chris the other day and decided that's fine, especially since most figures then are in the same place as last year. Plus it'd be a little fiddly and time consuming to get perfect.

**Comment by cgrandin** [comment]
Figure 16, 17, 28, 29, 30, 31, 43, 44, 46, 47, 48, 49, 50, 54, 56  are not referenced
Fig 25 is only referenced in caption of Fig 48 (which itself is not referenced, mountain plot of sensitivity to phi)
Fig 26 is only referenced in caption of Fig 49 (which itself is not referenced, selectivities for sensitivity to phi)
Fig 53 is only referenced in caption of Fig 54 (which itself is not referenced)

**Comment by cgrandin** [comment]
Tables 1, 3, (6, 7, 8, 9, 10 - new age prop data tables), 12, 17, 18, 27 are not referenced
Table 16 is only referenced in caption for table 17 (which itself is not referenced)

**Comment by cgrandin** [comment]
I'll start trying to reference the figures now.

**Comment by andrew-edwards** [comment]
Thanks Chris for going through.
Figure c is referenced (as Figures c and d). And Tables 1, 2 and 3 are (similarly in one go) on page 30.
I'm guessing you searched for "Table 1" etc.. So there are less than you specified (I hadn't thought there were that many).

**Comment by cgrandin** [comment]
Yes, that's why I deleted some of them. I realized I did the exact same thing last year :(
Some are still unreferenced, but I am working on those now.

**Comment by andrew-edwards** [comment]
Deleted some of what?

**Comment by cgrandin** [comment]
All figures are referenced as of commit  17dd624796354e07bbd2c98d08f7f1a2694477e3, but figs 25&26 are not referenced in the model fit text. I added a reference to them along with their counterpart sensitivity versions. Also search for ?? - we may need more text about the selectivity plot showing mcmc samples which are up and down between ages.

**Comment by taylori** [comment]
It's been a goal of mine to add more text about the selectivity plot (Figure 27), I just haven't gotten to it. If we don't get something in before this version, we should definitely discuss at the SRG and get something in before the final.

**Comment by cgrandin** [comment]
Sounds good - There is still flagged text in there (search for ** or ??) so I'll leave this open until either you write more or we remove that text.

**Comment by taylori** [comment]
Just committed new text. Thinking about this more helped me get straight in my mind why I think the crazy variability is present. I will leave open until at least one other person reads what I wrote to see if it makes sense and isn't riddled with typos.

**Comment by andrew-edwards** [comment]
Hopefully we won't conflict.... I just committed, but didn't touch the bit you may have worked on.

**Comment by cgrandin** [comment]
I think it all looks good, and there are no conflicts so you can probably shut this one down

**Comment by aaronmberger** [comment]
I think we are close enough with referencing nearly all (all?) tables and figures for now and my most recent build doesn't show any ** or ?? left, and Ian's text seems good (we can always adjust the post-SRG version if we need to later) so I'm closing but can be re-opened if someone deems needed

Now see chris comment so closing
