### ISSUE TITLE
Tuesday - who's working on what

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#250]
Chris - working on referencing all Tables and Figures.
Andy - want to read through some of the main text first, but will wait until Chris is done. So will check the placement of figures and tables in exec summary as that text is pretty finalised.

**Comment by aaronmberger** [comment]
Aaron - fixing forecast table per Ian, Andy, Owen and Aaron input over the last day - almost done; then going through Owen's comments pertaining to main text (already incorporated exec summary comments); then double checking US fishery text in 1.3.1 and 1.4.1 US section.

Just to note, I'll send along Owen's comments to all after today.  There were several though provoking ones that didn't/couldn't be addressed by today or even this year, but good to note.  I though I would make an 2018 milestone issue for some, but later this week or even after SRG

**Comment by taylori** [comment]
Ian - reading through the United States subset of "1.4.1 Overview of the fisheries in 2016" and watching issues for areas where my help is needed.

**Comment by aaronmberger** [comment]
I'm just reviewing things... getting to the point of fixing very minor things just becasue (we are close)

**Comment by aaronmberger** [comment]
closing this one... but let's aim to have a 'finished document' (i.e., no more commits) by 2:30.  We can then all merge and build and compare with a bit of time to spare to send to Miako (I told her 4PM)

**Comment by andrew-edwards** [comment]
Yes, I was hoping to read through more but am running out of steam. Spotting a few typos that I'll commit and then I'll do a big spell check.

**Comment by taylori** [comment]
I do have some edits to "1.4.1 Overview of the fisheries in 2016" in the
works but they are text-only and confined to the specific paragraph. I got
caught up in trying to automate a few numbers but will instead just add a
%manual2017 note.
First, however, I have to get out of my merge conflict. Can somebody tell
me how to wipe out my changes and conflicts and just catch up with
everybody?

**Comment by taylori** [comment]
OK, I think I'm good now, will commit change to introduction.rnw soon.

**Comment by cgrandin** [comment]
I'll be away for an hour or so, but will be back for the final Hurrah.

**Comment by taylori** [comment]
2nd paragraph of U.S. section of "1.4.1 Overview of the fisheries in 2016" revised to provide more detail on age comps in each sector. Aaron, if you have time, you could read through that bit.
