### ISSUE TITLE
Contact tribes to better report tribal happenings

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#252]
See section 1.3.1 (and elsewhere) - it seems like we could do a bit better describing the current state of tribal fisheries (e.g., fishery itself, or re-allocations, etc...)

**Comment by taylori** [comment]
US AP report received 2017/02/02 indicated small tribal catch, further indicating the need for better communication in 2018.

**Comment by taylori** [comment]
Got information from Joe Petersen in early December.
