### ISSUE TITLE
Final look through - just fix any dangling subsubheadings

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#255]
Once we've stopped tweaking text I can do this. 
Easy enough (just add a \clearpage in the text I think). Exec summary should remain good and I think might not actually have this issue.

**Comment by aaronmberger** [comment]
andy - did you ever do a spell check?

**Comment by cgrandin** [comment]
I did a spell check yesterday

**Comment by taylori** [comment]
Andy did one today, see comment at https://github.com/aaronmberger/hake-assessment/commit/d04b32acd4adf188e3b1e6e1667b42a94d26277c

**Comment by andrew-edwards** [comment]
Yes, I did one and committed 30 mins or so ago. Hardly any changes!

**Comment by aaronmberger** [comment]
Ok, good enough.  I think I'm done for pre-SRG version.  will wait for last check on dangling subs

**Comment by taylori** [comment]
Sounds like it's in Andy's court to fix dangling subs and then we submit. I will do quick skim for any glaring errors, but note that the is a pre-review draft document and need not be perfect in every way.

**Comment by cgrandin** [comment]
I will also do a quick read through now.

**Comment by andrew-edwards** [comment]
Just doing a minor tweak to first bullet point - I keep having to re-read it to understand it.

**Comment by andrew-edwards** [comment]
See recent commit: 0298aef regarding first sentence. By 'model structure' I think of the equations, but not the parameter values (e.g. phi) and data. 
So it might be more correct to say 'model for 2017 retains the structure of the 2016 model'? I think it's only parameter values and data that have actually changed, we haven't changed the underlying structure.

**Comment by taylori** [comment]
I like the change. In general, shorter sentences which don't try to combine multiple concepts, seem easier to read in documents like this.

**Comment by cgrandin** [comment]
I am OK with it either way.

**Comment by taylori** [comment]
I think the it's OK to say the model structure is "similar" rather than identical because the number of years and number of parameters (for recruitment and time-varying selectivity) have changed. I like the commit like it is and don't see need for further tweaking, but tweak away if you wish.

**Comment by aaronmberger** [comment]
good with me

**Comment by taylori** [comment]
To beat a dead horse, I don't think 2:30 pm on deadline day is the time to sort out the philosophical definition of what is a model.

**Comment by taylori** [comment]
We can do that over drinks in Vancouver.

**Comment by andrew-edwards** [comment]
Okay, fine by me. Have fixed the dangling subheadings already.

**Comment by andrew-edwards** [comment]
I'm done editing, and reading more won't help. Will wait until Chris/Aaron have merged in case they conflict....
So shall we all get caught up, build a .pdf each and do a quick compare (comparing .tex is super-quick).
Chris - we should just delete knitr-cache, yes? No need to delete any .RData files?

**Comment by aaronmberger** [comment]
Okay, I'm ready to build and compare

**Comment by cgrandin** [comment]
I rebuilt after deleting knitr-cache. No need to worry about the .RData file, it isn't used for anything. My copy is on the google drive.

**Comment by taylori** [comment]
I'm dropping out of comparison due to merge messing things up and not
wanting to accidentally make a commit forward of where you all are.

**Comment by cgrandin** [comment]
It's all fixed now, no problem!

**Comment by aaronmberger** [comment]
Mine is uploaded

**Comment by andrew-edwards** [comment]
Ian:
git stash  
should stash any of your changes. You can find them later (if you can remember where you stashed them).
Then you can fetch and merge. 
But, yes, no immediate rush.

**Comment by taylori** [comment]
I've figured out git stash but this is worse. It said that I had resolved the merge but there was still a .git/HEAD that shouldn't be there (or something like that which I didn't pay adequate attention to). Anyway, I deleted .git/HEAD and now it is headless and confused, and that file doesn't appear in my recycle bin. I can surely fix this by just checking out the repository to a new location and copying the ignored files into it, but I don't feel like doing that now. Yes, closing this is good.

**Comment by andrew-edwards** [comment]
I'm uploaded to Google Drive.
We had slightly different commits maybe, so may be minor typo differences.
I'll check the .pdf's. (Chris are you comparing .tex? I can if not).

**Comment by cgrandin** [comment]
git checkout master
might do it

**Comment by cgrandin** [comment]
Andy, I compared Aaron and I's tex files and there are no differences.

**Comment by andrew-edwards** [comment]
Great. .pdf compare taking a while to build - easier just to do it by eye by flicking between .pdf's.

**Comment by andrew-edwards** [comment]
Aaron - just fetch my latest commit.

**Comment by andrew-edwards** [comment]
Okay, Aaron and my .pdfs look identical. Chris checked that Aaron and his .tex files are identical. So that's good enough for me!
I spotted one minor edit, committing in 3d5a123 . 
Then I'm happy for Aaron to submit.

**Comment by aaronmberger** [comment]
Sorry Andy, I just sent it so this change will be the first adaptation going from pre-SRG version to the final version (nice spot).

**Comment by andrew-edwards** [comment]
Yes, no worries. Still a bit busy at the end there, but really only because we were all spotting the same minor edits, and getting messed up with conflicts.
We should do a practice 'conflict' some time. (I meant to suggest that for our JTC meeting!).
Have a good hake-free night!

**Comment by taylori** [comment]
For the record, I got my repository rebuilt and working by renaming the whole folder, checking it out again, copying "models" over, and rebuilding. Very easy though it took a while. I'm sure there are better ways. Comparison of my tex file to Aaron's found the only difference was the two periods that Andy added at the end.

Yes, a practice conflict at the JTC meeting would be great. 

OK, now walking away.
