### ISSUE TITLE
what to call PDF file?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#256]
Seems like the name changes every year for no good reason. Perhaps that's Miako's fault or the web developer. File on treaty website for 2016 is "pacific_whiting_status_2016-final.pdf", so I suggest we copy that with an updated year.

**Comment by cgrandin** [comment]
I would call it draft instead of final though, I think they change it after the SRG for final submission.

**Comment by aaronmberger** [comment]
last year we called it 'hake-assessment-2016-preSRG'

**Comment by aaronmberger** [comment]
I'm not sure if Miako changed it after that but I doubt it
