### ISSUE TITLE
sending to Miako

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#257]
Ok, shall I send Miako our draft and cc you guys?

My version matched Chris' with the exception that my version had the 'discarded bycatch' add and the late change in the acknowledgement correct spelling of 'from' - all else was equal

**Comment by taylori** [comment]
Fine with me. I would suggest that you cc Sean as well.

**Comment by aaronmberger** [comment]
Right.  I'll wait until I hear from Andy about how the comparisons look

**Comment by cgrandin** [comment]
Yeah, mine is missing the last typo change so don't use it.

**Comment by aaronmberger** [comment]
Okay, no differences between Andy and my .tex files so calling it done and sending to Miako (good work all!)

**Comment by cgrandin** [comment]
Thanks, I'm signing off. Talk on Monday at 1pm.

**Comment by aaronmberger** [comment]
Sent and CC'ed you all and sean, closing this issue

**Comment by andrew-edwards** [comment]
Didn't see this conversation, but I found .pdf's looked the same so good. I did one final commit (corrected some periods in two Table captions), so no big deal.
Great work all, I'm signing off soon.

**Comment by taylori** [comment]
Good job everybody. Talk to you at 1pm on Monday.
