### ISSUE TITLE
Update text on 2016 US tribal fishery

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#259]
Will wait until more details about catch.

**Comment by taylori** [comment]
Tribal catch has been identified but wasn't showing up in our database. It's likely that our total catch therefore is missing these landings, but they represent less than 1% of total catch so it is not worth trying to revise the models at this stage, just ensure that we get everything next year (as noted in issue #252). The shore-based processor which received the landings in question is looking into the cause of the issue so I will hold off on revising text until I know more details.

**Comment by taylori** [comment]
Sorry for spacing out and not getting to this one. Will work on this now. Never got to bottom of why the tribal catch wasn't included, but have a few leads that I need to chase down. For now will just change text to replace zero with actual value and say it was not included in model but is small (<1% of total catch) and shouldn't make a big difference but will be included in the future.

**Comment by aaronmberger** [comment]
Was just thinking about this one and had started some possible text to insert in the introduction section (paragraph starting line 81):

"Initial database extractions reported no landings of hake by tribal fisheries in \Sexpr{last.data.yr}.  However, the U.S. advisory panel report on the \Sexpr{last.data.yr} fishery (Appendix~\ref{chap:us-fishery-report}) indicated a tribal catch of 2,470 mt.  The Joint Technical Committee was not made aware of this catch until late in the assessment preparation process, thereby precluding an update to the overall catch this year.  However, this amount of catch is negligible relative to the total catch and thus would have negligible influence on model results and subsequent management forecasts. "

use any or none Ian

**Comment by taylori** [comment]
@aaronmberger, this text looks good to me so go ahead and commit rather than have me copy and paste and risk a mistake. If we want to get extra-obsessive we would add a note to Table a, Table 1, and Figure 4. However, I think that would be more distracting than helpful to say " U.S. tribal catches are included in the appropriate sector, **except in 2016 when they were not included as noted in section 1.4.1.**"

**Comment by aaronmberger** [comment]
Ok, I will just add this in the text as mentioned.  I agree that we don't need to discuss anywhere else as it just confuse people.
