### ISSUE TITLE
Catchability plot in assessment presentation needs extra posterior output

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#261]
Allan did this last year I believe. As of now, it is using this file:
/beamer/SRG/Data/posteriorsExtraOutput.sso
which needs to be updated for this year, if we want to include it.

**Comment by taylori** [comment]
I believe that this file was created using a modified SS executable which produced additional outputs. I think the modification was original made for the hake MSE which may have been necessary for efficiency. However, we can get the catchability values from the extra mcmc files by augmenting the fetch.extra.mcmc function. I will post an issue (probably will be issue #262), related to that and assign it to myself because I think I can get that done without too much fuss.

**Comment by taylori** [comment]
Correction, we already had issue #244 open on this one, so no new issue needed. I suggest leaving this one open until we get the plot working (I think folks have been interested in the estimated catchability in the past).

**Comment by taylori** [comment]
I extracted catchability values from the mcmc-extra runs but the results didn't match the MCMC or the posteriorsExtraOutput.sso that I was able to create from Allan's modified executable that found in his files. I'd like to investigate more but have meetings all afternoon today so will probably just replace the eps figure to save time for now.

**Comment by taylori** [comment]
Catchability values sorted out and added to model$extra.mcmc output. Now working on updating plot to be dynamic.

**Comment by taylori** [comment]
Recent commit (aeb8b7e) adds new make.mcmc.catchability.plot function to make this figure from the output now available in model$extra.mcmc. 

I don't want to create a conflict with in beamer-hake-assessment.rnw which Aaron is editing, so am pasting the revised content of the slide on Catchability which calls the new function and also updates the table to include posterior medians for 2015-2017 and MLE from 2017.

```
\frame{\frametitle{Catchability (\emph{q})}
 \bc
  <<histQ, fig.height=2.25, fig.width=5.5>>=
     # new code that is dynamic
     make.mcmc.catchability.plot(base.model)
  @
  \begin{table}
    \begin{tabular}{cccc} \hline
      MLE (2017) & Median (2017) & Median (2016) & Median (2015) \\ \hline
       \Sexpr{round(base.model$cpue$Calc_Q[1],2)}  & 
          \Sexpr{round(median(base.model$extra.mcmc$Q_vector), 2)} & 
              1.04 & 0.92         \\ \hline
    \end{tabular}
  \end{table}
 \ec
}

```

**Comment by taylori** [comment]
Closing issue thanks to Aaron reporting that the new plot works on his computer.
