### ISSUE TITLE
Add US AP report table to final document

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#262]
US AP report included a table that has to be put into code, but needs to be done for the final version of the document

**Comment by cgrandin** [comment]
Just a reminder to send me the table.. thanks

**Comment by aaronmberger** [comment]
I sent it at 1:38PM.... maybe still on its way...?

**Comment by cgrandin** [comment]
Have it now, our email is terrible!

**Comment by cgrandin** [comment]
Done in commit a1be3509ffa723d21350b125a8a706baaf330e01
