### ISSUE TITLE
Should the following sensitivity be removed from the document?

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#263]
In the Sensitivity Analyses section, there are 10 sensitivities listed, but we didn't do number 10 this year as far as I know:

"Change in the external analysis used to develop the age-2+ input survey biomass index time
series from an approach of using the K-S stratified kriging method with extrapolation to
using the K-S stratified kriging method without extrapolation."

**Comment by taylori** [comment]
No, I don't believe that we did this one and there was no need to do so since the SRG endorsed the extrapolation method presented last year, so we should delete that item from the list.

**Comment by cgrandin** [comment]
Done in commit ff4f1d330ea27b292b7cba353f0f5b0b1654db29
