### ISSUE TITLE
error in code underlying extra.mcmc

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#265]
I was modifying load-models.r to add things to the extra.mcmc extractions (issue #244) but was getting different values for catchability (as noted in issue #261), It turns out that I made a mistake in the setup underlying the extra.mcmc runs.

Specifically, when SS does MCMC, the bias adjustment of recruitment deviations is set to 1.0 for all years, regardless of the settings in the control file, because MCMC explores both the uncertainty within each deviation and the variability among them, making the bias adjustment unnecessary. The run.extra.mcmc.models function is intended to provide Report files that correspond to the 999 samples found in posteriors.sso, by running the model in MLE model with no estimation and the parameters all set to match the posterior sample. However, I forgot to account for the differences between MLE and MCMC in doing so and the resulting dynamics were slightly different. This means that figures 21, 22, and 42 are not quite right in our pre-SRG document and any additions based on the extra.mcmc would not be right without the fix.

I've got things sorted out by modifying load-models.r to adjust the bias adjustment settings in the control file in the extra.mcmc folder and now the catchability values match those created by Allan's modified executable. I'll commit the changes in a minute, but correcting the plots will require everyone to re-run the extra.mcmc (which on my computer took 8 minutes per model directory containing an "mcmc" sub-folder). I think that the following steps will make things right:

- merge my commit when you get a chance
- freshtex or delete knitr-cache
- source('all.r')
- build(FALSE, FALSE, run.extra.mcmc=TRUE)
- build.doc()

**Comment by aaronmberger** [comment]
worked for me, doc seem to build fine...

**Comment by taylori** [comment]
Great.
Here's the difference in the survey fit figure. It's pretty subtle, but with the corrected figure, the median from the MCMC is closer to the MLE, especially in the years 2001-2005.

old:
![image](https://cloud.githubusercontent.com/assets/4992918/22763388/3e69c07a-ee19-11e6-988d-1ff0ea6f73c5.png)

updated:
![image](https://cloud.githubusercontent.com/assets/4992918/22763379/2a7f5430-ee19-11e6-9b88-8a26529f28b9.png)

**Comment by cgrandin** [comment]
Nice catch - I re-ran the extra mcmc and it took about an hour but everything built correctly first time. I think you could close this.

**Comment by taylori** [comment]
Sounds good. Glad the system is working.

**Comment by andrew-edwards** [comment]
For the record, I re-ran also.
