### ISSUE TITLE
Clarify captions for Tables  6-10

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#267]
Clarify that the proportions at age are the proportions in terms of numbers (not biomass).
And mention that there is some weighting done (by catch), unless that's in the text.

**Comment by taylori** [comment]
We may also want to consider adding tables of catch by weight in the future.

**Comment by cgrandin** [comment]
Done in commit 3aec7b83030838476adbe1b20cf16229d4725575. The increased length of the captions means the tables now span 3 pages instead of 2 but I'm not terribly worried about that..
