### ISSUE TITLE
Call today?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#269]
Sorry to post this as an issue, but my calendar just told me that we have a call scheduled for today at 11:30 (in 15 minutes), and this seems like a quicker way to figure if this is happening or not than sending an email through the slow servers. Do we want a call? I am happy either way.

**Comment by andrew-edwards** [comment]
Yes, we said 11:30

**Comment by aaronmberger** [comment]
I'd like to check in, even if just for 10 - 15 minutes...
