### ISSUE TITLE
Summary of historical assessments

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#27]
Allan can create the plot that summarizes past assessment biomasses (Figure 51 in 2015)

**Comment by cgrandin** [comment]
If you add the data as a csv, I can integrate the code so knitr will do it.

**Comment by aaronmberger** [comment]
I have added generic text in the retrospective section that should be double checked once this figure created

**Comment by cgrandin** [comment]
I've addressed the issue in the text and added another year Sexpr, take a look and if you are happy we can close this.

**Comment by aaronmberger** [comment]
seems good to go to me
