### ISSUE TITLE
My document doesn't build anymore

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#270]
error in assessment-section.rnw

will look into later, need to run now

**Comment by taylori** [comment]
Doc built for me and our repositories appear to be in the same place. Edits this morning changed a table to add total biomass which could perhaps lead to a crash if you don't do freshtex.bat or delete knitr-cache. And of course remember to source all.r.

**Comment by andrew-edwards** [comment]
I haven't tried the document for a while, just focussing on my talk. May work a few hours tomorrow, else not until Monday.

**Comment by cgrandin** [comment]
I also just checked and it it working.. on commit 56c8460923eb5ca382272be03cd149734688b8c9

**Comment by aaronmberger** [comment]
okay, found issue with my stuff - somehow one of my model folders went missing.  I have no idea how that could have happen - thinking maybe my slick use of hot/quick keys and shortcuts fudged something up unintentionally... all good now so closing
