### ISSUE TITLE
I'm working on management presentation

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#271]
Will commit some stuff Monday morning.

I've made some progress but had to make a couple changes in other areas and don't want to commit anything until Monday so I don't accidentally mess something up that I'm not around to fix in case others work over the weekend.

**Comment by andrew-edwards** [comment]
I'm only going to work on sensitivity presentation. Will keep committing as I go along, but shouldn't be messing anything up.

**Comment by taylori** [comment]
Closing this. 
In about 15 minutes (just after 8), I'll grab a coffee and pastry at Waves Coffee: https://goo.gl/maps/wvhEjXdBcrw (out hotel door to Hastings, turn right, go to end of block, it's straight ahead directly across street). Or see you in the meeting.
