### ISSUE TITLE
rounding error in upper and lower value for default catch limit

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#272]
Will commit a fix momentarily.

We reported 95% credible interval for default catch limit for 2017 as 296,578 to 3,701,620 t, but these values came from plotting function make.forecast.catch.posterior.plot and were the limits of the darker polygon which used the "density" function and rounded to nearest value in vector of 512 x-values across the range.

Median was correct throughout. Correct values should be 293,697 and 3,710,305 t. Only impact of fix will be on text as this interval was not used in any calculations.

**Comment by andrew-edwards** [comment]
Just to confirm my understanding ...

Regarding the first comment - I presume it's because our 95% credible intervals are the 2.5% to 97.5% intervals, not the technically correct intervals that are 95% 'wide' but can shift to maximise something (I know what I mean for likelihood profiles!). The latter are more fiddly to calcualte, with a vector of x-values and some numerics, rather than just picking the 2.5% and 97.5%.

Hence when the latter method is used (which I think is true given Ian's comment) the numbers come out slightly different. But at the end of the day no big deal, I just want to confirm I understand. 

Thanks!

**Comment by taylori** [comment]
The old calculation wasn't quite 95% wide. I think it was probably a case of 2 pieces of code written at different times, each piece of which  that made sense but didn't interact perfectly.

The values were grabbed from the function that made the plot showing posterior distribution (Fig. 38). This code uses the base R function "density" which creates a smoothed estimate of the density over a range of (by default 512) x values, spanning the range of the input variable. In order to shade the central 95% darker in that figure, the code grabbed the x and y coordinates of the point on the curve which was closest to the 95% interval. It's easy to calculate the exact 95% interval, but getting the appropriate y-value for the curve at that point would have been harder, and the nearby point was close enough for purposes of the plot.

However, when the x values for that interval were output from the plot and used in the text, the difference is noticeable so it's worth using the quantile function instead of passing the calculation through "density". The updated code reduces complexity as the custom-knitr-variables calculation is no longer dependent on the plot function.

**Comment by taylori** [comment]
Also, Figs 42 and 43 in 2016 assessment show that the choice of extrapolation or not made almost zero difference in model results.

**Comment by cgrandin** [comment]
Thanks for catching this Ian. I believe it was my bad due to the rush I was in last year to get all the tables and plots working for the document. I didn't know where to get the output from at the time and figured that would work.. I have re-built and the numbers match yours.

**Comment by taylori** [comment]
This is an iterative process, just trying to take time to make little improvements like this when I notice that it's possible. Closing issue now.
