### ISSUE TITLE
4:3 or 16:9 presentations

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#275]
Change \documentclass[aspectratio=169]{beamer} to \documentclass{beamer} at the beginning of the beamer RNW file.

I have the data presentation working for both cases. If you add the out.width part to the knitr chunk like this:
<<data.overview.map, out.width='3.5in', out.width='0.9\\columnwidth'>>=

it might help fix tables or figures that go off the edge. Also for tables, if you change font.size and space.size to smaller values it might help.

**Comment by andrew-edwards** [comment]
I think you can just change the setting at the start, in:

opts_chunk$set(dev = 'cairo_ps',
               fig.path = 'knitr-cache/',
               fig.dpi = 300,
               fig.width = 6,
               fig.height = 4,
               out.width = '4.5in',  ......

I did that and it seemed to work. Save having to do each one individually.

**Comment by andrew-edwards** [comment]
Tried switching mine back to 16:9 but it's not automated enough so leaving as 4:3. Leaving issue open as it would be nice to automate the widths etc. and just have a simple change in settings at the start of the files.
