### ISSUE TITLE
Stock-recruit plot (Figure 32) - median is wrong

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#276]
Briefly looking at code the line labelled median is just the bias-adjustment term
exp(-0.5 * base.model$sigma_R_in^2) # bias adjustment

= 0.375.

Should instead plot the median - note that y-axis is relative to R0.

**Comment by taylori** [comment]
Oops, forgot this issue was here when I opened #280. Fixed as noted in that thread. Closing this one too.
