### ISSUE TITLE
SRG request for sensitivities to adding age-1 index to phi sensitivities done. 

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#277]
See commit 2fb0bd1beafcf65cc31acd939772bf07e5c02fc9, and make sure to download model runs 63-65 from the Google drive.

**Comment by cgrandin** [comment]
I accidentally included some work on adding an all-age-comps table, but it won't affect anything as it is.

**Comment by andrew-edwards** [comment]
Can't produce figures - do I just do
build()
knit(....)
?

**Comment by cgrandin** [comment]
Open R, source("all.r") then build() which builds the new RData files, then build the requests presentation

**Comment by andrew-edwards** [comment]
Think I did all that...

**Comment by andrew-edwards** [comment]
All good.
Do we want to add  phi=0.03 without age-1 index to the sensitivity group? Think it may be good.

**Comment by andrew-edwards** [comment]
I"m doing it anyway.

**Comment by cgrandin** [comment]
Sure, good idea. I'll do that.

**Comment by andrew-edwards** [comment]
Done and committed. Have to look at the density plot to actually figure out where the yellow and green lines are on biomass plot.

**Comment by andrew-edwards** [comment]
All double checked, and readme.txt file updated on Google Drive.
