### ISSUE TITLE
Figure 16+ captions - describe panels.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#278]

**Comment by taylori** [comment]
Also evaluate where these panels are the most useful ways to present MCMC diagnostics. Perhaps talk to someone who is more familiar with MCMC diagnostics.

**Comment by taylori** [comment]
I think Aaron understands this best so am assigning him to add descriptions of the diagnostics to the caption. We can think about whether the diagnostics are the best ones to display some other day.

**Comment by aaronmberger** [comment]
Ok, will do.  And agree, I'll add a 2018 milestone issue for revisiting MCMC diagnostic plots in general.

**Comment by aaronmberger** [comment]
done and closing

**Comment by andrew-edwards** [comment]
Aren't the top right ones more accurately the 'running mean [or median] and ??% percentiles?'. I'm assuming so as they look like figures that we've done in other assessments (but haven't looked into the code - hoping Aaron/Ian will just know!). Just to be more precise than saying smoothed.

**Comment by taylori** [comment]
Top right panel uses the "running" function from the gtools package as implemented in Ian Stewart's ancient r4ss function here:
https://github.com/r4ss/r4ss/blob/master/R/mcmc.out.R#L204

This appears to be the median across samples 1 up to N for each N as tested with the following function call:
gtools::running(1:5, fun=median, allow.fewer=TRUE, width=5)
1:1 1:2 1:3 1:4 1:5 
1.0 1.5 2.0 2.5 3.0 

The upper and lower lines appear to be 5% and 95% for a 90% interval.

**Comment by aaronmberger** [comment]
They are technically a running mean (I believe) but I couldn't find what the actual smoothing factor was (e.g., running mean over X samples) so went with more generic smoothing word.  happy to have it changed to running mean if you like, but again I only assume that is what it is.  Coda package doesn't give very specific interpretations of these (just says smoothed).  I also assume the shaded area is some percentile around the samples, but again haven't found any explicit description.  I will dig deeper if I have time....

**Comment by aaronmberger** [comment]
Ok, thanks Ian, I will expand on the caption describing this.

**Comment by taylori** [comment]
I was blindly copying the commands but didn't understand what they were doing. Having thought about it for 5 more minutes, I think the interpretation of the code is that running applies the chosen function (such as median) where the window has a width set to 999 points, but the allow.fewer=TRUE option has the window include only the first 1 at first and then moves across to the point where all 999 points are included. However, there's surely a more elegant way to describe that. If you're willing to give it a try, Aaron, that would be great.

**Comment by andrew-edwards** [comment]
Isn't it a cumulative running mean - i.e. mean over all samples from the start, which is why it settles down and is always noisy at first?

**Comment by aaronmberger** [comment]
That sounds like what it is, which actually doesn't seem very useful given the central limit theorem.  Though I suppose if there was drastic non-stationarity, especially a trend, you would see some wiggles.

**Comment by andrew-edwards** [comment]
Yep - all settling down is what you want. We had some nasty ones a couple of years ago that kept drifting and we couldn't use any of the results.

Central limit theorem presumably gets violated if there's drift because not all samples are identically distributed (or at least the same mean). Maybe don't quite need that in the caption :)

**Comment by aaronmberger** [comment]
I think we've exhausted this one (I guess that means we must be close to finished).... I will make some minor changes to the caption for completeness
