### ISSUE TITLE
lognormal distribution in Fig 32 wasn't right

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#280]
It was pointed out in the SRG meeting that the log-normal distribution shown next to the stock-recruit curve in Fig 32 didn't look right. Sure enough, I had set meanlog=1 but really needed meanlog=0 which makes the mean = exp(0)=1. Figure below shows the corrected plot on the right.

![image](https://cloud.githubusercontent.com/assets/4992918/23010823/496761f8-f3d2-11e6-8ee9-1cf38531ac04.png)

**Comment by taylori** [comment]
Fixed in commit aecfffd, closing issue now.

**Comment by andrew-edwards** [comment]
Still looks like the red line is not actually the median?

**Comment by taylori** [comment]
You're right. Thank you. Shows that my intuition about where a median should be is pretty rotten.

That's the whole point of the bias adjustment. The first figure was just wrong. The "fix" had mean = median R0 on a log scale, but that results in a bias on the absolute scale.  Commit from just now (aecfffd) applies a -sigma^2/2 adjustment which results in the resulting distribution having mean = R0 and median below that.
![image](https://cloud.githubusercontent.com/assets/4992918/23027604/a560e06e-f419-11e6-8f8c-c748a3042c47.png)

**Comment by taylori** [comment]
I believe that this is sorted out and so am closing again.
