### ISSUE TITLE
add 24-million MCMC case somewhere in the doc

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#282]
@aaronmberger would need to upload extended MCMC model to make it a full sensitivity or just .eps files showing the diagnostics.

**Comment by andrew-edwards** [comment]
Prob easiest to just use the .eps files as they're already done.

**Comment by cgrandin** [comment]
Agree with Andy since it is a one-off.

**Comment by cgrandin** [comment]
I added the diagnostic plots to the SRG appendix in commit cd62c2b2ec9b5ae774a9d4b2655c434500f56008. It assumes you still have the plots used in the beamer requests presentation. No real content yet in the appendix, just trying to get things set up so it's easier for everyone. I'm almost finished what I can get done for today.
