### ISSUE TITLE
Suggest we create an appendix that shows all SRG requests etc...

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#284]
This way we don't need to alter many sections of the document to cite addition figures/tables etc.  We just need to cite the appendix as whole once.

We could have one appendix that speaks to SRG requests (plots, etc.) and one additional appendix that hold the requested tables that presumably will be produced every year.

Thoughts?

**Comment by cgrandin** [comment]
This makes sense to me. It would be easier to edit one file instead of cobbling it together in multiple sections.

**Comment by aaronmberger** [comment]
Going to refer to the new issue I opened about completing this today, closing this one...
