### ISSUE TITLE
Include sensitivities in the SRG appendix

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#289]
I think we agreed to include all SRG requests in this appendix, and reference the main body when necessary.
I mostly added this issue so it's obvious where to put the sensitivities, and I can continue on this tomorrow. Cheers all

**Comment by aaronmberger** [comment]
Yeah, I figured anything that the SRG requests could go here and then just cite in main text that additional sensitivities were run in response to SRG requests to explore x, y, and z (Appendix X).
