### ISSUE TITLE
Tuesday afternoon

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#290]
Just to avoid conflicts:

Andy working on adding some text references to Chris's new aggregated age-date tables.

**Comment by andrew-edwards** [comment]
Now looking at the new biomass-at-age etc. Tables 21-24. Will understand them and add some text somewhere.

**Comment by andrew-edwards** [comment]
Just tweaking Fig 42 caption and then will get merged with everyone.

**Comment by aaronmberger** [comment]
Finishing up the SRG request appendix and will merge later this evening..

**Comment by taylori** [comment]
I have to quit for the day now. One more meeting tomorrow morning but from 11am onwards I've got things blocked out to help with remaining changes.

**Comment by andrew-edwards** [comment]
I'm all merged and everything seems to work. I'm done for the day, am here all day tomorrow ...
