### ISSUE TITLE
Maybe top panel of Figure 7 (age data) should have the same x-axis scale as bottom panel.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#298]
i.e. go from 1975 to 2016 (for 2017 assessment) so that you can more easily see whether the cohorts match up between data sources. 

[I'm just putting together a talk on using state-space models to give advice to fisheries managers, and will show the hake age data as it's so clean! Hence why looking at hake assessment.]

**Comment by taylori** [comment]
Definitely an improvement. We used to have diagonal lines for the big cohorts on either this plot or the one for the Pearson residuals. I remember concern that adding the lines leads the reader to see cohorts and the bubbles should just speak for themselves, but I'm not sure if we actively decided to remove them on purpose or they just stopped working with some update to the plot code.

**Comment by andrew-edwards** [comment]
Yes, part of me thinks the data should speak for themselves, but on the other hand it does make it easier to understand. I'll try them at some point and we can easily take them off if necessary. May also put fishery age comps at the top to be consistent with Figures 22 (fit to age data) and 23 (Pearson residuals).

**Comment by andrew-edwards** [comment]
I may try faint lines every four years (so not picking out particular cohorts, but allows every cohort to be easily traced).

**Comment by andrew-edwards** [comment]
Note to self - I started (and stashed) doing the diagonal lines (every four years). Bit fiddly to finalise so leave as is for now and come back to if time.
