### ISSUE TITLE
pathway to get to 2018 assessment

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#299]
Updating workflow to SS version 3.30 is noted as Issue #253 but a related question is how to move to new models for 2018 which would involve stuff like:
- backing up or renaming the Google Drive repository of 2017 models
- creating a new folder for 2018 models
- renaming the 2017 base (model 45) to something like 00_45_2017base and clearing out the rest of the models
- updating lots of stuff in [/doc/r/model-setup.r](https://github.com/cgrandin/hake-assessment/blob/master/doc/r/model-setup.r).

Since we don't yet have any 2017 data, it probably makes sense to try to convert the document to work with 3.30 first, then deal with moving to a 2018 model. However, that still leaves a variety of choices, including:
- create a branch for the changes required for 3.30 and plan to get that sorted out and merged before any new data for a 2018 model but theoretically could be done in parallel
- commit to getting the upgrade to 3.30 done and not bother with a branch

**Comment by andrew-edwards** [comment]
Looks like our models folder is just called 'models' (on our computers), so maybe move the 2017 ones to models17 or whatever we like on our computers, and then putting the new 2018 ones into models/  (when the time comes). 

Not sure about the Google Drive 2017 models - do we even need them there any more given we all have them (we should check)? 

Yes, looks like that's the convention for renaming the 2017 base run in order to use for 2018.

Agree we should try the SS 3.30 run with the 2017 data (as in #253). I think best to do as a branch in case we get in a mess. Then we can easily go back to master (rather than undo a bunch of commits, which gets messy). It's generally good to have the master branch working okay, and I'm not sure we'd be changing much on master until we get the 2018 results.

**Comment by taylori** [comment]
Your reasons for proposing to use a branch make sense. If most or all of our edits are to the branch then there will be no issue merging anyway.

Regarding model files, it makes sense that we can each rename the folder however we wish. Aaron and I will also be providing the base model files to a NWFSC assessment archive hosted on a non-public NOAA server, so that's an additional backup. Having said that, it looks like parallel to "Hake JTC 2017" on Google Drive are similar folders form 2016 and 2015, so it would be easy to just add a new 2018 folder with a "models" within it. But perhaps it's better to clean house more often to avoid clutter and make it easier to find the new stuff.

**Comment by andrew-edwards** [comment]
I don't mind either way about the Google Drive. Yes, if we're not running up against any Google Drive size limits then maybe best to just create a 2018 folder with it's own models folder. No point deleting if we don't need to.

**Comment by taylori** [comment]
I created a Hake JTC 2018 on Google Drive and put in the 2017 base model, but I see that the latest version of SS on the NOAA Vlab site: 3.30.08.02 has a bug associated with the hake model. The bug was already found and fixed in the context of some other model, but the fixed version isn't yet on Vlab, so I'll enquire if the fixed version can be made available (hopefully in the next day or two) before working further on the conversion.

**Comment by cgrandin** [comment]
I've been in meetings and so a little late to the discussion..

I was thinking we could just keep the same names, i.e. 45_BasePreSRG_v4 just to save having to change all the names in model-setup.r. They will all be in a different folder so it shouldn't matter.

Ian, I'll await your information on the bug and if we can move forward. I can create and push the new branch once I have the go-ahead.

**Comment by taylori** [comment]
As posted to issue #253, there's now a version 3.30 model that we can work with. I'm not sure if we should focus discussion on that thread or this one as I now realize they are a bit redundant.
