### ISSUE TITLE
To discuss when we meet on 13th December

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#304]
Thought I'd start some notes here about what to chat about tomorrow. Just a list:

1. Go through talks for Thursday
1. Overview of this year's assessment - new data and figures that Ian sent out on 5th Dec (preliminary run with new survey biomass). 
1. Given overview, may as well update first paragraph of Data and Assessment section on page 7.
1. Get up to speed with latest model runs and code (if possible) 
1. Go through the Issues and discuss/assign/delete as necessary.
1. Workflow - how to highlight what needs manually changing from last year (think last year I went through and put ** at the start of any paragraphs that need updating or thinking about); i.e. be careful about not being too overconfident about the automation!
1. I think lots of text wraps around lines, making it hard to see any tiny edits on GitHub. Discuss if want to change that (will lose some easy-to-see history, but that's okay). Pretty easy in Emacs - Alt-x fill-region, but have to be careful about any commented text  (% or #) that gets bumped to the next line. And also it makes it harder to search for phrases that get split over two lines.
1. Discuss where to have lunch.
1. Maybe refine the 'spawning biomass per recruit' as per  http://archive.gulfcouncil.org/council_meetings/BriefingMaterials//BB-06-2015/A-8%20SPR%20Presentation.pdf

**Comment by aaronmberger** [comment]
I have a few items to add but will do so when I get better internet (loading area for Coho ferry touch and go)...

**Comment by aaronmberger** [comment]
some other possible discussion points (some maybe similar to Andy's...)

Others things we should discuss next week with the JTC (just starting a mental list here):
1. Of the tagged '2018 assessment' issues in Github, which do we plan to tackle this round (some, all?)
2. Data preparation/exploration
     - age data sampling representative, and does it represent the same population as the wt at age samples?
     - is there a new maturity ogive?
     - new double read otolith data - reevaluate ageing error choices 
     - others
3. Model development/exploration
     - time-varying selectivity
     - natural mortality?
     - new maturity ogive and maturity x fecundity line in wt age age data file?
     - any use of geostatistical software
     - impact of any new ageing error vectors/matrices?
     - data weighting approach - keep it same or evaluate other approaches as sensitivity (e.g., Dirichlet Multinomial)
     - others
