### ISSUE TITLE
figure out process for submitting assessment document

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#306]
Confirm a few things:
- exact deadline
- who we sent it to
- how it gets onto the web
- any file size limitations
- etc.

**Comment by taylori** [comment]
Stacey Miller (stock assessment coordinator at NWFSC) is filling some of Miako's role in this regard for 2018. In a Jan. 16 email with subject "SRG meeting support and important dates" she wrote "JTC members, please plan to send me the draft assessment no later than COB Monday, February 12th."

I believe that she will distribute it to the reviewers as well as pass it along to the NOAA West Coast Region staff who will post to the hake treaty website.

**Comment by andrew-edwards** [comment]
Yes, I did confirm with after her email (sorry, should have updated this Issue). Don’t think there’s any problem about file size.

Also, you guys have to get it signed off by Owen, yes? I remember he saw a draft before submission with the caveat (from us) that it’s still being refined. Do you want to check with him when he needs it?
