### ISSUE TITLE
add spawning biomass per recruit to the glossary

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#307]
it's in the definition of SPR, but don't use the acronym SPR for this one

**Comment by taylori** [comment]
I just added this in commit 4c21475.

I also added a definition for "Logistic Transformation", since I used that term a lot in the description of the selectivity and change to 3.30.

Once someone reads through both definitions to make sure they make sense, please close the issue.

**Comment by andrew-edwards** [comment]
Thanks - yes, look good and should help.
