### ISSUE TITLE
explore alternative parameterization for time-varying selectivity

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#310]
I've just posted a draft paper by Haikun Xu et al. (currently in review at CJFAS) to the JTC Google Drive folder (in new "papers" folder with title 2DAR_Selectivity_Manuscript_Xu_Thorson_Methot_Taylor_0104.docx).

Hopefully sometime tomorrow I can upload a model that includes this setup as well as some illustrations comparing this parameterization to the status-quo hake assessment.

**Comment by taylori** [comment]
Sorry this has taken a while. I've just uploaded a sensitivity 2018.19.10_semiPara_tvSelect which uses the new semi-parametric selectivity option (as described in the Xu et al. manuscript on Google Drive). This is combined with Dirichlet-Multinomial likelihood as described in issue #315), so represents a change from 2018.19.15_compWeight_DirMult rather than directly from 2018.19_add_2017_tv_select.

Here are some pros and cons of choosing this alternative approach for selectivity.

**PROS**
- with an appropriately chosen sigma parameter, it's able to replicate the results of the status-quo approach reasonably well
- the parameter correlations are much lower (semi-parametric selectivity option has only 2 pairs of parameters with abs(correlation) > 0.7: log(R0) vs. M, and 2016 recdev vs. 2017 dev for age 1 selectivity, as compared to 24 pairs of parameters for the status-quo approach, where all but 1 set (R0 vs. M) were combinations of selectivity deviations.
- Jim Thorson's Laplace Approximation shows some indication that it may produce more plausible results for tuning the variance parameter (equivalent of phi) for this new approach--I had to adapt that code for SS 3.30 and am still working on this.

**CONS**
- It's a new option, the paper describing it is still in review, and it hasn't been as thoroughly explored as the old approach
- It may require some edits to the code for our plots of selectivity (Figures 25-27)--not sure yet on this one (though we may have to do that anyway even if it's just used for a sensitivity and not the base model)
- Hasn't yet been explored in an MCMC context (though due to lower parameter correlations, it should at least converge faster

**Parameters pairs with correlations > 0.7 with two selectivity options**
```
#### correlations > 0.7 for model with semi-parametric selectivity
CoVar <- h19.10$CoVar; tmp <- CoVar[CoVar$Par..i=="Par" & CoVar$Par..j=="Par",]; tmp2 <- tmp[abs(tmp$corr) > 0.7, 9:7]; tmp2[order(abs(tmp2$corr), decreasing=TRUE),]
#            corr           label.j                label.i
# 3      0.924315 NatM_p_1_Fem_GP_1              SR_LN(R0)
# 24385 -0.813420 Main_RecrDev_2016 Fishery_ARDEV_y2017_a1


#### correlations > 0.7 for model with status-quo selectivity deviations
CoVar <- h19$CoVar; tmp <- CoVar[CoVar$Par..i=="Par" & CoVar$Par..j=="Par",]; tmp2 <- tmp[abs(tmp$corr) > 0.7, 9:7]; tmp2[order(abs(tmp2$corr), decreasing=TRUE),]
#            corr                          label.j                          label.i
# 22765 -0.940650 AgeSel_P6_Fishery(1)_DEVadd_2007 AgeSel_P7_Fishery(1)_DEVadd_2007
# 23845 -0.928821 AgeSel_P6_Fishery(1)_DEVadd_2012 AgeSel_P7_Fishery(1)_DEVadd_2012
# 23194 -0.928484 AgeSel_P6_Fishery(1)_DEVadd_2009 AgeSel_P7_Fishery(1)_DEVadd_2009
# 13177 -0.916857 AgeSel_P4_Fishery(1)_DEVadd_2010 AgeSel_P5_Fishery(1)_DEVadd_2010
# 17552 -0.912005 AgeSel_P5_Fishery(1)_DEVadd_2008 AgeSel_P6_Fishery(1)_DEVadd_2008
# 20074 -0.900781 AgeSel_P6_Fishery(1)_DEVadd_1994 AgeSel_P7_Fishery(1)_DEVadd_1994
# 3      0.896250                NatM_p_1_Fem_GP_1                        SR_LN(R0)
# 18119 -0.894345 AgeSel_P5_Fishery(1)_DEVadd_2011 AgeSel_P6_Fishery(1)_DEVadd_2011
# 12694 -0.884787 AgeSel_P4_Fishery(1)_DEVadd_2007 AgeSel_P5_Fishery(1)_DEVadd_2007
# 17179 -0.884598 AgeSel_P5_Fishery(1)_DEVadd_2006 AgeSel_P6_Fishery(1)_DEVadd_2006
# 20680 -0.880418 AgeSel_P6_Fishery(1)_DEVadd_1997 AgeSel_P7_Fishery(1)_DEVadd_1997
# 19477 -0.872067 AgeSel_P6_Fishery(1)_DEVadd_1991 AgeSel_P7_Fishery(1)_DEVadd_1991
# 22340 -0.867687 AgeSel_P6_Fishery(1)_DEVadd_2005 AgeSel_P7_Fishery(1)_DEVadd_2005
# 24284 -0.857930 AgeSel_P6_Fishery(1)_DEVadd_2014 AgeSel_P7_Fishery(1)_DEVadd_2014
# 18502 -0.809337 AgeSel_P5_Fishery(1)_DEVadd_2013 AgeSel_P6_Fishery(1)_DEVadd_2013
# 24727 -0.798704 AgeSel_P6_Fishery(1)_DEVadd_2016 AgeSel_P7_Fishery(1)_DEVadd_2016
# 21295 -0.786897 AgeSel_P6_Fishery(1)_DEVadd_2000 AgeSel_P7_Fishery(1)_DEVadd_2000
# 16810 -0.773741 AgeSel_P5_Fishery(1)_DEVadd_2004 AgeSel_P6_Fishery(1)_DEVadd_2004
# 18889 -0.772784 AgeSel_P5_Fishery(1)_DEVadd_2015 AgeSel_P6_Fishery(1)_DEVadd_2015
# 13504 -0.759866 AgeSel_P4_Fishery(1)_DEVadd_2012 AgeSel_P5_Fishery(1)_DEVadd_2012
# 21710 -0.750531 AgeSel_P6_Fishery(1)_DEVadd_2002 AgeSel_P7_Fishery(1)_DEVadd_2002
# 21919 -0.726204 AgeSel_P6_Fishery(1)_DEVadd_2003 AgeSel_P7_Fishery(1)_DEVadd_2003
# 14852 -0.719423 AgeSel_P5_Fishery(1)_DEVadd_1993 AgeSel_P6_Fishery(1)_DEVadd_1993
# 14170 -0.710582 AgeSel_P4_Fishery(1)_DEVadd_2016 AgeSel_P5_Fishery(1)_DEVadd_2016
```

**Comment by aaronmberger** [comment]
Thanks Ian, I'll be taking a look at these runs (perhaps today or over the weekend) and maybe we can come to a consensus on or before Monday or early next week?

**Comment by andrew-edwards** [comment]
Thanks Ian. The main con is that it's not published or reviewed yet - that might be an issue, especially if we use it as the base model. I just started trying to read it but downloading the .docx seems to get corrupted, and reading online the equations don't show up. Could you please email me a copy (maybe .pdf is better, as ever), or post a .pdf.

**Comment by taylori** [comment]
I did both: uploaded PDF to Google Drive and also just sent to you by email. Thanks for taking a look.
On the one hand, the status-quo selectivity doesn't have a peer-reviewed manuscript supporting it either, but since it's been through SRG review for many years, that gives it a leg up. I'll check with Haikun on status of the review at CJFAS.

**Comment by taylori** [comment]
I've just uploaded an additional model, 2018.19.22_semiPara_tvSelect_sig0.695, which differs from 2018.19.10_semiPara_tvSelect in that the sigma_a parameter (s.d. of selectivity deviations as shown in equation 7 of Xu et al. manuscript) has been tuned using the Laplace Approximation of Thorson et al (2015), which was the basis for the original phi = 0.03 in the status-quo selectivity setup.

The 2018.19.10 model had sigma_a = 1.0 which was chosen by trial and error to produced similar results to 2018.19. The figure below shows the results of the optimization process used to estimate sigma_a.

The two models differ primarily in their estimate of the 2016 recruitment, where the slightly lower sigma_a (0.695 vs 1.0) gives the 2018.18.22 model less flexibility to attribute the catch of age-1 fish in 2017 to changes in selectivity, so the 2016 cohort is estimated to be higher.

I will provide code associated with the Laplace Approximation calculations over the weekend or on Monday, after I format it to be more readable.

![image](https://user-images.githubusercontent.com/4992918/35468495-ed4d5f00-02d3-11e8-934b-dbc10e346515.png)

**Comment by taylori** [comment]
Haikun reports that the status of the semi-parametric manuscript with CJFAS is "Awaiting AE Recommendation".

The figure below is an attempt to illustrate the difference in parameterization of the time-varying selectivity of the status-quo approach vs. the Xu et al. semi-parametric option. This could be included in an appendix or just used in a presentation, depending on what we choose to do with selectivity for either the base model or a sensitivity. It was created using code in doc/r/r-functions/figures-selectivity-parameterizations.r, just commited in 2fd14c5e9fdffd2f969e23019dd41837f86fc382.

The status-quo method has deviations around the original parameters, as shown in panel (a), which then go through a transformation, as described in equations (1)-(3) on page 40 of the 2017 assessment, to get to the resulting selectivity shown in panel (c). The semi-parametric option, as implemented in model 2018.19.22, has the same transformations for the baseline selectivity, but the deviations are applied to the resulting selectivity (e), not in the original parameter space (d). In the example shown, a big increase in selectivity for age 3 (in 1991) is achieved in the status-quo method through a negative deviation in age 4, making age-3 the peak with everything else scaled around it. The alternative approach applies the deviation directly to selectivity age age 3 (it's an exponential offset), with little change in other values. One impact of the alternative approach is that it's possible to have selectivity above 1.0, which I think just impacts the interpretation of fishing mortality for those ages.
![selectivity-parameterizations](https://user-images.githubusercontent.com/4992918/35476114-8b1a7444-035f-11e8-85cb-175c6394a41e.png)

**Comment by aaronmberger** [comment]
It shouldn't matter as long as the fully selected fishing mortality is associated with the max(sel-at-age), whatever the number is.  We could always re-scale the graphics to max out at one if we really wanted to for ease of interpretation, but not necessary in my mind.  I'm still exploring models, but I'm seeing advantages to using the new approach, regardless of method published or not.

**Comment by taylori** [comment]
The "mountains" plot looks a bit different with max > 1.0 but that could be adjusted to facilitate comparisons.

**Comment by aaronmberger** [comment]
I'd suggest we leave it as is for the SRG version, but perhaps afterwards or for next year we can add a flag to the mountains plot function that indicated if one wants the selectivity values re-scaled.  Or I guess, no flag would be needed, just always re-scale to max=1.0, right?

**Comment by aaronmberger** [comment]
My initial thought is to use the tuned 'phi' value.  The con is that it decreases flexibility with the most recent recruitment (problem encountered last year), where in some years we may want the most flexibility - however there is usually little information to inform the model about those recruitment so we are somewhat pissing in the wind anyway.  The problem, at least historically, hasn't been a chronic one and we do have other options to 'play with' recent recruitment estimates for sensitivity analysis or management advice (e.g., age-1 index and setting recent recruitment to average - no deviation).  Still formulating my thoughts on this....

**Comment by taylori** [comment]
The tuned value of 0.695 in model '2018.19.22_semiPara_tvSelect_sig0.695', compared to '2018.19.10_semiPara_tvSelect' with the value fixed at 1.0 indeed results in a bit less flexibility for age-1 selectivity and thus has a higher estimate of 2016 recruitment based on the above-average observations of age-1 fish in the 2017 fishery.

**Additional option for considering**
This new semi-parametric selectivity option was supposed to allow different variance parameters at different ages but when I tried this option it didn't work. In response to my question about this on Friday afternoon, Rick Methot said that the feature wasn't yet fully implemented, but then made a change and emailed me a revised executable. I've just uploaded a new model 2018.19.23_semiPara_tvSelect_age1flex where the folder includes the executable "ss_test.exe" with the fix that allows it to happen. The results are almost the same as 2018.19.22, except that 2016 recruitment is reduced. 

**Concerns about additional option**

1. the new SS version isn't yet publicly released and hasn't been tested as well, 
2. I don't know how to do the Laplace approximation for setting variance parameters in multiple dimensions or if that's even possible, so the sigma for age-1 is arbitrarily set to 1.0 while the sigma for ages 2-5 is re-tuned which reduced it from 0.695 to 0.692, and 
3. it's adding extra complexity requiring somewhat ad-hoc choices.

**Comment by aaronmberger** [comment]
hmm, blocked sigma t.v. select seems promising but perhaps for this year it should be a sensitivity given your concerns, for which I share.  Just eyeballing, it looks like the age-1 index trend would line mostly up with a 2016 recruitment somewhere between the following three cases evaluated so far:
- last year's tv selectivity with MaCallister/Ianelli weighting
- last year's tv selectivity with Dirch.Mult weighting
- the semiPara tv selectivity with sigma at 1.0 and with Dirch.Mult weighting

I'm going to run a profile over alternative sigmas ranging from something like 0.55 - 0.85 (given your figure above Ian) to see what we are looking at in terms of outputs for mgmt and any interaction with other likelihood components.  Unless you have already done this Ian when creating the figure above.

**Comment by taylori** [comment]
I didn't do a profile, I used the optimize function in combination with Thorson's NegLogInt_Fn function (fixed in the development branch of r4ss) to get the 0.695 value. I think you could use the determinant of the Hessian from steps in a profile to create a similar, but  smoother, figure to the one I posted above https://github.com/cgrandin/hake-assessment/issues/310#issuecomment-360958189.

For future reference, here are steps I used for Laplace approximation, in case I failed to include them in any other scripts or comments:
```
#### optimizing for model with semi-parametric selectivity
# define full path because wd is changed in function
direc <- file.path(dir.models, 'sel_tests/2018.19.10_semiPara_tvSelect_Laplace')

# delete record of any past optimizations
if("Optimization_record.txt" %in% list.files(direc)) {
  file.remove(file.path(direc,"Optimization_record.txt"))
}
Opt = optimize(f=NegLogInt_Fn,
    interval=c(0.05, 2.0),
    maximum=FALSE,
    File=direc,
    CTL_linenum_List=list(243),
    ESTPAR_num_List=list(150:225),
    Int_Group_List=1,
    PAR_num_Vec=NA,
    StartFromPar=FALSE,
    Intern=TRUE)
```

**Comment by taylori** [comment]
Just added script for Laplace approximation used to tune time-varying selectivity variance (which is more complete than code pasted into previous comment) as `doc/r/r-functions/tuning_selectivity_sigma_with_Laplace.R` in commit f3ad567ffe19ef9a8da8dd63cb027330097365a8

**Comment by aaronmberger** [comment]
Thanks Ian, I think your figure above is plenty fine-scaled to show the 'tuning'.  I thought I'd try a profile across a range of sigmas (those near the peak in your figure) just to look at the interaction between those different values and other likelihood components (e.g., survey index).  It may not show anything, and I'm guessing it won't given the similarities among runs (other than 2016 recruitment), but it might be worth having to show that key management quantities are or are not dependent on the sigma selection.

**Comment by taylori** [comment]
Agreement during today's phone call was to make this alternative parameterization a sensitivity and not yet adopt for the base model.

**Comment by andrew-edwards** [comment]
Ian - is Haikun (and co-authors) okay with us sharing the draft of the the manuscript. It will presumably have to be distributed to participants since we will need to reference it, even for a sensitivity. It wouldn't have to go on a public Google Drive or website, but once 40 people get it it would be fairly public.

**Comment by taylori** [comment]
Figures posted in comments on this issue haven't yet been included in the document, but I will remember to consider adding them if time allows in the days ahead. For now, I think this issue has been adequately addressed to close it.

**Comment by James-Thorson** [comment]
Ian

did you ever update NegLogInt_Fn to work with SSV3.3?  Grant Thompson and I are discussing on a separate thread.

**Comment by iantaylor-NOAA** [comment]
@James-Thorson 
I didn't recall doing so, but see this note that says I did: https://github.com/r4ss/r4ss/issues/44#issuecomment-360930400
