### ISSUE TITLE
Suggest change commit number for version 1.3 (final 2017 code)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#311]
Suggest Release v1.3 (post-SRG version of 2017 assessment - i.e. final version) should be commit b6f1409a7 from the end of 28 Feb 2017, not the one from 22 Feb 2017 as it is currently.

I think the 22 Feb version got tagged because that's the date that appeared on the front of the assessment (though it should have been 27 Feb which is when we submitted - I can automate the date).

Not a huge deal but I reverted to version 1.3 to test everything running on my new laptop, and some things didn't work (extra biomass-at-age tables etc.) as they were done after 22 Feb, as can be seen at
https://github.com/cgrandin/hake-assessment/compare/v1.3...master
(which nicely shows the commits from the v1.3 to latest master). 

The tables work fine on the 27 Feb version. Some bridging figures don't seem to work but I'm not going to worry - happy to get my new laptop in a state that things are running well.

I would edit the Release version  info but thought should check with Chris (not sure if it's bad form to retroactively change a release!). Not a biggie but should be quick to do when he gets back, and is good for the record.

**Comment by taylori** [comment]
Sounds good to me. I'm not sure how to do this, but go ahead and make the switch.

**Comment by andrew-edwards** [comment]
Ignore for now.
