### ISSUE TITLE
Get document building in 2018

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#312]
So I got my new laptop set up and can pretty much build last year's document (reverting to an earlier commit). With all the changes to SS etc. it would be good to get a full build working - presumably we need some dummy/simple sensitivity analyses and bridging for that? I think so - but can check.

I'll get updated tomorrow with SS. 

Ian (only person around this week) - does that sound like it's worth me doing, or should I work with you on something?

**Comment by taylori** [comment]
I agree that testing the document building is a high priority, and it wouldn't take too long to create some dummy alternative models, but if it's possible to reduce the number of required sensitivities, retrospectives, etc. that might be speed up the process as well.

I'll post a separate issue with some thoughts on bridging from 2017 to 2018 models

**Comment by andrew-edwards** [comment]
I just spoke to Chris (he's in!) - the document should build with his latest version. It basically has an updated SS3 file for last year's base case, plus last year's sensitivity/bridging runs. So not strictly comparable, but should build. And he also tested some sens/bridge runs with the new SS. So no need for us to set up some fake runs to get it working. Excellent.

So I'll get that going today, so I can start looking/editing some of the text.

**Comment by andrew-edwards** [comment]
Can't quite get it to run, as I get 
     Error in Ops.data.frame(natage.table.slim, selwt.table.slim) : 
     '*' only defined for equally-sized data frames
Chris was helping me earlier - he'll try and fix it tomorrow. I thought we figured it out (and I re-ran the forecasts etc.).

**Comment by cgrandin** [comment]
I created some dummy models to get the sensitivity plots and tables working back in November so building the document with sensitivity and bridging models should all be good to go (except for those small bugs that always creep in). I'm currently at commit 623c40ea98ed1a959b0f18f25c8a7a80adc4ea14 and the build() function works and the document builds.

**Comment by andrew-edwards** [comment]
Chris - after just running (when you were in my office) I get the same error as yesterday. The last line that gets printed out in my console is:
     Loading report file:  ../../models/00_55_2016base/extra-mcmc/reports/Report_999.sso

**Comment by cgrandin** [comment]
I get the same error which is good, I'll investigate.

**Comment by andrew-edwards** [comment]
Think we've fixed it in 8006d0cb - the pesky "Year" (previous SS) vs "Yr" (SS 3.3) issue.

Am re-running and will update.

**Comment by taylori** [comment]
Glad to hear and sorry for the troubles.
For future reference of things to search for, here's a list of the terminology alignments (copied from https://github.com/r4ss/r4ss/issues/141#issuecomment-292611174)
They have been implemented in r4ss such that even when `SS_output` is used to read a 3.24 model, it will rename the columns to match the new conventions used in 3.30 to facilitate comparison between the models. There may still lingering inconsistencies, however.

```
Previously                                              Now

Year = Yr                                               Yr
Gender = Sex                                            Sex
F_report_basis = F_std_basis = F_std_method             F_report_basis
SPR_ratio_basis = SPR_report_basis = SPR_std_method     SPR_report_basis
SSB = SPB                                               SSB
Spbio = spawn_bio = SpawnBio                            SpawnBio
BirthSeas = Birthseas = Bseas                           BirthSeas
Pr_ = PR_ = Prior_                                      Pr_
r.m.s.e. = rmse = RMSE                                  RMSE
Supr_Per = SuprPer                                      SuprPer
Y/R = YPR                                               YPR
```

**Comment by andrew-edwards** [comment]
So build(T, T, T) ran okay (did not crash), but the first warnings are:
```
> warnings()
Warning messages:
1: running command 'c:/windows/system32/cmd.exe /c cd ../../models/03_2017base_3.30_tv_pars/mcmc/forecasts/forecast-year-2017/01-0 & ss3 -mceval' had status 1
2: In shell(shell.command) :
  'cd ../../models/03_2017base_3.30_tv_pars/mcmc/forecasts/forecast-year-2017/01-0 & ss3 -mceval' execution failed with error code 1
3: running command 'c:/windows/system32/cmd.exe /c cd ../../models/03_2017base_3.30_tv_pars/mcmc/forecasts/forecast-year-2017/02-180000 & ss3 -mceval' had status 1
```

The knitr crashes in the executive-summary:
```
Quitting from lines 49-62 (./executive-summary/executive-summary.rnw) 
Quitting from lines 64-66 (./executive-summary/executive-summary.rnw) 
Error in format(round(x, dec.points), big.mark = ",", nsmall = dec.points) : 
  object 'cohort.catch.1999' not found
```
Chris - I'll take a look now, and/or we can work on it tomorrow. We are trying the mixture of SS versions, so maybe we should just make some dummy ones.

**Comment by andrew-edwards** [comment]
Might it be because we changed the assess.yr, but the MCMC runs in the new base model were done to the start of 2018?

**Comment by andrew-edwards** [comment]
Chris is off, so I'll take a stab at debugging based on my comment (two above).

Regarding Ian's comment about r4ss renaming the columns (thanks for the summary!), presumably that doesn't always work for us because we've re-defined some of the r4ss functions, yes? I will try and trace why I still get an error.

**Comment by andrew-edwards** [comment]
I have it succesfully building, as of commit f8a6066!
A few figures don't get built - think a couple are Yr/year issues (I'll work on those now), but a couple are because the years are out of alignment (which will get fixed when we do proper base run and assess.yr, i.e. Issue #316).

**Comment by andrew-edwards** [comment]
Regarding Ian's summary of renaming - should there also be     
fleet     to     Fleet   ?
Had to do this in commit  ea5c614    to get  two tables working.

**Comment by taylori** [comment]
Yes, I'm sure fleet to Fleet should have been on the list.

Even having matched the previous commit, I'm having some issues running `build()`. 

The first issue I traced back to the attempt to look for "ss3.par" in 
[r-functions/load-models.r](https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/load-models.r). A change that came with SS version 3.30 is that the .par file written (and read if requested) by the executable is hardwired to be ss.par, regardless of whether the executable is called ss.exe, ss_trans.exe, or ss_opt.exe. However, I don't see any place that we use the par file, so I think we could just remove the lines related to reading the .par file.

However, after that I'm getting an issue
```
Error in fetch.forecasts(model$mcmcpath, fore.yrs, forecast.catch.levels,  : 
  fetch.forecasts: There is a discrepancy between what you have set for the catch.levels names 
 and what appears in the forecasts directory '../../models/03_2017base_3.30_tv_pars/mcmc/forecasts/forecast-year-2017'. 
 Check the names in both and try again.
```

Perhaps instead of worrying about getting the document working on my computer, I should just focus on getting our 2018 new models sorted out. I have a mid-day appointment pulling me away from the computer for a bit regardless.

**Comment by andrew-edwards** [comment]
We did manually change ss.exe to ss3.exe in the new models folders (e.g. 03_2017base_3.30_tv_pars).

But agree - yes if you can focus on the new models that would be more efficient. 

I have one table left to fix, otherwise it builds okay - some calculations are wrong and figures are missing lines, but I presume only because we don't have consistency between models (some old, some new), and that will get sorted out with all 2018 models. Then I'll work on text this afternoon as per Issue #305 (line breaks for GitHub readability and flagging it for manual edits).

**Comment by taylori** [comment]
I'll focus on modeling, but do keep watch for anything related to .par files.

In the TPL file for Stock Synthesis, it has the lines
```
    // set the filename to all ADMB output files to "ss.[ext]"
    ad_comm::adprogram_name = "ss";
```
which should cause all of the default ADMB output files to have format ss.par, ss.cor, etc., in spite of our renaming the executable. The intent behind this change was to save users having to rename their .par file if they wanted to use it as a source of initial values.

**Comment by andrew-edwards** [comment]
Table doesn't build but should get rectified automatically - made it issue #317 to double check. Plus some figures get built but don't yet come out right - also expect because we don't have consistent models.

So - document builds! I'll start on #305.

**Comment by andrew-edwards** [comment]
I'll close as I (at least!) have it building. Will try Ian's new model run.
