### ISSUE TITLE
Change assess.yr-1 back to assess.yr as per 623c40ea9

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#316]
That commit was to get the document building. When doing build() I got:
     Error in Ops.data.frame(natage.table.slim, selwt.table.slim) : 
      '*' only defined for equally-sized data frames

This Issue is just a reminder to change it back at some point when we have the true models running.

**Comment by andrew-edwards** [comment]
And delete the appropriate .RData files and extra-mcmc/ folder.

**Comment by andrew-edwards** [comment]
Also change survey.end.yr and check other settings in model-setup.r

**Comment by cgrandin** [comment]
This has been done. assess.yr is now 2018.
