### ISSUE TITLE
Figure and Tables are mainly forced to go in a specific place

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#32]
Figures and Tables in Exec Summary are currently forced to go where they appear in the text, using the H in: 
\begin{figure}[H]  

But Figure b ended up two pages away from where it was first mentioned. I can sort these out nearer the end, and look at using [tp], since Latex treats the placements intelligently. This should, in theory, remove some of the unnecessary whitespace.

**Comment by cgrandin** [comment]
Andy, I think you are aware of this but I post here for everyone. I've been using 'H' for all figures, except when I wanted to force two of them together on a page to avoid large amounts of whitespace. In that case, I 'joined' them by using 'p' (see main-figures.rnw). I would just like to make sure some weirdness doesn't occur later if we start floating figures around.

**Comment by andrew-edwards** [comment]
Yes, you need the H for sure in the main-figures section. But in the Exec Summary it isn't so necessary (unless where there are multiple figures/tables close together, which may happen). 
I may have a play around nearer the end, if time..... I agree that too many floats can mess things up.
When I moved figure b to closer to it's text, the [H] ended up leaving two lines at the top of the page and then a figure, so it made sense to make it a [tp].
