### ISSUE TITLE
Update GitHub data folder with new data from Google Drive data folder

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#320]
Just to ensure it gets done.

**Comment by aaronmberger** [comment]
assigned to me, I'll get on this today or early tomorrow

**Comment by aaronmberger** [comment]
Related to issue #329:

All the data files have been updated except the following:

ovary-samples.csv (values for 2017 need to be entered, Ian do you have these?)
survey-comparison (I could not locate some of the entries, e.g., CV on no extrap 2017 survey, so may need to check with Rebecca)
survey-history (a few entries need filling in, may need assistance from survey folks)

I'm contacting survey folks today to finish this up.

**Comment by cgrandin** [comment]
I made a comment in another issue but I'll just say again here that I still need to add the new data for Canada. The age file has been split into 3 new files, with a new format so I'll need to write new code to deal with that.

**Comment by aaronmberger** [comment]
Chris, you are right for the 'raw' data files on the google drive.  However, I followed the same format as last year when compiling the 'raw' data files into the csv files in hake-assessment/data

Check it out, I think we are okay here (?)

**Comment by aaronmberger** [comment]
will need to merge my recent commits...

**Comment by cgrandin** [comment]
Yeah, thanks for doing that. I was going to do more work to make it drag-and-drop but this is fine also.

**Comment by aaronmberger** [comment]
I think we are all set with this one, closing now
