### ISSUE TITLE
May want/need to compare versions of SS_readforecast

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#322]
See db9bcd9  and the accompanying comments. 
Won't be hard to do, just a bit of detective work and saving different versions of the function (ours before it was commented vs r4ss and maybe vs older version of r4ss).

**Comment by andrew-edwards** [comment]
Bleh. The formatting (leading spaces) is different between files. 
Can't visually see any obvious differences - can see the error we had earlier today concerning "... multiple of 4...". But working backwards with Nvals and previous calculations that create that, can't see anything that changed. Tricky to see though. May not be needed, but took a look while build(T, T, T) was running.

**Comment by cgrandin** [comment]
I'll look at this Tuesday Jan 23

**Comment by cgrandin** [comment]
This is a non-issue at this point :)
