### ISSUE TITLE
run sensitivities

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#325]
Here is an initial list, broken down into must do's (requested by SRG or identified as of interest) and other possibilities:

Must do:
- add age-1 survey index
- higher/lower variation about stock-recruitment relationship (sigma-r)
- consider alternative values for steepness
- consideration of alternative SDs (or methods) for time-varying selectivity
- alternative (last year did higher SD on prior) parameterization of natural mortality

Other possibilities: 
- no cohort-based ageing 
- alternative maximum age assumptions for selectivity parameterization
- alternative maturity and/or fecundity ogive/relationships
- alternative weighting scheme (Dir. Mult or McAllister/Ianneli - whichever not in base model)
- potential alternative catch series for U.S. shoreside - pending outcome of discrepancy between tribal reported landings and what is in PacFIN - currently being looked into)
- potential alternative composition series for U.S. given [very small] differences when aggregate annual  composition was weighted by monthly compositions using monthly catch as the weight

Others?

**Comment by taylori** [comment]
That looks really complete to me. 

What would be the best way of dividing these tasks up?

For internal JTC purposes, it might also be useful for each one to write either a brief instruction on what's required to make it happen, or an R script to change the files, so that they could quickly be repeated on a future base model if we make changes along the way.

**Comment by andrew-edwards** [comment]
R script to change the files might easily run into problems and be more work than it's worth. Also, it can be instructive to (be forced to) manually edit the files.
Suggest it's better to add instructions as another 'How to...' section in the README.md, which is the obvious place to look. I think I ran some sensitivities last year (maybe?), but can't recall how to do it (or see any notes in the README). So how about a general 'How to run a sensitivity test', with general details (basically just edit the input file and run some command), followed by subheadings with what to specifically change for each specific sensitivity test?

**Comment by taylori** [comment]
This makes sense.
And we can add the titles as placeholders without yet filling in the details.

**Comment by kellijohnson** [comment]
When I did the sablefish assessment, where there were multiple coauthors, I found it helpful to have a .Rnw template the coauthors manipulated for each sensitivity such that at least one table was the same for all sensitivity runs and was named using a common naming structure.

**Comment by taylori** [comment]
Hi Kelli,
Thanks for watching and chiming in. Could you share an example of what that template looked like? If it's not too long you could just paste it into the issue, or send me email or whatever.
-Ian

**Comment by kellijohnson** [comment]
I attached the file here, though I had to change the name from .R to .txt for it to upload.
[sablefish_template.txt](https://github.com/cgrandin/hake-assessment/files/1661060/sablefish_template.txt)

**Comment by aaronmberger** [comment]
I'll start running the sensitivities using the temp base run after the bridge rune to include 2017 t.v. selectivity.  I will document the changes made from the base to each sensitivity and create a short-write up for the readme about doing sensitivities.  I'm holding off on incorporating these steps into a rnw for now, but can revisit as time allows using Kelli's example code above as a starting place.

**Comment by taylori** [comment]
Aaron could you just create that bridge run as well?

**Model numbering conventions**
Right now 2018.18 was just a copy of 2018.17 to allow it to have the name "temporary_base", but maybe that duplication is unnecessary. 

Also, if multiple folks are running sensitivities, it would be good to come up with a system for avoiding duplicate numbers. There's no real reason they need to be sequential, so it would be possible to block out different ranges for different folks. Or we could just make a numbered list of sensitivities to be run in the README and people can assign names. @aaronmberger , if that approach makes sense to you, perhaps you could commit a list of those you plan to work on (perhaps including extra numbers in case it's not clear how many will be in a given group)?

We could also use letters or addition numbers: 2018.18b or 2018.18.2 if there's any need to represent similarity among runs or add an additional model while keep things sequential, but that might just get confusing.

**Comment by aaronmberger** [comment]
Yep, I'll run that bridge also.  Is anyone else running sensitivities?  Andy, did you want to have a go on some of them (after some instructions build)?  I'm fine to go through them all, but if want some more experience with them let's split them up.

**Comment by andrew-edwards** [comment]
Yes, I can run some. Will force me to look at the input files more carefully. 
Yes, if you add some instructions in the readme that would be great, plus list the sensitivity runs with model numbers and people (as Ian suggested).

**Comment by cgrandin** [comment]
I think "make a numbered list of sensitivities to be run in the README and people can assign names" is a good idea. I can run some as well.

**Comment by aaronmberger** [comment]
Okay, standby....  I'm bridging the t.v. selectivity first, then run short mcmc on that, than will create sensitivity instructions...  let you know when ready

**Comment by taylori** [comment]
Having more folks look at the input files is definitely beneficial, both to see how the format has changed from 3.24, and also as another set of eyes to catch any potential issues (like TV selectivity not getting extended). And sharing the understanding and workload is useful too.

I have sensitivities to earlier models that I'd like to apply to the new temporary base for the following:

- change to Dirichlet-Multinomial likelihood for data-weighting (described in Thorson et al 2017 paper, issue #315)
- add "semi-parametric" selectivity (as described in Xu et al. manuscript, issue #310, recommended to be used in combo with Dirichlet-Multinomial above)

**Comment by aaronmberger** [comment]
A compilation of sensitivity runs have been listed on the README google sheet in the models folder.  I've attempted to comment on how to run some of these, but they may be (likely are) still a bit unclear.  Please ask if/when something is unclear or your unable to proceed.  

You will want start by creating a new directory for each run using the label in the readme.  

Then copy over the necessary base model (2018_19...) files: 2018hake_control.ss, 2018hake_data.ss, forecast.ss, ss3.exe, starter.ss, and wtatage.ss.

Make the necessary changes to the control, data, or both files as required for the particular sensitivity (see readme comments).

Run the executable.

Once all sensitivities are done we can do some comparisons using SSplotComparisons to evaluate how we may want to display/aggregate this information in the document.

**Comment by aaronmberger** [comment]
oh yes, and then upload your model files to the google drive model folder...

**Comment by aaronmberger** [comment]
Perhaps before we go too nuts with sensitivity runs, we should settle in on a likely 'preSRG base model'.  I'm thinking that model 2018.19_.....  (our most recent 'temp base') may not be our 'preSRG base' because of planned incorporation (or at least investigation) of the Dirichlet Multinomial data weighting and the non-parametric time-varying selectivity.  After we figure out if we are going to incorporate these into our preSRG base, we can then run the rest of the sensitivities to that model.  Our current sensitivities will not be 'one-off or one change type of sensitivity runs, which we want, if we change the base model.  Other than the two issues mentioned above, I don't think a priori that the rest of the sensitivity trials listed in the readme have a high probability of making the preSRG base model (other than perhaps some change in U.S. total catch as a result of ongoing tribal catch investigations). 

Shall we make a plan for addressing the DirMult and time-varying selectivity approach so that we can hone in on a base model?  Ian, you know the most about these two options, so I guess I'm wondering if you have time to investigate these further.  I can certainly help, but may need some guidance.

Thoughts?

**Comment by andrew-edwards** [comment]
Yes, that sounds sensible (I was also wondering about this last night). Basically do the bridging until we get a likely 'preSRG base'. 
Then first do the important sensitivities whose results may lead us to change the base model - likely the DirMult and time-varying selectivity approaches, as you mentioned.
Then settle on a base model to then (re)do all sensitivites from.

I'm going to hold off on running sensitivities to get the rest of the text flagged this morning.

**Comment by taylori** [comment]
Aaron's suggested plan does make sense. Sorry I just got going this morning and am still wading through all the issues and emails. I will upload some models that use the Dirichlet-Multinomial for you all to look at later this morning and work as quickly as I can to add in the alternative selectivity option. Yesterday I was working on a figure illustrating the comparison of two, but getting the models put together for consideration doesn't have to wait for that.

**Comment by aaronmberger** [comment]
Thanks Ian!  And no big rush, once we have a preSRG base the sensitivities can go quite fast.  I think the two cases your working on are our main axes of alternative base model considerations.  So we should all definitely take time to scrutinize...!

**Comment by cgrandin** [comment]
Sounds good, I also got going late today so just catching up. I already uploaded some sensitivities so we'll have to replace those if we decide to change the base model.

**Comment by taylori** [comment]
Dirichlet-Multinomial likelihood uploaded as model 2018.19.15_compWeight_DirMult, along with 2018.19.20 and 2018.19.21 which compare McAllister-Ianelli data weighting to Dirichlet-Multinomial option without any time-varying selectivity.

I will comment more about these models under issue #315.

**Comment by taylori** [comment]
I've just uploaded models `2018.19.24_MatOgive_1` and `2018.19.25_MatOgive_2` which use a new maturity ogive based on 1,947 samples with ages from north of 34.44 degrees (excluding 87 samples from further south continue to show patterns identified before of very different maturity, suggesting a potentially different stock). This is based on "functional maturity", where Melissa Head, who did the histology, had notes on some of the oldest fish like "This ovary appears to be incapable of spawning. I found 6 stage 3 oocytes, the rest of the ovarian tissue is hollow and dead. Senescence."

The impact on model results is quite small when the new maturity is applied to the average weight at age averaged across all years (first of the two new models). When instead it's applied to the table of weight-at-age with annual variation (second model), the impact is larger, with spawning biomass jerking around a lot more, and a big spike in 1975-1976 where the oldest fish were much heavier. But the overall impact is still muted by using the average value for the initial conditions and the unfished equilibrium. If we were to somehow project the wtatage matrix backwards prior to 1975 when the data begin, that might have a bigger impact, but would require lots of assumptions.

Here are a couple plots showing patterns in these maturity data. I will upload the code and notes in the morning. I just wanted to get something posted for our discussion tomorrow.
![maturity_at_age](https://user-images.githubusercontent.com/4992918/35545106-47362c4a-0522-11e8-8865-3677fe5e91c6.png)
![fecundity_comparison](https://user-images.githubusercontent.com/4992918/35545174-a4c62da6-0522-11e8-98c2-25211435a3e2.png)

**Comment by taylori** [comment]
Sounds like we're in agreement to use the new maturity curve (red line in previous comment).
This just involves using the wtatage.ss file from model `2018.19.24_MatOgive_1` with any other model that includes 2017 data.

**Comment by aaronmberger** [comment]
I updated the model readme document with anticipated model numbers for sensitivity runs.  Are there any more that we would like to do?  Any arisen that we don't already have for SRG discussion on time varying selectivity - what we used and progress on other (sigma-S) approaches?

**Comment by taylori** [comment]
Thank you.
I revised the description for the alternative phi sensitivities. To reflect updated data.rnw section explaining that a factor of 7 (connected to the parameter bounds being -5 to 9 for a width of 14) is a good conversion from the old phi with logistic transformation, to the new phi without (thus, 1.40 is the value in the base model instead of 0.20).

To avoid confusion, it might be worth changing the names from 2018.40.11_tvSelect_phi0.03, 2018.40.12_tvSelect_phi0.1, and 2018.40.13_tvSelect_phi0.3, to ...phi_xtralow, ..._phi_low, ..._phi_high.

I also revised the name of the first semi-parametric selectivity to not tie it to sigma=0.695, and added two more for future explorations:
2018.40.20_semiPara_tvSelect_option1
2018.40.21_semiPara_tvSelect_option2
2018.40.22_semiPara_tvSelect_option3

**Comment by aaronmberger** [comment]
Sensitivities that were identified have been run and uploaded (all but one) to the models drive.  I will have a deeper look into the results of these and update the model setup folder on Sunday morning.  I may end up running more sensitivities after I explore further.

**Comment by aaronmberger** [comment]
I changed the model setup file to incorporate the current list of sensitivities, but this broke the document build because of inconsistencies with the assessment-section.rnw so rectifying that now

**Comment by cgrandin** [comment]
Thanks for doing all the sensitivities Aaron, I am currently re-building everything and catching up.

**Comment by aaronmberger** [comment]
Changed text and figure calls in assessment rnw for sensitivity section.  Currently my build is halting at retrospective squid plot figure, let me know if your builds.

**Comment by cgrandin** [comment]
Aaron, can you push your changes? Then I'll be at the same error as you. Thanks

**Comment by aaronmberger** [comment]
Chris, perhaps merge my updates and let me know if you can build - recent updates are just syncing sensitivity plots in model setup with that referenced in text

**Comment by cgrandin** [comment]
Roger, will do as soon as my build() is done.

**Comment by taylori** [comment]
I'm getting some errors in assessment-section.rnw in references to sensitivities. This first one was 
```
Quitting from lines 2-1255 (./assessment-section/assessment-section.rnw) 
Quitting from lines NA-1255 (./assessment-section/assessment-section.rnw) 
Error in sens.models.4[[which(sens.model.names.4 == "Natural mortality SD 0.3")]] : 
  attempt to select less than one element in get1index
```
which seems to be from line 1130 in assessment-section.rnw:
```
\Sexpr{round(sens.models.4[[which(sens.model.names.4=="Natural mortality SD 0.3")]]$parameters$Value[1],3)} 
```
But now running after commenting that out leads to another:
```
Error in sens.models.4[[which(sens.model.names.4 == "Steepness prior mean 0.5")]] : 
```
@aaronmberger did you fix some of these already or should I try

**Comment by aaronmberger** [comment]
My most recent commits take care of those cross-referencing errors that developed from renaming sensitivity models names.  these were renamed to hopeful improve organization of key sensitivity runs as well data sensitivity runs and selectivity sensitivity runs

**Comment by taylori** [comment]
Everything is now working for me. Aaron, is it OK for you too, or could you have something in your knitr-cache that needs clearing out?
I see some red error messages after Tables 25 and 31 but will post separate issues for each of those so we can work toward closing this issue.

**Comment by andrew-edwards** [comment]
Mine builds - same two error messages as Ian.

**Comment by taylori** [comment]
The results of the sensitivities look reasonable to me based on what they cause previous iterations of the model to do. The high sigmaR model creates a too-big mismatch between equilibrium and initial conditions, while the low sigmaR has a mismatch between the sigmaR value and the estimated variability in the recruitment.

The wider prior on M dramatically increases the uncertainty in the model, which is probably a good characterization, but also pushes up the biomass in ways that make the median estimates perhaps less plausible.

I feel in general that they sensitivities are good and support the base model we've chosen. The only suggestion for change I see is noted in issue #361.

Lastly, I still hope to add one more for consideration related to the alternative selectivity parameterization.

**Comment by taylori** [comment]
Closing this issue to clean it up.
