### ISSUE TITLE
Document build working Jan 24 but see issue about TV selectivity

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#327]
The document will build now (commit c080d5bfd340271e1fcd06702c2b1edbe8f78584), with 2018 as the end year and 2017 as the last survey year.

See issue #326, I had to change all the TV selectivity plot calls to end one year less to make this happen.

You have to re-run the forecasting by running build(TRUE) to make sure the forecast years start at 2018.

Some things are broken, but it will build now at least!

**Comment by taylori** [comment]
Great news. Thank you!

**Comment by cgrandin** [comment]
Another note, there are broken tables right now but once we have the sensitivities for this year they should automatically be working again, so I'm inclined to not bother fixing them just to have to fix them again when we add the new sensitivities.

**Comment by andrew-edwards** [comment]
I have it building. Yes, I think any broken things will get fix once things are all updated. Some missing numbers (such as recent catch), but due to #320 so will get fixed automatically.
I'll get on with flagging text that we have to manually change (as per #318. After lunch.
