### ISSUE TITLE
Bridging figures/tables (and sensitivity)

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#33]
As the master, Chris, how do you envisage the incorporation of bridging (and sensitivity) figures and tables.  I'm guessing that you've already coded in some sort of skeleton based on last years document.  However, there will inevitable be changes in the number of figures/tables and their contents here because of the year-to-year uniqueness of these (save for those 'key' sensitivities that we are asked to output).  Looking for guidance before I dig in.

**Comment by aaronmberger** [comment]
...further.... I guess my thought was that this would be one place were we may have to just insert/call hard coded files....

**Comment by cgrandin** [comment]
It'll be fairly straightforward for me to have knitr make the plots and tables for the sensitivities. The sensitivity plots are very similar to the bridging plots, which I've already done. All I need is to know which sensitivities to include, and I will start the process. I see you have uploaded some sensitivity models, so I'll start with some of those (if I can get them downloaded on our slow network). Thanks Aaron

**Comment by aaronmberger** [comment]
Okay, in not too long I should have examples of what I was thinking for bridging and sensitivity plots...

**Comment by cgrandin** [comment]
Excellent.. I have downloaded some of the sensitivity models and will start to produce similar plots to last year (for now). I can add others later. cheers
