### ISSUE TITLE
Extra blank page (73) needs fixing - to do with can.ages and Tables 9 and 10

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#332]
I just tried for ages (moving \clearpage around etc.), but think it is to do with the extra column of NA's in can.ages. 
The NA column makes Tables 9 and 10 longer and I think causes the \clearpage to skip to the next page, which then becomes blank. Tables 6 and 7 are the same size (but without NA column) and are fine.

**Comment by cgrandin** [comment]
The NAs are caused by editing a csv file in Excel, then exporting as csv again. Excel, the wonderful piece of software it is, decides to add an extra comma at the end of each line of data. Because obviously that's what you would want right?

**Comment by andrew-edwards** [comment]
Ooh, that's a great feature.

**Comment by cgrandin** [comment]
Commit bb4a90c85032d3a64e7cebc7f3095bc94717ed46 fixes the age data file but I can't seem to get rid of the blank page. Also for some reason the page footer is sideways on the next page..

**Comment by cgrandin** [comment]
Ok, I fixed it now in commit 2cbfdc80bbe665a9592983bb62ef2eb0c43fd986
