### ISSUE TITLE
Copy 2017 SRG recommendations into Section 3.2

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#333]
The subsection heading gets automatically updated to say 'response to 2017 review' (that threw me off for a bit), but the text is still currently last year's.

**Comment by taylori** [comment]
Maybe that's an area where we should revert the automation to be manual. As long as you're replacing the entire contents of the recommendations, it might be better to manually update the number as well so that they are never out of sync.

**Comment by andrew-edwards** [comment]
Copied over and latex-ed. Leave Issue open as we still have to finish the responses.

**Comment by taylori** [comment]
Responses are now finished. As noted in #382, they should be checked over along with the rest of the document, but I think this issue can be closed.
