### ISSUE TITLE
fishery-sampling-history.csv should probably have values for JV for 2017

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#334]
I will add this if applicable

**Comment by aaronmberger** [comment]
YES! good catch - and that was on my mind when I was going through this but didn't catch it

**Comment by cgrandin** [comment]
Actually, there were no ages done from the JV fishery this year as I didn't know there was one until after the age requests were in. I don't think it will have any impact however, as the same shoreside boats were sampled from shoreside trips, some of which were in the same area as where the JV catches took place. So I'll close this and say the table is correct.
