### ISSUE TITLE
Table 16 caption last year said numbers for 2016 are preliminary and may be adjusted

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#336]
Numbers for 2016 have not changed this year. Presume that's okay?
Presumably caption should refer to last.data.yr (2016 is hardwired). 
If someone confirms I can fix.

**Comment by aaronmberger** [comment]
You may need to merge my recent commit as it included updates to the overry-samples.csv data file and there are a few adjustments to 2016

**Comment by cgrandin** [comment]
Sounds reasonable to me and probably a good idea

**Comment by taylori** [comment]
I think it would be OK to remove that disclaimer on sample sizes for the ovaries in general. If more sample sizes show up for any year, the table can be updated, but it's fair to just say these are the sample sizes we have.

We may need a separate table showing not total sample sizes, but ovaries that had histological analysis completed which were used in the estimation of an alternative maturity ogive  (yet to be uploaded, perhaps should be a separate issue).

**Comment by cgrandin** [comment]
This appears to have been done so I'm closing it
