### ISSUE TITLE
Update mean weight-at-age figure (Fig 12, colourful one)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#338]
This is EWAforDoc.eps  and gets done outside of knitr.

**Comment by taylori** [comment]
@aaronmberger did this get created when you made the wtatage.sso file? Also, Figure 6 was created by the data processing code. I should be able to create both things, but you might be closer to those functions related to processing U.S. fishery data.

**Comment by aaronmberger** [comment]
I can get those..

**Comment by aaronmberger** [comment]
uploaded the EWA eps (colorful wt at age file) and the Figure 6 catch rate figure that includes 2017

**Comment by andrew-edwards** [comment]
The new .eps seems to be corrupted. I can't open it just in ghostview (get a bunch of warnings, including that it thinks it's two pages and it's likely that another files has been included). 
Don't think this is related to your build problems.

Fig 6 bottom is good. Are you able to update Figure 5 as well (fishing and bottom depth figures)?

**Comment by aaronmberger** [comment]
Okay, just committed a hopefully not corrupt version of EWSforDoc.eps and the new version of fishDepthsUS.eps

Andy if these seem good, close at will...

**Comment by andrew-edwards** [comment]
All work, thanks. Feel like we're getting back on track....
