### ISSUE TITLE
Mountains plot (Fig 25, main.tv.selex) and Fig 26 only goes up to 2016 

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#339]
Tried fixing but I think didn't work (have to leave for a meeting).

**Comment by cgrandin** [comment]
This will be fixed once TV selectivity is output in the base model. See issue # 326

**Comment by cgrandin** [comment]
Fixed in commit dcaae0b790a3f54bc81cdd24c3d00e2fc0807d15
