### ISSUE TITLE
Think year is wrongly specified in selectivity lines plot

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#340]
See comment in d63815f54c37 . I think it should be changed, and will then match the caption.
Although
```
names(tv.selex$median)
```
does only go up to 2016 (presumably would be 2017 with the suggested change). May need to see where tv.selex gets defined.

**Comment by cgrandin** [comment]
I think this will be fixed once TV selectivity is output, again issue #326. last.data.yr - 1 will then have to be changed to last.data.yr and everything should be correct.

**Comment by cgrandin** [comment]
Fairly sure this is caused because these lines in `SSplotComps()` should be reference `sex` instead of `Gender`:

            `if (k == 1) {`
                `dbase_k <- dbase_kind[dbase_kind$Gender == 1 & `
                  `dbase_kind$Pick_gender == 0, ]`
            `}`
            `if (k == 2) {`
               `dbase_k <- dbase_kind[dbase_kind$Gender == 1 & `
                  `dbase_kind$Pick_gender %in% c(1, 3), ]`
            `}`
            `if (k == 3) {`
                `dbase_k <- dbase_kind[dbase_kind$Gender == 2, `
                  `]`
            `}`

So I could add a new version of it asw a new file called 'SSplotComps.r' or we could change it in r4ss.
Ian, what would you rather do?
