### ISSUE TITLE
Clarify period over which recruitment deviations are constrained to sum to zero

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#342]
Currently hard wired in caption to Figure 31 - see 392bdbd
Presumably 1970-2012 should be something like
```
\Sexpr{main.recdev.start}--\Sexpr{main.recdev.end}
```
which is currently 1970--2016
or
```
\Sexpr{main.recdevbias.start}--\Sexpr{main.recdevbias.end}
```
which is currently 1971--2016.
Or something else.

**Comment by taylori** [comment]
I should be `\Sexpr{main.recdevbias.start}--\Sexpr{main.recdevbias.end}`

which is calculated in custom-knitr-variables.r as
```
# range of "main" recdevs
main.recdev.start <- min(base.model$recruit$Yr[base.model$recruit$era=="Main"])
main.recdev.end <- max(base.model$recruit$Yr[base.model$recruit$era=="Main"])
```

**Comment by taylori** [comment]
CORRECTION. I copied the wrong line.

For real, it should be `\Sexpr{main.recdev.start}--\Sexpr{main.recdev.end}`, as calculated by the lines quoted in previous comment. 

The two things going on here are the bias adjustment to correct for difference between mean and median of lognormal, which only applies in the MLE context, and the separation of recdevs into 3 vectors to allow the main period to be zero centered without that period having an influence on the forecast or early years where there is less information.

**Comment by taylori** [comment]
Went ahead and committed change as part of 9b28cd1, seems to work, so now closing issue.
