### ISSUE TITLE
Where does the selectivity get averaged over the last five years, for Figure 42 (forecast age composition)?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#344]
Just curious - can't see in the code where that happens. Maybe it's done in SS. Not a big deal. Ian made the figure last year. Related to cb50a07.

**Comment by cgrandin** [comment]
Good point, I don't see anything in make.age.comp.forecast.plot() that would suggest it's being done in R.

**Comment by taylori** [comment]
The phrase in the caption "These estimates are based on the posterior distribution for selectivity averaged across the most recent 5 years" is ambiguous. SS does the averaging based on the first 2 settings in in this line of the forecast file (-4 to 0 being relative to the ending year):
```
#_Fcast_years:  beg_selex, end_selex, beg_relF, end_relF, beg_recruits, end_recruits  (enter actual year, or values of 0 or -integer to be rel. endyr)
 -4 0 -4 0 -999 0
```

So it's really the posterior distribution of selectivity in the first forecast year, which happens to be the average of the past 5 years.
The selectivity calculations are in load-models.r
https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/load-models.r#L883
and the figure is made in figures-age-comp-forecast.r
https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/figures-age-comp-forecast.r
which includes this note at the bottom:
```
# IGT 2017/01/30:
# make EPS file as a short-term measure for 2017 doc rather than
# make this figure dynamically
```
which is followed by some calculations of the proportions represented by the large cohorts.
If we have time, we could make that figure dynamic.

**Comment by andrew-edwards** [comment]
Thanks for explaining.

So the caption is actually fine, yes? Not actually ambiguous.

And I think the forecast is dynamic.  That last bit of code has 
```
if(FALSE){
```
before it and so doesn't get called. This year's figure is different to last year's. 

If Ian agrees then he can have the pleasure of closing the Issue!

**Comment by taylori** [comment]
Got it. I figured that I just ran the if(FALSE) code once to make the fig, but I now see in main-figures.rnw the line about "new (2017-02-08) commands to run code to build figure dynamically". I've just updated the comment at the end of figures-age-comp-forecast.r (commit ce8e581) to remove the .eps stuff and will now close this issue. Been a while since I've done that, so thanks for the opportunity.
