### ISSUE TITLE
phone chat to discuss 2018 base model

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#346]
Should we connect on Chris' line to finalize thoughts on selecting our base model.  We have several options to consider and we are now 2 weeks from the deadline.  Can folks reply which of the following works - afternoon only in hope that Andy can join.  I'm still exploring models today so perhaps starting on Tuesday.

Tuesday 1-2
Tuesday 2-3
Tuesday 3-4
Wednesday 1-2
Wednesday 2-3
Wednesday 3-4
Thursday 1-2
Thursday 2-3
Thursday 3-4

Let's choose the earliest day/time that everyone can make.

**Comment by cgrandin** [comment]
I can make any time Tuesday or Thursday, but none on Wednesday.

**Comment by taylori** [comment]
All times are OK by me. I'd say Tuesday would be better than Thursday unless Andy doesn't think he can make any of those times.

**Comment by andrew-edwards** [comment]
Thanks - Tuesday 1 works for me. The earlier the better.

**Comment by aaronmberger** [comment]
Ok great, Tuesday at 1 it is with hopes of deciding on a base model at that point or paving the way for any further analyses that need to be done in order to do so shortly thereafter....  talk then.

**Comment by cgrandin** [comment]
Ok tomorrow at 1 it is. I'll set up the conference line.
