### ISSUE TITLE
Is the fate-of-cohorts table now meant to be for all cohorts?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#348]
I was copying the 2017 SRG requests for the 2018 assessment into our document, and when doing commit 548456a noticed that the request (originally from AP) says
"A table in future assessment documents reporting on the model
     estimates of the annual weight of each cohorts that is caught,
     dies from natural mortality, and lives, by year."

Last year we created Table 25 for the ***main*** cohorts only as that was what was requested, as documented on p140 of 2017 assessment. It wasn't easy (Issue #283) but was worthwhile.

So, any thoughts on whether they do want similar tables for ***all*** cohorts, or it was just a typo and they missed our the word 'main' in the final SRG report? 

Probably best to check with the SRG (rather than create lots of tables that no-one really wants - presumably we'd have cohorts going back 20 years or so). I seem to think the original request was from Shannon (and we made the table, and related ones, because people were trying to do the calculations in their head over a conference call).

**Comment by taylori** [comment]
My sense it that this is just a unclear language in the request and not a cause for any change at this time.
Table 25 is a useful format only if it's just main cohorts--it would be overwhelming if it were too many cohorts. However, we could add tables in different formats if needed. If we're worried, we could try to work up additional tables or expand Table 25 just in case, but I think what we did (which was after the SRG if I'm remembering) is probably adequate.

**Comment by aaronmberger** [comment]
I agree, let's stick with the main cohorts for now (1999, 2010, 2014; could maybe add 2008).  It seems to me that the impact of fishing, relative to natural mortality, on the population by age is pretty clearly indicated here.  I don't see a large benefit from adding additional cohorts.. The only thing I can think of would be that adding a representative small cohort for comparison might show any difference (likely undetectable to the eye) how time-varying selectivity may influence the general patterns of catch and natural mortality between large and small cohorts.  

Though I still suggest we repeat what we did last year, unless we end up twiddling our thumbs the last few days (doubtful).

**Comment by andrew-edwards** [comment]
Yes, I thought it would be overwhelming with too many cohorts. Table 25 is built automatically (is working fine now). And, yes, let's stick with the same cohorts (makes it easy to compare to last year's assessment).
I could send John and/or Michelle a quick email to confirm (just so our response to SRG request is accurate).

**Comment by taylori** [comment]
We seem to have agreed to keep the formatting of Table 25, but I'm just re-using this issue to note that it's producing some negative values that shouldn't be there, and an error in red (on the following page): 
```
## Error in ‘[.data.frame‘(x$mcmc, , "SSB_SPRtgt"): undefined columns selected
```
I will work on fixing this now.

**Comment by taylori** [comment]
Table now fixed in commit 03d727f. The issue was that some of the SS output of numbers at age and other tables includes forecast years where they didn't before. The code in tables-age.r should now be a bit more robust to any changes of that type in the future.

Either because the forecast years are now included, or by accident from some change that I made, the table now shows the predicted start biomass for 2018 (see below), which is based on average weight at age since we don't have empirical data. Is that worth keeping or will it just add confusion?
![image](https://user-images.githubusercontent.com/4992918/35827992-d577308a-0a72-11e8-8a0c-a1b8d36ef45f.png)

**Comment by andrew-edwards** [comment]
I think it might be a little confusing (since we have the surviving 2017 biomass anyway, based on 2017 weight-at-age). Just might start creating more confusion, even though we explain in the caption why surviving and starting biomasses don't match up.
I can take a look at some point.

**Comment by andrew-edwards** [comment]
Let's leave as is. And someone already added text (thanks) to say we can do all cohorts if necessary but didn't to keep it shorter - nicely put.
