### ISSUE TITLE
Update model setup file

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#349]
I updated it to the current bridging model set and the current base model (2018.40).  The sensitivities will need to be updated after those are done.

**Comment by aaronmberger** [comment]
and added in the last years model 00_45_2017base, all that is remaining is sensitivities after base model settled

**Comment by aaronmberger** [comment]
this should be basically updated, pending additions/subtractions related to sensitivity models and SRG request models.  closing as no need to have as a reminder any longer

**Comment by andrew-edwards** [comment]
Awesome - thanks for running all the sensitivities.
