### ISSUE TITLE
Wednesday - who's working on what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#35]
Chris - bridging, sensitivity and retrospective figures; no text.
Andy - Executive Summary from Reference Points onwards.

**Comment by aaronmberger** [comment]
I'm working on sensitivity text (which will perhaps related to selecting
some specific figures...); have retrospective runs been completed?  I can
start on the text for that section.


On Wed, Feb 3, 2016 at 9:38 AM, andrew-edwards <notifications@github.com>
wrote:

> Chris - bridging, sensitivity and retrospective figures; no text.
> Andy - Executive Summary from Reference Points onwards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/35>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
I'm working through Intro and data sections and checking Tables and Figures.

Sounds like we are keeping out of each others hair.

**Comment by andrew-edwards** [comment]
Allan - merge Chris's latest (which includes mine) because I fixed a couple of things in those sections this morning. Sorry to get in your hair! I can do the automating of Table and Figure numbers if you like, and any numbers that get abstracted from output. And please flag (or delete) any references etc. that still need fixing with ** .

Aaron - I'm presume you're editing the sensitivity stuff in assessment-section.rnw. We can then just summarise with a couple of sentences in the main text.

**Comment by cgrandin** [comment]
The current code has the retrospective running code in it. You will be asked when you source(all.r). It is set up to run 15 years retros, so that the squid plot can be built. I am currently working on the plotting for the retrospectives. Aaron, if you could get me the sensitivity run plot suggestions I can get those up and running as well.

**Comment by minnowslayer** [comment]
made some changes to missing references section

**Comment by andrew-edwards** [comment]
Andy - done with Exec Summary for now. Going through everyone's commits from today to make things consistent (mainly on the Latex side of things) and add in missing Table/Figure refs that are still needed.
