### ISSUE TITLE
edits needed for Table 17

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#350]
Table 17 (Summary of estimated model parameters and priors in the base model) has a few issues, mostly related to the switch to 3.30. I can attempt to make these changes, but I suspect that @cgrandin could do a better job at it. Please everyone comment if any of these don't seem like good ideas or don't make sense.

- For parameters that are not estimated, such as SigmaR, I think we could just have a dash or NA for the bounds and prior columns since they really don't matter.
- The ranges reported for the Uniform priors don't match the bounds, but they should. We could also just leave it at "Uniform" and not repeat the bounds.
- Remove text "(double normal)" from section heading.
- Age range of estimated selectivity parameters for the survey should be 3-6, not 2-5. Range for fishery is correctly reported as 2-6 (fishery parameter for age 1 is fixed because of 1 fewer degree of freedom as noted in section "Variability on fishery selectivity deviations", as is survey parameters for age 2).
- The SD for the deviations on the selectivity parameters (phi) is no longer in column 12 of the parameter line, but now a separate fixed parameter with labels "AgeSel_P3_Fishery(1)_dev_se" through "AgeSel_P7_Fishery(1)_dev_se", but all values are set equal so any one of them could be accessed via something like `model$parameters["AgeSel_P3_Fishery(1)_dev_se","Value"]`. We could enter this as a separate row in the table and then give the prior on the deviations a distribution of Normal(0, phi).
- Due to the addition of the Dirichlet-Multinomial likelihood, we have 2 additional estimated parameters, which could get their own section called something like "Data weighting". The have labels "ln(EffN_mult)_1" and "ln(EffN_mult)_2" but should probably be called `$\log(\theta)$` to match text in new section "2.4.4 Age composition likelihood".

**Comment by aaronmberger** [comment]
Agree with these, and I like adding a Data Weighting specific section (simply because that is new this year).

**Comment by cgrandin** [comment]
This all sounds good, I figured we'd have to add to/change this table. I'll tackle this once I'm satisfied that the build() routine is fully functional.

**Comment by cgrandin** [comment]
Done in commit 79fce4460b17b6e131c340bd34250d547964fe16

Ian, I wasn't sure what you meant exactly in your 5th point in the point list above about creating a new row for the SD. Have a look at my changes and we can go from there.

**Comment by taylori** [comment]
I'm waiting for forecasts to rerun but will check as soon as I build.doc again.

**Comment by taylori** [comment]
Table looks perfect. Thank you @cgrandin !
