### ISSUE TITLE
Pearson age bubbles not plotting

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#354]
This is figure 23 currently..
Fairly sure this is caused because these lines in `SSplotComps()` should reference `sex` instead of `Gender`:

            if (k == 1) {
                dbase_k <- dbase_kind[dbase_kind$Gender == 1 & 
                  dbase_kind$Pick_gender == 0, ]
            }
            if (k == 2) {
                dbase_k <- dbase_kind[dbase_kind$Gender == 1 & 
                  dbase_kind$Pick_gender %in% c(1, 3), ]
            }
            if (k == 3) {
                dbase_k <- dbase_kind[dbase_kind$Gender == 2, 
                  ]
            }

So I could add a new version of it as a new file called 'SSplotComps.r' or we could change it in r4ss.
Ian, what would you rather do?

**Comment by taylori** [comment]
I'll quickly fix the r4ss version just so we don't have to worry about maintaining two versions in the future. I'm confused as to why this hasn't been causing problems earlier.

**Comment by cgrandin** [comment]
It was the switch to SS 3.30 I think and we just didn't have an issue for it. Andy wrote a note in the figure caption about it which led me to the problem. Thanks for fixing r4ss, there are probably more of them in the function to be switched.

**Comment by taylori** [comment]
I think r4ss is now fixed--I think that the use of gender instead of sex was limited to rarely used options that just hadn't been tested yet. 

The original problem with the titles in SSplotComps which inspired making a copy in figures-age-comps.r has been fixed, so I commented out the copy of that function in figures-age-comps.r. However, now I'm getting an error when building the document, so will hold off on merging those changes until I sort it out (hopefully tomorrow morning).

**Comment by taylori** [comment]
I made some updates to r4ss this morning to correct various issues that necessitated copies of functions in hake-assessment. SSplotNumbers has been removed in commit b02f52ee16748d4c231301c1f1e81ab0a4bc582 and SSplotData and SSplotPars were removed in commit 6a071afd9159ec1097ea04273017605c555af901, as the the r4ss versions are also now working as needed for this document. 

The changes to r4ss were significant enough that they remain only in the "development" branch pending further testing, and have not yet been merged into the trunk. Thus, please re-install using
```
devtools::install_github('r4ss/r4ss', ref='development')
```
