### ISSUE TITLE
Table 31 too wide, produces error

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#356]
Table 31 (results of selectivity-related sensitivities) is extending off the page and produces this error:
```
## Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 15, 14
```
It would be nice to keep these grouped together--could we have a landscape oriented page to make them all fit (as in Table 25)? I'm not sure how to do that, but can work on it after I sort out the separate issue for Table 25 (issue #348) if nobody else fixes it first.

**Comment by cgrandin** [comment]
Once I get up and running with the correct base model I will fix this

**Comment by cgrandin** [comment]
Done in commit 5e836a382a3b8fe7d4ae98488f2bad7708d18a83
