### ISSUE TITLE
Table 32 broken

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#358]
`## Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 15, 14`

**Comment by cgrandin** [comment]
Caused because steepness is not estimated in the 2018.40.02_h_fix_high model, and `cbind` to the other models fails because they have one more estimated parameter.

**Comment by cgrandin** [comment]
I've opened a can of worms with this.. I found out while fixing the tables (31 and 32) that the following do not exist in the derived_quants list any more for SS 3.30. I've paired them up with things that are similar that exists in the list. Any ideas Ian?

previously,            now
SSB_SPRtgt,          SSB_Btgt or SPR_Btgt 
Fstd_SPRtgt,         Fstd_Btgt or Fstd_SPR 
TotYield_SPRtgt,   ? Nothing seems to match this

**Comment by taylori** [comment]
Sorry Chris.
I should have remembered that some of the reference point names have changed.
I believe that these are the correct translations. However, we should still compare the table to last year's to make sure nothing looks funny.

OLD | NEW
-- | --
SSB_SPRtgt | SSB_SPR
Fstd_SPRtgt | Fstd_SPR
TotYield_SPRtgt | Dead_Catch_SPR

**Comment by cgrandin** [comment]
Great, thanks. I'll check all the values once done.

**Comment by cgrandin** [comment]
After much frustration, I got these working in commit 29775f5e6b25b54ffdc127f901cfefb9dc2a8e8c

**Comment by andrew-edwards** [comment]
Good effort (Chris was fighting with this for most of the day).
