### ISSUE TITLE
age 1 MSE simulations

### ISSUE THREAD

**Issue by minnowslayer** [cgrandin/hake-assessment#36]
Hi all - what do we want to do about including the closed-loop simulation results on the performance of an age 1 index that we presented to the JMC last May? Will this be an additional appendix?

Otherwise, since it's an area that nobody is currently editing, I could write a quick summary describing that little progress was made by the JTC on operating model develoment due to workload and other committments; but that there is the development of a spatial operating model occurring at UBC that we think will be useful for future analyses. I can put this in the UNRESOLVED PROBLEMS AND MAJOR UNCERTAINTIES section.

N.

**Comment by andrew-edwards** [comment]
I think we agreed a while back to not have an MSE appendix. 

I won't touch the "**NGT suggest next two paragraphs be removed" parts then, so hopefully we can easily merge.

**Comment by andrew-edwards** [comment]
Though I've tweaked some of the earlier paragraphs, and the merge stuff checks conflicts by line numbers. Maybe just write some text and just post it here and I'll copy it in, since it won't be long will it....

**Comment by minnowslayer** [comment]
Roger that. It'll be brief anyway

**Comment by allan-hicks** [comment]
Hi Nathan,
We could report the age-1 MSE investigations, but may as a late addition
once we have the rest of the document complete. I included a couple of
sentences regarding this in the acoustic data section, but it probably is
better to put in a more results oriented section.

I am starting to think that we don't need to report on our progress on the
MSE in the assessment document, but we should report on that status
somewhere. I feel that the assessment document should be results and
analysis. Maybe a short separate document that can be presented and given
to the SRG and JMC about our progress?  This can be something we do after
the 8th, but before hte SRG meeting.

I haven't looked at your paragraphs yet.

Allan

**Comment by minnowslayer** [comment]
I was going to write something like the following:

Due to other assessment commitments, the JTC made modest progress on MSE development.  We presented the closed-loop simulations evaluating the effect of including potential age 1 indices that were not yet complete in February 2015 at the May 6-7 JMC meeting in Victoria, B.C. The simulations showed that: introduction of age-1 survey results in lower catch, lower P(<B10 $%$) and a lower AAV but that comparable results in terms of catch and could be achieved using higher precision of age-2+ survey or alternative harvest control rules; the simulations assumed that an age-1 survey design with consistent, effective, and numerous sampling was used. In addition, the JTC has been communicating with a Ph.D. student at the University of British Columbia that has built a spatial operating model for Pacific hake: she presented her spatial operating model at the JTC’s December 2015 meeting; once her simulation analysis using it is complete and the results published, it could be a useful tool for the Pacific hake MSE.

But i think a separate document might be easier. Including some description of the results that I have above invites presenting the full set of results which i don't think we want. Perhaps we could flag this as a discussion for tomorrow's call?

**Comment by allan-hicks** [comment]
Sounds good to me.
