### ISSUE TITLE
Monday afternoon - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#360]
Even though I just made a minor edit to update the text, I'm going to not do any more of those yet (in case anything changes). Am reading through to understand the results and how it all fits together, which is more important.

**Comment by taylori** [comment]
I've been reading through looking at figures and trying to understand as well.

Right now, I'm going to try to add the new model to Figure 57 (summary of historical assessments), but won't edit any text for the moment.

**Comment by andrew-edwards** [comment]
Great. Was just looking at that figure and realising it needed updating! Was looking at it because the last few years of the biomass trajectory (Figure c) look a bit different to the same figure in the 2017 assessment. That will probably get discussed, but that thinking partly arises because of only looking at medians. Have to dig into some tables etc...

**Comment by andrew-edwards** [comment]
It's now Tuesday so I'm closing this!
