### ISSUE TITLE
potential revision to "Max. age selectivity" sensitivities

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#361]
I would suggest a change in the sensitivity for "Max. age selectivity" sensitivities. As implemented, the dev_mnyr and dev_mxyr columns have been changed to match the range of ages in question (e.g. for Max. age selectivity 10, there are devs estimated for parameters AgeSel_P3_Fishery(1) to AgeSel_P11_Fishery(1) (corresponding to ages 2-10, with the P2 parameter for age 1 fixed as a reference value.

But the phase should also be changed to be positive so that the base value can be re-estimated, not just the deviations.

Also, the description in the text should implies that both the fishery and survey selectivity are estimated up to the Max. age in each case, which I think is a reasonable way to do this, so the phase for the survey selectivity parameters should also be adjusted to go to the same max.

There are definitely other ways to do this, but I think these changes would be more in line with what we have said we're doing.

**Comment by aaronmberger** [comment]
Good catch Ian, I agree and can update these now.

**Comment by aaronmberger** [comment]
I updated the max selectivity sensitivity model files on the google drive.  These will need to be copied over to your models folder.  They are:
2018.40.07_maxSel_Age5
2018.40.08_maxSel_Age7
2018.40.09_maxSel_Age10

And then you will have to build() again eventually to get the R.Data files updated for those three.  
Ian, can you quickly confirm that I updated those control files in line with what your were thinking.

**Comment by taylori** [comment]
The control files look good to me. In commnit cb97135 I made 3 changes to the selectivity plots:
- take off the header 
- change the fleet name from "Acoustic_Survey" to "Survey"
- change the year represented from the final year (including deviations) to the baseline selectivity without deviations representing years up to 1991

The updated figure is shown below. To my eye, the base model in panel (a) remains the least strange looking of the set.
![image](https://user-images.githubusercontent.com/4992918/35835666-d40cf6e4-0a90-11e8-84f1-0124bf8b02e7.png)

**Comment by andrew-edwards** [comment]
I noticed that the headers for last year said the selectivity was for 2016, so I was going to put 2017 into the caption. But then I saw that ```years=1966``` is set in ```make.selex.plot()``` :
https://github.com/andrew-edwards/hake-assessment/blob/master/doc/r/r-functions/figures-selex.r
Ian, I think you put that in today, but doesn't it then use 1966 as the year in ```SSplotSelex()```?
I tried setting ```years=end.yr-1```  in the two commits that reference this Issue, and end up with the plot:

![image](https://user-images.githubusercontent.com/6977190/35841148-65574b22-0aaf-11e8-959c-1e4fb29ab8a2.png)

Panel (d) shows a large difference to Ian's above.

It's fiddly to further delve into the ```SSplotSelex()``` to look at numbers, so I just want to check which should be used.

**Comment by andrew-edwards** [comment]
And does it matter that we don't show the selectivites for the different values of phi? Maybe we should, and have a second figure?

**Comment by andrew-edwards** [comment]
Just to confirm - I did update the models folders as per Aaron's instructions above. Make sure we don't close this Issue until Chris confirms he has done so also.

**Comment by aaronmberger** [comment]
I think the use of 1966 sets the selectivity to the average (before year specific devs are applied) so that the figure shows an 'on average' selectivity rather than one for any specific recent year which would be influenced by the time-varying nature of our selectivity.  I think the idea was that it shows a more on average picture of what selectivity would look like under the different max selectivity age sensitivities, rather than an individual year.  

I wait for Ian to comment on this though...

**Comment by taylori** [comment]
Yes, 1966 could have been any year outside the range 1991-2017 where there is time-varying values. I think that showing a single year within the time-varying range could be misleading. However, perhaps there's value in showing a some of those years along with the average, along the lines of the plot below:

![image](https://user-images.githubusercontent.com/4992918/35870092-97cf9f4e-0b15-11e8-9459-971e6a38588a.png)

**Comment by aaronmberger** [comment]
Sure, that graph seems reasonable to me.  We could do the same structure IF we end up showing something similar for alternative phi (and/or sigma-S) sensitivities.  Although, we already have the code built to run the mountains plot for sensitivity to phi (again if we plan to show those figures again) - maybe just in SRG presentation (?).

**Comment by andrew-edwards** [comment]
I like the last plots, and showing two years is good. Last year's assessment (the panel titles) did say they were for 2016, so that's why I was confused (and wanted to check) about the move to 1966.
If you can implement that would be great, thanks.

**Comment by cgrandin** [comment]
I've downloaded the new models and built with them. So, feel free to close when you want.

**Comment by taylori** [comment]
Commit de34987 was supposed to revise the plot as pasted above (with slightly lighter colors for the 2016 and 2017 lines). However, it just failed to work when I tested in the context of the full document, so don't merge my fork for the moment. I'll close this issue once I have it working and have edited the caption to match the revised plot. 

I'm not 100% sure that the code is adequately general to work next year without some edits, but we'll deal with that if it crashes or looks funny.

**Comment by taylori** [comment]
Still can't figure out what I did wrong with the plot and why testing it outside of the document works fine but within it not. However, change is really low priority compared to other issues so I just reverted my edit and will come back to this after eating lunch and maybe focusing on other more important things. Will leave issue open to remind me to return at some point, assuming time allows.

**Comment by taylori** [comment]
The existing plot already addresses the original issue but I haven't given up on making the improvement discussed above. Keeping this issue open will remind me to revisit this.

**Comment by taylori** [comment]
I think I got this working now in commit 0effe2a. Figure should look like image below. Given bad track record of other recent change related to a figure (issue #374), I will leave the issue open until someone else confirms that the plot works for them.
![image](https://user-images.githubusercontent.com/4992918/36034849-30f80aac-0d6a-11e8-8cd4-b1dd79c26697.png)

**Comment by cgrandin** [comment]
Nice work on this Ian, I built the document and the plots appear exactly as yours do.

**Comment by taylori** [comment]
Excellent. Closing now.
