### ISSUE TITLE
revise maturity write-up and add associated figures

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#363]
Note that I should rewrie section 2.3.1 Maturity to describe new maturity ogive including adding code to produce figures illustrating results and comparing new vs. old ogives along the lines of those previously posted to issue #325.
![maturity_at_age](https://user-images.githubusercontent.com/4992918/35836935-d7dc268a-0a97-11e8-8b3f-81bb6f0e6b94.png)
![fecundity_comparison](https://user-images.githubusercontent.com/4992918/35836937-d9bdcc56-0a97-11e8-82cd-7927977b7bfe.png)

**Comment by andrew-edwards** [comment]
Great. I was thinking earlier that I'd seen the new figure somewhere, but couldn't spot it in the document.

**Comment by taylori** [comment]
Figs added and text revised in commit a990207f748f37c1232fecdbe48d1e6df3e3982b. I combined them into a single image so that the figure numbering wouldn't change, but this meant adjusting Figs 8-10, so that now survey figs 8 and 9 are together on a page, age-1 index fig 10 alone, and maturity alone. Feel free to adjust sizes as you wish. Figs 8 and 9 feel redundant as noted earlier, but I don't think it's worth taking the time to combine them for this year.

I still need to update Table 15 to replace length-based values with results of new analysis as a function of age. Will leave issue open until completing that (shouldn't take long).

**Comment by taylori** [comment]
Table now complete, closing issue.
