### ISSUE TITLE
Tuesday - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#364]
I'm still reading through to understand and get it all together in my head. Will try not to get distracted with minor things. There are still a lot of open issues, but some shouldn't take long to fix and some are wants vs needs (that I probably opened), so can be dropped if necessary. So I think we're still doing okay....

**Comment by cgrandin** [comment]
I'm trying to get some of the issues patched up, still trying to get table 32 working, and have to make table 17 fit for this year's model parameters.

**Comment by aaronmberger** [comment]
I'll make a first cut at updating text in the assessment section (starting at the top and working my way towards the sensitivity runs).

**Comment by andrew-edwards** [comment]
Think we could do with a phone call to touch base - 10am tomorrow?

To me the most important things are updating the text with how the model changed (I can probably do that but Ian/Aaron have a better sense of the logic). Then interpreting results and understanding the big picture (squid plot helps - 2014 cohort is looking more like 2008 than 2010). And we need to set the constant catch levels (as per the instructions in the readme). I can do those maybe.

**Comment by taylori** [comment]
Could we do 11am tomorrow instead? Aaron and I have a meeting from 9:45 to 10:45.

**Comment by aaronmberger** [comment]
11 works for me and probably a good idea

**Comment by cgrandin** [comment]
Yes, 11 is good - I have to leave around 12 for a going away lunch for my office mate.

**Comment by andrew-edwards** [comment]
Think I'll tackle the constant catch values (#362), using the instructions on the readme.

**Comment by aaronmberger** [comment]
I'll continue to work on updating the assessment-section text, currently at Assessment Model Results and continuing on from there tonight.  I did skip the bridging section as it looked like Ian was/has been working on that section.

**Comment by taylori** [comment]
Sounds good. Yes, I'm happy to wrap up the bridging section later now that the plots are all available to reference in the description of the impacts.

I'm still working on updating the text under "maturity" in data.rnw, but also revised main-figures.rnw and am adding a new .eps file (quicker for this year than integrating the code to make it dynamic). I will try to add those changes to your updated data.rnw shortly and then will quit for the evening.

**Comment by andrew-edwards** [comment]
I’m home for now but will finish the catch level calcs tonight and check it builds.

**Comment by cgrandin** [comment]
I'm working on table 17 now

**Comment by andrew-edwards** [comment]
Chris - note that Table 17 had NA's in the final 2017 version (I just checked to see what the table was and noticed them). Just in case you're struggling to get rid of some that are just fine ;)
