### ISSUE TITLE
AP reports

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#365]
I just uploaded a draft US AP report (google drive under 'Reports') on the fishery which goes into an appendix in our assessment doc.  I will make the changes to that appendix now.  I've been told there could still be a change coming as almost, but not all, AP members have seen it.

Any word on Canadian AP report?

**Comment by andrew-edwards** [comment]
We emailed Shannon et al. yesterday, asking to have it by Thursday.

**Comment by andrew-edwards** [comment]
Just received it from Shannon. Will tex it tomorrow. I'm prob done for the day after a long day yesterday.

**Comment by cgrandin** [comment]
I reviewed the Canadian AP report (thanks for adding it Andy) and it looks good. Will leave up to you guys to close this once you're satisfied with the US AP report.

**Comment by andrew-edwards** [comment]
These look done, thanks Aaron.
