### ISSUE TITLE
US Tribal/treaty potential missing catch

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#366]
Joe Peterson provided Ian and I with a spreadsheet showing US tribal catch which did not match the values extracted from our PacFIN database (they should be equivalent).

After looking further into this, there was fish ticket information missing at all levels for tribal catch: Joe had a few missing fish tickets that Washington Department of Fish and Wildlife had/found; WDFW was missing a handful that Joe had/found; and PacFIN is missing most of the above.

I'm being told that the best numbers for now, which are still not rectified in our PacFIN database, are the following:

2016: additional treaty landings of 2522.75 mt
2017: additional treaty landings of 6405.86 mt

These values would then be added to annual totals.

Given that it's late in the game, I just ran a sensitivity where I add in these catches and, as expected, it  makes effectively no difference in terms of stock status and trend.  

So, what to do?  I say we mention it at the SRG and add a section in the document about the missing tribal catch in 1) the data section and 2) the research and data needs section.  The latter specifying that better accounting of tribal catch needs to occur in our US coastwide databases (e.g., PacFIN).

Seem reasonable?

And just to note the US AP report indicates a tribal catch of 6012 mt for 2017.  Still different, but much more in line than what came out of the PacFIN database.

**Comment by andrew-edwards** [comment]
Sounds good - document it, but we can’t be expected to re-run everything. And from a total catch of 440,000t it shouldn’t make much of a difference.

**Comment by aaronmberger** [comment]
The missing catch lays on top of the base model for status and trend.

Base model SSB 2017                          : 2,286,740
Base model Bratio 2017                      : 0.6533
Missing catch Sensitivity SSB 2017     : 2,287,720
Missing catch Sensitivity Bratio 2017 : 0.6535

![compare2_spawnbio_uncertainty](https://user-images.githubusercontent.com/7946234/35929710-f41ceb4c-0be4-11e8-9e24-2c340099d693.png)

**Comment by cgrandin** [comment]
I agree, it makes no appreciable difference and it's too late to change. Showing it as a sensitivity should work for everyone.

**Comment by taylori** [comment]
I agree with the plan.

I also think that noting the fish ticket issues and leaving the catch out of the base model may put a bit more pressure on the groups involved, the Makah Tribe, Washington Department of Fish and Wildlife, and PacFIN, to improve this process for the future. When similar problems occurred last year, WDFW promised to improve things, but doesn't seem to have succeeded in doing so.

This raises a question:
How do you all feel about having some open issues (like check on tribal catch) associated with the "2019 assessment" benchmark? An alternative would be a new README-like document README itself where we list reminders for things to do or watch out for next year.

**Comment by cgrandin** [comment]
Either way would work, I personally like the idea of keeping the issues as GitHub issues.

**Comment by aaronmberger** [comment]
Open issues are fine with me with a 2019 tag.  I'll close this one as we seem to have agreement and open another tagged for 2019.
