### ISSUE TITLE
Table 26 (comparison to previous assessment) not working

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#369]
Chris knows why and will fix.

And next table (percentiles) has NA's - he's on it!

**Comment by cgrandin** [comment]
The NAs are caused by different names for quantities in SS 3.30 again, so I'm going to ask Ian for clarification (Issue #358 has 3 of them but there are 3 more):


Quantity | SS 3.24 quantity name
-- | --
Unfished female spawning biomass (B0,   thousand t) | SSB_Unfished
Yield at B40% (thousand t) | TotYield_Btgt
MSY (thousand t) | TotYield_MSY

**Comment by taylori** [comment]
Here you go. Sorry for not going through all these things myself.

Quantity | SS 3.24   quantity name | SS 3.30   quantity name
-- | -- | --
Unfished   female spawning biomass (B0, thousand t) | SSB_Unfished | SSB_Virgin
Yield   at B40% (thousand t) | TotYield_Btgt | Dead_Catch_Btgt
MSY   (thousand t) | TotYield_MSY | Dead_Catch_MSY

**Comment by andrew-edwards** [comment]
Chris - you couldn't have guessed  "Dead_Catch_Btgt"? Come on ...... ;)

**Comment by cgrandin** [comment]
We need to run extra.mcmc for last year's base model to get $extra.mcmc$Q_vector for this table
See this around line 690 of tables-parameters.r
```
    if(q.choice == 1){
      q <- round(median(base.model$extra.mcmc$Q_vector), 3)
    }else{
      q <- round(median(last.yr.base.model$extra.mcmc$Q_vector), 3)
    }
```

It would be nice if we had a way around having to run the extra.mcmc

**Comment by cgrandin** [comment]
Oh wait, it's not used - forget it, problem solved. I just commented it out.

**Comment by cgrandin** [comment]
I did this and it's working now in commit a3b433b2d3601f6e26f554046159ecf936a8121f

**Comment by taylori** [comment]
Got it. I misunderstood that you were talking about last year's values, not this year. I think it totally makes sense to hardwire the value from the previous year and not run the extra-mcmc.
