### ISSUE TITLE
Retrospective runs all the same output

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#37]
All the retrospective runs have the exact same output except for the time model was run. I did a DIFF on the Report.sso files and the covar.sso files. The starter file is modified as follows (for year-1):
0 #_init_values_src
1 #_retro_yr

And this (for year-2)
0 #_init_values_src
2 #_retro_yr
with the correct retro year in each starter file in each folder, and the model is actually run on this (I watch the output files being created).
Am I missing something else?

**Comment by allan-hicks** [comment]
I think that retro year needs to be negative

**Comment by cgrandin** [comment]
But of course... Thank you.
