### ISSUE TITLE
I'm fixing broken links to maturity stuff

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#370]
Somewhere along the line, changes to main-figures.rnw related to the new maturity figure and those immediately before it got accidentally reverted. This caused the figure links to break. Someone kindly fixed the links to point to the old figure. Now I'm in the process of restoring the new figure, and changing the links again.

Just letting you all know in case you get ?? or other errors related to the broken links.

**Comment by taylori** [comment]
Should all be fixed now.

**Comment by andrew-edwards** [comment]
I thought I fixed it, though maybe the wrong figure file was in there. Sounds like it's good.

**Comment by taylori** [comment]
@aaronmberger I think you've got an old version of the main-figures.rnw that keeps reverting the changes to the maturity figures.
The changes to lines 145-210 here are reversing the changes that I've made twice now. 
https://github.com/andrew-edwards/hake-assessment/commit/aa0bd104f1f83dd051a32b3a1abd7326cbe51052#diff-f7b0635899e78bd8d3373f4bacbc1f58
I'll make the changes a third time and have just pushed a rename of the old length-based maturity figure (kept around in case we want it for SRG talks) so that the document will create an error new code isn't used.

**Comment by aaronmberger** [comment]
Hmm, perhaps I didn't save any edits in my main-figures.rnw before merging?  I'll completely close my versions before merging again now.

**Comment by taylori** [comment]
Sounds good. It was easy to fix (commit 2121997). 

If you see "maturityNS.eps" anywhere in the code that's a sign that it's the old version of that section. The new one should have "maturity_plots.eps" instead.

**Comment by andrew-edwards** [comment]
Something funny happened along the way - I'm fairly sureI only changed \ref{fig:   } names to fix the undefined references warning, not any actual figures. It did look like the same changes kept getting done back and forth. Anyway, sounds like it's sorted, thanks.
