### ISSUE TITLE
Suggest changing Figure 11 y-axis label and legend to just 'Estimated age-1 fish'

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#373]
And not say 'recruitment', as elsewhere recruitment is used for age-0 recruitment (e.g. as specified Figs 15 and 16). 

Presumably when just 'recruitment' is used it refers to age-0. i.e. recruitment residual in 2015 refers to new fish in 2015. I can fix, just double checking first...

**Comment by taylori** [comment]
Good idea.
Done in commit 201c8de.
