### ISSUE TITLE
added new figure illustrating semi-parametric selectivity

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#374]
Posting issue to note that I added a new figure (snapshot below) in commit b3d174304091a2f7acb31ab8415b6b9d988e2572 that adds onto Andy's last commit from of about 30 minutes ago. The figure requires a function in
doc/r/r-functions/figures-selectivity-parameterizations.r (which was already in the repository but is now loaded by all.r). The figure is referenced in the sensitivities section. 

As soon as someone other than me reloads all.r and is able to build with the new figure, feel free to close this issue.

![image](https://user-images.githubusercontent.com/4992918/36011831-ebade602-0d0e-11e8-88ef-5e0c283df13b.png)

**Comment by andrew-edwards** [comment]
I got horizontal lines for b, c and d. Just deleted .Rdata and running build() again to see if that works (will update shortly).
Oh, and you have two panels (c)!

**Comment by andrew-edwards** [comment]
Nope. Deleted full knitr-cache to make sure, but I get this, with the funky y-axes:

![image](https://user-images.githubusercontent.com/6977190/36013054-db1201f4-0d16-11e8-80c6-18779dce51ab.png)

I'm done - we can look into it in the morning...... Cheers.

**Comment by taylori** [comment]
Very strange. 

The parameter for age 0 is -1000, a code used to indicate a selectivity fixed at 0, but age 0 is supposed to be excluded from the calculation and the plots:
```
  ages <- 0:20 # range of ages for which selectivity is defined
  a_min <- 1   # minimum age with selectivity (1 for fishery, 2 for survey)
...
  # subset of ages to show
  sub <- ages >= a_min 
...
  # first plot showing parameters by age
  plot(ages[sub], selpar_base[sub], type='l', lwd=4, axes=FALSE,
...
```
I just fixed the panel lettering goof-up in fig and caption with commit 19ecf99 -- thanks for catching that.

**Comment by taylori** [comment]
I think this one is all sorted out.

**Comment by andrew-edwards** [comment]
Not for me :( 

I'll redo everything (again?) at some point - just re-opening to make sure I double check. Chris had it working so I know it's something I need to re-run....

**Comment by taylori** [comment]
Sorry about that. There's really no need to have this figure be dynamic, so we could also just put the .eps file into main-figures and reference it there.
But if you have time to get to the root of it, perhaps that would update other things that need updating.

**Comment by andrew-edwards** [comment]
Works now.
