### ISSUE TITLE
Friday tasks ...

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#375]
Time to close issue #372.

**Comment by cgrandin** [comment]
I'll be there for 10am call also

**Comment by aaronmberger** [comment]
Just went through majority of Introduction section, making changes were needed and identified by **.  Didn't do Canadian fishery section (but also didn't see any **).

Ian question -  is this sentence still correct:
"During July and August, some operators
in the at-sea fishery continued to fish hake, forgoing the usual summer
opportunities in Alaskan waters."

I seem to remember from Dec JTC meeting that one ship was in port, but I don't recall anyone saying that they explicitly stayed back to fish hake and forgo AK trip (?)

**Comment by aaronmberger** [comment]
Moving on to data section to tackle **'s

**Comment by aaronmberger** [comment]
Also building 50% less sampled, i.e., more thinned, 24 million chain version of document now, should be done in 10  minutes.  AFter I have a look I'm going to immediately go back to our base version (will take a few hours to fully catch back up)

**Comment by cgrandin** [comment]
I will double check the Canadian fishery and management sections.

**Comment by aaronmberger** [comment]
see inserted ppt file comparing reference points and diagnostics for:
'Base - thin rate 10,000' compared to 'thin rate 20,000'

Some diagnostics seem a touch better, but overall I don't think its worth changing now or later for this year.  Reference points are near identical.  Mostly, it was created for potential SRG questions.  See what you think?  I posted the full doc build under compare-pdf folder on the drive.
[IncreaseThinCompare.pptx](https://github.com/cgrandin/hake-assessment/files/1711733/IncreaseThinCompare.pptx)

**Comment by andrew-edwards** [comment]
Thanks for those Aaron - yes, new one is very slightly better (less autocorrelation, as expected), but agree that the actual results are almost identical. So good to have in case anyone asks.

Chris - I did the main text AP part last night (and my suggested edits to the appendix), so it should be good but please read over.

I'll get caught up. Am good for 10am call.

**Comment by andrew-edwards** [comment]
Clarifiction Chris - I did the AP part but not the management part.

**Comment by cgrandin** [comment]
The Canadian AP report in the appendix looks good

**Comment by cgrandin** [comment]
I'm working on issues #341 and #335 today

**Comment by andrew-edwards** [comment]
Document builds with no latex warnings (undefined refs etc.), which is good. 

After our call I'm going to print it all out to take a read through the main section, then use that to edit the exec-summary (unless anyone wants to start editing the exec - I think it should be fairly straightforward).

**Comment by taylori** [comment]
Waking up too early seems to have taken a toll on me so I'm quitting early.
I'll be back on tomorrow from about 10am onward, and am available by phone between now and then if anything comes up that requires a more rapid response.

I'll send Owen an the current version of the document with the disclaimer that the Exec Summary and One-page summary along with a few other sections flagged by ** still need to be worked on.

**Comment by andrew-edwards** [comment]
Sounds good. I'm just reading through so have kept an eye on commits but not merged yet - will at some point. Chris and I are coming in tomorrow from 9-1. And I'll prob work some in the afternoon also, and Sunday. Aim to have a complete polished document by end of Sunday (or earlier), so we can read fresh on Monday and submit.

**Comment by andrew-edwards** [comment]
Am done for the day (fading fast). Great job Aaron and Ian with explaining the changes to the models and the bridging results - it all holds together nicely and seems to make sense, even though it is all quite complicated!

I have a bunch of edits to type up tomorrow but just standard minor edits for clarification, nothing major.
