### ISSUE TITLE
File not added

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#376]
I'm trying to build and this file is missing:
main-figures/age2plushake_03-17_NASC_BiomassAtAge_color.eps

I'm guessing someone just forgot to `git add doc/main-figures/age2plushake_03-17_NASC_BiomassAtAge_color.eps`

**Comment by aaronmberger** [comment]
I've got in my main-figures

**Comment by cgrandin** [comment]
It's on the Google drive. I should have checked there first. No worries

**Comment by andrew-edwards** [comment]
Yep. Hey, remember all that hassle we had yesterday and so ended up having to use the Google Drive ;)
