### ISSUE TITLE
Spell check everything

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#379]
Add each file in here as it's done

**Comment by cgrandin** [comment]
Here's what goes in your .emacs for aspell:
```
;; enable spell checker
(add-to-list 'exec-path "C:/Program Files (x86)/Aspell/bin/")
(setq ispell-program-name "aspell")
(setq ispell-personal-dictionary "C:/Program Files (x86)/Aspell/.ispell")
(require 'ispell)
(require 'flyspell)
(setq flyspell-issue-welcome-flag nil) ;; fix flyspell problem
```

**Comment by andrew-edwards** [comment]
Just remembered another way of doing this - spell check the
```
hake-assessment.tex
```
file, and then make changes manually in the appropriate .rnw files. Hmmm.... maybe (depends how ispell deals with R commands). I can have a go, maybe on Sunday (expect to catch most typos while reading through).

**Comment by taylori** [comment]
I got Aspell installed so went ahead with spellcheck to files for exec-summ, intro, data, assessment, research, main-figures, and main-tables, that are now corrected in commit 91fb37e.

I found one case of "Natual Mortality" that I copied from sens.model.names.1 in model-setup.r without noticing the typo. I fixed both locations, which means that **you have to `source(all.r)` to get the new `model-setup.r` and clear out `knitr-cache` to get the fixed caption in Figure 45**.

Other highlights were "acousitc" "likehood", "investigatation", and "transforamtion". I'm sure I was probably the source of most of the misspellings, so it's satisfying to fix them. No guarantees that there aren't a bunch of misspellings that slipped through the cracks, but this should help.

**Comment by taylori** [comment]
The only headache was that it tripped up on each of the citations, although they were easy to skip through.

**Comment by andrew-edwards** [comment]
It does that with .tex files also. Not sure why it can't ignore them, as it knows that other things are latex commands.

**Comment by andrew-edwards** [comment]
Just done one on hake-assessment.tex, only a couple of minor fixes (to the .rnw files). Off for lunch. Looking good for 3pm.
