### ISSUE TITLE
Sensitivity tables

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#38]
How are sensitivity tables being created?  I recall folks saying it is a bit of nightmare to format those.  As I am doing sensitivities I could be populating something with the reference point table like summary table for the individual sensitivity runs..... (?)

**Comment by andrew-edwards** [comment]
Looking at last year's - presumably no need for a special-case Table 18 (alternative survey 2012 and 2013 biomass values), but just a more general Table 19. And presumably Table 19 should look like the current Table 10, but just MLE's and a column for each sensitivity. 
Chris can probably do that quicker than any of us, and I think was going to do it tomorrow, so maybe leave it to him. 
But, I think he couldn't extract all the values for Table 10 (see the dashes in the bottom part), so if you know where they are that would be good.
Okay Chris? I assume you'll just adapt your code for Table 10 and add in the extra columns, once the sensitivities are decided upon.

**Comment by andrew-edwards** [comment]
And to answer your question of "How are sensitivity tables being created?"
By magic. ;)

**Comment by cgrandin** [comment]
Yes, I spent a lot of time on this already, and know the code. So I'll do it. Or at least set up the formatting of it.
**
I did have some trouble finding the location of some of the reference points in the output, so I'll need some help with that (probably Allan), and I'd like someone(s) to double-check the calculation of other values, some look suspect (like posterior recr. vals). The function is make.short.parameter.estimates.table()  in tables-parameters.r, look for lines like this:
mle.par <- c(mle.par, NA)
which are where I stuck an NAs in as a placeholder (which gets turned into dashes).
**
Also, if we want to include decision table entries for sensitivity cases, it would be much, much easier to just generate a whole new table for that sensitivity run than to append columns to the existing one.

**Comment by aaronmberger** [comment]
For sensitivity table comparisons at least, I was thinking of one maybe two (if too many columns) table(s) like Table 15 in last years document.  I understand that decision tables can get squirrely awfully fast.

**Comment by allanhicks** [comment]
It is also a good idea to break them not separate tables with similar
theme. Maybe one of the tables is the 'standard set'.

**Comment by aaronmberger** [comment]
agreed

**Comment by cgrandin** [comment]
I'm not sure what you're saying there, Allan...

**Comment by allan-hicks** [comment]
"into" not "not". Just separate tables for groups of sensitivities.

**Comment by cgrandin** [comment]
So far, there are no decision tables for any sensitivity runs. Obviously if we are going to add them, we need mcmc runs for the sensitivities we choose. If we aren't going to present any, we can close this issue.

**Comment by allanhicks** [comment]
Aaron and I have enough some mcmc's, but I think we should save those if asked for.
