### ISSUE TITLE
add text about log(theta) estimates

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#380]
Numerical values should be reported, but not bothering adding to tables for this year.

**Comment by taylori** [comment]
log(theta) values now calculated in custom-knitr-variables.r and numerical values reported in revised text under "Model Fit" within "Assessment model results". Not sure if my notation of
$\log(\theta_{\mbox{surv}})$ and $\log(\theta_{\mbox{fish}})$
is ideal, so feel free to adjust as you wish.

**Comment by andrew-edwards** [comment]
So the multinomial likelihood equation is repeated for the survey data and the catch data, yes? Again, I'll just add a sentence to explain this. Just want to double check. See commit that references this issue....

**Comment by taylori** [comment]
Changes to text about Dirichlet-Multinomial all look good to me. Definitely an improvement.
If you prefer \log \theta to \log(\theta) as written on the final line on page 42, then we should remove the parentheses on \log(\theta) elsewhere for consistency.

**Comment by andrew-edwards** [comment]
Thanks. I do prefer no (.) , but then realised I'd have to change others. Probably should change them but no big deal if we miss any.

**Comment by taylori** [comment]
No parentheses does look cleaner and it should be easy to change them, but I'll leave that to you to avoid conflicting edits. Note that log(theta) also occurs in Table 17.

**Comment by andrew-edwards** [comment]
That Table one is the only one in hake-assessment.tex, but leaving it, not crucial.
