### ISSUE TITLE
proposed changes to research and data needs

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#381]
Will make comments on this issue once I come up with some ideas for any changes needed.

**Comment by taylori** [comment]
I have no suggestions for changing the ordering, but flag a few below as potentially benefiting from changes:

1. _keep_ **Investigating links to ecosystem**

2. _keep but change_ **Continue development of the MSE** to reduce the text about things like "If a spatially, seasonally explicit operating model is needed" given that there seems to be clear direction toward a spatial operating model.

3. _keep_ **Conduct research to improve the acoustic survey estimates of age and abundance**

4. _keep_ **Continue to explore and develop statistical methods to parameterize time-varying fishery
selectivity in the assessment and with regard to forecasting** 

5. _reduce_ **Continue to investigate maturity observations of Pacific Hake** to focus on point (d) about fecundity, and add a point about genetic analyses of potential stock structure break associated with point Conception

Keep all others as they are, but in number 8, change "research catch" to "research catch and catch from tribal fisheries" as needing better account.

**Comment by aaronmberger** [comment]
I was thinking of adding one about subsampling otoliths by month when not all are aged.  This is to capture the seasonality of catch-at-age that has occurred in recent years, which is important when a significant proportion of sampled otoliths do not get aged and input into the assessment.

**Comment by taylori** [comment]
Changes proposed in my earlier comment have been made in commit 9f84d7b, but I didn't yet include Aaron's suggestion.
@aaronmberger I agree with the idea to add something about subsampling otoliths by month, but I think you could phrase it better. If you have time, please add anywhere in [research-needs-remainder.rnw](https://github.com/cgrandin/hake-assessment/blob/master/doc/executive-summary/research-needs-remainder.rnw) or just paste into this issue. If you don't have time, I'll come up with something myself.

**Comment by aaronmberger** [comment]
I can add that tomorrow morning (central time)

**Comment by aaronmberger** [comment]
added the subsampling otoliths to the R&D section, so I think okay to close....

**Comment by taylori** [comment]
The addition looks good to me. Thanks. I think we've got everything from you that I was hoping you could provide, so don't worry about hake for a while and safe travels back home.
