### ISSUE TITLE
Response to SRG requests

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#382]
Ian: can you have a look at these, in particular I didn't add any response yet to the first one (t.v. selectivity related) and made an attempt at the second one (maturity)

**Comment by taylori** [comment]
Yes, thanks. I'll take a look.

**Comment by taylori** [comment]
I edited the first two as requested and the rest all look good to me.
My edits should be read by others, but that will happen in the course of normal edits and review of the document, so I'm closing this issue.
