### ISSUE TITLE
"Section" or "section"

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#384]
I know I've been inconsistent. 
Seems like it would be easy to find/replace searching for "section~\ref" (or the other way) if we want to make them all consistent.

**Comment by andrew-edwards** [comment]
I use Section

**Comment by taylori** [comment]
As I make edits, I'm capitalizing Section in a few places.

**Comment by taylori** [comment]
Fixed remaining occurrences in commit 7f6d23d, now closing.
