### ISSUE TITLE
change "* at age" to "*-at-age"

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#385]
Until just now, I had been under the impression that hyphens were needed for "weight-at-age matrix" where "weight-at-age" is used as an adjective, but should not be present when the phrase is used as a noun, like "weight at age in the unfished equilibrium". However, I just read this Alaska Department of Fish and Game document 
https://www.adfg.alaska.gov/static/home/library/pdfs/writersguide_section4.pdf
which specifically lists "catch-at-age" and "length-at-age" as the type of compound word that requires hyphens when used as either an adjective or a noun.

There may still be cases where there should be no hyphens, such as "the weight at age 3", so a wholesale find/replace wouldn't work, but I think it would be easy to go through and fix the ones that should be fixed, unless someone else objects to this change.

**Comment by andrew-edwards** [comment]
Sounds good. Yes, I'd have thought only when adjectives, but then I saw one yesterday as a noun and thought hyphens would be appropriate. I'll keep an eye out while reading through. Good thought about the wholesale find-and-replace [find and replace?].

**Comment by taylori** [comment]
I've made this change for assessment-section.rnw and just now a few more in data.rnw (commit 
5f4542b), but haven't looked elsewhere.

**Comment by taylori** [comment]
Fixed a few remaining occurrences in commit b4860ed, now closing.
