### ISSUE TITLE
section 2.2.

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#386]
I updated all the text except the following in 2.2.2:
**Should DFO surveys be
mentioned....

Chris or Andy, do you want add something there.  Seems to me DFO surveys should be included there, or at least any main ones...

**Comment by andrew-edwards** [comment]
Think I flagged it because we'd said which US surveys weren't used but kind of omitted Canadian ones.

We could just say  "....pre-recruit survey or any DFO surveys were not used ....."

Easiest fix.

**Comment by aaronmberger** [comment]
done..
