### ISSUE TITLE
Suggest switching order of sections 3.2 (Response to 2017 SRG) and 3.3 (Description of Base model)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#388]
It seems more logical to talk about the details of the model before responding to some of the technical requests. Fairly easy switch to make.

**Comment by aaronmberger** [comment]
I'm fine with that.  Our (NWFSC) typical stock assessment document flow is to talk about responses to last review before the new model, but I see your point.  The way it is now kind of makes it such that responses to the SRG can't be too descriptive if new things are used in this years model as you would just be describing things twice, unless all that is said in the response is see model description.  So long winded to say... seems reasonable.

**Comment by taylori** [comment]
I agree. I'm happy to help rewrite any of this if you want--just delegate as you wish.
