### ISSUE TITLE
Saturday work flow

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#389]
As I'll be on a flight for 4 hours likely without internet access, I'm just going to read the document noting places that need edits/fixes/etc.  I can then cross reference that list once I'm on internet.  I'd hate to make changes to rnw files and then have conflicts with stuff that you guys are doing.

There were errors in my knit last night, something to do with decision table maybe, but didn't diagnose.  I'll try again soon, but either way not a big deal for now.

**Comment by andrew-edwards** [comment]
Great. I'm still reading through and will type up a bunch of edits. I'm working until 1:30. Likely won't get to the Exec Summary today but will do tomorrow morning.

Hope your trip goes okay.

**Comment by cgrandin** [comment]
I'll be working until 1, am to read through and also make sure all tables and figures are intact and make sense.

**Comment by andrew-edwards** [comment]
I know I said I'll type up my edits, but feel free to make any others you see. I don't want to hold anyone up.

**Comment by taylori** [comment]
I'm going to make a few small changes to "1.4.1 Overview of the fisheries in 2017" suggested by Owen (who has only read a few pages so far) and change the text about selectivity as noted in issue #390.

Then, unless something new has come up or I'm reminded of stuff that I promised to do, I'll try to take some time to start reading things.

**Comment by andrew-edwards** [comment]
I'm going to start typing up some edits to the main text. I'll keep pushing and merging so we don't get any conflicts. 

Haven't finished reading through yet but feel I should get typing.

**Comment by taylori** [comment]
Sounds good. I just committed some changes to assessment-section in da7a4eb5432332cb2b827580473561ce002f181a to sort out issues #384 and #390, but am not expecting to commit any further text changes anytime soon.

**Comment by andrew-edwards** [comment]
I'm done for now. Back later this afternoon...

**Comment by taylori** [comment]
I'm quitting for the day. I'll check in on the issues at some point in the evening in case there are any specific questions I can help with, but probably won't contribute anything much until tomorrow once Aaron has a chance to look at the catch numbers for the sensitivity analysis. Feel free to call or text my cell phone if you need a faster response.

Ideally I would not spend much time working on this tomorrow, but I also have some appointments on Monday that will limit my contributions that day, so will do what I can to help make sure all gets sorted out in time.

**Comment by andrew-edwards** [comment]
Thanks. I'm just editing and can just post any questions that come up as Issues (even small ones). 
I'll work tomorrow to get the main text finished and the exec-summary done - I don't mind doing that as I was away last week. Thanks for working today...

**Comment by andrew-edwards** [comment]
I'm done for now. If I do anything tonight (doubtful) it will be to finish reading the last 7 pages of the main document.
Tomorrow I'll get all my edits done, then update the exec-summary and one-page summary. Aim to have it polished by Sunday night, so we can finish up on Monday (notwithstanding that Aaron's travelling and Ian has appointments. We're doing well though, despite some issues today...
