### ISSUE TITLE
Exec Summary have just 3-5 research needs, or repeat them all?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#39]
Repeating all from main text is now easy. Allan had suggested we just include the first 3-5, which I think makes sense, and I think Chris agrees.
Nathan suggested re-ordering one also (see latest version). So for now leave them duplicated and then we can look at them at some point.

**Comment by cgrandin** [comment]
We agreed on the call. closing..

**Comment by allan-hicks** [comment]
Not sure how to list just the first three (I think the first three should
be fine for the Exec Summary) without writing a new .rnw file.  I'll leave
it up to Chris in case there is an elegant way to do this.

**Comment by andrew-edwards** [comment]
I can do it....

**Comment by cgrandin** [comment]
Thank you Andy
