### ISSUE TITLE
note as needed that proportions are in numbers, not weight

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#392]
Some of Owen's comments that I incorporated into commit 353e48d08e7a114a5fe5b3cc956d0a32d1db5913 was about ambiguity on whether we're talking about proportions of numbers or weight in phrases like " 44% of the CP catch was age-3" and "The most abundant year classes in the Canadian Freezer trawler catch...."

I've just added things like "(by numbers)" in the places he flagged, but it's probably worth keeping this issue in mind as we edit other sections. I think that in general, all of our proportions are by numbers with the exception of things like Figure 44 where we explicitly label proportions by weight.

**Comment by andrew-edwards** [comment]
I got one earlier. Somewhere....

**Comment by taylori** [comment]
Probably can close this anytime.
