### ISSUE TITLE
Suggest moving 2.4.3 (variability on select. devs) and 2.4.4 (age composition likelihoods) out of data section

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#393]
They're not really data, rather technical model details. 

Obvious place would be as subsections in 3.3 Description of Base Model. 

Not doing yet since making edits on the text, just noting it while I think of it. No big deal if they should stay.

**Comment by taylori** [comment]
Fine with me, but again dependent on time available. It would be easy to just note this for next year.

**Comment by andrew-edwards** [comment]
Yes, I'll just leave them. They are under a subsection called 'Estimated parameters and prior probability distributions' (which would probably what should be moved out of Data section, but not now as it involves re-reading text).
