### ISSUE TITLE
Sunday work flow

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#394]
I think it will be mostly just Andy today.

I'm going to finish sorting out issue #391, but probably not until late afternoon or evening.

Owen is reading a version of the document from 5pm yesterday and send me some edits going up to page 48 so far. The comments aren't anything major, so I'll hold off on trying to contribute anything from them until later in the day when he's further along and Andy has had a chance to complete his edits.

**Comment by andrew-edwards** [comment]
Sounds fine. I only have five pages of main text to go, will do up the edits, and then go through Exec-summary. Good that Owen has no major edits so far (I keep spotting the odd one that has already got fixed). Fine that it's just me - I had that week away on my TMB course (which was awesome by the way) so happy to put in the time today.

**Comment by aaronmberger** [comment]
I've been making a running list of 'last minute edits' (essentially very minor things), but I will wait until Andy makes his and then go through the document on Monday to see if any of mine persist.

**Comment by taylori** [comment]
Back at work for a short while. Andy good work making so much progress. Seems like we're getting pretty close.

I'll start by working through the issues and commits that Andy mentioned my name as needing to confirm the change, then move to fix the landings csv file, and maybe start any corrections that Owen flagged since Andy seems to be committing often.

**Comment by taylori** [comment]
@andrew-edwards I'm commenting on a few of your commits. Let me know if you are getting the notifications about this (no rush to do so).

**Comment by andrew-edwards** [comment]
Yep - they show up in Notifications (which I wasn't sure about either). Very useful.

**Comment by andrew-edwards** [comment]
Okay, I've finished edits to the main text. May have some minor ones for captions but I'll do them tomorrow if time. Am taking a break for a bit, then will tackle the exec-summary. The other week I did flag what should need changing, and so hopefully it shouldn't be too bad (there's not tonnes of text in there). Will definitely get exec and one-page finished tonight.

**Comment by andrew-edwards** [comment]
Once done tonight I'll upload a .pdf to the Google Drive, so anyone can easily download it to read (particularly exec summary) if you don't have time to rebuild. Am thinking Aaron is flying on Monday, yes?

**Comment by taylori** [comment]
Good work Andy. 
I'm just back online and going to try a a few minor edits based on comments from Owen. Feel free to revert or not merge anything I do. Anything that's not obviously an improvement I'll post an issue to allow others to choose to make a change tomorrow or not.

**Comment by aaronmberger** [comment]
I’ll have some time Monday AM.  I fly back Tuesday.

**Comment by taylori** [comment]
I committed edits based on comments from Owen in 4725603. A bunch of his suggestions were things that were already fixed. The rest were often areas where the phrasing was a bit ambiguous so I tried to make things a little more clear. Please feel free to look them all over if you wish.

**Comment by taylori** [comment]
I'm going to bed. 

I'll check in when I can tomorrow to contribute if needed. I can adapt my schedule to be more available if problems arise, but hopefully any final edits will be smooth and easy and we can submit to Stacey early.

Remember that this is a draft version and need not be perfect.

**Comment by andrew-edwards** [comment]
Thanks. Made a couple of minor changes to Owen's, but they were generally great. 

I'm done soon. Just rebuilding all figures. Will upload to Google Drive.

**Comment by andrew-edwards** [comment]
Uploaded .pdf to compare-pdf's on Google Drive.

Main thing tomorrow is to have one other person read over the Exec Summary and One-page fairly carefully. And the catch-based sens run. And checking some edits and formatting I think..... Cheers.

**Comment by aaronmberger** [comment]
My small list of text edits can wait until the final version as all are very minor.

**Comment by aaronmberger** [comment]
I uploaded my pdf build as of 6:50 AM Pacific just to double check, but if something really different about mine compared to you three don't worry about that now.
