### ISSUE TITLE
Fig 60 (historical assessments) - MLEs or medians or (presumably) a combination?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#395]
I can't quite tell from the .csv input file.

So can maybe just add to the caption something like 
"Estimates are MLEs or medians depending on the model structure."

**Comment by cgrandin** [comment]
I know that all models since 2007 were MCMC medians, but prior to that would need some in depth investigation.

**Comment by taylori** [comment]
I think it would be adequate to say "Estimates are MLEs or MCMC medians depending on the model structure." No need to track down all the old assessments to figure it out.
