### ISSUE TITLE
base.model$mcmccalcs$smed contains MSY so text is wrong

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#396]
In custom-knitr-variables we have
```
median.bio.min  <- f(min(base.model$mcmccalcs$smed), 3)  # min median biomass
median.bio.min.year <- names(which.min(base.model$mcmccalcs$smed)) # year of min
```

but 
```
> tail(base.model$mcmccalcs$smed)
     2019      2020        unfished      Btgt         SPR           MSY 
1.1154350 0.9470050 2.0321075 0.8128425 0.7296075 0.5175175 
```
and so we end up with MSY being the minimum value. So the following in assessment-section.r:
```
median female spawning biomass declined throughout the late 2000s,
reaching a time-series low of \Sexpr{median.bio.min}~million~t in
\Sexpr{median.bio.min.year}. 
```
gives the MSY values at the end instead of the minimum of the time series. 

Not a difficult fix (just constrain the years presumably), I just don't want to get distrcated into doing it now, and should probably make sure it doesn't mess up any other text (hence raising as in issue).

**Comment by taylori** [comment]
See here https://github.com/cgrandin/hake-assessment/issues/254#issuecomment-364598126
for a comment with link to code change on a fix to similar problem. I probably should have done a more thorough check for other potential issues.

The origin is that there used to be a mix of SSB_ and SPB_ so filtering for just one or the other was adequate to get the time series or the references points, but now that the terminology has become more consistent, a different filter is needed.

I help with this, but probably isn't top priority.

**Comment by andrew-edwards** [comment]
And need same fix on line 262 of exec summary.
