### ISSUE TITLE
Figure 25 working for everyone?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#397]
I presume that the caption for Figure 25. `**[Not building, but no error shows up?! May get fixed automatically].` can now be removed.

**Comment by andrew-edwards** [comment]
Yes, think so. I put it there weeks ago.

**Comment by cgrandin** [comment]
I removed it in and am closing.

**Comment by andrew-edwards** [comment]
Damn - beat me to it.

**Comment by andrew-edwards** [comment]
I'd already done it and just pushed - I'll fix any conflict and then push again.

**Comment by andrew-edwards** [comment]
Exact same edit - no conflict. Nice.
