### ISSUE TITLE
Monday Monday Monday

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#398]
I think we can aim to submit by 3pm (or earlier), unless anything major comes up. 

My plan is:
1. Merge Aaron's, and check the numbers match. DONE (see comment on his commit though).
2. Compare his .pdf with mine to make sure we're all updated. DONE - .pdf's are identical (I didn't check all the main text, but everything else is good). [Table of Contents page numbers were off in Aaron's - I think he just run latex twice to get them updated]
3. Update text/sens runs as per #391 (I'll do that around 10 - Ian feel free to have a stab beforehand if you're available, no worries if not). Then remove .Rdata, source("all.r"), build(), delete knitr-cache and rebuild. DONE.
4. Pick off some issues - close any that we don't get to (and I'll make a note to reopen them later). Search for any remaining ** in the .pdf. And any '% Manual 2017' comments in the executive-summary (they should all have a 2018 confirmation). DONE.
5. Read one-page summary carefully. DONE
6. Read exec-summary. - I didn't but others have been. DONE.
7. Skim through whole document keeping an eye out for any formatting issues. DONE.
8. Submit and close this Issue!

I'll just edit this comment to say Done for each one. 

Chris is sick but has come in. Ian/Aaron - if you could read over the one-page and exec that would be great. I think I've highlighted the relevant things in the one-page. I expect people might want to know up front about the 2014 year class appearing smaller than it appeared last year, but that's based on medians, and the credible intervals still lie within the 2017 assessment ones (I explained that somewhere).

**Comment by cgrandin** [comment]
I'm here and working..

**Comment by taylori** [comment]
Just read one-page summary. Looks good to me.

Andy and Chris, feel free to shift figs and tables around, but I think it's at a good enough stage whenever you're ready to let it go (with or without any of the Exec Summary changes I proposed in #403.

I'll be eating a late lunch now myself, but will check for notifications by 2pm in case there's anything you want me to look at.

**Comment by andrew-edwards** [comment]
Thanks Ian. I just updated the one-page so take another look if you didn't have that version - just some consistency in notation.

I can prob shift those figs and tables around easily - easiest to do it at the end. I'm going to read through exec summary fairly quickly, then do that and I think we're done.

**Comment by taylori** [comment]
Changes look good to me. Fire when ready!
