### ISSUE TITLE
In Executive summary, figures in wrong place

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#402]
In the executive summary, figure k and table j appear after the **Research and Data needs section** begins, which breaks up the document in a weird way.

**Comment by andrew-edwards** [comment]
Thanks - was going to look out for that sort of thing. I can sort it (there might be some hardwiring of figures/tables to over-ride the latex ones). I think last year I had it looking sensible, so can try and do the same now. Am just printing to have a read-over.
