### ISSUE TITLE
minor edits to Exec Summary, status of 2017 cohort

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#403]
I'm about to commit a few minor edits to the Exec Summary, based on suggestions from Owen and my own thoughts (though I haven't read it carefully). One issue Owen flagged is that we say there is no info on the 2017 cohort but also report it below average. The median deviation is 
```
median(base.model$mcmc$Late_RecrDev_2017)
[1] 0.02517285
```
which I think is probably just MCMC sampling noise, so I took it out of the list of below average cohorts in 2 places.

Please look over commit that will reference this issue momentarily and feel free to not merge if you have any doubts or disagreements with these late-stage edits.

**Comment by andrew-edwards** [comment]
Thanks. I think I did wonder about that yesterday when I updated some numbers, but kept it the same as last year. Will take a look.

**Comment by aaronmberger** [comment]
I just caught up and built the document.  The executive summary one-page looks good to me.  One thing I flagged for consideration of inclusion in the one-page summary was the following sentence:

'While there is large uncertainty in the 2017 estimates of relative fishing intensity and relative spawning biomass, the model predicts a less than 6% joint probability of being both above the target relative fishing intensity in 2017 and below the B40% relative spawning biomass level at the start of 2018.'

I could go either way.  We can revisit this later too, no need to make further changes now.

**Comment by andrew-edwards** [comment]
Thanks. Could leave out the first bit, just start with:
"The model predicts ...."
That does summarise the status nicely.

**Comment by andrew-edwards** [comment]
Before the "Based on the default harvest rule...." bullet, yes? As it's stock status, so should come before the harvest rule stuff.

**Comment by andrew-edwards** [comment]
I went with
![image](https://user-images.githubusercontent.com/6977190/36124527-3e202848-1005-11e8-83de-3e8123494f12.png)

If I get one thumbs up then I'll submit!!
