### ISSUE TITLE
Fecundity/Maturity table needs units of kg

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#405]
Table 16 - should we add kg for fecundity in the caption or table header?

**Comment by cgrandin** [comment]
Also right-justify the number of samples column.

**Comment by taylori** [comment]
Good question. We could definitely add "(kg)" to the "Mean weight" column, but it's not clear if that should also be used for fecundity. The assumption is that the eggs produced are proportional to the body weight of mature individuals, but the proportionality is unknown, and effectively estimated via the log(R0) parameters. So it's not quite right to say the units of fecundity are eggs, but I'm not sure it's quite right to call it kg either.

**Comment by andrew-edwards** [comment]
Suggestion to add the total sample size  - easier to add into caption of Table 16.

**Comment by cgrandin** [comment]
I'll add kg to the mean weight column (but not to fecundity), right-justify the sample size column, and either add a new row with the total sample size or add that calculation to the caption.
