### ISSUE TITLE
Extra table requests and .csv files

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#408]
An AP member asked for the following (having sent her the .csv files for Tables 20-25).

"Thank you Andy!  Can we please have tables 11, 12, and 18 also?

And originally we had tables like 6-10 all the way back essentially the end result was like table 24 but broken down by fleet. Is that possible still by chance? At least by country?"

Chris said he can do the .csv files, else I'll get to them next week.

I'm not sure we want to have Tables 6-10 in the document going back forever (it's easier to compare them when they're small) - presumably they're findable in older assessments. We can ask at the SRG meeting for what people want, so we shouldn't change the document yet.

**Comment by aaronmberger** [comment]
I just uploaded a file to the JTC2018 data folder called "RawProportionsBySector" - this is all the age comp data that we have. By raw I mean that these are simply the age comps by year and sector, they have not been weighted in any manor because they have not yet been aggregated like in the assessment.

I'm not sure if we want to just send them this file or auto-create tables like the others.

**Comment by cgrandin** [comment]
I made the code spit out these 3 tables as well as the others, so it's exactly what's in the assessment document. The files are `fishery-input-age-proportions.csv`, `survey-input-age-proportions.csv`, and `median-population-estimates.csv` and are located in the `doc/out-csv` folder. You only have to make the document, not re-run `build()` or any of that.

Commit afb707bb3c95b51f421bd3c703801815ea387534

**Comment by aaronmberger** [comment]
great, thanks Chris!

**Comment by cgrandin** [comment]
See commit 39ff56f9df395c12e9f1f37940f76787d8254cca

Done

**Comment by cgrandin** [comment]
Andy, can you send these off since you have the email chain going? Thanks

**Comment by andrew-edwards** [comment]
Thanks Chris. Just sent them off (and CC'ed Chris). I'm thinking the 'Tables 6-10 for all years' bit didn't get done (only taking a quick look at the commit and not checking the rebuilding - I'm home with sick son). In the email I said to Shannon to raise it at the SRG if people want all the years - I think it might get a bit cumbersome, but we can do it. Just not a high priority right now.
