### ISSUE TITLE
Move maturity ogive from bottom to top panel of Figure 12.

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#409]
It's a little confusing right now (as maturity does not have units), as Ian had mentioned a while back. Then also change the y-axis of bottom panel.

**Comment by cgrandin** [comment]
We don't have the code for this figure, it was uploaded as an EPS file in the main-figures folder.

**Comment by taylori** [comment]
First, let me upload the code--was in too much of a rush to clean it up and make sure underlying data didn't include vessel locations.

Second, help me understand the suggestion. In the current figure, the center point of the blue points in the top panel are identical to the blue line in the lower panel. We could put the blue line behind the points, or just drop it entirely. See also comment on issue #405 about units for fecundity.

**Comment by cgrandin** [comment]
I think placing the line behind the points would aid the eye in seeing where the centers are in relation to one another. Just my thoughts.

**Comment by andrew-edwards** [comment]
Yes, blue line behind the points.

**Comment by taylori** [comment]
Got it. I think this is a good idea and will get it done soon.

**Comment by taylori** [comment]
Figure updated in commit dbf52c0. Maturity data is now uploaded in new CSV file so I made changes to data-tables.r and all.r to load data and source new plotting function. 
Modified figure pasted below, with blue line moved and slightly revised caption. 

@andrew-edwards please feel free to request changes or close if this matches what you were looking for.

Oops, I just noticed extra comma at end of ylab in lower panel. Just committed fix not shown in figure below.

![image](https://user-images.githubusercontent.com/4992918/36329166-dbf32446-1319-11e8-94c6-fa3532b89d1f.png)

**Comment by cgrandin** [comment]
Looks good to me, thanks Ian.

**Comment by andrew-edwards** [comment]
Awesome, thanks. That's much clearer (I had some great skiing and am now back to it!).
