### ISSUE TITLE
Did the proportions-at-age data get updated with the revised catches for the sensitivity run?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#411]
I'm thinking not. So we should clarify that in the documentation of the sensitivity run. Or update the data, but I think that's a lot of work for people (so only if time).

**Comment by aaronmberger** [comment]
You are referring to the catch-weighted averaging of sector-specific proportions to calculate a single aggregated annual age composition, correct?  No, the sensitivity only included an update to the total catch, age composition remained the same.  I can run that one to have it in our 'back pocket'.  It will likely change the proportions by very small percentages (~ tenths to hundredths of a percent I'm guessing).

**Comment by taylori** [comment]
The sector-specific weights would already include the "small changes to the pre-2017 catch in the U.S. fisheries" since those updates were lost in model input files, not database extractions. So it would just be the tribal and J.V. revisions that weren't included. My inclination would be to not bother doing anything different at this stage.

**Comment by andrew-edwards** [comment]
Yes, Aaron, that's what I meant. Agree it won't change things much (on Canadian side either), because the total catch was so big. Great, just wanted to clarify, thanks.

**Comment by cgrandin** [comment]
I would need to run the shoreside age proportion data through my weighting routine first, then send to you Aaron, at which point you could run it through the aggregated weighting algorithm.

**Comment by aaronmberger** [comment]
If you have time, you can send that to me.  I'll then aggregate with US ones and run a sensitivity to see if it makes any difference at all (just to satisfy our own curiosity).

**Comment by cgrandin** [comment]
I'm out of the office,  I can get it to you first thing Tuesday?

**Comment by aaronmberger** [comment]
No problem, that leaves my PLENTY of time... have a good weekend!

**Comment by cgrandin** [comment]
You too, and Ian and Andy too, have a great weekend.

**Comment by cgrandin** [comment]
I woke up sick today, am behind schedule and going to try to make it in but may not.

**Comment by taylori** [comment]
Chris, get whatever rest you need. We'll be able to get by with what we've got in hand.

**Comment by cgrandin** [comment]
I came in today to make sure I got everything updated and for a meeting I agreed to months ago for PCod. 
I just looked at the code I use for calculating age proportions and it turns out that the JV error in catch wasn't propagated into these calculations. So, the Canadian proportions are correct as they stand.

**Comment by taylori** [comment]
Good news. Thanks for checking.

**Comment by aaronmberger** [comment]
okay, great

**Comment by aaronmberger** [comment]
As expected, newly aggregated age comps (using updated catch totals by sector as weights) resulted in very very minor changes to the comps and no difference in model results (below).  I'll keep this run in our back pocket for the SRG, but am not going to anything further with this now.... will close this issue.

![compare2_spawnbio_uncertainty](https://user-images.githubusercontent.com/7946234/36508996-14cd3eda-1713-11e8-86f0-f1812e25e8c1.png)
