### ISSUE TITLE
the future of text versions of model files at end of document

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [cgrandin/hake-assessment#412]
The Pacific Fisheries Management Council has moved from inserting model files as appendices at the end of the assessment document to archiving them and uploading them to the website.  They can still be cited in the assessment document.  So it may be worth discussing omitting appendices F-J with the SRG and finding out if uploading them to the treaty website along with the assessment document is possible.

**Comment by andrew-edwards** [comment]
Yes, though I just chatted with Jaclyn (new on the SRG) and she often looks at them in the document. But let's bring it up and have the discussion.

**Comment by andrew-edwards** [comment]
I think there's a way of embedding files in .pdf documents, but needs to be using pdftex (or pdflatex) which means having .png files for all our figures not .eps. However, this may be needed at some point due to web accessibility issues.

**Comment by andrew-edwards** [comment]
The JTC Terms of Reference actually says we have to include:

11. Appendices
11.1. A list of definitions and acronyms for technical terms used in the document.
11.2. Complete input files for the stock assessment program(s).

So maybe we should leave the text, but also archive the files.

**Comment by andrew-edwards** [comment]
No need to deal with this, but for the record I just found latex packages embedfile and attachfile (and attachfile2) that insert files into .pdf's. But they only work with `pdflatex`, which when it runs it makes all the `.eps` files into `.pdf` files, and so takes forever. Just making this note in case we ever come back to it.
