### ISSUE TITLE
Bridging run adding the fishery age comps before adding the survey?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#414]
Just wondering (and I don't think I can see it in #313 but I think we may have discussed at some point) - clearly (Fig 15, p112) shows that adding the 2017 survey index pulls the recent years down, then adding the fishery age comps doesn't make much more of a difference. However, did anyone also try adding the fishery age comps first (without the survey index)? 

The text (p51) says the addition of the age comps (fishery and survey) had relatively little additional impact ... indicating the ages were consistent with the model estimates without those data. The age residuals are small for 2017 (Fig 25).

So that somewhat could imply that adding the age data first also has the same effect. If we have time then it may be worth doing such a run (if not done already) - it's been brought up that the survey is bringing the biomass down (and so would it be possible to have a 2018 survey?). But the data seem consistent and so it would be good to know if a non-2017-survey model would give similar results.

**Comment by aaronmberger** [comment]
Andy, I think that is a good idea.  I have not done that run.  Perhaps Ian did when doing the bridging, but if we haven't it would be worth doing and I can do that one.

**Comment by taylori** [comment]
I think this is a good idea. You could also add yet another option where the survey ages are added before either fishery ages or survey biomass.

I just posted issue #416 to help us keep straight what additional sensitivities are being run and keep track of the numbering.

**Comment by aaronmberger** [comment]
attaching a pdf comparing one alternative bridge chronology - survey still mostly driving trend in recent years, but entirely.
[CompareAltBridge.pdf](https://github.com/cgrandin/hake-assessment/files/1749162/CompareAltBridge.pdf)

**Comment by taylori** [comment]
This makes sense. It looks like the fishery ages reduces the 2014 cohort but leaves 2010 alone, so the impact is only on spawning biomass in 2016 and beyond. Adding the survey biomass brings 2010 down as well, which causes an impact on spawning biomass from 2012 onward.

**Comment by aaronmberger** [comment]
And for completeness a second bridge set where survey ages are introduced first.  Nothing really new here, suggesting survey ages were in line with what was expected given 2017 assessment.
[CompareAltBridge2.pdf](https://github.com/cgrandin/hake-assessment/files/1749227/CompareAltBridge2.pdf)

**Comment by andrew-edwards** [comment]
Aaron - if it's easy then please remake it in more landscape style (for the talk) - the code in beamer is
```
  <<bridge.biomass2, fig.height=4.5, fig.width=8, out.width='0.9\\columnwidth'>>=
    oldpar <- par(mar=c(5,4,1,1),no.readonly = TRUE)
```
though I can't see where \columnwidth is set (or if it's needed). So a similar aspect ratio would be good.

**Comment by aaronmberger** [comment]
Okay, updated the readme and uploaded those model runs to drive.  Yes, I was just going to ask if you wanted any particular figures uploaded as .eps.  So the second one in first alternative bridge set, sending over email now

...

**Comment by aaronmberger** [comment]
Okay, just sent you one but let me try an alternative with better aspect ratio

**Comment by aaronmberger** [comment]
landscape version coming over email now...

**Comment by andrew-edwards** [comment]
Got it thanks. Aspect ratio is perfect.

Sorry, are you able to do the one with adding fishery data first? Makes a bit more sense (because without a survey you wouldn't have the survey ages). Email is fine - once we've settled on one I can add to GitHub.

**Comment by aaronmberger** [comment]
Sure.  GitHub doesn’t like .eps uploads, but I can put into a figures folder in assessment folder.

**Comment by taylori** [comment]
Seems to be hit or miss with .eps uploads.
The [beamer/SRG/Management/Figures](https://github.com/andrew-edwards/hake-assessment/tree/master/beamer/SRG/Management/Figures) folder has a few .eps files that worked fine, as does [doc/main-figures](https://github.com/andrew-edwards/hake-assessment/tree/master/doc/main-figures). So far, I think it's only been the maps that got messed up.

**Comment by cgrandin** [comment]
About the .eps uploads - it depends which software you used to create them. If you used a Unix-based software on Windows the end-of-lines are \lf which are switched to \crlf by Github. I can't find the related issue now but we can fix this once done.

**Comment by taylori** [comment]
It makes sense the the software would be the key difference. Thus, it seems that .eps files created in R using `cairo_ps()` are OK while the maps that Andy converted from PDF using imagemagick or whatever were the issue.

**Comment by aaronmberger** [comment]
As well as .eps files created in Adobe Pro, they also have that issue.

**Comment by aaronmberger** [comment]
Okay, just committed your eps file Andy to SRG\Assessment\Figures

this is the one I meant to sent first

**Comment by andrew-edwards** [comment]
Thanks, now included. That was worth doing.

If people request to add it to the document we can probably just do it manually.
