### ISSUE TITLE
Should fix some of the ranges of axes

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#415]
Figure 15 recruitment deviation panel goes to 2-3 years beyond 2018. I had a quick delve into the code but it's a bit convoluted so I'll leave it for now. The panel was in the talk last year (so I'm keeping it), it's just a bit fiddly to see exactly which year is which for the recent years that change. 

I can work it out and state it for the talk, but we should presumably update the code when we have time. Similarly for some other similar bridging figures (and I thought there were more other ones but they may well have got fixed the other week).

**Comment by taylori** [comment]
I think this is a bug in r4ss, as the forecast years should be removed in the same way they are in other plots. I'm looking into it.

**Comment by taylori** [comment]
Can close this issue as soon as checklist in #418 is complete (and confirmed to work).

**Comment by taylori** [comment]
Completed as discussed in #420 and #418. Can always be reversed later.
