### ISSUE TITLE
extra sensitivities

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#416]
This is related to #414 but is a more broad title to continue as needed even once that issue is closed.

I started 3 additional sensitivities that I just now remembered to list on the README streadsheet on Google Drive, but haven't yet uploaded them:
- 2018.40.26_semiPara_tvSelect_sig_est
- 2018.40.27_downweight_fishery_ages
- 2018.40.28_downweight_survey_ages

The first is a suggestion from Jim Thorson to explore the MCMC performance of the sigma parameter in the alternative time-varying selectivity (he says the MCMC samples of the should be unbiased so the Laplace Approximation method of estimating that variance parameter is not needed as it is for the MLE). This is more just for our own understanding in case we want to make the switch for 2019. 

The 2nd and 3rd are related to issue #410.

The numbering probably overlaps with the extra catch run that Aaron already did, so I'm happy to renumber as needed.

**Comment by taylori** [comment]
As discussed on issue #414, at this stage it's probably easier to just upload .eps figures related to any additional information we want to include from the additional sensitivities, rather than add them to model-setup.r and create the Rdata files and all that.
If we find that anything needs to be added to the final document, we could do those extra steps during or after the SRG.

**Comment by aaronmberger** [comment]
Fully agree...

**Comment by cgrandin** [comment]
Ian, if you upload these sensitivity models I don't mind adding them into a new sensitivity group and putting them in the sensitivity presentation.

**Comment by taylori** [comment]
Thanks @cgrandin 

I uploaded the two sensitivities used in the extra squid plots to Google Drive:
2018.40.27_downweight_fishery_ages
2018.40.28_downweight_survey_ages
they include a "retrospectives" folder with 18 models within it, which will take a while to download. Alternatively, you could download everything in the main folder except "retrospectives" and then run these commands:
```
h4027 <- SS_output('../../models/2018.40.27_downweight_fishery_ages/')
h4028 <- SS_output('../../models/2018.40.28_downweight_survey_ages/')
SS_doRetro(masterdir=h4027$inputs$dir, oldsubdir="", years=0:-17)
SS_doRetro(masterdir=h4028$inputs$dir, oldsubdir="", years=0:-17)
```
Or just rely on the .eps files for the squid plots.

My notes for loading and running these models and making the squid plots is attached:
[notes_on_downweighted_retros.r.txt](https://github.com/cgrandin/hake-assessment/files/1749846/notes_on_downweighted_retros.r.txt)

**Comment by andrew-edwards** [comment]
Am thinking we don't need this - someone can agree by just closing Issue!

**Comment by aaronmberger** [comment]
I'll agree and close... as I don't think we are going to add any more to the document this year.
