### ISSUE TITLE
Missing minus sign on page 41?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#419]
Last night I tried going from (6) back to (4), kind of ignoring that one has p_ay and on has p_a, and I end up with (4) being 

\tilde{p}_a = - 1/2 .....

i.e a minus sign is different. Maybe someone should independently check, thanks.

**Comment by taylori** [comment]
Good catch. I just compared to top few lines in 
https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/selectivity-transformation-notes.r
which has the minus sign present
```
# testing logistic transformation
trans.fn <- function(x, x.low = -5, x.high = 9){
  -.5*log((x.high - x.low + 2e-7)/(x - x.low + 1e-7) - 1);
}
```
Not sure how I lost it, but please fix.
