### ISSUE TITLE
Some sensitivity figures need updating 

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#42]
Chris, I'm hoping you can help with these. 

I rearranged the plot order and model groups to match the text in my last commit.  The new first page of sensitivity plots deals with survey no extrap and age-1 index.  On the lower graph, I'd like to specifically show the recruitment deviate density plot for 2014 (instead of the recruitment time series).  The caption here has been changed.  It is called 'compare14_densities_Late_RecrDev_2014' when I run the following:

base <- SS_output(dir="22_preSRGbase_copy",covar=F,verbose=T)
Survey_noExtrap <- SS_output(dir="32_Sensbase_Survey_noExtrap",covar=F,verbose=T)
Age1Index <- SS_output(dir="33_Sensbase_Age1Index",covar=F,verbose=T)
mymodels <- list(base,Survey_noExtrap,Age1Index)
mysummary <- SSsummarize(mymodels)
modelnames <- c("base","Survey_noExtrap","Age1Index")
pdf("C:/Users/Aaron.Berger/Documents/AMB/Hake/2015.2016/sensitivity/compare_22_32_33.pdf")
SSplotComparisons(mysummary, legendlabels=modelnames,plotdir=wdir,print=TRUE,endyr=2015,indexPlotEach=T,new=F,indexfleets = c(2,2,2,2),densitynames = c("SPB_Virgin","R0","Main_RecrDev_2010","Late_RecrDev_2012","Late_RecrDev_2014","SR_BH_steep","ForeCatch_2016"))

The second page will be for the selectivity sensitivities (now sens.model.inds.3) following your the five plot 'layout' that you made for the bridging.  Top panel is subplot 2, then the lower four are the 'sel02_multiple_fleets_age1' graphs that are output when using SS_plots function.  These will show the actual estiamated selectivity pattern for each case.  At some point, I'd like to figure out how to add uncertainty measures.  Allan has previously done this using the posterior, but I will have to then run an mcmc on three more models.

The third page will then be the 'standard key' sensitivity runs.  I think I've done this correctly in the main-figures.rnw, but a check over would be a good idea.

Let me know is more info needed.

**Comment by aaronmberger** [comment]
Perhaps you have a better idea for the selectivity graphics... feel free try something different then specified above

**Comment by cgrandin** [comment]
I am working on this

**Comment by cgrandin** [comment]
I did the 5-panel one but am having difficulty with the density plot. SSplotComparisons with subplot argument 14 creates 6 plots, so I will have to extract the code that builds them and create a new function. This will take some time...

**Comment by aaronmberger** [comment]
If it is too much trouble for now, we can just go with the subplot 8 (recruitment time series).  The main feature of the addition of the age-1 index is the change in the estimated precision (more precise) of the 2014 recruit size.  It is harder to see this on the full time series plot.  But would be okay for now.

**Comment by cgrandin** [comment]
It's ok, I figured out how to do it without having to hack code I think.. Does this look correct to you?
SSplotComparisons(mysummary, legendlabels=modelnames,plotdir=getwd(),print=TRUE,endyr=2015,indexPlotEach=T,new=F,indexfleets = c(2,2,2,2), densitynames = c("Late_RecrDev_2014"), subplots = 14)

**Comment by aaronmberger** [comment]
Yes, that way you only end up with one subplot 14.  Nice....!

**Comment by aaronmberger** [comment]
To be extra clean, you could get rid of the indexfleets statement also

**Comment by cgrandin** [comment]
These are done. Closing..

**Comment by allan-hicks** [comment]
Yo can probably set print=F to avoid creating a png file.I'm not sure if it
actually doing that or not, though.
