### ISSUE TITLE
Make recruitment figures go to 2018

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#420]
This came about from issue #418. Figures e, 32 and 33 should go to 2018 for consistency with the "comparison" recruitment figures like Figures 15, 16 and 50.

**Comment by taylori** [comment]
@cgrandin did you start on this? I'm happy to help but don't want to make conflicting edits.
Looks like make.recruitment.plot in figures-timeseries.r has two vectors defined, so we could just switch from one to the other in the filtering.
```
non.equil.yrs <- start.yr:(end.yr - 1)
yrs <- equil.yr:end.yr
```
or we could just change the end.yr value in the call to that function.

Another strategy would be to leave everything as it stands now and ask the SRG what they think is best.

**Comment by cgrandin** [comment]
@taylori I haven't done anything so if you've figured it out then by all means go ahead and commit!

**Comment by taylori** [comment]
Done in commit 1991f21183ef5c3bd46c431739d991816ccc6859. Call from main-figures.rnw was to end.yr-1 and in the other case, it was excluded in the function within figures-timeseries.r, so those are now consistent.
Also Figure 33 now has top and right margins reduced to match Figure 32.

This should also close issue #415. It's easy to switch back at any time in the future if we wish to.
