### ISSUE TITLE
Put 2016 recruitment in the 'Estimated parameters and derived quantities' table

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#421]
I fins I've been wanting to reference this value a lot while going through the sensitivity presentation. I think we should add it for the document. I may try before the SRG.

**Comment by andrew-edwards** [comment]
Okay. Is there a way (or an option would be good so it can stay as is in the document) to remove the blank row before the Parameters subheading. The table currently just about fits on my slide (currently p21) with some negative space at the top. An extra row will push it off the bottom again.

I'm assuming the same function builds the table in the presentation and the doc.

**Comment by cgrandin** [comment]
Nobody asked for this so I'm going to move it to 2019

**Comment by kellijohnson** [comment]
Is this the same as #507, which is closed, so can we close this one as well?
