### ISSUE TITLE
Edits for Assessment talk

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#422]
Starting a new issue for simplicity, and so I can make a note (checklist!) of what I still want to do (not sure what I'll get finished tonight - will get done Sunday morning). Also so you guys can comment here.

To do:
- [x]  see #406 comments/discussions
- [x] update r4ss and check recruitment plots change
- [x] add MCMC diagnostics slide (first uncomment what's already there - trace plot worked, second one didn't - should add Fig 19 and Fig 20)
- [x] probably move SRG slides to after model description (since then have explained phi)
- [x] check main headings and section titles
- [x] remove any remaining ** and update Outline slide
- [x] spell check
- [x] practice what to say

**Comment by taylori** [comment]
Your responses to comments on #406 all makes sense. Please don't get bullied into using United States spellings.

Just looked at your changes to assessment from last night. I think it's looking good. 
You've explained both the selectivity stuff and the Dirichlet-Multinomial weighting very clearly.

Commit https://github.com/r4ss/r4ss/commit/da7f9e25e78508d999e7b30dfc9de96a801330ca shifts the diagonal lines for the cohorts to go through the center of the points so fix should happen automatically with update to 'development' branch of r4ss.
If you want those lines removed, add `cohortLines=c()` as an additional input to both calls to `make.fleet.age.comp.pearson.plot()`
I will make some comments about bubbles plots unrelated to this talk in a new issue (probably will be #423).

**Comment by andrew-edwards** [comment]
Thanks - no worries about spellings! 

Okay I haven't updated r4ss so that fix will get done.

Am thinking of moving the SRG response to the end of the talk, because then some of the stuff will have been already covered.

**Comment by andrew-edwards** [comment]
Just ran through talk making minor corrections. Will likely take 45-60 minutes, depending on questions and clarifications along the way.

**Comment by aaronmberger** [comment]
Just got to Lynnwood and had a chance to look over assessment talk - very nice flow Andy, I like it!  Just a couple comments as I went through it, none critical at this point:

-MCMC diagnostics section not showing bubbles tracking slides at top of presentation – need subsection{} maybe…   (same issue for 2017 SRG recommendation section)
-Slide 17: are the circle and red line hidden under the MCMC samples? Does the circle (observations) show up as a vertical line?
-Slide 18: Survey has now ‘seen’ 2014 cohort – remove yet
-Slide 19: Big 1999 and 2010 cohorts seem to fit particularly well (can we include 2014 in there now too?)
-Slide 20: no graph yet as I’m sure you are aware
-Slide 28: 2014 cohort estimated to be large, though likely not as large as 2010 – slide 26/27 shows substantial overlap of credible intervals so I’m wondering if ‘likely not as large’ could be misleading  (same language on summary slide)

**Comment by taylori** [comment]
Sorry I haven't had time to look it over in detail, but two comments on issues that Aaron raises:

The version on Google Drive as well as the one that I built most recently show the Pearson residual bubble plots on Slide 20.

Regarding 2010 vs 2014, I just looked at the ratio of 2014 to 2010 which shows has median estimate of ratio at 63% and only 5% chance that 2014 is bigger:
```
> hist(base.model$mcmc$Recr_2014 / base.model$mcmc$Recr_2010, breaks=50, col='grey', main='')
> median(base.model$mcmc$Recr_2014 / base.model$mcmc$Recr_2010)
[1] 0.6318122
> mean(base.model$mcmc$Recr_2014 > base.model$mcmc$Recr_2010)
[1] 0.048

```
![image](https://user-images.githubusercontent.com/4992918/36655518-fc1bd686-1a77-11e8-8bf6-657a956d2cd2.png)

**Comment by aaronmberger** [comment]
The joint approach of looking at the 2014 and 2010 mcmc estimates is a good way to examine this (rather than as independent observations) and it looks like 'likely' is just fine, thanks Ian.

**Comment by andrew-edwards** [comment]
Should probably add this calculation to the document.
