### ISSUE TITLE
info about potential request for alternative fecundity model

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#425]
If there's an additional request for alternative fecundity, we should be able to use the wtatage.ss file in the old model `2018.19.25_MatOgive_2` where the Fleet = -2 matrix is the maturity * weight-at-age.

Any change in equilibirum assumption would need to go in vector associated with Year = -1940, and any change in forecast assumption would either be added as a new value for Year = -2018 (though I'm not positive that forecast years, in which case we would need to add forecast assumption to Year = -2017.

**Comment by taylori** [comment]
models 2018.40.29 and 2018.40.30 have been added.
The first is "SRG request to use make fecundity proportional to weight-at-age (no change to equilibrium or forecast)"
The second is "SRG request to use make fecundity proportional to weight-at-age (also equilibrium and forecasat)"
but we need to define shorter names in model-setup.r to use in the legend of the plots.

**Comment by cgrandin** [comment]
I'm not seeing how the forecasts work for these runs. The standard code I wrote for build() reads in the forecasts for mcmc runs only. Where are they in these runs? I see SSB_XXXX for the years in the report file but I wanted to make sure those were them for SSB_2019 and SSB_2020. Even a code snippet from what you did earlier to plot them @taylori would help. Thx

**Comment by taylori** [comment]
Forecast is quick and dirty plot earlier this evening was shown by changing endyrvec input to SSplotComparisons:
```
SSplotComparisons(SSsummarize(list(base.model, h1, h2)), endyrvec=2020)
```
However, I just realized that the default forecast files in the base model that were used in this case are based on the default harvest control rule, so probably not really relevant and it would be good to just end in 2018.

**Comment by cgrandin** [comment]
@taylori, I spent a while trying to understand this. I see there are SSB_2019 and SSB_2020 in the Report.sso file. Are those being used by SSplotComparisons? If so are they the 'correct' ones?

**Comment by taylori** [comment]
Yes, I think they are correct in the sense that they would represent the MLE values when applying the default harvest control rule. But I now see that most of our forecasts are based on MCMC for the base model, and with the full range of different forecast catch options, so don't know how useful it would be to show these forecast values for this one sensitivity analysis.

**Comment by aaronmberger** [comment]
building now...

**Comment by aaronmberger** [comment]
sensitivity one built and looks great...  I've uploaded it to the SRG website and clipped it here
[beamer-hake-sensitivity.pdf](https://github.com/cgrandin/hake-assessment/files/1763404/beamer-hake-sensitivity.pdf)

**Comment by cgrandin** [comment]
Thanks @aaronmberger, yours has the right plots for max-age selectivity. I'll use this one.

**Comment by andrew-edwards** [comment]
Thanks Aaron - I was just checking to see if Chris needed this but you beat me to it...
