### ISSUE TITLE
Francis  data weighting in assessment

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#426]
SRG informal suggestion to add text in assessment about why Francis approach was not used here.

**Comment by andrew-edwards** [comment]
Have added Francis2011 to .bib (I had it already). Pretty sure that's the paper people are talking about.

**Comment by andrew-edwards** [comment]
Suggest we postpone this to 2019 unless it appears on the official SRG requests for 2018.

**Comment by taylori** [comment]
Unanimous agreement on this. I just assigned to 2019, closing for now.

**Comment by taylori** [comment]
For future reference, the easiest path to applying the Francis data weighting option is to use the `SS_tune_comps` function in r4ss, which calls on `SSMethod.TA1.8` also in r4ss, which was written by Chris Francis to implement his TA1.8 method described in Francis, R.I.C.C. (2011). Data weighting in statistical fisheries stock assessment models. _Can. J. Fish. Aquat. Sci._ 68: 1124-1138.

The first step would be switching back from Dirichlet-Multinomial likelihood to standard Multinomial by reversing steps listed here: https://github.com/cgrandin/hake-assessment/issues/315#issuecomment-360621656.

Second, run `SS_tune_comps(model, option="Francis")` which returns a table that can be copied into the sample size multiplier section near the bottom of the control file. It also writes the table to a file called "suggested_tunings.ss" in the directory with the model files.

Repeat as needed until the values in the `Francis_mult` column reported by `SS_tune_comps` are close to 1.0, indicating that further tuning isn't needed.

My understanding is that this tuning method was not intended to work well with flexible time-varying selectivity, so it may take longer to converge and produce less reasonable results than for a model with time-invariant selectivity.

**Comment by kellijohnson** [comment]
The current assessment (2019) has a sensitivity using Francis weights, and text was added to the data-section regarding McAllister-Ianelli and Francis weighting protocols. Noting here, that Rick Methot has mentioned that it is convoluted to do data-weighting with autocorrelated selectivity and that they are working on how to do this for future versions of SS.
See a3e2097ee9157b1cb9fea92cb9ac1a40548996df 3f5909c0ac87fb32b6dd1884714a51df09317c53 and b8ec33f3461e2935d051c4ed917cc17c2a7a3f89
I think we can close this now.

**Comment by andrew-edwards** [comment]
Sounds good. Maybe mention Rick's point in our text? Your call....

**Comment by kellijohnson** [comment]
I would rather leave Rick's point off of the document because it will lead to more defined work for us and just do it when it becomes available.

**Comment by andrew-edwards** [comment]
We should clarify in the document exactly which Francis 2011 method we use in the sensitivity.

**Comment by kellijohnson** [comment]
Table 2 in Francis (2011) has multiple methods, but only one method, T2.6, applies to us because we are referring to the multinomial distribution. I added the information to the reference. I used \citealp to give a comma without adding the parentheses.

**Comment by taylori** [comment]
@kellijohnson I should know this better, but the function that Chris Francis and Andre Punt contributed to the r4ss package (which gets called by `SS_tune_comps` is called `SSMethod.TA1.8`, so my understanding is that it was applying method TA1.8 from the Francis (2011) paper. I don't remember the paper well enough to know how this compares or relates to T2.6.

OK, just looked at the paper. In Table A1, it shows that Method TA1.8 uses weighting assumption T3.4, which Table 3 shows corresponds to T2.6 or T2.7 in Table 2.

All this seems very confusing and backwards, but it seems that you're right that T2.6 is the weighting applied, and yet given that Chris and Andre called the function TA1.8 suggests that maybe that's the more relevant name. Alternatively, you could just reference the paper and say as implemented in the R package.
