### ISSUE TITLE
Searching in pdf

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#43]
I have done a couple of searches in the pdf for a specific word and it showed zero results, even though I know that the word is in the document. For example, search for "credibility". Then search for "redibility".  For some reason the "c" is not seen by the pdf.  Searching for "interval" seems fine.

I don't want to make a big deal of this, but I use the search option a lot. For example, search for "Pacific Hake". It only returns one result, in a heading.

Any ideas how we can make searching more useful?

**Comment by andrew-edwards** [comment]
Works fine in my local build. I'm using dvips then ps2pdf .

**Comment by allan-hicks** [comment]
Hmmm. I observed this in mine and Chris' builds.  Maybe you will have to
build the final version. Are you using MikTex?

**Comment by andrew-edwards** [comment]
Yes, MikTex 2.9.

**Comment by cgrandin** [comment]
It thinks they are ligatures. Try copy-pasting a word with a 'c' or 'fi' in it from the PDF to a text editor, and those will not copy. I put these two lines in the preamble.tex:
\input{glyphtounicode}
\pdfgentounicode=1
and these two in hake-assessment.rnw:
\usepackage[T1]{fontenc}
\usepackage{lmodern}
And mine now works. See this solution:
http://tex.stackexchange.com/questions/57866/pdf-files-show-fi-but-searching-for-or-copying-them-does-not-work
As soon as I push you will get this

**Comment by allan-hicks** [comment]
Awesome. I knew you could figure it out.  Let me know when you push, and
then I'll create a draft for Owen and Jim.
Thanks,
Allan

**Comment by cgrandin** [comment]
I've pushed that up, we are still missing a lot and the sensitivity tables are wrong. Give them those caveats!!
