### ISSUE TITLE
Residual plots for different maximum ages of fixed selectivity 

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#430]
I've done these in the appendix. But Figure 25 caption says

"Figure 25. Pearson residuals for base model MLE fits to the fishery age composition data.."

So it says MLE fits but the function call is 
```
make.age.comp.pearson.plot(base.model)
```

but 
```
> make.age.comp.pearson.plot
function(model,                  ## model is an mcmc run and is the output of the r4ss package's function SSgetMCMC
...
```

Code works for the new max ages (even though model is not an mcmc run but the function says it should be), but scale is different to Figure 25.

Question: is Figure 25 for MLEs or medians? I can't tease it out from ```SSplotComps``` that is called by ```make.age.comp.pearson.plot```

[And I'll remove 'fishery' from the caption]]

**Comment by andrew-edwards** [comment]
Also can't see how to make the scale of circles consistent between figures.

**Comment by taylori** [comment]
The Pearson residuals in Figure 25 are MLEs. It would take some work to aggregate the Pearson values from the extra-mcmc folder if we ever wanted to show MCMCs.

By default, the bubbles should all be on a comparable scale. The legend should adjust to span the range of values in each case so may not match. The scaling is dependent on an argument `cexZ1` to the SSplotComps function, which is 1.5 by default. This makes a Pearson residual of 1 (or -1) have a cex value of 1.5.

**Comment by andrew-edwards** [comment]
Thanks - wanted to check about MLE v MCMC. MLE is what we want, so that's good.

That makes sense - the bubbles look to be the same scale across the figures, it's just the legend that changes. 

That's easier than I thought - I'll just add a note to the captions to say that.

**Comment by andrew-edwards** [comment]
Someone should just check the code in the commits that do the new Figures A.1-A.4.  Think it's all good.

That person can then check this box - [ ]

**Comment by taylori** [comment]
Just built the doc and looked at Figures A.1 through A.4 which seem useful. More flexibility with max. age = 10 reduces the residuals for ages 7-9, but seems to increase them for some of the older ages as expected. It's not a big difference regardless.

**Comment by andrew-edwards** [comment]
Leaving open to add a bit of text to Appendix based on Ian's comment.

**Comment by andrew-edwards** [comment]
Screw it, not adding text. Figures are there.
