### ISSUE TITLE
Table related to SigmaR

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#432]
I'm working on a table of mean recruitment vs. R0 at different SigmaR values that can contribute to whatever we show for request number 1.

**Comment by aaronmberger** [comment]
I did run a base model profile over sigma-R including how alternatives influence derived quantities such as depletion
![profile_plot_likelihood](https://user-images.githubusercontent.com/7946234/36763189-b6f50874-1bdb-11e8-9324-aae160e349cb.png)
![sigmarprofs](https://user-images.githubusercontent.com/7946234/36763205-ce907680-1bdb-11e8-92ed-29d17ea5d1c9.png)

**Comment by taylori** [comment]
Profile is even better. Code and plot below are what I've come up with. We could easily apply the `getR0` and `getMeanRecr` functions to all the models in the profile to get a similar plot from the larger set of profile models.

![image](https://user-images.githubusercontent.com/4992918/36763557-55ac7690-1bdd-11e8-8894-2fa0711d73cf.png)

```
# look at mean recruitment vs. R0
getR0 <- function(model){
  # R0 in units of billions of fish
  round(exp(model$parameters["SR_LN(R0)","Value"])/1e6, 3)
}
getMeanRecr <- function(model){
  # Mean recruitment over the years 1966 to 2017 (or final data year)
  round(mean(model$timeseries$Recruit_0[model$timeseries$Era=="TIME"])/1e6, 3)
}

getR0(base.model)
getMeanRecr(base.model)

getR0(mod.sig1.0)
getR0(mod.sig1.0)

# make table
sigma.table <- data.frame(sigmaR = c(1.0, 1.4, 1.8), R0 = NA, MeanRecr1966to2017=NA)

# add R0 values
sigma.table$R0[sigma.table$sigmaR==1.0] <- getR0(mod.sig1.0)
sigma.table$R0[sigma.table$sigmaR==1.4] <- getR0(base.model)
sigma.table$R0[sigma.table$sigmaR==1.8] <- getR0(mod.sig1.8)

# add Mean Recruitments
sigma.table$MeanRecr1966to2017[sigma.table$sigmaR==1.0] <- getMeanRecr(mod.sig1.0)
sigma.table$MeanRecr1966to2017[sigma.table$sigmaR==1.4] <- getMeanRecr(base.model)
sigma.table$MeanRecr1966to2017[sigma.table$sigmaR==1.8] <- getMeanRecr(mod.sig1.8)

# 
plot(sigma.table$sigmaR, sigma.table$R0,
     type='o', pch=16, lwd=3, col=4, ylim=c(0,4), yaxs='i', las=1,
     xlab="SigmaR", ylab="Number of recruits (billions)", axes=FALSE)
axis(1, at=c(1,1.4,1.8))
axis(2)
box()
lines(sigma.table$sigmaR, sigma.table$MeanRecr1966to2017,
      type='o', pch=16, lwd=3, col=2)
text(labels="Mean recruitment (1966-2017)", 1, 2.5, col=2, adj=0)
text(labels="Equilibrium recruitment (R0)", 1, 1.4, col=4, adj=0)
```

**Comment by taylori** [comment]
Forgot to mention that my main point is that the mean recruitment is more consistent with R0 in the base model than in the low or high sigmaR models. Here's the `sigma.table` calculated in the code in my previous comment.

sigmaR | R0 | MeanRecr1966to2017
-- | -- | --
1 | 1.503 | 2.292
1.4 | 2.108 | 2.343
1.8 | 3.569 | 2.442

**Comment by taylori** [comment]
Added figure as below to presentation in commit 64466d1. 
Basis for figure is new function called by all.r (see commit for details). We can make a smoother version from the likelihood profile in future documents/presentations if there is interest, but this is quicker for now.

![image](https://user-images.githubusercontent.com/4992918/36810392-6a7e6f4a-1c7f-11e8-9c6a-540707634a34.png)
