### ISSUE TITLE
age 2+ in table 18

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#433]
In Table tables-timeseries.r

I think we just need to change
  tot.bm <-
    ts$Bio_all[ts$Yr %in% yrs]

to 
  tot.bm <-
    ts$Bio_smry[ts$Yr %in% yrs]

in

**Comment by taylori** [comment]
Also need to change load-models to make extra.mcmc$timeseries$Bio_smry reflect the median, not the MLE.
Also will need to change the caption and header in the table.
I'll work on this now.

**Comment by andrew-edwards** [comment]
Not fully following, but aren't we adding a column rather than replacing one?

Seems a bit dangerous to redefine something like tot.bm, as it may get used elsewhere.

**Comment by taylori** [comment]
Good points. I will make it adding a column, rather than renaming.
And regardless will use a different variable name for age-2+ rather than changing tot.bm.

**Comment by taylori** [comment]
Commit b2b2d93 adds Age-2+ column to Tables 18 and 19 (snipped below). 

This requires getting extra values from the timeseries tables in the extra-mcmc report files, everyone needs to delete \models\2018.40_base_model\2018.40_base_model.RData
and re-run `build()`

Here is the checklist once you've rebuilt your RData file:
- [ ] Ian
- [ ] Aaron
- [ ] Andy
- [ ] Chris

![image](https://user-images.githubusercontent.com/4992918/36803686-2f641c78-1c6d-11e8-8b93-3d94ae786165.png)

**Comment by aaronmberger** [comment]
I was last to do this which [presumably] my lack of speed gives my the opportunity to close.... doing now

**Comment by taylori** [comment]
Change somehow got lost in Table 18, added back in d0466cc.

**Comment by andrew-edwards** [comment]
Closing, presuming that people will delete knitr-cache at some point (I just did, and presumably I'd submit the final version).

**Comment by taylori** [comment]
Somehow the edits to Table 18 in commit b2b2d93f794ea87d06f4645096704e113e2c8bf6 were lost.
I can't figure out how they disappeared to have just manually restored them them in commit a48ebe0.

**Comment by andrew-edwards** [comment]
I have them okay. Something funny happened earlier with one of my edits also.  Presume you deleted knitr-cache.
