### ISSUE TITLE
Trevor Branch - typos (from email)

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#434]
- [x] Figure k looks very odd: probabilities are all substantially
higher for the second last and lower for the last catch level.

- [x] Page 30 “Some data sources were not included but have been
explored, were used for sensitivity analyses, or were included in
previous stock assessments but not in this one.” should be “This
assessment does not conduct some sensitivity analyses, or explored the
inclusion of some data sources, that were included in previous stock
assessments.” Note that the age-1 acoustic index is listed here as not
being in sensitivity tests, but in section 2.2.1 it say that there was
a sensitivity test done.

- [x] 2.1.1 remove the apostrophe and s after AFSC’s and NWFSC’s.

- [x] p. 35 ((Berger et al.. 2017)) should be (Berger et al. 2017).

- [x] p. 36 “The 2017 survey biomass index declined from the 2015
index to 1.42 million metric tons, which is 0.66 times the 2015 index”
could instead be written “The 2017 survey biomass index declined 34%
from the 2015 index to 1.42 million metric tons”.

- [x] p. 36-37 “These samples were collected from bottom the
acoustic survey, winter and summer acoustic research trips, from”
should be “These samples were collected from the acoustic survey,
winter and summer acoustic research trips, the …. and the U.S. West
Coast…”

- [x] p. 39 2.4.2 “Gadidae” is a family name, not a genus, and
should therefore not be italicized.

- [x] p. 42 “effective samples sizes” should be “effective sample sizes”.

- [x] Seems wasteful to have a page break before Section 3, also
does not appear in other sections (I think).

- [x] p. 51 second line “remaining highly uncertain” should be
“remained highly uncertain”.

- [x] Suggestion: make Figure 24 narrower.

- [x] p. 57 3.5 the model does not integrate over the uncertainty in
the survey catchability, since this is fixed from the analytical
formula.

- [x] p. 61 “whereby the input samples sizes” should be “whereby the
input sample sizes”

- [x] p. 63 “implausibly high estimates recent recruitments” should be
“implausibly high estimates of recent recruitments”

- [x] p. 63 “had higher estimates of 2016 and” should be “had higher
estimates of 2016 recruitment and”

- [x] p. 64 3.9 “age-2 and age-1, respectively, individuals to to
predict” should be “age-2 and age-1 individuals, respectively, to
predict”.

- [x] p. 64 “appears to maybe be more similar” should be “appears to
be more similar” or “is more similar”.

- [x] Table 19: there are extra spaces after the “-“ for some of the
data in some columns, notably all those in the second-last column.

- [x] Figure 20 top-right panel “equilibirum” should be “equilibrium”.

**Comment by cgrandin** [comment]
KeyParameterGelman_MultChain.eps needs modification for the last item

**Comment by andrew-edwards** [comment]
Figure k issue got addressed in the meeting - graph is correct, and looks funny because the 2018 catch is so high for catch option g.

**Comment by andrew-edwards** [comment]
Page 30 comment - the suggested replacement has different meaning. Suggest leaving as is, or replacing with:

"Some data sources were not included in the base model, but have been explored or used for
sensitivity analyses, or were included in previous stock assessments but not in
this one." 

Feel free to thumbs up or down!

**Comment by andrew-edwards** [comment]
Final checkbox in list - should 'bottom the' actually be 'bottom trawl surveys'?? Trevor suggests deleting 'bottom the', but I would like clarifiction, thanks.

**Comment by taylori** [comment]
Bottom trawl is the last item on the list, so I think deleting the first bottom as suggested is correct. But in the current doc, I'm not seeing the typo:

> These samples were collected from the acoustic survey, winter and summer acoustic
> research trips, from the U.S. At-Sea Hake Observer Program (A-SHOP) observers aboard com-
> mercial Catcher-Processor vessels, and from the U.S. West Coast bottom trawl survey.

**Comment by andrew-edwards** [comment]
I should have checked. Aaron already did it 7 days ago!

Just a note that we didn't do all of Trevor's edits - some were only very minor.
