### ISSUE TITLE
put csv files for tables for Google Drive?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#437]
Shannon asked about getting updated csv files now that we've revised some tables, especially Table 22.
Does out-csv get repopulated every time build-doc() is run?
Should we create a folder on Google Drive to share all those files with meeting participants?

**Comment by andrew-edwards** [comment]
Yes, they get updated automatically. Mine (dated this morning) matches the updated one in document.
What else would it be apart from Table 22?

**Comment by taylori** [comment]
I just created a "Tables from assessment report" in the SRG folder on Google Drive and dragged the files from out-csv into it: https://drive.google.com/drive/folders/1uQ3y_MWW6yjA6ksiTOH6pp9WRVCnL5s0.

If that seems like an OK solution to whoever sees this first, please close.

**Comment by andrew-edwards** [comment]
I thought the original ones were somewhere but I can't really see where, so that seems fine to me....
