### ISSUE TITLE
Bold captions?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#44]
What do you think of bold captions or caption labels?

**Comment by aaronmberger** [comment]
I've always like bold caption labels (Figure XX; Table YY) followed by regular caption text.... just two cents here...

**Comment by minnowslayer** [comment]
I likewise prefer them

**Comment by andrew-edwards** [comment]
Done. See latest commit. And a small indent after the first line, which better distinguishes captions from the main text. Easy to change options in hake.sty, search for {caption}, line 96.

**Comment by andrew-edwards** [comment]
Sorry, didn't mean to close. Kind of up to to the person who raised the issue to agree/disagree and then close if necessary.....

**Comment by cgrandin** [comment]
This is fine with me!

**Comment by allanhicks** [comment]
I haven't seen the new document, but I think we agree to close this.
