### ISSUE TITLE
Dinner options

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#440]
Depending on our workload, here are a few ideas in Edmonds thanks to Trevor

- Very expensive and outstanding food, decor etc.: Epulo http://www.epulobistro.com/
- Medium and amazing burgers: Hamburger Harry's http://www.hamburgerharrysedmonds.com/
- Simple seafood, excellent rockfish tacos: Anthony's Beach Cafe (bottom floor https://www.anthonys.com/restaurants/detail/anthonys-beach-cafe
- Seafood (more expensive): Anthony's or Arni's seafood 
https://www.anthonys.com/restaurants/detail/anthonys-homeport-edmonds
http://arniesrestaurant.com/
- Thai (excellent, moderate price): Thai Cottage

Another nice, but quite expensive, place that I ate at once before is Salt & Iron: http://www.saltniron.com/

**Comment by cgrandin** [comment]
I vote for Epulo. It doesn't look that expensive and has a bunch of different things..

**Comment by cgrandin** [comment]
It was great. I still have Pizza 🍕

**Comment by andrew-edwards** [comment]
Couple of Indian restaurant options - we usually have a curry one night:

Sitar- http://www.sitarrestaurant.net

Indian Gate- https://www.indiagaterestaurant.ca

**Comment by aaronmberger** [comment]
both look good to me and Indian cuisine sounds good...
