### ISSUE TITLE
short delay for MCMC 24 million

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#441]
Just woke up and am getting errors with the VPN required to connect to my desktop: "AnyConnect was not able to establish a connection to the specified secure gateway. Please try connecting again.". 

Luckily with light traffic at this hour, the office is only 10 minutes away so I'm going to hunt down the MCMC run in person and should be able to upload shortly.

**Comment by taylori** [comment]
OK, just uploaded long run as `mcmc_24mil` to `2018.40.30_fecundity_matrix2`. I also renamed Aaron's shorter chain to `mcmc_12mil`.

So I think we all need to 
- Rename `mcmc` on our computers to `mcmc_12mil`
- Download `mcmc_24mil` and rename to `mcmc`
- Re-run `build(T)`

- [ ] Ian
- [ ] Aaron
- [ ] Chris
- [ ] Andy

**Comment by cgrandin** [comment]
Thanks Ian, don't forget to source all.r also: `source("all.r");build(T)`

**Comment by cgrandin** [comment]
Document built successfully, with all tables and figures for the 24 million run.

**Comment by andrew-edwards** [comment]
And delete 12-mil figs and tables (or just delete knitr-cache).

**Comment by andrew-edwards** [comment]
Ian - do you need to check the box? Close this?
