### ISSUE TITLE
No older data used in 1991 assessment

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#442]
Looking at 1991 assessment just uploaded along with others to "references" folder in Google Drive: https://drive.google.com/drive/folders/1hsvj43F6YAklU4pOsKI1ZKCy5J4HLm0j
Shows no indication of data prior to 1977, but maybe that's when the model started.

I'm stepping away from desktop now, might be slightly late for meeting.

> Data Sources
> The data elements used in the synthesis model are as follows: 1) a time
> series of catch at age from the u.S. and Canadian fisheries for Pacific
> whiting (1977~90), 2) yields in biomass from the U.S. and Canadian fisheries
> for the same years, 3) age composition in the U.S. and Canadian zones from
> NMFS triennial groundfish assessment surveys (1977, 1980, 1983, 1986, 1989),
> and 4) survey biomass estimates for the u.s. and Canadian zones for the same
> years. The survey biomass estimates for the Canadian zone were adjusted
> because of inadequate survey coverage as described in Dorn et al. (1990).
>

**Comment by aaronmberger** [comment]
I don't think we need this to remain open for now.  This will pertain to investigating SRG request about equilibrium fecundity via wt-at-age.... closing
