### ISSUE TITLE
add text to executive summary about alternative model

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#446]
I just committed some additions related to this as a first cut - tried to explain the situation briefly and the cite the appendix.  I figure this only needs to be in the executive summary and not copied to the main document.  If we want it in the main document it will be easy enough to copy over.

**Comment by aaronmberger** [comment]
and learned how to put commit link in here.... f51ecf81143a3c4c8a2a1a97b24c44a092002528

**Comment by aaronmberger** [comment]
oops, first time messed it up, wrong link, second try.... 638105959062fe46732e68e90bcfbb8dd5526fd8

**Comment by taylori** [comment]
I made some edits to the Exec Summary text and added a note about the inconsistency. A check of te impact of correcting that inconsistency shows little change other than the 1970s.

- Model 1 is the base
- Model 2 is the "alternate model"
- Model 3 is 2018.40.31 which I'll upload soon which is the alternative base + revised catch-at-age for pre-1975 and 2017 onward 

![image](https://user-images.githubusercontent.com/4992918/36867246-6cae99e6-1d49-11e8-886e-25954ff8beee.png)

**Comment by andrew-edwards** [comment]
Okay, Ian's note disappeared and is now back in. Please take a read and then close this.
