### ISSUE TITLE
draft JMC presentation finished

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#449]
Hopefully everyone is enjoying the weekend and you all won't see this message until after my presentation to the JMC on Monday morning.

However, for the record, I've just uploaded a complete draft beamer-hake-JMC.pdf to "Hake JTC 2018" on Google Drive.

I also committed the changes to make this presentation, along with some minor edits to a few plotting functions that were incorporated into the talk.

I tried to make the edits to the plotting functions in a way that new options were added while maintaining the default behavior as used in the assessment report, but I haven't tried building again to check. If anything breaks, we can always revert to the v1.5 release https://github.com/cgrandin/hake-assessment/releases for building.

I'm hoping to take the day off tomorrow, but will check for any comments on this issue sometime in the evening. If you look at the presentation and anything seems really out of whack, please send me a text message at any time.

**Comment by aaronmberger** [comment]
This looks good to me Ian.  The only thing I saw was an extra period on bullet four of Page 3.  I got an error when trying to build it, but didn't spend time debugging it for me.  I just used the google drive version for now.  Thanks again for representing the JTC at the JMC!

**Comment by aaronmberger** [comment]
I should be around and available most of the day today and tomorrow until 1PM so if anything comes up Ian that you need help on (or an extra pair of eyes) just start an issue.

**Comment by taylori** [comment]
I just commit a new version of the JMC presentation file which removes the extra period (thanks Aaron) and adds back the lines
```
source("all.r")
load.models.into.parent.env()
```
which I had commented out to expedite building while working in the R workspace using build.doc().
I'm guessing that having those back will allow it to build for any of you.

The JTC presentation took something like 2 hours, with lots of questions about the maturity and weight-at-age calculations, but no clear conclusions or direction so far. The final presentation (with fixed period) is on the Google Drive in the JMC folder.
