### ISSUE TITLE
Unhardwire q in Table 26 (of 2018 final version)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#451]
Not sure if this got done, but open it so we check it next year.

Also remove extra ) in R0 and B0 rows.

**Comment by cgrandin** [comment]
All done in commit d28f10b8b797e2496cd62a726a4edfe24eb61c8a. I changed the parantheses also for R0 and B0 rows in commit 0863b0382e75b9419428f8ca466ff5b24927c60b.
