### ISSUE TITLE
Revert assessment edits done at end of 2018 assessment

### ISSUE THREAD

**Issue by kellijohnson** [cgrandin/hake-assessment#455]
The LaTex code diverged a bit from the standard practice at the end of the 2018 assessment season. Can someone who knows the .tex files better than myself edit the files to remove some of the complexity that won't be needed for the 2019 assessment? Mainly I referring to the added Appendix for the "Alternative base model".

**Comment by cgrandin** [comment]
I always clean everything up at the beginning of the assessment cycle so that it works for the new year. Usually I start looking at this in November.

**Comment by kellijohnson** [comment]
Thanks @cgrandin

**Comment by andrew-edwards** [comment]
Great Kelli that you're looking into it already. I'm pretty swamped for the next few weeks so won't be ;)

Yes, it gets a bit frantic towards the end (i.e. during the SRG meeting), and given we submitted the revised version on the ferry on the way home, we likely never went back to tidy things up. I can help with that also....

**Comment by taylori** [comment]
As discussed just now, it seems like this one can be closed.
