### ISSUE TITLE
Finalize the JTC meeting agenda

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#456]
@aaronmberger, thanks for putting together the draft agenda for the December JTC meeting. Are you up for adding the suggested start times of the different events and let us know when to look it over before circulating it, or do you want to hand that off to somebody else?

**Comment by aaronmberger** [comment]
Yes, I can finish up a draft and will circulate to JTC for final input.  I'll circulate after I hear back from survey team, Mike, and Nis about their proposed time slots.

**Comment by aaronmberger** [comment]
sent off to Miako, we should be good, closing...
