### ISSUE TITLE
sens.model defined?  Can't build (run all.r)

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#46]
I don't see where sens.model is defined.... beginning my line 260... I'm thinking it should be sens.model.xx.yy something

i <- 1
for(sens.model in sens.model.inds.1.for.table){
  sens.models.1.for.table[[i + 1]] <- models[[sens.model]]
  i <- i + 1
}

**Comment by cgrandin** [comment]
Does source("all.r") work? And are you doing a save.image() after?

**Comment by aaronmberger** [comment]
No, that is were it gets hung up on that bit of code in all.r

DEBUG: Loading model  22_preSRGbase  as base model

Error in models[[sens.model]] : subscript out of bounds

**Comment by aaronmberger** [comment]
Yes, normally save.image() afterwards

**Comment by cgrandin** [comment]
Make sure you are merged to my current commit - it should work!

**Comment by andrew-edwards** [comment]
Chris's latest commit works for me. I'll try Aaron's now (minor change in selectivity model group).

**Comment by andrew-edwards** [comment]
Seemed to work for me.

**Comment by cgrandin** [comment]
Aaron, are you still having issues?

**Comment by aaronmberger** [comment]
Yes, it is hanging up in the selectivity section.  I'll look more into it

**Comment by cgrandin** [comment]
My guess is that this is the same problem Allan had. I've fixed it now so I'm closing this.
