### ISSUE TITLE
Update structure for 2019 (SRG report etc.) and flag what needs to be changed

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#460]

**Comment by andrew-edwards** [comment]
I'll try and do this today - as usual put ** before sections/paragraphs that need thinking about or checking (basically that aren't fully automated). Makes it clearer what we still need to edit (and what we've updated already)....

Home now. build(T,T,T) still running okay.....

**Comment by cgrandin** [comment]
Mine is still running for the 3 alternate cases.

**Comment by andrew-edwards** [comment]
Mine too (even without the 2018 and 2019 base cases). Though computer was off for a bit when I left.
May not get any text done yet - nearly finished the catch calculations.

**Comment by andrew-edwards** [comment]
Done and pushed the catch calculations - be instructive if you can independently do them. Yes, be nice to have automated (given we have three more examples), but will be somewhat fiddly to do (I know you'll see it as a challenge though!).

I won't get any text done. build is still running (on the third MCMC one) so can't compile the document anyway.

**Comment by cgrandin** [comment]
I have the automation of the catch calcs partially done. It will happen during the forecasting step. I just have to make sure that the numbers are the same as what you got, then we can run for the other cases.

**Comment by andrew-edwards** [comment]
Excellent, thanks for doing that. It's good to have done it manually for the base case, but would be a bit tedious to do it for all three (and any other runs requested by SRG). My numbers are uploaded in my recent commits.

**Comment by cgrandin** [comment]
For the SPR one it's hard to make it as efficient as possible, i.e. how to plan the jump in catch to optimize number of runs done. I might just go with a 1000 catch reduction each time

**Comment by andrew-edwards** [comment]
I knew one of them would be fiddly. But you'd see it as a computational challenge!

**Comment by andrew-edwards** [comment]
Getting back to the title of this Issue.... I've flagged all text with `**` that needs some manual updating/thinking about.    Each `**` refers to the start of a paragraph or caption, or sometimes a full section. Easy to search for on the .pdf. So we'll gradually pick them off.

So awesome to have so much of it automated. I can't build the document (to do with the pesky 2019.02.32, but we're doing new runs anyway so didn't want to get sidetracked) so there may be minor latex issues - I don't like editing and not checking the .pdf, but oh well.

Haven't copied in all the SRG requests yet, will do when can build.

**Comment by andrew-edwards** [comment]
Finished yesterday. SRG responses still flagged as necessary
