### ISSUE TITLE
SRG request: make sure data-weighting is adequately documented

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#463]
From 2018 SRG report
> The 2018 assessment diverged from past practice in its approach to determining the data weights applied to the age-composition data. Past assessments used an iterative approach (sometimes referred to as the McAllister-Ianelli approach) to arrive at these weightings. The 2018 assessment incorporates the weightings as estimable parameters, thereby eliminating the need for iterative reweighting. This streamlines the assessment process and the SRG considers it to be a sensible and useful improvement. **However, the SRG requests that the JTC provide thorough documentation of all changes in methods of data weighting.** 

It's not totally clear what the request is, but probably an indicator that we should better document both the base model approach and any other methods used in sensitivity analyses.

Assigning to @aaronmberger as lead author to worry about how/where to fit this into document and @taylori as having more past involvement in these approaches so able to help write documentation

**Comment by taylori** [comment]
Not sure how much will be done on this request this year, but in case it's useful, info on data weighting approaches in SS is described in this post to VLab https://vlab.ncep.noaa.gov/group/stock-synthesis/discussions-forums-/-/message_boards/view_message/4220876
I can adapt some of that into the document if needed.

**Comment by andrew-edwards** [comment]
I think it was concerning changes over time (through different assessments). Though  it's kind of related to their point 8 about documenting changes in assessments. I'll leave a placeholder for you guys.

**Comment by kellijohnson** [comment]
Would it be sufficient to look in just the last few years how data weighting was done and add some text to the document or is the SRG expecting more than just a few years? I think I can get this done quickly if it is the former.

**Comment by aaronmberger** [comment]
I think a running table that incorporates all [non-trivial] changes to model structure would be best and would speak to both this request (data weighting specific) and the related SRG request about more general changes to model structure. This would ideally go back to the start of the Treaty period (say 2008), but should at least go back 5 or so years.  And once created, would be a standard table that we just add on to each subsequent year.  The creation of such a table should be milestoned for 2020.

Having said that, I think for this year we could have an SRG response prepared that quickly highlights recent changes, and cites the other SRG request/response that will say something like the above (the larger plan).  We already talk about the dirichlet multinomial (text still in there from last year), so I think this response could even be just a table showing what was done the last few years (maybe last 5) and what the resulting fishery and survey weights were for each assessment year.  Something like that, maybe....?

**Comment by kellijohnson** [comment]
What do you guys think of this table, which also speaks to SRG Request 8 in the 2019 document? I have also asked for input from @taylori and Owen Hamel via email.

[pacifichake_assessmentdifferences.xlsx](https://github.com/cgrandin/hake-assessment/files/2829475/pacifichake_assessmentdifferences.xlsx)

**Comment by kellijohnson** [comment]
@taylori suggested that we truncate the table to begin in 2011 as the SRG request says because the table is fairly SS specific and prior to then TINSS or other models were also presented.

**Comment by cgrandin** [comment]
I agree, 
Maybe just comment out those three lines in the csv, using #
That way we can add  easily if someone asks

**Comment by andrew-edwards** [comment]
Thanks for doing. I can't open the .xlsx (often the case on my machine), but from a converted .pdf I get the idea. I can check in the assessment doc. Great that we're still actually doing some of the SRG requests (after dampening expectations at the start of the document!).

**Comment by kellijohnson** [comment]
I think we can close this as long as people aren't too depressed that I cannot figure out how to left align the entire column of text when there are multiple lines per row (i.e., the "Change" column" of Table 36).

**Comment by andrew-edwards** [comment]
I was going to suggest fudging it in Latex (fake blank rows with text only in that column, with ~~ to indent it), e.g. second row:
```
 & & & & & & ~~except for age-composition likelihood
```

 But Chris made you make a function so he can look at it ;)   Ho ho...

The offset rows are a little hard to see; probably an easy setting to change?

**Comment by cgrandin** [comment]
This annoyed me so I found a way to fix it. As usual something silly **p{5cm}**
