### ISSUE TITLE
SRG request related to weight-at-age data and B0

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#467]
Not pasting long text of discussion in 2018 SRG report, but here is bold request at the end of it:
> The SRG requests that the JTC examine the historical weights-at-age data, evaluate approaches for parameterizing fecundity-at-age for years without data (pre-1975), and evaluate other methods of deriving biological reference points such as B0. 

As noted, this wraps up lots of things, but posting this issue to note that @aaronmberger is taking the lead on the exploration of patterns in the data.

**Comment by aaronmberger** [comment]
I think we can close this.
