### ISSUE TITLE
Possible extra sensitivity runs

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#471]
Could do:
1. Set 2018 weights-at-age to 2017 values or average of last five years (rather than last three). Hard to justify going back much further (if changing weights-at-age are representative of changing environmental conditions).

**Comment by cgrandin** [comment]
Best to set the 2018 wtatage to long term mean as we do for projection years and historical pre-data years.

In document: "Mean weights were assumed to remain constant prior to the first observation and after the last observation within the range of years in the matrix."

That would be a 'consistent way' of inserting wt-at-age data for years that we don't have.

**Comment by cgrandin** [comment]
We've beat this to death.. We can't calculate the 5-year means without the US wtatage R source code and possibly more. Closing for this year.
