### ISSUE TITLE
Find wtatage_calculations.R

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#472]
From 2018, 2018.40_base_model\wtatage.ss has this in the header:
```
#C 2018 Hake weight-at-age file
# empirical weight-at-age Stock Synthesis input file for hake
# modified from file created by code in the R script: wtatage_calculations.R
# original creation date: 2018-01-11 16:39:23,
# modification date: 2018-01-29
```

If we are able to get age data then we'd need the wtatatage_calculations.R, but I can't see that on this repo. 

Can maybe check r4ss but I doubt it's there.

**Comment by andrew-edwards** [comment]
Just remembered there's a private US hake data repo that gets used - presumably it might be in there. Much like Chris does our preprocessing, then Aaron merges them for the assessment input.

**Comment by cgrandin** [comment]
We have agreed to move forward and were able to pillage the required wtatage lines from other wtatage.ss files so I am closing this here. In future, we need to make this more transparent though so that we can do it if US government closes again.
