### ISSUE TITLE
Can we easily do projections for sensitivity cases (without MCMC)?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#482]
Some of our proposed sensitivities involve changing the weights-at-age for the projections (setting to the long-term average). Can't see that we normally do projections for MLE runs, so look into if it's easy or not. Else think about doing an alternative model run with full MCMC for the projections changing (see also notes on Google Drive readme).

**Comment by andrew-edwards** [comment]
Or just discuss with respect to last year's alternative model run. One of the new sensitivities/bridge models should help with the understanding, and the new colour wtatage plot with 1975-1979 average for early year should show the unreasonableness of repeating the full alt model run last year.

**Comment by cgrandin** [comment]
We agreed on adding 3 new MCMC models.
