### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#484]
- [x] Build wtatage figures for new sensitivities (may need to wait for build() on MCMC's though)
- [x] Both to do the new catch values for projections
- [x] Add table of new fecundity runs (probably just refer to them by run number for simplicity)
- [x] Run long MCMC's over the weekend for three new sensitivities
- [ ] Check through tables and figures .rnw for any more that need un-hardwiring
- [ ] Work on text (next week)

**Comment by cgrandin** [comment]
I'll do the table of wtatage sensitivities and the text for that section.

**Comment by andrew-edwards** [comment]
Have set up my 3 long MCMC runs (32, 36, 38). Chris doing the same, and we'll check them on Monday, build(T, T, T) [using the trick for the 2019 and 2018 base models again so they don't recalculated], and create the new appendices for 32, 36 and 38.

**Comment by andrew-edwards** [comment]
Mine ran as well. I'll keep them as back up (_andy) on my machine, but download Chris's to use for the document. Obviously they should be the same (I'll maybe check).

**Comment by andrew-edwards** [comment]
Closing, as done most of this (and rest covered in #460).
