### ISSUE TITLE
To discuss on Monday 28th 

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#486]
Chris and I can get a .pdf build by the end of the day to show what we've done. Maybe it's worth keeping the 1pm meeting today as a bit more high-level (especially as it sounds like you have to spend time getting up and running again). Then a more detailed discussion tomorrow. 

The main thing is whether or not it would be possible to get the 2018 age data in. Are the US data even available? Basically all the model runs that we've done would be repeated (as models 2019.03.**) but with the new age data in. This also involves updating the weight-at-age files, and control files. So very fiddly, especially with the different assumptions about fecundities (that we'll get written up today).

We have three sensitivies run as MCMCs (MCMCs are taking about 50 hours). Chris and I both ran them over the weekend and they worked.

That seems to be worth discussing today. Then Chris and I can spend the rest of the day getting our results in order in the document to then discuss in more detail tomorrow.

**Comment by aaronmberger** [comment]
I agree with high level today and more detailed tomorrow.  I'm working on getting the US age comp data today.  The latest is (and we can discuss later today:
1. all available US age comp data should be uploaded by COB today
2. was told this morning that an update to MS final catch will occur and be ready by tomorrow AM (this is lower priority in my mind but if ready by the morning might as well include it)
3. If 1 and 2 above occur, Kelli and I can do US data extraction and have data available by tomorrow mid-day
4. We then could run the code to create wt-at-age table (including Canadian weights) and combine the age comp data (available COB Tuesday at the earliest if all goes smoothly)
5. We could then add this info into what you guys have already built and, at best, have a full "update" base model by Thursday (again if all goes smoothly).

We can chat about all this at 1PM.

**Comment by andrew-edwards** [comment]
Thanks. One option could be to update the base model, show a sensitivity to our current base model (2018 ages are averages of 2015-2017), and, if they're not drastically different, leave all our existing sensitivities relative to our existing base model. Or at least just update the three MCMC runs we did (just not all the minor sensitivities like changing sigma_r or whatever).

To me that seems achievable and verifiable in a short time, without changing everything else.
