### ISSUE TITLE
Github error

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#487]
Anyone come across this error when using shell (or trying to interact with github in general):
Failed to connect to github.com port 443?

Some information on google about setting (resetting) configuration: 
git config --global http.proxy http[s]://userName:password@proxyaddress:port 

Just wondering if anyone has come across this - I was fine before shutdown and now getting this error when trying to fetch Chris or Andy to get up to speed

**Comment by kellijohnson** [comment]
Normally that means that your firewall is not allowing you to connect to the internet. Can you pull from a different repo as a test that git is failing for all repositories?

**Comment by aaronmberger** [comment]
no, can't access/pull from any repo at the moment

**Comment by cgrandin** [comment]
It's possible your IT blocked GitHub. Hopefully not. Can you go to the GitHub website?

**Comment by aaronmberger** [comment]
Yes, I can go to GitHub website and browse whatever

**Comment by aaronmberger** [comment]
Tried that, I'm wondering if somehow a windows update I did put the git shell exe behind a firewall?

**Comment by cgrandin** [comment]
Also, try `git clone https://github.com/aaronmberger/hake-assessment` in a different folder and see if that works

**Comment by cgrandin** [comment]
If you did, try opening the port using something like this: https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by aaronmberger** [comment]
Using standard command prompt line I can run fetch, diff, merge, but errors on push because not linked to my git username and password I think.  Just tried the clone and it also failed to connect.

**Comment by kellijohnson** [comment]
do you have 2factor authentication?

**Comment by aaronmberger** [comment]
I don't think so, or at least nothing would have changed - I'm contacting IT to get the exe past the firewall

**Comment by cgrandin** [comment]
I had this happen to mine not long ago. I* think I went to github.com, to my account Settings and SSH keys then deleted my key

**Comment by cgrandin** [comment]
![image](https://user-images.githubusercontent.com/4551051/51860085-99890c80-22ed-11e9-950a-52ae07cd4d56.png)

**Comment by cgrandin** [comment]
Also could be your anti-virus software is now blocking port access. Try disabling it if you can

**Comment by taylori** [comment]
FYI, I'm not having issues, but I haven't restarted my computer in a while in spite of instructions to do so. I'm waiting until I'm in the office tomorrow so I can get more rapid help if things don't work right.

**Comment by aaronmberger** [comment]
Thanks for all your comments on this - it was a firewall issue and is now resolved.  Somehow a Windows 10 McAfee was install was pushed to my computer despite having a Windows 7 system.  Why does shit hit the fan only when the fan is at top speed?  Closing this sucker...
