### ISSUE TITLE
Implications of not including dummy year of survey data?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#488]
We have this for the survey data:
```
2013    7       2       1929235   0.0646
2014    7       -2      1         1      # dummy observation
2015    7       2       2155853   0.0829 # note: "revised in early 2016 from 0.092 to 0.0829"
2016    7       -2      1         1      # dummy observation
2017    7       2       1417811   0.0632
```
and did not add a dummy observation for 2018. Everything worked so it is only a problem if we have a 2019 observation (i.e. you only need dummy for intermediate years)?

**Comment by aaronmberger** [comment]
Good question.  I don't think it should matter if the dummy years are in there at all.  I think they are there just so there is temporal continuity for visualization.  But with stock synthesis, I never can be sure until I try a run without and compare.

**Comment by andrew-edwards** [comment]
Bridging model of adding in the 2018 catch (and running model to start of 2019) showed no difference (page 117 of the hake-assessment.pdf that I uploaded to Google Drive earlier). Presumably that's the comparison, and it's okay.
