### ISSUE TITLE
Friday afternoon - who's doing what? (To avoid duplication).

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#49]
Andy - I may actually read the thing! Then I can start going through main text and update it with the relevant text from Exec Summary.
We have finalised all model runs, senstitivites and retrospectives, yes? I.e. no results should change now.

**Comment by aaronmberger** [comment]
Yes, I think we are pre-SRG final there.  Possibly, maybe....

**Comment by andrew-edwards** [comment]
Ha ha - your reply makes sense when I look at the Issues page. The automatic sending of issues to email isn't always so useful!
Great. 
And I didn't do what I said I would above. Maybe tomorrow....
