### ISSUE TITLE
Check posteriors.sso and derived_posteriors.sso for extra lines before trying to load

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#491]
This breaks the build() code frequently so I should fix it at some point. Note to self :)

*Perhaps a regexp to remove all lines after ^Iter.\* near the bottom of the file or something*

**Comment by taylori** [comment]
Running MLE estimation is supposed to write a single line in those files representing the MLE estimates of all the values, but if somehow they don't get deleted by the executable before-hand as they are supposed to, the extra lines will be appended. One option would be to manually delete posteriors.sso and derived_posteriors.sso before running any MCMC, and make sure no further model runs take place in the mcmc folder.

**Comment by taylori** [comment]
The regexp would probably be quicker, so that's a good idea.

**Comment by kellijohnson** [comment]
I also ran into the same problem. Specifically, the file had an extra row of parameter names and derived quantity names before each row of estimates. The vector of names was longer than the vector of estimates, where the latter was the correct length. The extra rows of names started after Iteration 2400 for the base model. This didn't happen all of the time though. I wrote the following code to maybe help in the future. This code is only correct if you want to keep those parameter lines that come after the weird line of parameter names. If not, then @cgrandin's pseudo code is better.
```
read_posteriors <- function(dir) {
  posts <- read.table(file.path(dir, "posteriors.sso"), 
    header = TRUE, fill = TRUE, stringsAsFactors = FALSE)

  if (all(grepl("^[[:digit:]]", posts[,1]))) return(posts)
  posts <- posts[grep("^\\d", posts[, 1]), ]
  posts[posts[, 1] == 0, 1] <- (max(as.numeric(posts[, 1])) + 1):
  (nrow(posts) + as.numeric(posts[1, 1]) - 1)
  return(posts)
}  
```

**Comment by cgrandin** [comment]
Ok, I fixed it. Thanks Kelli for the code, you spurred me into action on this. Take a look at the commit, it reads, then fixes, then writes the two files before trying to load in the load.ss.files() function.
