### ISSUE TITLE
Forecasting fails for run 32

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#493]
Run 32 is summarised in: https://docs.google.com/spreadsheets/d/17kSbmyr85OT0gFbrh7MtXfuTEQSeivA1Gu4iTJvFsvk/edit#gid=0 
Basically, the pessimistic bits from last year's alternative run. 

For the default harvest rule, we are calculating the catch levels.
When we put 679,000 t (the median for 2019 from doing `median(out$ForeCatch_2019)` from `derived_posteriors.sso`, then run `ss3 -mceval` it fails with the following warnings:
```
#V3.30.10.00-safe;_2018_01_09;_Stock_Synthesis_by_Richard_Methot_(NOAA)_using_ADMB_11.6
Tue Jan 29 11:35:31 2019

 warning: poor convergence in Fspr search 0.4 1
 warning: high Fmult for Fspr: 40 needed to come close to low SPR 0.4 1
 warning: poor convergence in Btarget search 6.01523e+06 1.50381e+07
 N warnings: 3
Number_of_active_parameters_on_or_near_bounds: 0
```

This broke Chris's new code, plus we just tried it manually as per Aaron's `forecast-find-decision-table.R` and that also breaks. Presumably (looking at Fig A.1 from last year), the stock is being depleted for some MCMC cases when the median catch is used for 2019. 

Thoughts?

**Comment by andrew-edwards** [comment]
For 32 the results are:
```
> median(out$SSB_Initial)
[1] 4060370
> quantile(out$SSB_Virgin)
     0%     25%     50%     75%    100% 
3160310 3860765 4060370 4262348 4931850 
> quantile(out$SSB_2019)
     0%     25%     50%     75%    100% 
 988092 2098003 2837550 4073390 9852880 
> quantile(out$Bratio_2019)
       0%       25%       50%       75%      100% 
0.2473320 0.5217342 0.7168605 0.9942625 2.1676900 
```
So some MCMC samples whack up the 2019 spawning biomass, pulling up the median, which is used to calculate the 2019 catch (through the harvest rule, but this catch is too high for the lower biomass MCMC samples.

**Comment by andrew-edwards** [comment]
If this gets fiddly and time-consuming, we can just present MLE results for this run.

**Comment by taylori** [comment]
@andrew-edwards I tried to look into this by downloading model 2019.02.32, changing forecast file, and re-running `ss3 -mceval`, but it looks like files from the -mcmc step are not present as I don't get the error and don't get a full posteriors file even with forecast catch at 0. Am I missing something, or could you upload the files you're getting the error from?

**Comment by cgrandin** [comment]
@taylori That's the issue we are having I think. What's missing? I see posteriors.sso and derived_posteriors.sso are there and populated

**Comment by taylori** [comment]
The `ss3 -mcmc` step would have created a `ss.psv` file which is the binary file that ADMB uses to store all the parameters sampled during the MCMC run. Running `ss3 -mceval` then feeds those values back into the model and runs additional code (flagged by `if(mceval_phase() )` in the TPL) to create the files like posteriors.sso. But it looks like the `ss.psv` got deleted or not uploaded to Google Drive. If you can track it down, things should work, otherwise it would require re-running the MCMC.

**Comment by cgrandin** [comment]
I found the psv file, and am trying the forecasting step now. I should have remembered this but thanks @taylori for the :bulb:

**Comment by andrew-edwards** [comment]
Don't think it built, but not really needed now so closing (I didn't try very hard).
