### ISSUE TITLE
Alternative catch stream for last year

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#495]
We included this in our new base run (based on run 25 from 2018). The numbers in 2018 Table a match those in that run 25 (and so are slightly different to our 2018 base run), and so don't change for this year. However, 2016 and 2017 both have one ton more in the hake_data.ss (new base, and run 25 from 2018) file than what appears in Table a. Table a is derived from catches.R. 

Obviously not a big deal as it's only 1 t, but for consistency it would be nice to have the numbers match and someone will notice it. Am thinking it's probably a rounding issue, in the way that Table a gets constructed versus the data files. There's not one simple table of catches in `data/` so it's not as simple as just adding 1 t to the final two years.

**Comment by kellijohnson** [comment]
What about landings-tac-history? Can't we use the total column of that table to make the hake_data.ss file or am I missing something?

**Comment by andrew-edwards** [comment]
Yes, currently that file and the hake_data.ss file are not integrated. I couldn't quickly unravel exactly where the numbers came from, or which files get built from individual other files (e.g. US and Can catches). Maybe it is just best to just change it in landings-tac-history for consistency and any minor discrepancies. I thing @aaronmberger normally does that stuff.

I can't test this now as can't build the document until the annoying run 32 is fixed.

**Comment by aaronmberger** [comment]
I think we are good here.  Issues associated with the alternative catch stream from last year have been all sorted out this year.  Data in 2019 assessment Table a match the base model data file.

**Comment by andrew-edwards** [comment]
Great. And the other data tables (Can, US etc.) add up to give Table a values? (I forget this minute how they all link together).
