### ISSUE TITLE
Suggestions for today's phone call

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#497]
Thanks Aaron for doing the new model set up. Chris and I looked through and it looks good. A few of questions we can discuss, with number 1 being the most important.

1. What to use for wtatage and fecundity for the projections. Based on the JTC discussion, Chris and I settled on using 2015-2017 mean for 2018 onwards. The current 2019.03.00_base_model however has the historical average. Please download hake-assessment-29-jan-2019.pdf that I just uploaded to the Google Drive. 

Basically if you can read section 3.4.2 on pages 53-55, that should get everyone up to speed. That text was written assuming we didn't have 2018 age data, but can be updated easily enough - the description of the runs will be the same, just need a bit of updating. 

The heatmaps on pages 150-153 show the different assumptions for the different model runs. The runs are summarised on the table on page 107, which is essentially that on https://docs.google.com/spreadsheets/d/17kSbmyr85OT0gFbrh7MtXfuTEQSeivA1Gu4iTJvFsvk/edit#gid=0  to which we just added the location of the new 2019.03.00_base_model run.

2. We will have to decide what to use for 2018+ given the configuration issue in SS (#496).

3. I had to change INIT of h from 0.88 to 0.95 to get 2019.02.00_base_model (and sensitivities) to run. Aaron hasn't needed to for 2019.03_00_base_model, which is great. Just mentioning in case things stop converging again.

4. I wrote down a couple of minor points of clarification.

**Comment by taylori** [comment]
sorry can't join call today, meeting with Nis about MSE stuff. Let me know if things come up that I can help with.
