### ISSUE TITLE
Did we get the fishery reports from either industry group?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#500]
Chris emailed them a few weeks ago. Any reply (maybe I wasn't CC'ed)?

Obviously both need updating (I just haven't flagged them).

**Comment by cgrandin** [comment]
Not yet, I’ll follow up with them.

**Comment by aaronmberger** [comment]
I think I mentioned the Friday before the assessment due date.  But yes good to follow up on these. Chris, will you do Canada and I can contact U.S.

**Comment by cgrandin** [comment]
Sure thing. I did ask both originally and can forward you the email I sent out. Mike O replied but didn’t have the report.

**Comment by cgrandin** [comment]
Canada added in commit 55c47fe1cc9b96fa12d207bff0ceae030abb24c2. Closed for the year.
