### ISSUE TITLE
Download new models

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#501]
You will need to download again all models in 2019.03_models folder on google drive, including 2019.03.00_base because thanks to Kelli, we've now corrected a small (but important) error in the age comp aggregation.  It doesn't make much of a difference in terms of stock status or other management quantities but the previous version was not fully incorporating the Mothership comps in 2018 and 2017 as it should be.  All models now in 2019.03_models folder are now fixed.

**Comment by andrew-edwards** [comment]
So just the proportions-at-age changed, yes? We have seven fecundity models running, but none of those changed the data file (only wtatage) so we can just copy them in. 

Or did weights-at-age change? If so we'll have to redo the ones we did today (and Aaron you'll have to update the "vector for catch-weighted average wt-at-age over the time period 2016-2018" you sent use earlier. 

Note that you need to delete old folders on Google Drive -it seems to keep them even if you update new ones with the same names (Aaron's from this afternoon are still there, but same folders are there for 9:32pm). Ha ha -I just refreshed and you've just deleted them!

Chris did start MCMCs (and I don't have the files) so we can fix those and run some short ones in the morning to build the document. Thanks Kelli for double checking and finding the error.....

**Comment by cgrandin** [comment]
Sounds like an easy fix. I’ll change all the fecundity sensitivities tomorrow morning prior to uploading

**Comment by aaronmberger** [comment]
Yes, just the proportions at age changed for 2017 and 2018.  Essentially two lines in the .data file.  No changes to weight at age.  Changes to model results are visually undetectable (via summary figures).

**Comment by cgrandin** [comment]
Thanks. I diff'ed everything to make sure it's all good. I copied the data file into all the fecundity folders and their associated MCMC folders

**Comment by aaronmberger** [comment]
Perfect, change only in data file. Given the quickness of all this data compilation, I'm doing one more check over of the wt-at-age file - should be done in 30 min or less.  Kelli has checked all other SS input files.  I'll respond  on this issue when done and we can call the SS files "final".  I don't anticipate any changes so keep running your fecundity models (and Kelli, the sensitivities), but I'll let you know either way shortly.

**Comment by cgrandin** [comment]
I've uploaded all fecundity models to Google drive. They each have an mcmc run of 24,000 with sampled every 10 just as a short run. We don't need to use the mcmc output, it's just there as a placeholder for getting the document building.

**Comment by aaronmberger** [comment]
I just reconstituted the wt-at-age file and got the exact same thing.  So let's call the input SS files final for this year.  I think everyone is up to speed on the new models in the google drive (or are aware of them), so closing this issue.
