### ISSUE TITLE
Thursday afternoon

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#503]
Just to keep track of who's doing what (so we don't overlap):

We have the document building (with Aaron's bridging) - I'm just running the build() to get new results. Note that build() now excludes re-building the previous year's model (line 373 of model-setup.r).

Chris - just setting off MCMC runs (12000000) for the extra fecundity sensitivites. He's doing all seven though we'll likely just show three. We'll look at the results to see what to put in. 

Andy -  will update the table of fecundity runs plus heatmaps,plus description of the weight-at-age stuff. If time will update MLE figs for our fecundity sensitivites.

Structurally the document is there, some text will need updating (anything with **), and some issues to start plugging away at!

**Comment by aaronmberger** [comment]
That's great guys, can I get caught up and build too then?  I am working on the Bridging section of the text right now.

**Comment by andrew-edwards** [comment]
Yes - build(T, T, T). Just takes a while.

**Comment by aaronmberger** [comment]
I think Kelli is looking at the sensitivity section of the text...

**Comment by taylori** [comment]
I haven't been following closely as I'm working on helping Nis with write-up of his MSE work.

I took a quick look at input files and output of 2019.03.00_base. The changes to the input files all look good. The 2018 age data looks to be on track with expectations from last year (including 2-year-olds supporting the above-average 2016 recruitment estimated last year based on the 1-year-olds in 2017 fishery).

Waiting for an email, but I expect to be able to provide text for status update on genetics analysis sometime tomorrow (issue #463).

Let me know if you see a need for me to compile the document and/or if there are specific areas that you would like me to contribute to.

**Comment by aaronmberger** [comment]
Thanks Ian!  The genetic analysis update would be great.

**Comment by aaronmberger** [comment]
Are we ready to switch over to the new 2019.03_XX sensitivities and comment out those not being used this year - in the model-setup file?

**Comment by andrew-edwards** [comment]
The ones Kelli just did? Yes, probably I think. We kept the 2019.02.XX ones in so it builds, and as placeholders for the new ones. If they're all the same it's an easy change in emacs - I'll leave it to you...

**Comment by andrew-edwards** [comment]
I'm off soon. Still finishing off the weights-at-age write up, but nearly there. Have updated Table 33 but not the related figures yet.

**Comment by aaronmberger** [comment]
Still working on bridging text, almost done though

**Comment by andrew-edwards** [comment]
Friday: I'll finish up the weight-at-age figures and text (not the text on the sensitivities as not done yet), then input placeholders for the rest of the 2018 SRG requests (some of which we don't have time to do).

**Comment by aaronmberger** [comment]
Friday: I'll finish up bridging text and pointers to figures/tables, including updating related figures as needed.  Now that I have the document building, I can update our sensitivity list (model-setup; I'll do this first thing).  Later this morning, I'm going to start going through the executive summary (top to bottom as a first pass).

**Comment by andrew-edwards** [comment]
Great. I did go through the exec summary and flagged what needs changing/thinking about (some may need waiting for the final results), but yes, good to start thinking about it again. There'll be some new text needed requiring model update from last year.
Chris did the model-setup for our fecundity runs (different order to 2019.02.XX) so I'm going through those and will probably just call them Run XX etc. for the figures, since we have a table explicitly for those runs. Given the subtleties between runs, I feel the SRG meeting will go smoother if people are referring to Run 51 not 'early weight-at-age is this without time-varying fecundity and blah blah'. Sound good?

[Usual sens runs can keep the longer names as they're useful]

**Comment by andrew-edwards** [comment]
no need to wait - just don't touch our weight-at-age sensitivities (Runs 51 onwards I think). We've set the early ones up up like last year, but you just may want to regroup them or show the different types of results (I did it based on our 2019.02.XX, but easy to change around).

**Comment by andrew-edwards** [comment]
There are a few figures that no longer knit (not ones I was working on) - think they'll get corrected tomorrow when we build(T, T, T) so I just skip through them when latex-ing.
