### ISSUE TITLE
There's a blank page between end of tables section and figures section

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#51]

**Comment by andrew-edwards** [comment]
Done.

**Comment by allanhicks** [comment]
This has crept back in. I think it is a simple adjustment to the figure height

**Comment by andrew-edwards** [comment]
I'll fix it now - I think it's to do with the [p] not [H] issue, since it's actually different to the original issue [blank page was before Figures heading].  [p] is generally bad to use, but Chris had a few in for the two-figures-on-a-page, and then a few more crept in over time.

**Comment by andrew-edwards** [comment]
Chris said the internet said to use [p] for double figures (two within one   \begin{figure}  .... \end{figure} ) I guess to force them to start on a new page, else they would go off the bottom. But since we have no text then everything can start on a new page.

**Comment by andrew-edwards** [comment]
Created a conflict with Allan (because he added/removed some figures and I'd also change main-figures.rnw). I'll resolve it then push....

**Comment by andrew-edwards** [comment]
Fixed.

**Comment by andrew-edwards** [comment]
Fixed, but peole should merge with mine before making more figure changes. (If you've done some then commit and push and I can deal with the merging and conflicts.)
