### ISSUE TITLE
For 2019.03.00_base_model, extra-mcmc/reports/ has different number of files than last year

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#515]
Just curious (and want to confirm if we have more than 2000 MCMC samples). 

2018 base model extra-mcmc/reports had Report_1.sso to Report_2000.sso  (and similarly for other files)

2019.03.00_base_model:      has  Report_1.sso to Report_2199.sso   . 

Aha -  `num.mcmc.samples` is now 2199. 

Am thinking it's to do with Aaron changing the starter/control file or whatever? Anyway, presume it's fine to have 2199 samples (means the thinning was slightly different, or the burn-in is not what we say in the readme file). Just have to figure out exactly what was done.

Just mentioning so it gets clarified.

**Comment by aaronmberger** [comment]
Darn.  So it appears that I changed the starter file to "400 # MCeval burn interval" and "1 # MCeval thin interval" in the MCMC folder but the starter file in the model folder itself was left at 201 and 1, respectively.  Apparently when running -mceval it looks to the main model folder starter for these parameters (not mcmc folder starter file).

Here are my fixes given that we will want to stay consistent with our burn in period (and not halve it like I did):
 - re run mceval (quick)
 - re upload mcmc model files for 2019.03.00_base
 - unfortunately we will have to rebuild the base model RData file, redoing forecasts and extra mcmc :(
   So I'll rerun build(T,F,F,"2019.03.00_Base") -

**Comment by aaronmberger** [comment]
I mean build(T,F,T,"2019.03.00_base") b/c want to rebuild extra-mcmc for base only

**Comment by aaronmberger** [comment]
Okay, the new mcmc files are uploaded to the google drive and I am rebuilding my RData file for 2019.03.00_base using build(T,F,T,"2019.03.00_base").  This will take an hour or two.  

Check box when you've downloaded the new base model mcmc folder and rebuilt your RData file with the correct (or our standard) number of MCMC samples .

Download new mcmc folder from google drive:
- [ ] Aaron
- [ ] Kelli
- [ ] Chris
- [ ] Andy

Rebuild RData file for base model:
- [ ] Aaron
- [ ] Kelli
- [ ] Chris
- [ ] Andy

**Comment by kellijohnson** [comment]
@aaronmberger I have rebuilt all RData files ... can you click the box for me?

**Comment by kellijohnson** [comment]
@cgrandin I contacted github and they said that I cannot click because I don't have contribution rights to the repository ... can you add me?

**Comment by cgrandin** [comment]
Ahhh. Ok I added you as a collaborator. Sorry I didn't do that sooner.

**Comment by kellijohnson** [comment]
No worries, I can click now!

**Comment by aaronmberger** [comment]
Why make lists if you can't check things off - where's the satisfaction?  Glad it's resolved...

**Comment by andrew-edwards** [comment]
My build didn't work (the extra-mcmc folder was locked and didn't get overwritten). Fixed and re-running....
