### ISSUE TITLE
Forecast tables using 2018 catch (row d) uses old, incorrect, values

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#517]
Currently, the forecast tables that evaluate setting future catch at the 2018 catch level for 2019-2021 (row set d on forecast tables) uses an old catch amount (416,000).  It should be 410,000 (after rounding).  It's a small enough difference to not worry about now.  I'm just going to alter the caption for now.  I'll change it from "including catch from 2018" to "including catch similar to 2018".  If we have time further on down the road we can re-run forecasts.  Not worth it in my mind given only 5 days out.  This issue can remind us to fix this if time or later before the SRG meeting (or not at all this year - it's a super small difference).

**Comment by aaronmberger** [comment]
Okay, I'll update that file and commit it now.  Then we can run build(T,F,F) at the end of the day right?

**Comment by cgrandin** [comment]
You need to put the name of the model in or it will try to do them all. i.e. `build(T,F,F,"2019.03.00_base")`

**Comment by aaronmberger** [comment]
And just to remind us to do it!

 - [ ] Kelli
 - [ ] Aaron
 - [ ] Andy
 - [ ] Chris

**Comment by andrew-edwards** [comment]
Technically we should also rerun the fecundity sensitivities. We can just do the one(s) that we end up showing the results for in the Appendix. Easy to rerun (just leave overnight), but wait until we have to.

**Comment by andrew-edwards** [comment]
And maybe do #515 for the fecundity ones also, if we have to rerun. But wait for now.

**Comment by andrew-edwards** [comment]
Regarding my above comment - we had them correct for #515. I'll make a batch file to re-run the fecundiy runs for this issue.

**Comment by andrew-edwards** [comment]
So run the batch file in the above commit when you're done for the night - it will update the catch levels (and redo all the forecast calculations, hence do it when you're done). I haven't tested.

**Comment by andrew-edwards** [comment]
You also need to delete the old 04-416000 directories from each mcmc/forecasts/forecast-year-XXXX directory (one directory for each year) for each run from 52-58 (and base if you didn't re-run everything - I had to anyway).
build() hopefully then works. I'll try in the morning....

**Comment by aaronmberger** [comment]
Mine finished and the build looks good (upon quick scan).

**Comment by aaronmberger** [comment]
Ha!  The new base forecast with 410,000 catch (vs 416,000) catch didn't even change SSB decision table percentages - though it did slightly for fishing intensity.  Good to have the correct number either way.

**Comment by kellijohnson** [comment]
Sorry for my ignorance, but you mean decision table management action d should now be 410,000. I hope so because that is what I have.

**Comment by andrew-edwards** [comment]
We did originally have 416,000 in all the runs, but then the catch got updated when you guys came back (avoiding some double counting I think).

**Comment by aaronmberger** [comment]
Can we close this one (https://github.com/cgrandin/hake-assessment/issues/517#issuecomment-460334853)
Andy, I see you haven't checked the box yet, but I think you did as you wrote the batch file.
