### ISSUE TITLE
Monday tasks - who's doing what?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#518]
My plan for today is to:
1) Finish off first cut at research and data needs (I have an email out to survey folks about #3)
2) Look through wt-at-age and fecundity stuff (sections 2.3.1, 2.3.3, and 3.4.2) and respond to Andy's highlighted areas, etc.  Regarding section 3.4.2 - This could be broken up into information that goes into A) data, B) base model through bridging, C) response to SRG requests, and D) sensitivities. 
3) Then update text for 3.4.3 - assessment model results

Is anybody planning to continue to work on response to SRG requests (3.3) or sensitivity analysis (3.8)?

**Comment by kellijohnson** [comment]
- [ ] @kellijohnson == 3.3.5, 3.3.6, and 3.3.8.
- [ ] I think that 3.8 is done, except for Figures. @kellijohnson will double check this section.

**Comment by cgrandin** [comment]
Andy will be in around 10, I'll talk to him then and we will discuss doing the sensitivity sections.

**Comment by aaronmberger** [comment]
Seems like Kelli already has the sensitivity section done or mostly done.  Maybe the addition of the fecundity related sensitivities?

**Comment by kellijohnson** [comment]
I wasn't sure if the "fecundity sensitivities" were being included elsewhere?

**Comment by cgrandin** [comment]
I think they should be included in the same section, but we can add that part.

**Comment by aaronmberger** [comment]
Agree, I like the treatment of the fecundity runs as sensitivities, rather than put somewhere else and then possibly being interpreted as base model "alternatives"

**Comment by cgrandin** [comment]
We should use the MCMC outputs though, shouldn't we? I'm talking about the biomass/recruitment medians with credible intervals, etc. not the decision tables or projected advice. MCMC output is statistically "better" than MLE.

**Comment by aaronmberger** [comment]
But then why are we treating the fecundity sensitivities differently than the others.  We've never done that before, save for last years "alternative" model, though that was in an appendix.  I just don't want folks to grab on to those runs in particular, b/c they have a full MCMC associated with it, and think they should be treated any differently then a sensitivity.  Comparison to base model and other sensitivities is still valid using MLE.

My thought is that we would bring the MCMC runs with us to the SRG in case they do not like our reasoning for what we used during the pre-1975 and post-2018 periods and would like to see MCMC runs based on some different assumptions.  The SRG would have to have a solid reasoning to suggest a different base model and thus MCMC runs than the one we come with.

The one thing I can see happening, in particular, is the SRG wanting to see alternative decision tables to see how different forecasts would be under different post-2018 scenarios.  Then they would task us with that for overnight work - but we would already have that done and based on MCMC! 

One thing we could check is to see if the inference changes when comparing the base model to the alternative fecundities when using MLE versus MCMC.  My prediction is that the relative difference will be the same, but maybe not.  That would be one reason to add MCMC run sensitivities.  Just hope the SRG doesn't then suggest all sensitivities should be based on MCMC.

I'm not married to these points, just my personal opinion at this point.

**Comment by cgrandin** [comment]
Assigned homework that's already done is the best kind..

Your reasoning sounds good to me, I will go ahead and make "appendices" for the fecundity sensitivities which contain everything the the alternate base model contained last year, based on MCMC. We can just comment these out in the "distributed" version and make our own version with them included for showing later if necessary.

The sensitivity section in the main document will have MLEs for fecundity sensitivity, just like the rest.

**Comment by andrew-edwards** [comment]
How about we *temporarily* add the MCMC sensitivity fecundity figures (easy) for sensitivities (keeping the MLE ones) just to compare them for now and then decide. If we end up keeping the MCMC ones then we just say it's not practical to do MCMC for all other runs.

I think it is worth doing the decision tables etc. in an Appendix for model run 53 (easy), since

a) it is like last year's base model (but people are keen for time-varying sensitivity, so we've gone with that this year as it makes more sense).

b) it is the only other model that can properly include the 2018 weight-at-age data (see Table 33). This justifies not doing all the runs in appendices.

Just saw Chris's comment - actually, yes, make Appendices for other runs (which ones explicitly??) to take a look and then comment out. It's not much work to do that. My feeling for now is that we'd just want run 53 left in, but, yes, worth taking a look at the others (and have them built to show if people ask).

**Comment by aaronmberger** [comment]
That sounds like a good plan.  Kelli do you agree with this approach?

**Comment by kellijohnson** [comment]
I like having the MLEs in the document, to make them like other sensitivities, and then having the appendices commented out (eventually).

**Comment by aaronmberger** [comment]
53 for sure for Andy's reasons, but perhaps also 54 b/c the only difference there from the base model is how the forecast period is done (average over 2016-2018), especially for decision table values

**Comment by cgrandin** [comment]
I'll make identical appendices for all 7 of them, and we can pick and choose which we want to look at

**Comment by andrew-edwards** [comment]
I'm just getting caught up, and am in and out for the next little while. Will decide what to do later!

**Comment by andrew-edwards** [comment]
I'm done for the day - sorry, bunch of different things going on today. Can focus on it all day tomorrow and rest of the week....

Don't forget to do commit mentioned in #517 before calling it a day (I nearly did!).

**Comment by aaronmberger** [comment]
Are we done with this one?

**Comment by cgrandin** [comment]
I added all the figures and did the sensitivity section so yes. Closed.

**Comment by andrew-edwards** [comment]
Two unchecked checkboxes are done?

**Comment by kellijohnson** [comment]
Yes Sir!
