### ISSUE TITLE
Aaron broke US AP table 

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#519]
This table needs fixing as I changed the table structure in the .csv file to match what was sent (us-ap-catch.csv).  I figure that those AP report appendices should simply be what they send us (though I had to integrate 2 reports into 1 from what the US sent us ("thanks for that guys, we aren't already busy enough!")).  Sensei Chris the master table maker can probably do this in a minute or two, but I can get to it later if not beaten to it...  :)

**Comment by kellijohnson** [comment]
I already did it this morning, see 80d4a4b970cdbada92a67c96e3c9925473a7efc3.

**Comment by aaronmberger** [comment]
Sensei Kelli then... thanks!  Kelli, you can have the satisfaction of closing this one then.  And checking the box...  :)

This task was completed.
- [ ]

**Comment by aaronmberger** [comment]
darn, try again...
 - [ ] Kelli
