### ISSUE TITLE
smart.load not defined

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#52]
When starting fresh, smart.load is not defined and thus causes an error.  It is called here:

if(exists("models")){ ## Only ask if the models list exists
    smart.load <- readline(prompt = "   Use smart load (will only reload newly-added models, thus keeping any forecasting done previously)? [y/n] ")

and if "models" doesn't exist yet (as would be the case) smart.load doesn't get defined, but a logical statement is evaluated at the beginning of the load models sequence that uses smart.load.

if(reload.models == "y" | reload.models == "Y"){
  cat("\n\nLoading models...\n\n")
  if(!exists("models")){
    models <- NULL
  }
  if(smart.load == "y" | smart.load == "Y"){
    smart.load <- TRUE
  }else{
    smart.load <- FALSE
  }
.....

I can come up with some kludges, but I'll leave it up to Chris for a more elegant fix.  For current work around I just initially define it as "n" and go from there.

**Comment by allanhicks** [comment]
I just committed a simple fix, but I'll let Chris review.

**Comment by aaronmberger** [comment]
Okay, chris close please upon review

**Comment by cgrandin** [comment]
If it is working for you, that's great - I will fix it up better once I turn my computer back on.
