### ISSUE TITLE
Table 16 - Maturity and Fecundity needs updating

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#521]
We should change the columns to:
Age
Number of Samples
Maturity ogive
Mean weight
Mean Fecundity

And then note in the caption that weight and fecundity are year-specific from 1975 - 2018.

**Comment by kellijohnson** [comment]
Fixed with 5e5e64a695783d9eb5443134c88d6ac03f04cea3

**Comment by kellijohnson** [comment]
Figure 12 has the "Old" and "New" fecundity relationship as well. Can I change the code to only have the new relationship. I did findstr to search for "new fecundity" in the text and I couldn't find anywhere that phrase was used, so I am assuming the change would be fine.

**Comment by cgrandin** [comment]
Good idea Kelli, it's in R/figures-maturity-ogive.R

**Comment by aaronmberger** [comment]
agree, we don't need the 'old' any longer

**Comment by kellijohnson** [comment]
Am I correct in assuming that the maturity-at-age in the weight-at-age file is only calculated using fecundity samples "North of 34.44"?

**Comment by cgrandin** [comment]
@kellijohnson Yes

**Comment by kellijohnson** [comment]
Great. I got this all fixed and will close once I am sure it builds.
