### ISSUE TITLE
median posterior estimates - not matching?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#522]
why does table 18 indicate relative spawning biomass in 2019 is 64.1%;  Table 26 says 51.4%; Figure 31 looks to be the 64%.  Need to look into this.

**Comment by cgrandin** [comment]
I'll look into this in the morning. I am running the forecasting again with the proper catch of 410000 as fixed in forecast-catch-levels.R as I leave the office...

**Comment by aaronmberger** [comment]
What?  We missed something last year - unheard of...   ;)

**Comment by cgrandin** [comment]
There was also a hardwired value for last year's q median which I fixed. It was mentioned elsewhere but I cannot find it.

**Comment by kellijohnson** [comment]
#451
