### ISSUE TITLE
Explore forecast year biological inputs via Stock Synthesis version 3.30.12

### ISSUE THREAD

**Issue by aaronmberger-nwfsc** [cgrandin/hake-assessment#523]
This is related to setting wt-at-age and fecundity-at-age during the forecast period that is independent from the empirical data period (i.e., do not have to loss the most recent year of empirical data to include an X year recent average, for example).  Flagging this for 2020...

**Comment by andrew-edwards** [comment]
2020 ones will get reopened later.... ;)
