### ISSUE TITLE
Extra page b/t Table 21 and 22

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#527]
Adding row for 2019 may have pushed this table to be too large.   Just flagging this to remember to fix.

**Comment by andrew-edwards** [comment]
Saw that - I can try now just to get it done before lunch....

**Comment by andrew-edwards** [comment]
Foolish me for thinking it'd be a quick fix. Not succeeded yet. Will chat with Chris at some point, but we'll get it done......

**Comment by andrew-edwards** [comment]
I tried commenting out the \clearpage, adding one in beforehand, and messing with the margins. Alas...
Table 22 doesn't add a page but is very similar (has longer caption).

**Comment by cgrandin** [comment]
Getting a lot of entries in those tables, needed to make the font smaller to fit it on the page.
