### ISSUE TITLE
Spell check assessment before submission

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#537]

**Comment by cgrandin** [comment]
Just write notes here on what you've spell-checked

**Comment by andrew-edwards** [comment]
I can do it - ispell the whole hake-assessment.tex file then edit the .rnw's. Will try today, and then again on Friday...

**Comment by andrew-edwards** [comment]
Will also fix any ordering issues in the Exec Summary (sometimes has to be done manually to keep tables and figures sensibly together). Not until Friday though.

**Comment by cgrandin** [comment]
Spell checked:

- [x] executive-summary.rnw - Chris, thursday @ 1PM
- [x] assessment-section.rnw - Chris, thursday @ 1PM
- [x] introduction-section.rnw - Chris, thursday @ 1PM
- [x] data.rnw - Chris, thursday @ Noon
- [ ] main-figures.rnw
- [ ] main-tables.rnw
- [ ] one-page-summary.rnw
- [ ] research.rnw
- [x] acknowledgements-section.rnw - Chris, thursday @ 1PM

**Comment by andrew-edwards** [comment]
Thanks Chris, and I did one earlier in the week, so we should be good....
