### ISSUE TITLE
Clean up layout of Exec Summary

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#54]
There's a lot of whitespace in Exec Summary, which I can tidy up by letting Latex float the figures and tables. I know Chris fixed them with H (which is great in main-figures), but Latex should do a better job. 

How about I try from 9-10am Saturday morning (and no-one else messes with Exec Summary to avoid any conflicts)? If it messes up I can just not commit my changes. It will look a lot better, and reduce the impact of Chris's issue (which I can't quite fix) of hyperrefs inthe pdf in the Exec Summary linking to the main figures/tables rather than the Exec Summary one. I think the main text ones are still good.

**Comment by allan-hicks** [comment]
Sounds good to me. I'm concentrating on the tables to make sure they are
complete and correct.

**Comment by andrew-edwards** [comment]
I'm printing (eventually) the Exec Summary, will read and then try moving figures. I need to leave by 11:30, so will commit by then. Back later....

**Comment by andrew-edwards** [comment]
Okay, I haven't done this yet. Have some minor edits and was playing with fonts. Won't commit. Will be back around 1:30-2.

**Comment by allan-hicks** [comment]
I'm working on tables

**Comment by cgrandin** [comment]
I have table 5 nearly done, hope you didn't start that one..

**Comment by cgrandin** [comment]
That's the fishery sampling history one

**Comment by allan-hicks** [comment]
Crap, just finished it

**Comment by cgrandin** [comment]
Really, you did the whole xtable code and everything?

**Comment by allan-hicks** [comment]
Just committed it

**Comment by allanhicks** [comment]
But I haven't seen if it works because there is wierd stuff going on with
the Rdata files. I have to completely clear my workspace for it to
recognize the new variables in all.r.

I've almost got it compiled

**Comment by allanhicks** [comment]
It could also have been that it created the table in knitr-cache with the
error, but I didn't clear the cache.  I was really confused last night
because I moved to a new computer, but didn't clear the cache, and was
seeing last year's model results! I learned to clear the cache

**Comment by cgrandin** [comment]
Yes, and you can just delete the files for the table you are working on. That way, it doesn't rebuild all of them, just the one you are on.
The table code you pushed will give you a simple table but no vertical lines, etc. I have done all of that using tabularx environment, so we can use mine if you're ok with that.

**Comment by andrew-edwards** [comment]
Closing this (and it got a bit off topic!). I may have to tweak again if we keep the new font, but I've put that in a new issue.
