### ISSUE TITLE
When clearing knitr-cache and knit("..."), first latex run fails; but knit again and good

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#544]
@cgrandin - we can chat tomorrow (or next week). Basically one of the retro .Rdb files gets corrupted and no figures get created, but then knit again and they all get built. 

NOT a huge deal as it works out okay, just worth understanding at some point...

**Comment by aaronmberger** [comment]
Now that everything is done except maybe some text edits.  I'll probably delete all RData files and clean my knitr-cache too (using freshtex.bat) just to make sure.  Or would you not worry about RData files as we all just had similar documents yesterday.

**Comment by andrew-edwards** [comment]
I wouldn't worry about .RData as we haven't changed any model runs or catch levels etc., and had matching results yesterday.

knitr-cache for sure (and close R if you haven't for a while as it will remember stuff).

But we all have it working. 



I deleted my knitr-cache because the caption didn't seem to update (even though it should as knitr detects changes), but it was because I put the change in the wrong place. (Fixed and pushed)...

knitr is clever and only remakes chunks if the text within them has changed, but it won't detect if a function definition (called from a chunk) has changed. Hence good to delete every so often (as Chris does...).

**Comment by aaronmberger** [comment]
all worked for me, if okay with Chris and Kelli we can close this one

**Comment by andrew-edwards** [comment]
I think the knitr-cache doesn't properly get deleted if one of the .Rdb files is open in R as it's locked.

Just testing - damn, still get error. Will manually fix now and figure out one day....

**Comment by andrew-edwards** [comment]
Fixed by deleting knitr-cache, restarting R (this is the key), then knit again. Explains why Chris (and others) don't get the error because I think he uses a batch file.

**Comment by andrew-edwards** [comment]
Fixed this, see above commit. (Aaron, I just run `knit("hake-assessment.rnw")` in R (not `build()` or anything), but without restarting R - so the lazy-loading of .Rdb files gets messed up somehow). 

Anyway, I know some people frown upon `rm(list=ls())` at the start of files, so if it messes anyone up then just revert. (If you have any specific settings for when you load up R then it might mess them up, but I think you should all be good). Okay, I'm off now to play in the snow....
