### ISSUE TITLE
Fix figures/tables in Exec summary if any get moved around (on Friday)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#546]
They were good this afternoon on my printout, but I think something just moved. I can do. (Basically want to keep certain figs and tables together, but sometimes we over-ride the latex defaults to finalise it - but if things change then it needs tweaking).

**Comment by aaronmberger** [comment]
I liked all you text changes to the one-page and executive summaries.  I'm good to go there, so feel free to make any needed final figure/table location changes.

**Comment by cgrandin** [comment]
I just un-hardwired the last bits in the on-page summary. This is the last issue so I'm going to read through and look for anything weird
