### ISSUE TITLE
Cohort calculations - don't merge yet (I think)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#549]
Chris was automating lots of these, so maybe Aaron and Kelli don't merge his in yet until he's done. I think you'll get conflicts. He can fix it. I'll check if he's in....

**Comment by aaronmberger** [comment]
In one area, or for the whole document?  Cause I think Kelli just found an error in 2.1.2 where comp numbers in text don't match numbers in table.  She found (sorry Kelli for stealing your thunder!) that the numbers in the text come from base.model$catage and the table comes from base.model$agecomp

**Comment by aaronmberger** [comment]
I'm guessing that the base.model$agecomp is data and the base.model$catage is predictions.... but checking on that

**Comment by andrew-edwards** [comment]
I was wrong about what Chris was automating. He merged and had no conflicts. Leave this open so you can figure out Kelli's spot....

**Comment by cgrandin** [comment]
The cohortCatch() function in utilities.R and top.coh() in custom-knitr-veriables.R both use catage. Those are what are used in all the text when referring to how much of a cohort was caught in a given year (top.coh) or total caught in lifetime of a cohort (cohortCatch)

**Comment by kellijohnson** [comment]
In 2.1.2 numbers derived from top.coh used and then at the end of the sentence it gives reference to Table 11 which is derived from base.model$agecomp, the numbers for 2018 do not match when referring to the 2010 cohort.

**Comment by cgrandin** [comment]
I am looking

**Comment by cgrandin** [comment]
In 2.1.2 the first thing it says in the paragraph we are looking at is "The aggregate fishery age-composition data..."

Table 11 is based on weighted age-composition data and catage is the catch estimates. I think the text in 2.1.2 should match table 11 since it refers directly to it.

Since I just wrote the function yesterday, I can tackle this if you agree. Good find Kelli - thanks

**Comment by aaronmberger** [comment]
I was just looking at that too - you are right Chris.  Please go ahead and fix.  Maybe you want to keep that function in case we want to use estimated comps, and then just make another for data comps (using base.model$dat$agecomp

**Comment by andrew-edwards** [comment]
I'm not following this, but the numbers on p33 don't match Table 11. Specifically, final three sentences of top paragraph,  the 5% and 27% and 26%. The code is
```
In \Sexpr{last.data.yr - 1}, \Sexpr{top.coh(last.data.yr - 1, 3)}.
In \Sexpr{last.data.yr}, \Sexpr{top.coh(last.data.yr, 3)}.
See Table~\ref{tab:main-all-age-data-fishery}.
```
Think it's related to what you're looking at.

Also, a bit of context is needed because the previous sentences talk about catches in the fleets, so it's not clear what's being referred to here. (and uncapitalise 'The'). :)

**Comment by cgrandin** [comment]
Ok it's done. The argument `use.catage` allows us to still use the estimates with the same function. The figure , table, and text are all now using `model$dat$agecomp`

**Comment by cgrandin** [comment]
Andy the top.coh() functioni has a `cap` argument which allows de-capitalization of "The". I fixed the ones you were looking at but for future knowledge.

**Comment by andrew-edwards** [comment]
@cgrandin  - can you just clarify what that sentence refers to. A bit of context is needed because the previous sentences talk about catches in the fleets, so it's not clear what's being referred to here.

**Comment by andrew-edwards** [comment]
And move reference to Table 11 a bit earlier, rather than at end of paragraph :)

**Comment by aaronmberger** [comment]
I think the numbers are good now and refer to aggregated age comp data related to fishery catch.  Previously, it was from estimated catch at age matrix.

**Comment by andrew-edwards** [comment]
Chris is adding something (it's just not clear when you read the whole paragraph).
