### ISSUE TITLE
Run 53 isn't actually the Base 2018 model

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#550]
The summary Table 37 (I'll fix the 'models' typo in the caption) points out that Run 53 isn't the Base.

But legends (and some text I think, plus Table 34 column header [which looks a bit funny) do say 'Run 53 - Base model'. I think it needs clarifying.

Either (I'll give two options, vote thumbs up for what you think):

**Comment by andrew-edwards** [comment]
1. Edit the name to just say Run 53 (consistent with others, plus I'm expecting people to have to refer to the table a lot - I can print a copy out for the meeting).

**Comment by andrew-edwards** [comment]
2. Add a caveat in the Table caption and text, pointing out that it's not quite the same but for brevity we call it that.

**Comment by andrew-edwards** [comment]
When doing this, add in legends for for Figures 63 and 64.

**Comment by aaronmberger** [comment]
Yep, #1 seems good.  The best we can do is say run 58 (right?) has the same structure as the 2018 base model (but with updated data - so forecast period is slightly different because of averaging last three years).  Is that a correct interpretation from Table 37?

**Comment by andrew-edwards** [comment]
Okay - I'll edit the text (have a few minor tweaks for it).

**Comment by cgrandin** [comment]
Just change this line in `model-setup.R`:

```
sens.model.names.5 <- c("Run 52",
                        "Run 53 - Base 2018",
                        "Run 54")

```

To say whatever

**Comment by andrew-edwards** [comment]
I have a conference call I need to sit in on, but I'll try and keep typing up edits.

Chris - can you make the change (everyone remember to then delete knitr-cache).
