### ISSUE TITLE
In assessment presentation, where does this number come from?

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#557]
The 2014 cohort is estimated to be large -- only 5% chance of being larger than 2010.

Where did you find the 5% probability? I want to generalize it in the presentation code.

Thanks

**Comment by aaronmberger** [comment]
In executive summary there is this:

\Sexpr{prob.percent.2014.rec.gt.2010.rec}\%

**Comment by aaronmberger** [comment]
should be 3% this year

**Comment by cgrandin** [comment]
Awesome thanks
