### ISSUE TITLE
Wt-at-age / Fecundity - what's going where

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#560]
My first thought was to have different parts of this in the relevant sections including:

Data section: mention updates to wt-at-age data (historic update and addition of 2018 data); mention that pre-1975 weights are not applicable to this assessment (from Puget Sound);

Assessment section: what we did including t.v. fecundity from 1975-2018; mean wt-at-age for pre-1975 and forecast period; brief overview of response to SRG request related to wt-at-age; mention sensitivities done and coming in that talk

Sensitivity section: go over all the alternatives

The question that remains is then where do we put Figure 15 and related comments. I thought in the assessment presentation either while introducing the base model or during the response to SRG section to explain why the base model is configured the way it is.

Thoughts?

**Comment by andrew-edwards** [comment]
Agree with all that. 

Figure 15 (and 14?) probably in response to SRG section. Then get into all the alternatives in the senstivity talk.

**Comment by cgrandin** [comment]
Figs 14 and 15 are in the response to SRG section, and I think they belong there.

**Comment by andrew-edwards** [comment]
Think this is all done, so closing....
