### ISSUE TITLE
Empty subsections

### ISSUE THREAD

**Issue by kellijohnson** [cgrandin/hake-assessment#563]
Empty calls to \subsection{} make the bookmarks without a title. Not a big deal, but I didn't want to remove them if @cgrandin had them for a reason.

https://github.com/cgrandin/hake-assessment/blob/096dd733cae8ba32324c45af0d66d433256311f6/beamer/SRG/Assessment/beamer-hake-assessment.rnw#L118

**Comment by andrew-edwards** [comment]
Do they affect the little dots at the top?

**Comment by andrew-edwards** [comment]
Bit like (fake) bookmarks for a Table of Contents.

**Comment by kellijohnson** [comment]
Ha ha. I thought the same thing and rebuilt without the empty calls and you still get the same number of dots. The number of dots is dependent on the number of slides for each section.

**Comment by andrew-edwards** [comment]
Hmm.... in that case they may not be needed....

**Comment by cgrandin** [comment]
I didn't have them there for any reason! Thanks

**Comment by andrew-edwards** [comment]
Guessing that we copied an example one the first time we made the talks, and never dug into exactly what everything does (given the usual time crunches!).....

Feel free to take them out (at your peril, ha ha). Actually, if you do them in one commit then they can easily be put back in with a git revert if we do notice any problems.....
