### ISSUE TITLE
How do we have relative fishing intensity for same year

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#567]
Example - 2018 relative fishing intensity has value for "Posterior from 2018 base model." This is likely a bug in table code. Setting up as new issue because I want to keep seperate from the other list of assessment presentation issues.

![image](https://user-images.githubusercontent.com/4551051/52879659-90cd6e80-3114-11e9-84ea-5dc37589e8cf.png)

**Comment by andrew-edwards** [comment]
Good spot - the same table in 2018 assessment also (incorrectly) has a number in the same spot (as you'd expect, given it's the same code).

Happy digging....

**Comment by cgrandin** [comment]
Actually Aaron spotted it so kudos goes to him :1st_place_medal:

**Comment by cgrandin** [comment]
Well that was easy

**Comment by andrew-edwards** [comment]
Jaclyn spotted this also - just going over a couple of clarification questions she sent me yesterday.

Good to know people are reading it carefully!
