### ISSUE TITLE
Shouldn't the historical assessment plot show 2019 biomass from 2019 assessment?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#568]
I know it wouldn't be compared to anything else, but it would probably be helpful (to show here if it's vastly different to 2018). 

Think just involves adding an empty column (and NA for 2019 assessment) to assessment-history.csv?

**Comment by aaronmberger** [comment]
Yes, the 2018 assessment had it go until 2018, but I see in Figure 72 it only goes to 2018 (not 2019) as you say Andy.  Good catch.
