### ISSUE TITLE
Look at Trevor's comments before SRG and incorporate edits in final assessment document

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#569]
Note received from Trevor:
[Mostly you can ignore the more substantive comments at the start
(since some of these will disappear or be clarified), but I leave them
in so you are aware of the kinds of thoughts I may bring up in
discussion during the review.

The minor ones are typos that should probably be fixed before the
assessment is finalized.]

The word document he sent is attached here.
[Comments on hake assessment.docx](https://github.com/cgrandin/hake-assessment/files/2871336/Comments.on.hake.assessment.docx)

**Comment by kellijohnson** [comment]
Responses to minor comments
 - fixed grammar comments
 - Don't agree with comment about R packages -- too many are used to cite all of them, I think we should only cite those that are offer a major addition for a certain year, e.g., if we used C. Stawitz's growth package next year.
 - Not sure what to think about MLE comment
 - I do not think the structure of the document should be changed, keep status quo to reduce confusion
 - Figure 8 - maybe just track major cohorts with color, or do we do a gradient, which I think might just be distracting

**Comment by aaronmberger** [comment]
Regarding MLE comment: he is technically correct that it is the 'mode of the posterior density' or sometimes called 'highest posterior density' estimate.  I really don't want to change our language throughout the document to this obscure language that only statisticians would recognize.   A compromise would be that upon first use of MLE we mention that these estimates are technically the mode of the posterior distribution because prior distributions are part of the objective function, but for simplicity we refer to these estimates as MLE throughout this document.  Or something like that....?

Regarding Figure 8 - we do add lines for major cohorts in our presentation.  I think the cohorts really standout, colors would just beatify the figure not add much understanding, in my opinion.  But Trevor is the figure guy...

**Comment by aaronmberger** [comment]
Any thoughts on Trevor's comment 9:

9.	The analysis on p. 47 (Figure 15) looking at trends over time in weights for each age, produces some odd results, with the red fitted line not appearing by eye to be a good fit to the data. e.g. age two data looks to be increasing but slope is negative, while ages 10-15 look to have negative slopes but slopes are estimated to be positive for some. In the explanation it says weights were inverse of the variance, but should be inverse of standard errors, i.e. SD/sqrt(n) to take into account sample sizes. Variances, of course, do not change as sample sizes go up, they just get more precise. In all of the older ages the fitted line is under the data for years 1975-1983 or so. I support the idea of running MSE on scenarios with fixed or declining weight at age over time.

I don't follow: "Variances, of course, do not change as sample sizes go up, they just get more precise."
I'm guessing this is population variance versus sample variance, where population variance doesn't change but sampling variance can get more precise with increasing sample size. I think it might just be a wording issue.  In this analysis, it is the sampling variance (variance associated with the samples) that is used.  Under assumptions of independent, normally distributed residuals, weighting at 1/variance corresponds to a maximum likelihood estimator for the model.  And this type of weighting can help with heteroscedasticity. 

Clearly, it's a simple procedure to answer one question about the time series.  Lot's of other options.

I also don't think the results are "odd", given the weighting procedure.  The only odd thing is that it remains clear that the average weight is higher in those early years, but that's just the data.  The odd thing to me is that with such high sample sizes during those early years, we don't see any sort of cohort effect as we see throughout the post-1980 or so period (see attached sample size figure, where colors correspond to sample sizes not the underlying wt-at-age like our Figure 14).
![empirical_wtatage_2018_alldata_numbers_color](https://user-images.githubusercontent.com/7946234/52902629-63da9380-31c8-11e9-8573-d238994111cf.png)

**Comment by cgrandin** [comment]
I have code (from Sean Anderson) to produce a colophon for things like the R packages and versions automatically. If we run out of things to do I can add this if we all think it would be beneficial.

**Comment by andrew-edwards** [comment]
Thanks for looking into these. I think any big changes like moving sections around should be discussed at the meeting (structure hasn't changed much, and people generally haven't wanted anything changed - consistency makes it easier to compare documents from year to year).

I noticed some figures/tables were out of order, but, hey, we only had a week! In particular Kelli's new table should come earlier, but I didn't want to start moving things.

MLE - yes, mention once (and change next year if necessary). I can mention in my talk if no-one has beforehand.

Agree there should be a consistent system for submitting comments to JTC. Partly so one of us sees the email and posts it on GitHub - I don't check my email too much during hake assessment (and nor does Chris).

He mentioned page breaks - we deal with that for the final version (and I think we've gone through this before - starting Assessment section on new page breaks it up a bit).

Anyway, some good stuff to bring up at the meeting.

**Comment by kellijohnson** [comment]
Figures and Tables are now in the "correct" order. Can we close this?
