### ISSUE TITLE
Make the models list its own rdata file

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#57]
Everytime I save.image() after I change the R code a little, it takes about a minute for the thing to save. If the models list had it's own file, this would take only a second.

**Comment by cgrandin** [comment]
I'm going to leave this until the document has been submitted as it will most likely impede our progress.

**Comment by andrew-edwards** [comment]
Sounds good. Hopefully we should soon just be onto editing text in .rnw files, not anything that gets called by all.r. Hopefully.

**Comment by cgrandin** [comment]
I think we're pretty close to that now

**Comment by taylori** [comment]
This seems like a good idea (at least for next year). Would there be any value in augmenting the SS_output function in r4ss so to optionally write an .Rdata file containing the list it creates? The challenge would be keeping track of model names vs. filenames of the multiple Rdata files.
