### ISSUE TITLE
incorrect label on time series/histogram figure

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#572]
From Julia (NWFSC):

[I don't know if you recall, but last year there was a typo on the time series/histogram figure for the 1998 year class (labeled as 1999). I believe someone corrected it on your end, but I see the error carried through to this year. I've attached the correct figure to this email.]

**Comment by andrew-edwards** [comment]
I was sure we fixed that last year, but it says 1999 in last year's assessment. Let's share the file through Google Drive rather than GitHub, if you can upload it Aaron, thanks.

**Comment by aaronmberger** [comment]
I just pasted her comment in without looking at it until now.  I guess I don't see the problem.  The figure is supposed to highlight the 1999 year class.  We are highlighting the 1999 year class not the 1998 survey year.  I think it is correct as is.

**Comment by andrew-edwards** [comment]
Yes, you're right. 1999 is the big cohort. It is correct (but wasn't at some point last year, hence the possible confusion).
