### ISSUE TITLE
Maturity figure (Fig 12) has old mean weight on panel

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#573]
Jaclyn says that the mean weight is not representing this year's values. Double-check

**Comment by kellijohnson** [comment]
My mistake, I fixed the figure for this year and I just calculated a mean, so it is not a weighted mean.

**Comment by kellijohnson** [comment]
I get the weight at age values from the model rather than having them hard-wired. From the base model we could just grab the -1940 values because aren't those the mean?

**Comment by kellijohnson** [comment]
There is already an argument that specifies which years you want to use. We just have to give it a valid value or range, where 1966 to 2018 are currently valid. Right now, the 1966 is the mean, so it works, but I don't know how to make this where it will always be the weighted mean.

**Comment by andrew-edwards** [comment]
I also made some notes last night and will update the caption.

**Comment by kellijohnson** [comment]
The plot is fixed with 56b54a105deeabdedb97091186928ae13be490a4
