### ISSUE TITLE
SRG requests (from John, from SRG as a group)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#576]
SRG Requests to the JTC – Day 1 (Feb 19, 2019)
1.	Please include a catch stream level of 500,000 t in the forecast tables of relative spawning biomass at the beginning of the year and fishing intensity and the risk tables showing probabilities related to spawning biomass, relative fishing intensity, and the 2020 default harvest policy catch for alternative 2019 catch options and 2020 catch options. See Issue #574

2.	Think about utility of Age-1 index in context of MSE based on previous presentation in 2016 from Alan Hicks. How can this work be carried forward in the context of the improved MSE to stabilize our estimates of recruitment. Does an age-1 index provide value to the assessment? Under what circumstances, if any, does an age-1 index help? This is a longer-term request

**Comment by cgrandin** [comment]
Take a look at c23bee8c1266dd6a1330c63065d9ac4cea4f615c and ced9cdfe2051e6ea11346591c45a3e4e4798ef20 as a step toward understanding uncertainty with age-2 cohorts in the retrospectives. Trevor asked for this.
