### ISSUE TITLE
Saturday - who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#58]
Andy - Executive Summary, re-placement of tables and figures to reduce whitespace and improve readability. So if no-one else touches it that would be great, since stuff will get moved around a bit.

**Comment by andrew-edwards** [comment]
Chris has been in all day and has now left - he'll probably check the Network Graph at home on his phone to make sure that we're working ....

**Comment by cgrandin** [comment]
Haha just to keep up on what's happening

**Comment by allanhicks** [comment]
I'll be back on tables and figures tonight with the goal of completing
those sections. That shouldn't mess too much with exec summary.

**Comment by andrew-edwards** [comment]
Andy done with Exec Summary for tonight. My earlier commits should show the minor text changes I made, later ones involved rearranging of order of tables and figures.

**Comment by andrew-edwards** [comment]
I'm done for the night, though I may check in later to make sure my changes didn't screw everyone up..... Back tomorrow. I have a few more minor edits to improve understanding, and will look into fonts. Again.

**Comment by aaronmberger** [comment]
Okay, I guess I'll continue moving through the assessment section updating text and output references.

**Comment by andrew-edwards** [comment]
Sounds good. And it looks like you merged my stuff okay and so I assume it's still working good for you.

**Comment by aaronmberger** [comment]
likety-split, if that's even a saying
