### ISSUE TITLE
Agenda for JTC working meeting

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#589]
Okay, 'Agenda' is a bit formal! Things off the top of my head that we should go over tomorrow (order is random for now):
- [x] each person show their workflow on their computer so we all understand (i.e., how editing code/files and running R, SS3, latex, git and GitHub)
- [x] go through open issues and assign them
- [x] go through last year's SRG requests and discuss
- [x] go through talks for for Wednesday's JTC meeting
- [x] deadlines for getting final data

**Comment by aaronmberger-nwfsc** [comment]
Sounds good Andy; except Kelli and I will have to verbally describe our workflow - we both have 'travel' laptops (i.e., no access to our normally work tools) as our center is cracking down on international IT asset use.  We can chat more about this tomorrow.
