### ISSUE TITLE
Monday morning - double-check we all have the same numbers

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#60]
Maybe Monday morning we should all make a .pdf from the same commit, upload to Google Drive, and   double check that we all have the same results. To ensure that we're all using the same sets of results etc. I'm pretty sure we are, but would like to be sure so we don't have identical documents except for different results.

**Comment by allan-hicks** [comment]
Good idea. How about we compare the sensitivity table and the 2015 spawning
biomass a depletion for the base model. We can throw in teh retros to make
it complete, if desired.

**Comment by aaronmberger** [comment]
Agree.  But wondering who's working on the automation (analysis/document/presentation) for responses to SRG?

**Comment by andrew-edwards** [comment]
Allan - not sure what you mean about 'throw in the retros'. Isn't everything in there? Oh, I think you mean compare the retros (as well as other parts)? We should be able to easily compare the .pdf's (by flicking back and forth between two open versions in full-page view it's pretty easy to spot errors, as everything should be formatted the same). Would only take a few minutes to compare the whole document - I can do it if everyone uploads on Monday morning.
Presentation can probably be done in beamer easily enough. I haven't used it but the tables and figures are all made. Not worrying about that yet though....

**Comment by allanhicks** [comment]
Sounds good. I have been thinking of the presentations and the figures.
Even though I have used beamer in the past, I find that I can put a
presentation together a lot faster in powerpoint, and we'll be rushing to
put figures together before and during the SRG.  But, something to think
about after Monday.

**Comment by cgrandin** [comment]
This sounds great, and to do it in the most efficient way, why don't we put all our hake-assessment.tex files on the Google drive and then we can run diff on them. This will show us every difference and save a bunch of time.

**Comment by andrew-edwards** [comment]
Good idea, since a diff on the .tex files will run quickly, and show up any differences in Tables. Won't show up differences in Figures, but if the Tables are the same (and all automated numbers in text), then seems that the Figures will likely be the same. But we can still check the .pdfs after to be sure.

**Comment by cgrandin** [comment]
I'm now in the office for a couple hours. Going to read as much as possible and address issues then head out.

**Comment by aaronmberger** [comment]
I'm working through assessment section - mgmt performance, then model uncertainty, ref points, projections.... reading through and filling in as needed.  Only adding minor additions of text as needed, mostly filling in blanks and checking table/figures.  

I plan to work until 1 or 2, then take a 'super' break and continue on later this evening...

**Comment by aaronmberger** [comment]
What time should we all build and then compare?  Chris, do you want to specify a cut-off time, then we can merge and build, then send you the .tex file???

**Comment by cgrandin** [comment]
I'd like a bit to finish the executive summary tables, let's say around 11 o'clock we get ready to compare. Hopefully I am done by then.

**Comment by andrew-edwards** [comment]
Okay - 11am. I've committed and merged Allan and Aaron. If you guys have any more edits then commit and push them now; Chris is doing one now. Chris and I will merge ours, then you can merge from us. Probably need source("all.r") again as some table stuff happened I think. 
Then upload your hake-assessment.tex file to Google Drive (in the  Write Up folder I guess), and hake-assessment.pdf (appending your name to the filename), and we'll do a compare.

**Comment by allan-hicks** [comment]
Wow, your emails from over an hour ago are just coming through.

**Comment by cgrandin** [comment]
Yes, we have been crippled all day. Ottawa just finished their day so now we get internet again. Really makes it hard to do the job
