### ISSUE TITLE
Figure 16 and 17 top right panel...?

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#61]
MCMC diagnostic plots - panel top right is empty for both figure 16 and 17

**Comment by cgrandin** [comment]
Turns out we needed the gtools package which has the 'running' function which mcmc.out requires. Fixed.

**Comment by cgrandin** [comment]
This may not be fixable. When I make the plot in Rgui, it looks perfect. Something happens when cairo_ps saves the eps file that doesn't record those lines. Not sure what to do here - looking for suggestions.

**Comment by allanhicks** [comment]
Which lines are you referring to? The plot I have in my build from a few
minutes ago shows everything I expect.

**Comment by aaronmberger** [comment]
Mine looks good too

**Comment by cgrandin** [comment]
The upper right panel, moving average plot on figs 16 and 17. Neither Andy nor I have anything in the plot.

**Comment by andrew-edwards** [comment]
Mine are missing too. It's the two top-right panels in each of what are now Figures 15 and 16. The trace plots (top-left panels) are fine, but the top-right (running means??) are empty. I just re-did all.r (but didn't reload anything) and they're still there. I'll do a complete rebuild from scratch (reloading everything) just in case that fixes it. Am printing whole thing out to have a read....

**Comment by andrew-edwards** [comment]
Just reloaded all models etc. from scratch - panels are still empty. I did Allan's upgrade the other day (r4ss from github??).

**Comment by cgrandin** [comment]
Go into your R session, do a source("all.r") then these:

cairo_ps("test.eps")
make.mcmc.diag.plot(base.model, subplot = 2)
dev.off()

Take a look at the file and the plot seems fine. But when knitr does it that upper panel fails to be drawn. Hmmm.

**Comment by cgrandin** [comment]
Fixed it. I feel silly now. You have to have all the packages you are using in the first code chunk of hake-assessment.rnw as well as in the R code. If found this by building the whole think with full warnings and messages written to the pdf. You can do this by uncommenting the call to opts_chunk$set in the initial knitr code chunk, and commenting the 'clean' one. I saw that it wasn't able to do it (function 'running' was not found) and remembered that the gtools package supplied this, so connected the dots. Anyway, a lot of investigation for a simple require(gtools) call..
Closing...

**Comment by andrew-edwards** [comment]
Yes, get the same. Are you sure the gtools thing is actually needed? It seemed to break after that (or did it never work, I hadn't really looked?). There's a function  "running" that sounds like itmight get easily defined a few times. But then why would it work in the console but not knitr. 
Quick fix - oh, you've just done it....

**Comment by allan-hicks** [comment]
It ust have been that Aaron and I already had gtools loaded?

**Comment by cgrandin** [comment]
I think what happened is that I copied the source for 'running' function into utilities.r as some point, and committed it. Then, I deleted it when I put in the require(gtools). I bet you were building on an earlier version which had the running function in it. My best guess anyway.
