### ISSUE TITLE
Italics in Table 20

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#62]
How can we make certain cells in italics?

**Comment by andrew-edwards** [comment]
I saw one of the captions mentioned italics, so maybe it's already done in a table? Unless it's the caption for the table you're working on ;)  xtable() is a bit trick to format certain cells, but I think Chris has done it somewhere. Chris or I can take a look tomorrow - let us know which cells in which table.  
If you add \emph{..} anywhere you may need to make it \\emph{..}

**Comment by cgrandin** [comment]
Yes it's easy, you need double backslashes before the emph in the tables-xxx.r code. I can do it if you let me know which ones.
