### ISSUE TITLE
Sunday - who's working on what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#69]
Andy - will merge all Chris's then check all last night's commits, then take a read. May look into new fonts.

Aaron (Andy copying this from other issue): I'm working through assessment section - mgmt performance, then model uncertainty, ref points, projections.... reading through and filling in as needed. Only adding minor additions of text as needed, mostly filling in blanks and checking table/figures. I plan to work until 1 or 2, then take a 'super' break and continue on later this evening...

Chris - reading and addressing issues.

Sounds like we may start editing similar minor things, so commit and push often, even for minor edits (as Aaron has been doing this morning it looks like).

**Comment by allanhicks** [comment]
I am loking through figures to make sure they are all there (will fix matuirty one and write text for it) and they look correct.  Then I'll read through the assessment section tonight and give the document a complete look.  I won't start on the assessment section until later, so hopefully won't duplicate too much.

Thanks everyone!

**Comment by andrew-edwards** [comment]
Allan, I think some of the main figures were not referenced in the text. So we should keep an eye out for that. 
Looks like a lot of things are getting cleaned up. I've merged everyone's and just made some minor edits, but it's coming together nicely.

**Comment by allan-hicks** [comment]
Yep, I'll keep an eye on references when I read through it.

**Comment by andrew-edwards** [comment]
Great. Do you (Allan) have two Github names? Under this issue I see allanhicks and allan-hicks (those hyphens again!). Seems to work okay though.
Incidentally, Chris and I aren't even using email (ours is so slow and useless from home) - the bell symbol at the top right of your github page (when you're signed in) has a blue dot to show unread notifications, which I think seem to be new issues or comments on issues. 
And I think that even if you reply to an issue via email, it still gets put onto the Github website. So you can reply either way, which is pretty neat....

**Comment by allan-hicks** [comment]
Yes, I've been replying via email a lot, but I think I'm associated with
two email accounts and sometimes I reply from a different one. I don't
understand why, though. Not a problem for me, at least as far as I can tell.

**Comment by andrew-edwards** [comment]
Yes, emailing or commenting on the Github site seems to work fine.
I have a bunch of minor edits on the Exec Summary that I haven't typed up yet - can do that tonight or tomorrow morning. Off home now, may work a bit more later. But I'll keep an eye on the issues for sure.
