### ISSUE TITLE
Age-1 fish are age 1

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#70]
I've tried to be consistent with hyphenation, and am fairly sure it should be:
age-1 fish   (because age-1 is used as an adjective)
but
fish that are age 1.  (because 'age 1' is not an adjective). 
Just explaining why I may be making such minor changes ;)  [Saying 'fish that are age 1' never sounds quite right, but seems to be what is done in fisheries.]  
Not really an issue (sorry!), just a heads up. Can close it fairly soon I guess.

**Comment by allanhicks** [comment]
Yes, Hastie appreciates this very much (he is out local hyphen expert)

**Comment by andrew-edwards** [comment]
I'm also trying to get the minimal change possible in a commit. I think I deleted a comma yesterday!
