### ISSUE TITLE
Should we add Recr_2014 to the correlations scatterplot?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#72]
This would mostly be interesting to see hw correlated it is with the 2016 harvest advice

**Comment by cgrandin** [comment]
I don't see why not. It should be straightforward to add.  Shall I do it ?

**Comment by andrew-edwards** [comment]
"Should be straightfoward." You tempter of fate.

**Comment by cgrandin** [comment]
I'm going to try it now

**Comment by cgrandin** [comment]
I forgot that I made it so it was a trivial addition - we can add any rec year easily.. It's done

**Comment by allan-hicks** [comment]
Great. I notice that the Canadians are working during the Super Bowl.
Would that be the case during the Stanley Cup?

**Comment by cgrandin** [comment]
Haha, maybe :) only a short time left I guess
