### ISSUE TITLE
mathptmx font - looks good?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#73]
Just commited a new font - mathptmx, line 70 in hake.sty.
I think it looks bolder, and it prints okay. Text looks a little smaller, but we were using 12pt anyway.

If everyone can use it (I think it's one of the default ones installed in latex/miktex, so hopefully it works for all, including making a .pdf) and we want to go with it, then I can tidy up some other things. I see that some of the tables can be made a bit bigger, plus it may have moved some figures/tables in Exec Summary, so I will just check they're still positioned okay. 

Let me know. I'm heading home shortly, will check in tonight.

**Comment by aaronmberger** [comment]
I like it, sticks out real well on my screen.  how about print outs...?

**Comment by cgrandin** [comment]
I like it too, works fine.

**Comment by andrew-edwards** [comment]
Printing is fine. I think Allan's good, yes?

**Comment by allan-hicks** [comment]
Haven't printed it, but on screen looks good. Thanks
