### ISSUE TITLE
Clicking on figure or table references in the executive summary takes you to the main figures section

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#74]
This is a really annoying problem for me, as I am a click-and-return type. I'll work on this but wanted others to know there was an issue.

**Comment by andrew-edwards** [comment]
It's to do with the counter starting again at 0. I did try to fix it but gave up. See what I wrote when this was an earlier Issue. And see my commented out attempts on line 325 of hake-assessment.rnw .

And then go to the interweb... Good luck.Seems that it should be fixable.

I had actually just checked and saw it was still like that, but the Table of Contents and main text work okay. The tables and figures are close by the Exec Summary text now, and not an issue for me as I avoid using a mouse (and will have the final thing printed out anyway).

**Comment by cgrandin** [comment]
Fixed. You need the 'chngcntr' package if you don't have it.

**Comment by andrew-edwards** [comment]
Sounds like cheating.

**Comment by cgrandin** [comment]
Nope, just the right input into google search :)

**Comment by andrew-edwards** [comment]
Seems to work. I did try those extra commands you added, but they changed the numbering of the main stuff.

**Comment by andrew-edwards** [comment]
Well, some of us were avoiding new packages because somebody couldn't install them ;)

**Comment by cgrandin** [comment]
Haha, well I'm at home now, where stuff works... What 'extra commands' ? I better check the numbering in the main section again

**Comment by andrew-edwards** [comment]
It works. Commands are straight after \begin{document}.  You can't hide from the 'blame'....
Oh, and searching in the .pdf works fine for me. Even words with ff in them. May have been a font thing before (for Allan?), but I think it always worked for me.
Okay, I'm off now.

**Comment by cgrandin** [comment]
Me too. I did a lot in the last couple hours. You did loads today. That should make tomorrow easier. Cheers, enjoy your eve,
