### ISSUE TITLE
selectivity colors

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#75]
Either the selectivity in the selectivity sensitivities plots (Figure 43) are labeled incorrectly, Figure 26 (2015 selectivities) are incorrect, or there are some big differences between the MLE and MCMC estimates of selectivity.

**Comment by aaronmberger** [comment]
I'm not seeing what you are, they seem fine to me...?  It looks to me like Fig 43 panel (a) MLE point estimates are fairly close to Fig 26 MPD estimates.  Fig 26 is for the most recent year, and now that I think about it I'm not sure exactly what Fig 43 represents.  Would be the average selectivity across years shown in the standard SS_plots function...?

**Comment by allanhicks** [comment]
The heading on the plots in Figure 43 says in 2015. I realize that I was
just expecting the colors to be the same. The two figures use opposite
colors for fishery and selectivity. I'll look into this and see if there
are other places that consistency will help.

**Comment by aaronmberger** [comment]
Ah yes, that bugger called consistency in large documents... err.  But fix once and knit away again next year...

**Comment by allanhicks** [comment]
I never thought I would knit.

**Comment by aaronmberger** [comment]
pays to read the actual graph, rather than assume what one thinks he doesn't know is shared globally

**Comment by aaronmberger** [comment]
fixed selectivity colors so consistent between fig 43 and 26; keep an eye out for other inconsistencies when doing read through - closing this one
