### ISSUE TITLE
Complete replies to 2015 SRG recommendations

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#77]

**Comment by aaronmberger** [comment]
I worked on 4 out of 5 here.  The 5th is regarding maturity ogives - Allan?  The others could really use a read over by one of the JTC members that was at the 2015 SRG.

**Comment by allan-hicks** [comment]
I'll do that now by looking at your commits through github.

**Comment by aaronmberger** [comment]
I just incorporated Allan's comments so will close this for now.
