### ISSUE TITLE
Exec Summary table e could be a bit larger (font or space allotment) for old folks

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#79]

**Comment by andrew-edwards** [comment]
Yes - see #73 regarding new font. Seems like we're all happy with it, so I'll make certain tables bigger. I'll close this one, as there's a few other things I'll do under #73.

**Comment by allan-hicks** [comment]
I fooled around a lot with this and this is what it has to be to fit on the
page in portrait.  I think that all of the columns are useful, but the the
only way to make it bigger is to delete some columns or spilt the table.

**Comment by andrew-edwards** [comment]
Yes, I made a and f bigger, but e has to be small.
