### ISSUE TITLE
line endings and paragraphs

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#8]
I have noticed when a paragraph is written as a single line that it is difficult to see the changes on GitHub (website) because it highlights the entire line. For example, look at the first couple of sections of the Executive Summary (especially the paragraph starting with "The assessment uses a Bayesian estimation approach").  Does anyone have a suggestion to make it easier to identify where changes have occurred in a single paragraph?

**Comment by cgrandin** [comment]
Just click 'Split' instead of 'Unified' on the top right of the panel! Andy and I were wondering that too, but started looking around and there it was.
