### ISSUE TITLE
Black Monday -  who's doing what?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#80]
Andy - have merged everyone's - I think all seems good. Have some edits to type up - will first do One-page Summary, then Exec Summary (Aaron - let me know when you've finished editing Exec Summary, thanks!).

**Comment by aaronmberger** [comment]
done with exec summ pass

**Comment by cgrandin** [comment]
I am reworking the executive summary tables. Looked at Allan's changes, and figured we should be using the booktabs package for this. They have no vertical liines, and underlined multi-column headers.

**Comment by aaronmberger** [comment]
I'm going through the main document addressing ** where I can.

**Comment by allanhicks** [comment]
I am going to concentrate on finsihing the data section and giving the assessment section a good work through

**Comment by allanhicks** [comment]
Chris or Andy: Can you merge often today so that we are all kept up with changes and can see the most recent document. I'll rebuild after every merge.

**Comment by andrew-edwards** [comment]
I've done edits to One-page summary. Going to do some edits to text in Exec Summary.
Yes, we'll keep merging. I also check people's changes (by clicking on the nodes on the Network graph), mainly for consistency etc.

**Comment by allanhicks** [comment]
As for the Exec Summary tables, if it is too much time, I don't mind the format of table d with the full box.

**Comment by aaronmberger** [comment]
Working through responses to 2015 SRG recommendations...

**Comment by aaronmberger** [comment]
done with exec summary

On Mon, Feb 8, 2016 at 11:48 AM, andrew-edwards <notifications@github.com>
wrote:

> Andy - have merged everyone's - I think all seems good. Have some edits to
> type up - will first do One-page Summary, then Exec Summary (Aaron - let me
> know when you've finished editing Exec Summary, thanks!).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/80>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
I'm almost there with the extrapolated crapola. Will merge soon.

**Comment by allan-hicks** [comment]
Cool.
I just uploaded my commit for the extrapolated table, figure, and text.
Sorry that I forgot about that.

**Comment by allan-hicks** [comment]
But, I have a conflict I'll try to fix

**Comment by andrew-edwards** [comment]
Our internet has completely seized up, but Chris thinks it’s because DFO runs scripts etc. over ‘lunch’. I’ve done some edits and am trying to merge Aaron’s but can’t fetch right now – will try again at 1pm. Plus I’m hungry.

 

Andy

-- 

Dr. Andrew Edwards 

Andrew.Edwards@dfo-mpo.gc.ca <mailto:Andrew.Edwards@dfo-mpo.gc.ca> 

http://www.chebucto.ns.ca/~english <http://www.chebucto.ns.ca/~english> 

Marine Ecosystems and Aquaculture Division, Pacific Biological Station,

Fisheries and Oceans Canada, Government of Canada, 3190 Hammond Bay Road,

Nanaimo, British Columbia, V9T 6N7, Canada. Tel: +1 250-756-7146. Fax: +1 250-756-7053.

 

La station biologique du Pacifique, Division des ecosystemes marins et de l’aquaculture,

Pêches et Océans Canada, Gouvernement du Canada, 3190 chemin Hammond Bay,

Nanaimo, Colombie-Britannique, V9T 6N7, Canada. Tél: +1 250-756-7146. Fax : +1 250-756-7053.

**Comment by andrew-edwards** [comment]
Andy trying to fix up Table f - see issue #86.
