### ISSUE TITLE
Survey section 2.2.1

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#81]
I filled in some of the blanks using the AcousticSurveyTimeSeries_2015.csv file that your provided Allan (and just committed).  I made this issue just to make sure that there weren't any [very] last minute updates with survey numbers.  There still are a couple of **comments in there that need to be addressed.

**Comment by cgrandin** [comment]
We should really be using Sexpr{}s for the values in there, e.g. \Sexpr{fmt0(survey.history[survey.history$year == 2015,]$biomass, 2)}

**Comment by cgrandin** [comment]
I will do this, will place them in the all.r file so we have the values generalized for next year

**Comment by aaronmberger** [comment]
Thanks Chris and I agree.  Figured I wouldn't be spending time on anything not critical to 5PM deadline today.  But I'm sure it only takes you a few minutes... me - a bit longer.

**Comment by allanhicks** [comment]
I'll have a look at this. Because I'm not familiar with all the names of variables you are using, it is faster for me to just write in the numbers rather than take 10 minutes searching for the values.  I guess I'm just sleep deprived and stressed out.

**Comment by cgrandin** [comment]
If you go into R and look at survey.history, it's all there. It's just the data frame that was read in from the CSV file.

**Comment by cgrandin** [comment]
I generalized this part, closing it up!

**Comment by allanhicks** [comment]
I added survey-comparisons and further generalized the code. The values previously entered for the comparison between extrapolated and non-extrapolated were different than what I had. They may have been from an earlier run. I'll double check these.

**Comment by allanhicks** [comment]
The percent extrapolated entered previously used the extrapolated biomass as the denominator. I used the non-extrapolated biomass, but I'll fix to use extrapolated so that it agrees with how the sentence is written.
