### ISSUE TITLE
Assessment model results section - recruitment sub-section

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#84]
Last paragraph:

I also get 1.43 for SD across 1971-2012.  But I get 1.56 for SD across 1966 - 2014 (begin of bias adjustment period).  Should we be reporting all the way back to 1946? I'm not sure what that tells us?

**Comment by allan-hicks** [comment]
I think that reporting only 1971-2012 is relevant. Not sure what it means
to report those non-informative years.

**Comment by cgrandin** [comment]
Agree, go ahead and delete the 1946-2014 values.

**Comment by aaronmberger** [comment]
done and closing
