### ISSUE TITLE
Table f row names

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#86]
Row names in Table f do not make too much sense to me, and have notation that doesn't seem to be used elsewhere. I'll have a go at editing them in a bit.

**Comment by allan-hicks** [comment]
Make sure that you verify this with me, as we have spent years coming up
with that wording and notation.  A change now may be more confusing htan
helpful.

**Comment by andrew-edwards** [comment]
Yes - I'm making a dummy second copy so you can easily see any changes. The problem is that a lot of it is not defined anywhere (I don't thing). 
Oh, what is SPR_{MSY-proxy} ?

**Comment by andrew-edwards** [comment]
Is SPR_{MSY-proxy}  just  SPR at  F_{\text{SPR}=40\%}   . I think the MSY doesn't need to be there??

**Comment by allan-hicks** [comment]
SPR=40% is the proxy for MSY.

I did notice that it uses F_40%, when we agreed to use SPR=40%.

I see your point and look forward to seeing the new table.

**Comment by andrew-edwards** [comment]
Okay - done in latest commit. The old table is there on the next page so you can easily flip back and forth to see what changed. 
Then I'll delete one of them.

**Comment by allanhicks** [comment]
I like the new table. Good job. Can you make the edits,Andy?

**Comment by andrew-edwards** [comment]
Yes.
