### ISSUE TITLE
Incorporate Sean's comments

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#96]
I suspect this will be for the final version...?

**Comment by cgrandin** [comment]
I'll try to download it. Wish me luck

**Comment by cgrandin** [comment]
I can't download it.. anyone else able to?

**Comment by aaronmberger** [comment]
I had a quick look and some are easy fixes and some are a little more
though provoking and some require rearranging entire sections (e.g., ex
summary unresolved problems.... section)

On Mon, Feb 8, 2016 at 2:29 PM, cgrandin <notifications@github.com> wrote:

> I'll try to download it. Wish me luck
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/96#issuecomment-181595129>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by andrew-edwards** [comment]
Someone said we can do these after submission if necessary. Okay to close?
