### ISSUE TITLE
Why are 2015 relative biomass values reported in the sensitivity section?

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#97]
I think that these should be 2016

**Comment by aaronmberger** [comment]
I believe you are right, good catch

On Mon, Feb 8, 2016 at 2:30 PM, allanhicks <notifications@github.com> wrote:

> I think that these should be 2016
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/97>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
Fixed
