### ISSUE TITLE
Progress an past research needs

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#98]
I think that we should just remove this for now. We can add it for the final version, if we feel it would be useful.

**Comment by aaronmberger** [comment]
agree

On Mon, Feb 8, 2016 at 2:52 PM, allanhicks <notifications@github.com> wrote:

> I think that we should just remove this for now. We can add it for the
> final version, if we feel it would be useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/98>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by aaronmberger** [comment]
commented out this section for SRG draft, closing for now and we can decide later if needed
