### ISSUE TITLE
Andy and I had to go to his house to finish

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#99]
Because we had no internet. Just so you know what the delay was. I will merge everything now..

**Comment by allan-hicks** [comment]
Great.  Sorry about the internet issue and thanks for finding a solution.
I'm merging now and will have a look through the doc.

I've been looking at Sean's comments.  I think that we can incorporate some
of them after the draft is out and before the final version.

**Comment by cgrandin** [comment]
We have no email at all, either. The DFO network is clearly screwed. Thanks for looking into Sean's comments, I still can't get them because our email is down.

**Comment by allan-hicks** [comment]
Ah man, that sucks. Here is an email I sent earlier:
~~~~~~~~~~~~~~
Just wondering when we will cut off any more commits. Then How shoudl we
deal with the final edits without overlap?  Should we let Chris make final
changes? Or commit and deal with conflicts if they arise?

I've noticed that the GitHub servers must be slow also because issues I've
been creating sometimes don't show up for a while.

If there is anything that Aaron and I can do to help, let us know. Our
internet is OK today.

Thanks,
Allan
~~~~~~~~~~~~~~~~~~

**Comment by minnowslayer** [comment]
I'm a bit behind with edits too. I have only small ones that I could either
commit or provide comments on the pdf. Do we have a preference?

**Comment by cgrandin** [comment]
Nathan, it would be easier if you commit your edits, then we can see the exact changes in the GitHub commit diff view.. We have no email so don't send it to my DFO email. Thanks

**Comment by minnowslayer** [comment]
no prob

**Comment by cgrandin** [comment]
I think we should strive to submit this by 5 as agreed. I'll take a look at Nathan's changes when I get them and merge them in. There are quite a few double stars still which I think only Allan can answer (US fishery). If possible we should clear all of those up now.

**Comment by aaronmberger** [comment]
Allan, if you can quickly address several of the ** left, I think we are
pretty much there.  I've done the ** that I felt confident answering and
the issues that I could do.

On Mon, Feb 8, 2016 at 3:42 PM, cgrandin <notifications@github.com> wrote:

> I think we should strive to submit this by 5 as agreed. I'll take a look
> at Nathan's changes when I get them and merge them in. There are quite a
> few double stars still which I think only Allan can answer (US fishery). If
> possible we should clear all of those up now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/99#issuecomment-181626353>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
check my new commits. I'll search elsewhere now

**Comment by cgrandin** [comment]
I'm pretty much just merging and building at this point, making sure everything is still working.

**Comment by aaronmberger** [comment]
I think I'm done with commits so you shouldn't see more from me.  standing
by....

On Mon, Feb 8, 2016 at 4:08 PM, cgrandin <notifications@github.com> wrote:

> I'm pretty much just merging and building at this point, making sure
> everything is still working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/99#issuecomment-181634010>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
I'm done with commits for now. Once Andy finishes, can Chris create a pdf and upload it to Google Drive or email it to all of us? I think it would be safest to work from the master pdf, just to make sure.

I feel that right now we should only focus only important or glaring issues.  I'm done wordsmithing unless I find something incorrect.

**Comment by cgrandin** [comment]
Agreed - Nathan and Andy are still committing, so I'm waiting on him and Andy to finish.
